### ISSUE TITLE
Missing export button

### ISSUE THREAD

**Issue by alphakex2** [material-table-core/core#101]
The export button is missing, How do I enable it?

**Comment by DewangS** [comment]
I am having same problem unless they have changed the settings. Could someone please help? I've below MT definition in my code

```
<MaterialTable
                title="Customer Applications"
                icons={tableIcons}
                columns={columns}
                data={reportData}
                options={{
                    exportButton: true,
                    search: true,
                  showTitle: true,
                  isLoading: true,
                  
                  //exportDelimiter: '        ',
                  headerStyle: {
                    backgroundColor: "#01579b",
                    color: "#FFF",
                  },
                  
                }}
              />
```

**Comment by matthewoestreich** [comment]
@alphakex2 @DewangS 

The way exporting is handled has changed. Please see [here](https://material-table-core.com/docs/breaking-changes#exporting) and [here](https://material-table-core.com/demos/export/basic) for more info.

**Comment by DewangS** [comment]
ok, just found out that they have removed the default export feature from the original material table due to some bloating jspdf changes though following their advise I've installed the @material-table/exporters package and added below code.. still can't see any EXPORT button. This is very important feature for me as I am creating reports and the data needs to be exported as PDFs. Guys please help as I wasn't expecting such drastic changes. The reason I moved from original Material Table to the core is due to lack of support. I am really concerned now with this new branch. see the below code ...

```
<MaterialTable
                title="Customer Applications"
                icons={tableIcons}
                columns={columns}
                data={reportData}
                options={{
                    exportMenu: [{
                        label: 'Export PDF',
                        //// You can do whatever you wish in this function. We provide the
                        //// raw table columns and table data for you to modify, if needed.
                        // exportFunc: (cols, datas) => console.log({ cols, datas })
                        exportFunc: (cols, datas) => ExportPdf(cols, datas, 'CustomerApplications')
                      }, {
                        label: 'Export CSV',
                        exportFunc: (cols, datas) => ExportCsv(cols, datas, 'CustomerApplications')
                      }],
                    search: true,
                  showTitle: true,
                  isLoading: true,
                  
                  //exportDelimiter: '        ',
                  headerStyle: {
                    backgroundColor: "#01579b",
                    color: "#FFF",
                  },
                 
                  
                }}
              />
```

**Comment by matthewoestreich** [comment]
Considering you appear to be the only one having an issue with this, would you mind creating a reproducible demo? Via StackBlitz or CodeSandbox.

Are you getting any errors?

**Comment by DewangS** [comment]
@oze4  No I am not getting any errors. In terms of the code, I guess that's what all I have for the MaterialTable definition. Rest of the code is just the column definition and API call during the page load via useEffect(). the API call just populates the reportData[] JSON array straight from the API response without any transformations etc. I can see all the data etc so, there no other issue nor any errors. Just can't see the EXPORT button

```
const columns = [
  { field: "lastName", 
    title: "Surname", 
    searchable: true,
    cellStyle: {
        width: 300,
        minWidth: 300,
        whiteSpace: 'nowrap',
      },
      headerStyle: {
        width: 300,
        minWidth: 300,
        whiteSpace: 'nowrap',
      }
},
    {
    field: "otherName", 
    title: "Other Name", 
    searchable: false,
    cellStyle: {
        width: 300,
        minWidth: 300,
        whiteSpace: 'nowrap',
      },
      headerStyle: {
        width: 300,
        minWidth: 300,
        whiteSpace: 'nowrap',
      }
    },
  { field: "regoNumber", 
  title: "Rego No.", 
  searchable: true,
  cellStyle: {
    width: 200,
    minWidth: 200,
    whiteSpace: 'nowrap',
  },
  headerStyle: {
    width: 200,
    minWidth: 200,
    whiteSpace: 'nowrap',
  } },
  { field: "permitType", 
  title: "Permit Type",
  cellStyle: {
    width: 150,
    minWidth: 150,
    whiteSpace: 'nowrap',
  },
  headerStyle: {
    width: 150,
    minWidth: 150,
    whiteSpace: 'nowrap',
  } },
  {
    field: "carpark",
    title: "Car Park",
    cellStyle: {
        width: 50,
        minWidth: 50,
        whiteSpace: 'nowrap',
      },
      headerStyle: {
        width: 50,
        minWidth: 50,
        whiteSpace: 'nowrap',
      }
  },
  {
    field: "bay",
    title: "Bay",
    cellStyle: {
        width: 20,
        minWidth: 20,
      },
      headerStyle: {
        width: 20,
        minWidth: 20,
        whiteSpace: 'nowrap',
      },
  }
];

```

**Comment by matthewoestreich** [comment]
Can you please use something like StackBlitz or CodeSandbox? It's just a million times easier. If you need API calls, you can use something like [JSON placeholder](https://jsonplaceholder.typicode.com/), which gives you fake data to use while still reproducing actually making API calls. 

I also went ahead and created a Live Demo on the website, which is working.

https://material-table-core.com/demos/export/basic/#live-demo

Help me help you.

**Comment by DewangS** [comment]
ok, that's really interesting .. my code is identical to yours and I can see the button on your live demo. Let me see if I can add some code to codesandbox. will get back to ASAP. Thanks for your prompt help. Much appreciated.

**Comment by matthewoestreich** [comment]
What version are you on? Possibly an issue with the version? Let me verify the version that's being used on the website.

**Comment by matthewoestreich** [comment]
Yea the website is on 2.3.4 (currently at 2.3.26 I believe). So it's behind. Let me update it and see if we have the same issue.

**Comment by DewangS** [comment]
ok, here is the codesandbox link. Apparently it's working on codesandbox (please ignore the missing icon). It's really odd.. Not sure what's wrong with my environment

[https://codesandbox.io/s/elegant-lalande-3teq8?file=/src/App.js](https://codesandbox.io/s/elegant-lalande-3teq8?file=/src/App.js )

Package versions from my package.json are as pwe below ...

```
"@material-table/core": "^2.3.8",
    "@material-table/exporters": "^1.0.4",
```

**Comment by matthewoestreich** [comment]
Try upgrading to 2.3.26. I just upgraded the website and it's working.

That is weird, though. Because the sandbox is working for me...

<img width="1028" alt="1" src="https://user-images.githubusercontent.com/21092343/108609851-67e0b380-7396-11eb-80ff-579f2b8883e1.png">

<img width="1029" alt="2" src="https://user-images.githubusercontent.com/21092343/108609858-6d3dfe00-7396-11eb-9f41-12d182f94030.png">

**Comment by DewangS** [comment]
ok @oze4 will do and let you know if the problem persists.

**Comment by DewangS** [comment]
@oze4 Bingo....!!! I can see the EXPORT icon\button after I upgraded @material-table/core to ^2.3.26. Thanks very much for all your help. You are a life saver 👍

**Comment by matthewoestreich** [comment]
Cheers!

**Comment by DewangS** [comment]
ok, while now I can at least see the export button and can export the data as PDF or CSV, clicking this button ONLY exports visible data from the browser. If I change the ExportPdf() function by supplying it with an array of all of my data, I get a report with blanks i.e. not data gets exported..just column headers and several pages of blank rows underneath.

For CSV, If I include the entire dataset array, I get an error..see below

**TypeError: console.err is not a function**

**node_modules/@material-table/exporters/csv/index.js**

```
return col.title;
    })).addRows(Array.from(data)).exportFile();
  } catch (err) {
    console.err("err in ExportCsv : ".concat(err));
  }
}
```
I tried to add console.log() to see the data and can see all 175 JSON objects. As it stands, the export is not useful as we can't expect users to export every single page individually .. is there anything I am missing here? I've updated the sandbox to reflect this and you will find exactly identical results..

**Comment by matthewoestreich** [comment]
I'm not sure I follow. Would you mind editing the SandBox?

**Comment by DewangS** [comment]
first of apologies for the confusion as I should have opened a new bug as this is unrelated to the original button issue. Please close this as I've created a new bug for a better visibility and management.

Sanbox link is added to the new bug report. If you can't reproduce please let me know as I could manage to see same errors on codesandbox as well
