### ISSUE TITLE
Unable to export all data as PDF or CSV

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#102]
**Describe the bug**
ok, while now I can at least see the export button and can export the data as PDF or CSV, clicking this button ONLY exports visible data from the browser. If I change the ExportPdf() function by supplying it with an array of all of my data, I get a report with blanks i.e. not data gets exported..just column headers and several pages of blank rows underneath.

For CSV, If I include the entire dataset array, I get an error..see below

```
TypeError: console.err is not a function

node_modules/@material-table/exporters/csv/index.js

return col.title;
    })).addRows(Array.from(data)).exportFile();
  } catch (err) {
    console.err("err in ExportCsv : ".concat(err));
  }
}
```
I tried to add console.log() to see the data and can see all 175 JSON objects. As it stands, the export is not useful as we can't expect users to export every single page individually .. is there anything I am missing here? I've updated the sandbox to reflect this and you will find exactly identical results..

**To Reproduce**

[https://codesandbox.io/s/elegant-lalande-3teq8?file=/src/App.js](https://codesandbox.io/s/elegant-lalande-3teq8?file=/src/App.js)

**Expected behavior**

MT should allow ALL data to be exported as PDF and CSV, not just visible data. Also, it would be an added bonus if we can export the Title.

**Comment by matthewoestreich** [comment]
I'm not sure I follow. Would you mind creating a sandbox?

Edit: didn't see the sandbox at first. Looking at it now.

**Comment by matthewoestreich** [comment]
This is expected behavior. The `ExportPdf` function only exists to help you out. It just serves as the default export method for Pdf/Csv. It's the exact code that exists in `material-table`. It's only there to do one thing.

You'll have to write your own `ExportPdf/Csv` method if you want to handle how (or which) data gets exported.

Something like...

https://codesandbox.io/s/solitary-monad-820vc?file=/src/App.js:7893-9347

```js
exportMenu: [
  {
    label: "Export TXT",
    //// You can do whatever you wish in this function. We provide the
    //// raw table columns and table data for you to modify, if needed.
    // exportFunc: (cols, datas) => console.log({ cols, datas })
    exportFunc: (cols, datas) => {
      // See comment above.
      // If you want to export reportData you'll need to
      // integrate that logic yourself.
      console.log({ reportData });
      function download(data, fileName) {
        const a = document.createElement("a");
        a.href = URL.createObjectURL(new Blob([data], { type: "text" }));
        a.setAttribute("download", fileName);
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      }
      const reportDataDL = JSON.stringify(reportData, null, 2);
      download(reportDataDL, "myfilename.txt");
    },
  },
];
```

**Comment by DewangS** [comment]
Fair enough though it doesn't make sense as it can traverse through max 20 rows but can't exceed to all rows? I actually started using MT for my tabular reporting as getting data aligned in react-pdf to generate decent looking reports with the company logo and header\footer etc was getting way too complicated. Thought as least MT will be more appealing and also allows export as PDF (even without the Title text but that can be ignored for now). 

So, I guess I now have to go back to react-pdf and do lots of styling in order to get tabular report.

**Comment by matthewoestreich** [comment]
I agree. I believe there is a separate issue for that problem. Although, if you have your data in state, you could just do this:

```js
// Here we are inside our functional component
const [dataInState, setDataInState] = useState( myDefaultData );

<MaterialTable
// ...
label: "Export Something",
exportFunc: () => {
    // logic to export
    download(dataInState, 'myfilename.csv');
}
/>
// ...
```

Again, you can do whatever you want there.

Edit: Your data doesn't even have to be in state...

```js
// Outside of component
const myData = [
// ... your data goes here
];

// Inside of component
<MaterialTable
// ...
label: "Export Something",
exportFunc: () => {
    // logic to export
    download(myData, 'myfilename.csv');
}
/>
```

**Comment by matthewoestreich** [comment]
I believe we *should* pass all data by default, but this is tricky. What if someone is using remote data? Etc...

The idea behind providing an array of export objects (ie: `{ label: "foo", exportFunc: (col, data) => {} }`) is so that you can have freedom to do whatever you want. If you just want to use "default" export, like how `material-table` handles it, you can (via the `@material-table/exporters` package). 

`mbrn/material-table` *only* allows you to export to CSV or PDF. What if you want to export to a different format? What if you need to make an API call there (in order to grab all data)? Well, now that is extremely easy for you to do.

**Comment by matthewoestreich** [comment]
In `@material-table/exporters` there was an issue with logging the error `console.err` vs `console.error`..

I have published v1.0.5, which fixes this.  Would you mind updating your `@material-table/exporters` package and trying again? The error should be more clear now.

**Comment by DewangS** [comment]
Thanks for the pointers. I have used this exportFunc() custom export CSV though my need is to export as PDF. My data is in state.

**Comment by matthewoestreich** [comment]
```js
import 'jspdf-autotable';

export default function ExportPdf(columns, data, filename = 'data') {
  try {
    const JSpdf = typeof window !== 'undefined' ? require('jspdf').jsPDF : null;
    if (JSpdf !== null) {
      const content = {
        startY: 50,
        head: [columns.map((col) => col.title)],
        body: data
      };
      const unit = 'pt';
      const size = 'A4';
      const orientation = 'landscape';
      const doc = new JSpdf(orientation, unit, size);
      doc.setFontSize(15);
      doc.text(filename, 40, 40);
      doc.autoTable(content);
      doc.save(filename + '.pdf');
    }
  } catch (err) {
    console.error(
      `exporting pdf : unable to import 'jspdf-autotable' : ${err}`
    );
  }
}
```

That is the exact code we use to export to pdf. It's the exact same code in `mbrn/material-table`.  How were you exporting to pdf before?

This...

```js
// in mbrn/material table you just do the exportButton, right?
options: {{ exportButton: true }}
```

That is the same as doing... (there is literally no difference)

```js
{
    label: "Export PDF",
    exportFunc: (cols, datas) => ExportPdf(cols, datas, 'myfilename')
}
```

If that doesn't suite your needs, I fail to understand how you were exporting before..

**Comment by DewangS** [comment]
upgraded exporter to 1.0.5, now getting below error when I try to export all rows by clicking the Export CSV option :(

**error in ExportCsv : TypeError: row.map is not a function**

**Comment by matthewoestreich** [comment]
So here is the issue with using `reportData` with `ExportCsv`...

It (`ExportCsv`) expects an array of arrays. Aka an array, which each element in that array is itself an array (in this case an array of strings). Each element (array of strings) represents a row of data.

You are supplying an array of objects. That is why we are unable to map.

Top is what we expect, bottom is from `reportData`...

<img width="723" alt="a" src="https://user-images.githubusercontent.com/21092343/108612689-99667880-73b0-11eb-9afe-9bc012f7c5fe.png">

**Comment by matthewoestreich** [comment]
So, if you do something like this it will work.. (you just need to convert each object into an array of strings, where each string is the value from the key: value...) I know that's kind of confusing, but this example should help..

https://codesandbox.io/s/charming-hooks-kk3gi

```js
{
  label: "Export CSV",
  exportFunc: (cols, datas) => {
    // Turn data into an array of string arrays, without the `tableData` prop
    const reportDataFinal = reportData.map(({ tableData, ...row }) => Object.values(row));
    ExportCsv(cols, reportDataFinal);
  }
}
```

**Comment by matthewoestreich** [comment]
@DewangS now I understand that is confusing, so I made some changes to `@material-table/exporters`.. You don't have to worry about supplying an array of arrays, etc.. now.

If you update to v1.0.6, all you have to do is this: (I tested this and it worked for me)

https://codesandbox.io/s/charming-hooks-kk3gi?file=/src/App.js (updated)

```js
{
  label: "Export CSV",
  // Using `headerRow` is the same as using `cols`
  exportFunc: headerRow => ExportCsv(headerRow, reportData),
}
```

**Comment by matthewoestreich** [comment]
@DewangS actually, use v1.0.7 - I forgot to make the same change for `ExportPdf`... apologies.

**Comment by DewangS** [comment]
Yay... mate, you are a legend. :)

I used your logic for both i.e. PDF and CSV and now can see all rows... phew..!!!

Thank you so very much for your prompt help. Much appreciated.

**Comment by matthewoestreich** [comment]
Cheers!

**Comment by DewangS** [comment]
@oze4  I just installed v1.0.7 though got below warnings, do I really need to install these packages?

npm WARN @material-table/core@2.3.26 requires a peer of @date-io/core@^2.10.6 but none is installed. You must install peer dependencies yourself.
npm WARN @material-table/core@2.3.26 requires a peer of @material-ui/core@^4.11.2 but none is installed. You must install peer dependencies yourself.
npm WARN @material-table/core@2.3.26 requires a peer of react@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN @material-table/core@2.3.26 requires a peer of react-dom@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
