### ISSUE TITLE
Actions on Toolbar. No way of having a sticky action icon when selection is activated

### ISSUE THREAD

**Issue by LuisPinaSoares** [material-table-core/core#103]
- #### Please include a demo of the issue/behavior/question you have
https://codesandbox.io/s/material-table-starter-template-forked-6snxl?file=/src/index.js

**Describe the bug**
I cannot find a way of having an action icon that sticks on the toolbar when i have selection option true. They all disappear or appear on selecting or not rows.

**To Reproduce**

1. Go to one of selection box
2. Click on it
3. See error, no combination of icon actions objects for toolbar stays on the toolbar consistently

**Expected behavior**
At least one action option should be sticky, `position: 'toolbar'`. For example there exists the `position: 'toolbarOnSelect'` and it presents the same behaviour of `position: 'toolbar'`.

**Additional context**
Version on table `"@material-table/core": "^2.3.26"`

**Comment by LuisPinaSoares** [comment]
There is a way to have the intended behaviour, but is a workaround, having 2 actions that do the same but with different position values.
 ```javascript
          actions = {[{
            position: 'toolbarOnSelect',
            icon: tableIcons.Pdf,
            onClick: () => {
                // Do action A
            }
          },
            {
              position: 'toolbar',
              icon: tableIcons.Pdf,
              onClick: () => {
                // Do action A
              }
            },
          ]}
```

**Comment by matthewoestreich** [comment]
I think the idea behind this is - if you have a row selected, why do you need to see the export pdf button? Isn't it more intuitive to have a separate menu for when row(s) are selected? For example, why show a delete button if there is nothing selected to delete?

**Comment by LuisPinaSoares** [comment]
I understand what you are saying. But what if you have an independent action that is not related with selection, like export all information on the table or some filter activated through the toolbar icon.
Wouldn't it make that a valid case for the sticky button?

Having said this, i understand that you might have an external unrelated button that does this task, but in this specific case, i use the table as my main view component and i don't want to add additional view cluttering elements.

**Comment by matthewoestreich** [comment]
I do not think that is a valid case for a sticky button. Why show the export button while a row is selected? It doesn't make any sense to me. @Domino987 thoughts?

**Comment by LuisPinaSoares** [comment]
OK. Don't think of it as an export, but as a filter button for example.
I can filter stuff on the table, if they are selected or not, does it make more sense this way?

Additional comment. The behaviour I want is achievable without doing nothing to crazy. I think probably is not worth it for you guys to loose time with this one at least for now.

**Comment by matthewoestreich** [comment]
Right. Same concept. Why would you be concerned about filtering rows when a row is selected? Wouldn't you want the selection menu to appear when you have a row selected? The idea is that the actions available while a row is NOT selected will be different from those when a row IS selected. It's all about context. Like Windows doesn't put your entire start menu in the dialog that pops up when you right click something. Actions for the "thing" that was right clicked show up. Same concept. When a row is selected, we want the selection menu to appear.

**Comment by LuisPinaSoares** [comment]
Agreed.
I Consider the issue closed
