### ISSUE TITLE
Action buttons with columnsButton option render stacked instead of in a row

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#109]
**Describe the bug**

This bug is similar to #94. The difference is that both the `columnsButton` key in the `options` prop and the `actions` prop are specified.
From experimentation on the rendered output, `flex:1` should be added to the parent `<div>` containing the button `<span>`s.

**To Reproduce**

```
<MaterialTable
  ...
  options={{
    search: true,
    columnsButton: true,
  }}
  actions={[
    {
      icon: RefreshIcon,
      tooltip: 'Refresh',
      isFreeAction: true,
      onClick: onRefetch,
    }
  ]}
/>
```

**Expected behavior**
All toolbar buttons render in a row.

**Screenshots**
<img width="286" alt="Screen Shot 2021-03-05 at 5 09 18 PM" src="https://user-images.githubusercontent.com/6295083/110184123-e6494680-7dd5-11eb-84b7-61b9b72e9091.png">

**Desktop (please complete the following information):**

- OS: OSX (OS shouldn't matter)
- Browser Chrome
- Version 88.0.4324.192

**Comment by matthewoestreich** [comment]
Closing as we have published a fix for this.

**Comment by peacechen** [comment]
Edit: Thanks for releasing a new version. The version published to npm is correctly bumped (2.3.28). The release version on Github says 2.3.27
https://github.com/material-table-core/core/releases/tag/v2.3.27

**Comment by matthewoestreich** [comment]
That's my fault. I'll fix that when I'm back by my computer. It should still work though, the releases on GitHub shouldn't mess with NPM.

**Comment by peacechen** [comment]
It's been working well. Thanks again.

Couple housekeeping points:
The release still says 2.23.27 instead of 2.23.28.  There are duplicate 2.23.27 release descriptions.
https://github.com/material-table-core/core/releases

The tag in the repo should also be 2.23.28. There are duplicate 2.23.27 tags.

Not crucial of course, but will help reduce confusion when looking back at the release history.
