### ISSUE TITLE
typing: forcing refresh data not achievable in typescript

### ISSUE THREAD

**Issue by mdpx** [material-table-core/core#110]
as core's docs is wip, I'm still referring to the mbrn version.

seems you can't do what the [second example here](https://material-table.com/#/docs/features/remote-data) shows when using typescript

![image](https://user-images.githubusercontent.com/31342918/110201159-9bdecd00-7e9c-11eb-928f-7cf26a052b9e.png)

the simple solution is adding a question mark in index.d.ts:
![image](https://user-images.githubusercontent.com/31342918/110201310-5ec70a80-7e9d-11eb-8164-988d6db728b5.png)
I think it should be safe as the implmentation takes both arguments as optional:
![image](https://user-images.githubusercontent.com/31342918/110201594-d9dcf080-7e9e-11eb-8253-b3489216ff03.png)

**Comment by matthewoestreich** [comment]
Are you using `mbrn/material-table` or `@material-table/core`?

**Comment by mdpx** [comment]
> Are you using `mbrn/material-table` or `@material-table/core`?

core of course

**Comment by yejiyang** [comment]
@mdpx Any thoughts about this issue? https://github.com/mbrn/material-table/issues/2501 How to type ref on material-table

**Comment by mdpx** [comment]
> @mdpx Any thoughts about this issue? [mbrn#2501](https://github.com/mbrn/material-table/issues/2501) How to type ref on material-table

the pr will fix it.
to type ref: `createRef<MaterialTableProps<your row data type>>()`, or use `as` like I did
