### ISSUE TITLE
groupTitle prop in options does not return column key

### ISSUE THREAD

**Issue by bishoym** [material-table-core/core#115]
As per my question on the Gitter channel on [March 7, 2021 3:50 PM](https://gitter.im/material-table/Lobby?at=6044da0e120cd84f78fd55c6), in order to properly override grouping, a column key is required.

The default behaviour of grouping is to display ` > Column Name: Value` but if you attempt to override using the groupTitle prop inside options, the column name is missing. 

## Sample of the current returned object in `groupTitle`
```
data: (3) [{…}, {…}, {…}]
groups: []
groupsIndex: {}
isExpanded: false
path: ["male"]
value: "male"
```

**Comment by matthewoestreich** [comment]
Hi! Per our guidelines, we require a reproducible sandbox. Would you mind creating one?

**Comment by matthewoestreich** [comment]
Closing this per no response. Please feel free to reopen - we are just trying to keep issues clean.

Thank you!
