### ISSUE TITLE
onCellEditApproved validate doesn't get fire

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#116]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

Don't have one on sandbox yet but will add it later

- #### Please try to be as detailed as possible

So, I have a MT with only one editable cell. The cell has a validation which is defined in the column definition as a standard. When I do RowUpdate or BulkUpdate, the validation kicks in and shows an error in RED and doesn't allow user to save the value. All good so far ...

The same validation doesn't work or say doesn't fire when you use onCellEditApproved. You have to manually call your validation routine and even after calling the validation and REJECTING the value with a REASON, the helperText below the cell to indicate what the issue is, never appears. 

Seems more like a bug unless I don't know how to show the REJECT reason as a helper text, I will just stay with the rowUpdate and bulkUpdate for now.

Has anyone experienced this?

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by DewangS** [comment]
ok, here is a sample code in the [sandbox](https://codesandbox.io/s/objective-ptolemy-sz884). You will notice that during the OnCellEditApproved event, it does validate License number though fails to display the error in the HelperText

Scenarios...

1.  Try Bulk Update by clicking the PEN icon on the top right. When you enter invalid License Number (more than 3000), you will see an error text in RED underneath

2.  Try Row update by clicking the PEN icon in front of any row and enter more than 3000 as a License Number, you will see the value gets rejected and an error text underneath

3.  Now, try the cell edit by clicking the editable License Number column, enter any value greater than 3000 and try to accept your changes by clicking the 'correct tick' icon, you will notice the changes gets rejected though **no error getting displayed underneath**

**Comment by Hatko** [comment]
Have the same issue

**Comment by Domino987** [comment]
Seems like when mbrn added the cell edit feature, it was not connected to the error settings. Good catch.

**Comment by Domino987** [comment]
This is fixed with 3.0.10. Thank you for the issue
