### ISSUE TITLE
Problem with hiding columns in Column selector

### ISSUE THREAD

**Issue by appukuttan-shailesh** [material-table-core/core#117]
I am not sure if `hidden` and `hiddenByColumnsButton` are working as expected.

I need to hide a column (lets say "name" in the below example taken from the [live editor in docs](https://material-table-core.com/demos/columns/hide)) from the table and ALSO the column selector. I imagine I would do the following:

```
function HideColFrmTbleNotFrmColsBtn() {
  return (
    <MaterialTable
      icons={TABLE_ICONS}
      options={{ 
        // Allow user to hide/show 
        // columns from Columns Button
        columnsButton: true
      }}
      data={[
        { 
          name: 'Foo',
          surname: 'Bar'
        },
        { 
          name: 'Baz', 
          surname: 'Fee', 
        },
      ]} 
      columns={[
        { 
          title: 'Name', 
          field: 'name', 
          hidden: true,
          hiddenByColumnsButton: true
        },
        { 
          title: 'Surname', 
          field: 'surname',
          hiddenByColumnsButton: false
        }
      ]}       
    />
  )
}
```
But I still see the "name" field in the column selector:
![Peek 2021-03-09 11-46](https://user-images.githubusercontent.com/24866517/110459323-23128780-80cd-11eb-858e-9c2991ba78dc.gif)

Am I using this incorrectly?
I have read the instructions [here](https://material-table-core.com/demos/columns/hide) and [here](https://material-table-core.com/docs/breaking-changes/), and believe I have followed them proprerly. They pretty clearly say:

![image](https://user-images.githubusercontent.com/24866517/110459669-88667880-80cd-11eb-83db-e3d12cdd8a95.png)
which is what I have done above (isn't it?!).

**Comment by matthewoestreich** [comment]
Hi! The way the columns button is handled has changed. See here for more info. https://material-table-core.com/docs/breaking-changes#columns-button

**Comment by appukuttan-shailesh** [comment]
@oze4 I had actually read the info on that page before:
>I have read the instructions [here](https://material-table-core.com/demos/columns/hide) and [here](https://material-table-core.com/docs/breaking-changes/), and believe I have followed them proprerly. 

https://material-table-core.com/docs/breaking-changes#columns-button gives me two options:
![image](https://user-images.githubusercontent.com/24866517/111447483-c4bd5880-870d-11eb-96aa-5db96de485ca.png)

I wish to use the **first option**, as attempted below. I am not sure if I understand this correct. I am editing the **live editor** on this page to figure this out: https://material-table-core.com/demos/columns/hide/

**Objective:** to hide the column "**name**" from appearing in the drop down column selector.

When I set all columns to `hiddenByColumnsButton: false`
I still get both fields in the column selector:
![image](https://user-images.githubusercontent.com/24866517/111447309-9c355e80-870d-11eb-88e0-9fad57c1ac72.png)

But more appropriately, based on info in https://material-table-core.com/demos/columns/hide/, 
![image](https://user-images.githubusercontent.com/24866517/111450701-f1bf3a80-8710-11eb-95f3-c59894bb9709.png)

I set `hiddenByColumnsButton: true` for the "**name**" column and keep it as `hiddenByColumnsButton: false` for the "**surname**" column:

![image](https://user-images.githubusercontent.com/24866517/111450927-2c28d780-8711-11eb-89ec-7bb3117a6f07.png)

But I still get the same output as before.

Apologies if I haven't followed the instructions properly (the docs probably needs a bit more clarification if thats the case; I would be happy to make a PR once I understand it myself), but can you show me how to update the code on the [live editor](https://material-table-core.com/demos/columns/hide/#live-demo) such as to hide the "name" column from appearing in the column selector?

**Comment by appukuttan-shailesh** [comment]
@oze4 : Could we reopen this ticket, as it seems to be unresolved?

**Comment by abhishek0502** [comment]
I am facing the same problem - hiddenByColumnsButton doesn't work for me.

**Comment by appukuttan-shailesh** [comment]
As far as I have tried, things don't work as per the documentation.

What works for me currently is along these lines:
- `hidden` is used for initially (default) hiding a particular column in the table, and which you wish to alllow the user to view (Add to table) if they so desire
- `hiddenByColumnsButton` seems (as per documentation) to be **intended** to be used for disabling hiding/viewing a particular column by the user.... _but does not work as expected!_
- my use case was to simply hide a particular column permanently from the user, but to have the data passed on as part of `rowData`. What I did was to simply **not** specify the column (attribute) I wanted permanently hidden in the table `columns` parameter. I do still get access to this attribute in `detailPanel`.

**Comment by peacechen** [comment]
`hiddenByColumnsButton` had been working but must have been broken recently.  I'll try to find out when and why.

The relevant code is at:
https://github.com/material-table-core/core/blob/master/src/components/MTableToolbar/index.js#L156

Aha, there's a fall-through return in the next block that's essentially an "else" which also returns a menu item:
https://github.com/material-table-core/core/blob/master/src/components/MTableToolbar/index.js#L178

This line needs to be added at line 156
```
                if (col.hiddenByColumnsButton) return null;
                if (!col.hidden) {
...
```

Upon further inspection, the fall-through return on 178 is exactly the same as the JSX block above. That's a bug and should be removed. @oze4 do you concur?

**Comment by peacechen** [comment]
@oze4 Will you remove the redundant return, or shall I submit a PR?  It would be preferable for #144 to be merged so this fix doesn't pile onto that.

**Comment by matthewoestreich** [comment]
@appukuttan-shailesh apologies for that - somehow the changes I made were reverted (to code that didn't work). I have since updated the code and published v2.3.31, which should fix this for you.

**Comment by appukuttan-shailesh** [comment]
Thanks for resolving this @peacechen , @oze4

**Comment by vizardkill** [comment]
@peacechen  

Will this property have an attribute associated with location?

for the translation of the text

for example > EN > "Add or remove columns" in ES> "Mostrar u ocultar columnas"
