### ISSUE TITLE
Table Not retriving newData when row update and fixed Columns is set.

### ISSUE THREAD

**Issue by giovannisc** [material-table-core/core#118]
**Description**
When fixedColumns parameter in options prop is set onRowUpdate not receive newData arguments with the new changes.

You can see the wrong behavior in the link below:
https://codesandbox.io/s/material-table-starter-template-forked-005gz?file=/src/index.js

To reproduce try to update data, click on update action button then update some information, finally confirm operation. After that delete fixedColumns parameter in options prop and try again, this time it will work normally.

- OS:  Ubuntu
- Browser: Firefox
- Version: 86.0

**Comment by matthewoestreich** [comment]
Thank you very much for this!  We would love to merge a PR for this issue, otherwise we will get to it when we can.

We really appreciate you bringing this to our attention!

**Comment by andreasstrey** [comment]
Hi,

i had the same problem. I don't have a fix for the behavior but i can explain it.

For the fixed columns a second table is used as an overlay. When the edit buttons are part of the fixed columns, the second table will used to trigger the updates but doesn't recognize the changes in the first table. It seems that the data that are used to render the components in the two tables are not connected correctly.

In the end i used custom css to add `position: sticky` to the columns.
