### ISSUE TITLE
Export button don't appear on using exportButton: true

### ISSUE THREAD

**Issue by edwardp22** [material-table-core/core#120]
I am defining the property `options={{ exportButton: true }}` but the corresponding button don't render on screen. If I import material-table instead of @material-table/core it works fine.

You can see an example here:
[https://codesandbox.io/s/material-table-starter-template-forked-sqo1v?fontsize=14&hidenavigation=1&theme=dark]

- OS: Windows 10 Pro
- Browser Chrome
- Version 89.0.4389.82 (oficial Build) (64 bits)

**Comment by matthewoestreich** [comment]
Hi! This is because the way exporting is handled has changed. See here for more. https://material-table-core.com/docs/breaking-changes#exporting
