### ISSUE TITLE
hooks change in m-table's parent component causes pageSize reset when props has function properties and data is remote

### ISSUE THREAD

**Issue by mdpx** [material-table-core/core#122]
reproducible example [here](https://codesandbox.io/s/material-tablecore-with-axios-hooks-gvxzp)

when using axios-hooks, only happens when using custom column renderer,
when using the original axios, works fine even with custom renderer.

I assume this has nothing to do with axios-hooks as it works when not using custom renderer.

**To Reproduce**

1. click on the pageSize menu
2. click on "5" or "20"
3. wait till remote data returns
4. See error: the menu display not updated with selected pageSize
5. comment the render function from line 23
6. repeat step 1~3, no error this time

**Expected behavior**
the pageSize menu should update when user select another pageSize, no matter using custom column renderer or not.

**Desktop**
- OS: windows
- Browser: chrome
- Version: 89

**Comment by matthewoestreich** [comment]
Completely agree! Thanks for pointing this out. We would love to an accept a PR for this!! Otherwise, we will get to it when we can.

Thanks again.

**Comment by Domino987** [comment]
This seems like a weird bug. I will take a look at it. Thanks :)

**Comment by mdpx** [comment]
Hi! digged deeper and located the problem together with some related issues, but no idea what to do, need your decisions.

I think the real title of this issue should be "hooks change in m-table's parent component causes pageSize reset when props has function properties and data is remote".
I've updated the [sandbox](https://codesandbox.io/s/material-tablecore-with-axios-hooks-gvxzp), you can see raw axios won't work either if the `useState` hook change happens.

in this case, calling the refetch function returned by `useAxios` triggers a hook change in parent component, causing a rerender in m-table, where new props is a deep clone of previous one, and the new column `render` function !== the previous one (I don't know how react implements this, as I know lodash's `cloneDeep` only copies reference for functions).

then `propsChanged` is true in `componentDidUpdate`, `setDataManagerFields` is called:
https://github.com/material-table-core/core/blob/0e953441fd9f9912d8cf97db103a8e0cb4f43912/src/material-table.js#L137-L151

and because `this.isRemoteData()`, pageSize is reset to initial option:
https://github.com/material-table-core/core/blob/0e953441fd9f9912d8cf97db103a8e0cb4f43912/src/material-table.js#L119-L120

@Domino987 you mentioned this line in [mbrn # 1941](https://github.com/mbrn/material-table/issues/1941), I agree with you that remove`this.isRemoteData()` condition. I see no reason for this as the only timing to set pageSize from options is when initializing. I've tried several examples with this removal and everything works fine.

in another similar [mbrn # 1644](https://github.com/mbrn/material-table/issues/1644) the opener suggests using `&&` instead of `||`, which I don't understand, [related pr](https://github.com/mbrn/material-table/pull/1638) is closed by mbrn.

further, I think it would be better if `propsChanged` remains false in this case, but no clue how this can be achieved.

**Comment by mdpx** [comment]
@oze4 @Domino987 any thoughts on this?

**Comment by Domino987** [comment]
Hi. Can you create a PR with the update you made by removing the remote data and i will check of that works?
