### ISSUE TITLE
cellStyle throws exception on new row

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#123]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

I've a dynamic cell styling which changes the background and the text color based on the data value of that cell. While it works on the initial table render it throws an error on 'onRawAdd' event. basically it throws an error as the rawData becomes undefined for the new row for some odd reason.

[CodeSandbox sample](https://codesandbox.io/s/objective-ptolemy-sz884)
  

**Describe the bug**
Upon raw addition, the cellStyle throws an error due to undefined rawData element.

**To Reproduce**

1. Open the sanbox sample [code](https://codesandbox.io/s/objective-ptolemy-sz884)
2. Click on '+' sign on the top right

You will see below exception .....

```
Cannot read property 'licenseNo' of undefined
Object.cellStyle
/src/mtBulkUpdate.jsx:61:51
  58 |     width: 150,
  59 |     minWidth: 150,
  60 |     whiteSpace: "nowrap",
> 61 |     backgroundColor: backgroundColor(rawData.licenseNo),
     |                                             ^
  62 |     color: textColor(rawData.licenseNo)
  63 |   };
  64 | },
View compiled
▶ 24 stack frames were collapsed.
```

**Expected behavior**

The background and text color of the cell should changed based on the user entered data values

**Screenshots**
```
Cannot read property 'licenseNo' of undefined
Object.cellStyle
/src/mtBulkUpdate.jsx:61:51
  58 |     width: 150,
  59 |     minWidth: 150,
  60 |     whiteSpace: "nowrap",
> 61 |     backgroundColor: backgroundColor(rawData.licenseNo),
     |                                             ^
  62 |     color: textColor(rawData.licenseNo)
  63 |   };
  64 | },
View compiled
▶ 24 stack frames were collapsed.
```

**Desktop (please complete the following information):**

- OS: **MacOs Mojave 10.14.5**
- Browser Version :  **Chrome 88.0.4324.150 (Official Build) (x86_64)**

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by matthewoestreich** [comment]
[![Edit dazzling-payne-rtw38](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-payne-rtw38?fontsize=14&hidenavigation=1&theme=dark)

Hello. The issue appears to be with your code somewhere.

**Comment by DewangS** [comment]
Thanks @oze4 for looking in to this. I've followed your code and made couple of other changes as it seems to be working now.
