### ISSUE TITLE
Row Font set to inherit overrides theme font

### ISSUE THREAD

**Issue by devzeebo** [material-table-core/core#124]
Continuing the discussion from here:

https://github.com/mbrn/material-table/issues/2080#issuecomment-778761244

[Workaround (as of 2021-03-16)](https://github.com/mbrn/material-table/issues/2080#issuecomment-762074957):

[robin-sf](https://github.com/robin-sf): "My current workaround (to avoid hardcoding) is to import the theme file and use it as so:"
```
options={{rowStyle: { fontFamily: typography.fontFamily, ...typography.body2 }}},
```

**Comment by matthewoestreich** [comment]
Yes, you can use themes. [See here](https://material-table.com/#/docs/features/styling). Same concept, since we are a fork of that repo.

**Comment by moranbw** [comment]
I don't believe this answers the question.  If you use ThemeProvider at the root of your component tree, Material-Table should respect this.

**Comment by matthewoestreich** [comment]
That's a good point. Reopened. 

Any ideas on how to respect the theme while supporting these legacy props? Just merge them into the theme?

**Comment by matthewoestreich** [comment]
Just to make note; it looks like we are using 2 themes. One at the root, one that wraps the MTableScrollbar component.

**Comment by shaselboeck** [comment]
When I am setting this option `rowStyle: {fontFamily: "Roboto", fontSize: "0.875rem"}` it works, but not in row editmode.

**Comment by christophervizcarra** [comment]
Are there any updates on this issue? I'm using v4.3.44 and it would be preferable to not declare a rowStyle on every table.
