### ISSUE TITLE
Grouping data by column with object as field property

### ISSUE THREAD

**Issue by vizardkill** [material-table-core/core#125]
Given following set of data:

`[
  {
    id: 1,
    word: "word1",
    nested: {
      prop1: "value1",
      prop2: "value2"
    }
  },
  {
    id: 2,
    word: "word2",
    nested: {
      prop1: "value3",
      prop2: "value4"
    }
  },
  {
    id: 3,
    word: "word1",
    nested: {
      prop1: "value1",
      prop2: "value2"
    }
  },
  {
    id: 4,
    word: "word4",
    nested: {
      prop1: "value3",
      prop2: "value4"
    }
  }
]`

and column definition:

`{
    title: "Nested",
    field: "nested",
    render: (rowData, renderType) =>
      renderType === "row"
        ? rowData.nested.prop1 + " " + rowData.nested.prop1
        : rowData.prop1 + " " + rowData.prop2
  }`

grouping does not work as expected.

**Please try to be as detailed as possible**

After dragging and dropping last column (Nested) on grouping area, there is only one group of data value1 value2 instead of expected two: value1 value2 and value3 value4.

Is there any way to achieve grouping for columns with custom data render applied based on nested object?

Full code example:

[codeSandbox](https://codesandbox.io/s/material-table-starter-template-ddugk)

**Comment by vizardkill** [comment]
???

**Comment by oze4** [comment]
The issue looks to be somewhere in your code.

[![Edit dazzling-payne-rtw38](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-payne-rtw38?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matthewoestreich** [comment]
My bad closed/commented on the wrong issue. Sorry. I will get to this one next.

**Comment by vizardkill** [comment]
You do an incredible job in honor of mbrn, if you need support I would love to help you in any way I can, I do not want material table to close its doors to future updates.

**Comment by matthewoestreich** [comment]
Thank you. That means a lot and is greatly appreciated. @Domino987 deserves all the praise (he has 2nd most contributions and knows this repo like the back of his hand).

We will take any and all help we can get 😄 

Cheers.

**Comment by Domino987** [comment]
hi @vizardkill The nesting and grouping is internal and the render only defines what is displayed. So changing the render function does not group them together. I don`t think that your use case is possible right now. Sorry.

But yes, we take and appreciate all the help we can get to get it up and running;)
