### ISSUE TITLE
How to prevent table title changes during onSelectionChange event?

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#127]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

don't have any working demo right now on codeSansBox.

- #### Please try to be as detailed as possible
- 
If you enable selection on your table, upon clicking the checkbox against each row, you will see the table title changes to reflect total selected rows e.g. **5 row(s) selected Search**

How to prevent this? I don't want my static table title to change when user selects rows

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by matthewoestreich** [comment]
You should be able to override the header component. Then you should be able to exclude the counter.
