### ISSUE TITLE
Column Width is not holding true

### ISSUE THREAD

**Issue by elpinto007** [material-table-core/core#128]
# Column width in Material-Table

- #### Please include a demo of the issue/behavior/question you have
I have tried a few different methods to try to define a column width. I have tried to use cellStyle, as well as headerStyle. Along with width on the column itself. For some reason, my table refuses to take that value. I used the developer tools and I saw that the inline styles add the width, and a max-width value. 

My main issue is that I find some columns take up a lot more space than they need (eg a date field). I am very new to React and Material-Table so I most definitely and doing something wrong.

Here is what I have tried:
`{
      title: "Phase",
      field: "phase",
      lookup: { 1: "1", 2: "2", 3: "3" },
      cellStyle:{
        maxWidth: 150,
        width: 150,
      },
      headerStyle:{
        maxWidth: 150,
        width: 150,
      },
    },`

Also tried:
`{
      title: "Requirement Type",
      field: "requirementType",
      lookup: { 1: "Technical", 2: "Business" },
      width: 300,
},`
Thank you for the help and the great work everyone is doing!

**Comment by matthewoestreich** [comment]
Hi. Would you mind creating a sandbox that shows the issue you are having, per our guidelines?

**Comment by matthewoestreich** [comment]
If this is still an issue, please reopen (or ping me and I can reopen if you can't) with a SandBox.

Thank you!
