### ISSUE TITLE
Looking for a fix to https://github.com/mbrn/material-table/pull/2428

### ISSUE THREAD

**Issue by gardengeek99** [material-table-core/core#129]
I looked in the current code here and it seems to have diverged.  Does this branch support specifying a function for determining whether a field is editable?  And if yes, is it used?

**Comment by matthewoestreich** [comment]
Can you please provide where in the code you looked, as well as a Sandbox, per our requirements?

**Comment by gardengeek99** [comment]
I was able to successfully use isCellEditable function to determine whether individual cells are editable.  So, the issue stated in the description has been fixed in material-table-core and I am switching to using this.  Good job all!
