### ISSUE TITLE
RESOLVE unable to resolve dependency tree - trying to install this fork

### ISSUE THREAD

**Issue by masbaehr** [material-table-core/core#13]
Any idea what to do? 

```txt
npm ERR! Found: @material-ui/core@4.11.2
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"4.11.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"4.0.1" from @material-table/core@2.1.18
npm ERR! node_modules/@material-table/core
npm ERR!   @material-table/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by matthewoestreich** [comment]
Thanks for opening this issue. I will look at this in a couple of minutes. It's odd because this didn't happen to me when I tested after publishing.

**Comment by matthewoestreich** [comment]
@masbaehr are you installing @material-table/core in a fresh project or an existing project? I tried both and cannot reproduce this issue.

What command are you running?

**Comment by masbaehr** [comment]
Does your project have  "@material-ui/core": "4.11.2", as a dependency? i tried on a clean project (without node_modules folder) and without package-lock.json 

i was able to circumvent with --force command

just did npm install

npm version: 6.14.10

**Comment by matthewoestreich** [comment]
Yep. I used `npx create-react-app` then installed material-ui and @material-table/core without any error/issue. I did use `yarn`, though, so let me test with `npm`.

This is the package.json file:

```
{
  "name": "testing",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-table/core": "^2.1.18",
    "@material-ui/core": "^4.11.2",
    "@material-ui/icons": "^4.11.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by matthewoestreich** [comment]
Can someone else test this out as well? @thefat32 @Domino987 

I can't reproduce. Just tested a fresh project with `npm` and I got no errors.

**Comment by masbaehr** [comment]
Note that i had the same issue with original material-table 1.69.2 , and it worked again when i set it to 1.69.0 
However i also re-tried on a different project and it went trough.. Very weird issue.. will try to post more info when i get it again. Thankfully i have multiple projects to switch the material-table :P

**Comment by matthewoestreich** [comment]
Thanks for the info! If you notice any patterns please let us know. Def a weird issue.

**Comment by matthewoestreich** [comment]
After doing some more research on this, I noticed a couple of odd things (which I have attempted to resolve).

- [`package-lock.json` was included in `.gitignore`](https://github.com/material-table-core/core/blob/5710c4c0892fd09aa835a51e0a086f16c0154f51/.gitignore#L5) - I have since [resolved this](https://github.com/material-table-core/core/blob/master/package-lock.json)
- Dependencies essentially had versions pinned ([no `~` or `^` being used](https://github.com/material-table-core/core/blob/57c62caf584821ca64903dbec6923c98cb69fc78/package.json#L50-L79)) - I have since [resolved this](https://github.com/material-table-core/core/blob/master/package.json#L49-L79)
- Outdated deps have been upgraded

A new version has been published as well.. would you mind testing it out?

**Comment by masbaehr** [comment]
I just tried on a different project where i did not update the packages yet, and with the 2.1.19 it did not happen! Yay.. 👍
