### ISSUE TITLE
How to reset the applied sorting?

### ISSUE THREAD

**Issue by jothikannan89** [material-table-core/core#131]
I have sortings enabled for the columns, so users can apply the sorting for the results in the table. For some cases, I want to reset the applied sorting for columns. 

Is there any way to reset/remove the applied sortings?

I tried something like 
```
          onChange={() => {
           console.log(tableRef);
           if(tableRef.current){
             tableRef.current.dataManager.orderBy = -1;
             tableRef.current.dataManager.orderDirection = "";
           }
        }}
```

But this is working for sometime, and sometime not

**Comment by matthewoestreich** [comment]
Hi. Would you mind providing a sandbox that shows what you're looking for?

**Comment by Domino987** [comment]
You need to force a rerender after the setting of the datamanger. so try this:

  ```
const [,rerender] = React.useState(0)
...
 if(tableRef.current){
             tableRef.current.dataManager.orderBy = -1;
             tableRef.current.dataManager.orderDirection = "";
             rerender(s => s +1)
           }
```

**Comment by matthewoestreich** [comment]
Please feel free to reopen if the provided solution does not work. Thanks again!
