### ISSUE TITLE
TS definition error TS2304: Cannot find name 'CSSProperties'

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#140]
**Describe the bug**

Error during build:
> ERROR in ../node_modules/@material-table/core/types/index.d.ts:95:34 - error TS2304: Cannot find name 'CSSProperties'.
> 95   }) => { value: unknown; style: CSSProperties } | unknown;

**To Reproduce**

I'm using material-table 2.3.29 in a non-CRA Typescript project. That version adds the `renderSummaryRow` prop which has corresponding TS definition updates.
I can't post company code here for repro. The TS transpiler in the project doesn't resolve from `@types/react` unless the file has a `.tsx` extension. `index.d.ts` obviously doesn't match that, and so the TS transpiler pukes. Is renaming that to `index.d.tsx` a thing?  Alternatively, could we change the `CSSProperties` type to something that doesn't depend on `@types/react`?  The best option would be to get the transpiler to recognize ts files with JSX in it, but that's proving difficult in this setup.
 
**Expected behavior**
Build should succeed.

**Desktop (please complete the following information):**

- OS: OSX (doesn't matter)
- Browser Chrome (doesn't matter)
- Version N/A

**Comment by peacechen** [comment]
I inspected the TS definition file some more and found that replacing `CSSProperties` with `React.CSSProperties` allows the build to succeed. I'll create a PR.

**Comment by matthewoestreich** [comment]
Looks like this has been resolved.
