### ISSUE TITLE
Column width auto-fit to its contents

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#145]
**Describe the bug**

Column sizing in material-table has been a mystery. I've tried passing in widths to `headerStyle` and `cellStyle` with no discernible effect. Setting `tableLayout` to auto or fixed doesn't get the results that I need. 

Here's a screenshot of the populated table. Notice that the `LINE #` column is much wider than its contents. Is there a way to get the column to shrink its width to fit the data? Conversely, it seems to expand to a certain degree to fit larger content.

<img width="922" alt="Screen Shot 2021-04-04 at 3 01 56 PM" src="https://user-images.githubusercontent.com/6295083/113520353-24ae5e80-9558-11eb-8693-7686078990e1.png">
 
 
**To Reproduce**

Nothing special with the code, just pass in data with multiple columns.

**Expected behavior**

Shrink width to fit data in cells.

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version 86

**Comment by matthewoestreich** [comment]
Thank you! That's def an issue if those props do absolutely nothing.

**Comment by ChinmayaNathany** [comment]
Hi @peacechen 

I was having the same issues but solved it by using the width as a percentage!
Obviously this is just an interim fix :)

So:
```
{
   title: 'abc',
   field: 'abc',
   width: '5%'
}
```
This works for me

**Comment by peacechen** [comment]
Thanks @ChinmayaNathany that helps. How well does that work on different size screens (mobile, tablet, desktop) ?

**Comment by ChinmayaNathany** [comment]
@peacechen  I haven't tried it on anything but desktop

**Comment by matthewoestreich** [comment]
I agree - the sizing has always been somewhat of a mystery to me as well (it's just confusing tbh)..

With that being said, I quickly scanned the [Material Design white paper for data tables](https://material.io/components/data-tables) and was not able to find anything about automatically shrinking cell width to fit data. I think we need a good review of these "little" things, just to make sure we are following the Material Design spec appropriately. 

From what I make of it each row should attempt to evenly space each cell - according to the spec.

@Domino987 thoughts?

**Comment by peacechen** [comment]
It does appear that `auto` evenly divides the width by the number of cells. Fixed has some weird not-useful behavior. Since those already exist and are in use, perhaps a new mode such as `shrink` could be introduced that is a variant of `auto`. It would first evenly divide the width by number of cells, then shrink the width of columns that have white space. Easier said than done.

**Comment by matthewoestreich** [comment]
I like it.

**Comment by andremantaswow** [comment]
> Hi @peacechen
> 
> I was having the same issues but solved it by using the width as a percentage! Obviously this is just an interim fix :)
> 
> So:
> 
> ```
> {
>    title: 'abc',
>    field: 'abc',
>    width: '5%'
> }
> ```
> 
> This works for me

Can't believe it was this easy...

I was trying in both `cellStyle` and `headerStyle` but it was ignored. putting it at the root of the column like this worked. Thanks
