### ISSUE TITLE
Incompatible version of @date-io/date-fns in dependencies & peerDependencies (Reopen of #47)

### ISSUE THREAD

**Issue by ramilamparo** [material-table-core/core#146]
Looks like the dependencies for @date-io/date-fns has been updated to version 2.x which is incompatible with @material-ui/pickers 3.

Change was made in commit with 65ca89fc2ea8d95c917a44a4055abfb35aa2a060

For now, installing @material-table/core v2.3.28 solves this issue.

**Comment by matthewoestreich** [comment]
This has been [resolved](https://github.com/material-table-core/core/blob/master/package.json#L99). Sorry about that! My fault.
