### ISSUE TITLE
Better support for automated functional testing markers

### ISSUE THREAD

**Issue by gabriel-kohen-by** [material-table-core/core#147]
This is a followup to a suggestion by @Domino987 on Material table Gitter (4/4/21) to open this as a feature request.

Per good practices of being able to locate components during functional tests (For in instance using WebDriver etc), it's common to use test-dataid to mark the component. It's a standard that the React test library promotes and mentioned by Ken Dodds in building resilient tests. I could relatively easily do so to Material UI components at large but cannot do the same to Material Table(example mark TableCell). Any idea how can I inject these extra properties/attributes without having to wrap them in an additional component?

**Comment by Domino987** [comment]
Yes I agree that this would help with the testing.
Can you try to add a PR to address this? Thanks for the idea.

**Comment by gabriel-kohen-by** [comment]
FYI: @fernando-garza-by, @elena-casillas-by, @edgar-arroyo-by, @edgar-pozadas-by. Let's see if we can have some bandwidth for this in the near future.
