### ISSUE TITLE
Right align numeric inputs when editing to be consistent with view mode

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#149]
**Describe the solution you'd like**

Numeric types in material-table are right-aligned. However when editing, they are left-aligned, which is HTML's default for all inputs. This makes the body content look like it's not aligned with the header.
<img width="745" alt="Screen Shot 2021-04-07 at 10 24 18 PM" src="https://user-images.githubusercontent.com/6295083/114029463-24a3ac80-983f-11eb-833c-462e3675a269.png">

Inputs on numeric columns should have the style `{text-align: right}` applied.

**Describe alternatives you've considered**

Only alternatives are CSS hacks.

**Comment by peacechen** [comment]
The code in MTableEditField/TextField.js attempts to right-align, but the style is applied to the parent TextField instead of the underlying input.
https://github.com/material-table-core/core/blob/master/src/components/MTableEditField/TextField.js#L10

Moreover, the style should be `text-align: right` instead of `float: right` passed to `inputProps` (lowercase i).
https://github.com/material-table-core/core/blob/master/src/components/MTableEditField/TextField.js#L27

The same fix applies to CurrencyField.

**Comment by matthewoestreich** [comment]
Per [material design](https://material.io/components/data-tables#specs) all numbers should be right aligned. Nice catch!

**Comment by oze4** [comment]
Per [material design](https://material.io/components/data-tables#specs) all numbers should be right aligned. Nice catch!

**Comment by Domino987** [comment]
This should be resolved now. Ty
