### ISSUE TITLE
disabled row being selected by select all

### ISSUE THREAD

**Issue by alphakex2** [material-table-core/core#150]
How do I stop the select all from selecting disabled rows? The issue can also be experienced on this demo https://material-table.com/#/docs/features/selection under the Conditional Selection Boxes Example

**Comment by SKaralius** [comment]
Hey, you should add a `selectionProps` prop to MaterialTable component, like so:

```
  selectionProps: (rowData) => {
      const disableCondition = true;
      rowData.tableData.disabled = disableCondition;
      return {
          disabled: disableCondition,
      };
  },
```
And also update @material-table-core, because this issue is not fixed in material-table package.

**Comment by Domino987** [comment]
Should be fixed now
