### ISSUE TITLE
User table interactions are cancelled whenever parent element render is called.

### ISSUE THREAD

**Issue by SKaralius** [material-table-core/core#151]
Hi,

I have seen an issue that is relevant to me in material-table repo, but I don't see that issue here, so I'd like to submit it for you.
[Issue in material-table repo](https://github.com/mbrn/material-table/issues/2790)
It even has a pull request attached, so maybe it wouldn't be too hard to fix?

I also made an example to show this issue with minimal code.

[CodeSandBox simple demonstration]( https://codesandbox.io/s/wonderful-forest-9px3s?file=/src/App.js)

My example is a little different from the description of the bug in the issue by the other user, but I believe they have the same root cause. 

To see the undesired interaction in the code sandbox that I linked, simply click on the edit action, and try to select some of the values in the select component under "Culprit" column. Row editing will turn off, without you actually submitting or cancelling it. Yes, there are work arounds for this example, but being able to edit your components state in edit is essential in more complex scenarios.

**Comment by matthewoestreich** [comment]
Thanks for this. I completely agree.

I will look into getting [this PR](https://github.com/mbrn/material-table/pull/2818) added to this repo. Also, we are actively pushing code here so if you feel like fixing it then sending over a PR, we try to stay on top of them. Otherwise, I *should* have time to look into this tomorrow.

**Comment by matthewoestreich** [comment]
Looks like @Domino987 merged a PR for this, which has since been published. Thanks again for this!
