### ISSUE TITLE
Position of function actions depends on selection setting and not on defined position

### ISSUE THREAD

**Issue by timkrase** [material-table-core/core#153]
**Describe the bug**
As soon as you do not define a plain object for the actions but rather a function depending on the rowData, the "position" of the resulting object is ignored and set depending on the "selection" setting.

If, for example, you want one action in the row and another in the toolbarOnSelect (and therefore define "selection" as true in the options) both actions end up in the selection toolbar.

**Demo**
https://codesandbox.io/s/material-table-starter-template-forked-zm809

**To Reproduce**
In the demo you'll see that the action that is defined to be in the "row" is not there and both actions appear in the toolbarOnSelect as soon as you select something.

**Expected behavior**
One action in the row and one in the toolbarOnSelect, as defined by the positions.

**Additional context**
In material-table.js, the position for function actions is set between lines ~200-220. If selection is true, the position is defined to be the toolbarOnSelect. If selection is false, the position is set to "row".

The rowActions function inside common-values.js filters actions for the row by the following criteria: `a.position === 'row' || typeof a === 'function'`. As the form defined by material-table.jsfor these function actions is `{action: myActionFunction, position: 'toolbarOnSelect'}` if selection is true, the action never has a chance to make it into the action component because it is neither a function nor has 'row' position.

As we need the feature at work I tried to build a (simple and unsophisticated) fix. I expanded the rowActions function to let all function actions pass through, independent of the position value defined by material-table.js (because it's not the intended one anyway). As far as I could see the Action component does not know about it's context (row or toolbarOnSelect) so I had to decide whether to display an action based on a combination of the position and whether the data is an array (toolbarOnSelect) or a single value (rows). The size for the row width depends on the actual data of the rows so I calculated the maximum number of displayed actions right at the beginning and just passed this through instead of recalculating. This is probably far away from being an optimal solution but I just wanted to leave it here as food for thought for future contributors.

You can see an overview of my changes here:
https://github.com/material-table-core/core/compare/master...timkrase:actionsFix?expand=1

**Comment by timkrase** [comment]
Well, writing all of this down and having another look at the source did let me realize that I was solving all of this overly complicated....

There is already proper support for actions of the shape `{action: function, position: string}` as this is how the getProps code currently resolves this. So why not directly pass the action like this...
Only problem then are the prop-types and ts-definitions. I added them and opened a PR so you can decide whether this should be added: #154 

Discussions can be continued inside the PR.

**Comment by matthewoestreich** [comment]
@timkrase thank you for your contribution/time!

**Comment by mvitkin** [comment]
Hi, as far as I can tell, this issue is not fixed. This code sandbox running on the most recent version of material-table/core still has the issue:

https://codesandbox.io/embed/material-table-starter-template-forked-6kc8vz?fontsize=14&hidenavigation=1&theme=dark

Maybe I'm missing something, is this working for others?
