### ISSUE TITLE
Export menu doesn’t close after action

### ISSUE THREAD

**Issue by RobertGardner** [material-table-core/core#158]
**Describe the bug**
When selecting an action in the Export menu, the action succeeds but the menu stays open. An extra click outside the menu is required to dismiss the menu. 

**Expected behavior**
The examples at material-ui.com all show an explicit call to close the menu after a menu item is clicked. The material-table/core code does not do this, and there doesn’t appear to be a way to force the menu closed. 

**Additional context**
This is obviously a minor bug in a well designed and implemented feature, but it is a bit of an annoyance to the user.

**Comment by matthewoestreich** [comment]
Completely agree! Thanks for opening this.
