### ISSUE TITLE
Duplicate columns when using editable row and fixed columns

### ISSUE THREAD

**Issue by bimbeonguyen** [material-table-core/core#167]
Describe the bug
There is a bug when clicking edit button with fixed columns at material-table then focus on the fixed column. Duplicated columns appears after pressing 'Tab' button on keyboard

Expected behavior
Duplicated columns don't appear

Codesandbox: https://codesandbox.io/s/react-material-editable-table-forked-o1w7c?file=/src/App.js

**Comment by matthewoestreich** [comment]
Nice catch! Thank you very much for opening this.
