### ISSUE TITLE
enabling columns with the columnsButton doesnt work

### ISSUE THREAD

**Issue by MarianBe** [material-table-core/core#168]
Whenever i try to show or hide any column i get an error `Uncaught TypeError: Cannot read property 'props' of undefined`
![image](https://user-images.githubusercontent.com/773986/116425150-61f9c980-a842-11eb-88e9-afa45353ba88.png)

It seems to be broken with the latest version, check this minimal codesandbox: https://codesandbox.io/s/focused-visvesvaraya-uiev4

**Comment by MarianBe** [comment]
looks like this here is the issue: https://github.com/material-table-core/core/commit/277459a0a3da79b94dc198bc830051e104b08377?branch=277459a0a3da79b94dc198bc830051e104b08377&diff=split&w=1#diff-03a5008fa690d71e0f9293401cbcf9e6551d38852b99a6a1dccd233217084602R182

**Comment by matthewoestreich** [comment]
That is actually the fix not the issue. This should be working.

**Comment by matthewoestreich** [comment]
It looks like when refactoring I left a `this.` on a functional component. 

I have since removed that - this should be working now in v2.3.32. Would you mind giving that a shot and reporting back?

**Comment by MarianBe** [comment]
fixed with v2.3.32
