### ISSUE TITLE
resizable

### ISSUE THREAD

**Issue by pouryapb** [material-table-core/core#171]
https://github.com/material-table-core/core/blob/2dcc2f8e0ab83493dcbd2c4c384714059ffe1f3e/src/components/MTableHeader/index.js#L18

resizable headers didn't work until I put `handleMouseMove` and `handleMouseUp` inside `useEffect` and added `props` and `state` to dependency array
thought you might want to know this :D
to make this compatible with rtl, `(e.clientX - state.lastX)` this needs to be multiplied by -1

**Comment by matthewoestreich** [comment]
Thank you!

**Comment by matthewoestreich** [comment]
Do you already have a PR for this? Or changes you could throw into a PR real quick? That would be awesome!

**Comment by pouryapb** [comment]
You know I'm working on another project and don't know if I can manage 8 windows open in front of me 😄
But I will fork the project today and try make changes on both

**Comment by pouryapb** [comment]
There you go
