### ISSUE TITLE
onBulkEdit incorrectly offsets the header

### ISSUE THREAD

**Issue by Llolow** [material-table-core/core#176]
![Alt Text](https://i.gyazo.com/2c1e334a03cd9961c01a07e7fc9f3c1c.gif) 
Like you see when we click on BulkEdit with the new version, it's delete the whitespace that we had in the version 2.3.30.
With this PR #144 

But TableCell is removed and the th of Action isn't removed,

  - #### [CodeSandbox](https://codesandbox.io/s/inspiring-sinoussi-bjr6g)

1. Click on edit in the table header
2. You can see the table moved to the left
3. If you want to see the old version moved to material-table/core -> 2.3.30

**Comment by matthewoestreich** [comment]
I think @peacechen is creating a PR for this. If not I can look into it.

**Comment by matthewoestreich** [comment]
So does this work in version 2.3.30?

If so, the recent changes that were made caused this. @peacechen @Domino987

**Comment by peacechen** [comment]
I have a vague recollection that this issue occurred in 2.3.30 before the showDetailPanel prop was added. Would like help confirming this @Llolow

**Comment by Llolow** [comment]
Yes this is the change in the commit  [97403eb](https://github.com/material-table-core/core/pull/144/commits/97403ebddd8b28c84161a2c3f99a94d7a64a1985).

So when we have `props.mode === "bulk"` now this return nothing, and before we had a TableCell this is the whitespace we have with bulkEdit in 2.3.30

**Comment by matthewoestreich** [comment]
I had a feeling!

@peacechen why was that change needed again? It looks like we will need to figure something else out.

**Comment by matthewoestreich** [comment]
I reverted that line and published a new version (v2.3.34) - this should be fixed.

Thanks again!

**Comment by peacechen** [comment]
Unfortunately reverting that breaks the `showDetailPanelIcon` prop.  The full fix is to adjust the header row to remove all of the empty columns in edit mode.
Please re-open this and I will debug further.

**Comment by matthewoestreich** [comment]
Ok cool. I'll open a separate issue to keep things searchable.
