### ISSUE TITLE
Detail Panel Issues

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#177]
Returning an empty cell/column when using bulk edit mode breaks the detail panel. 

@peacechen 

> Unfortunately reverting that breaks the showDetailPanelIcon prop. The full fix is to adjust the header row to remove all of the empty columns in edit mode.
Please re-open this and I will debug further.

**Comment by matthewoestreich** [comment]
@peacechen all we should have to do is this (I tested and it's working)..

@Domino987 just let me know and I'll merge/publish it..

https://github.com/material-table-core/core/blob/b96131562e95b07b64ac89775f92ebb2334b2314/src/components/MTableEditRow/index.js#L162-L166

**Comment by peacechen** [comment]
Does that leave an empty gap in edit mode where the delete icon lives?  Not a big deal unless there are multiple action buttons that take up a chunk of space. That's an improvement that can be looked at later if someone needs it.

**Comment by matthewoestreich** [comment]
I think it is. At least that is more of a visual thing and doesn't impede functionality like misaligned columns/rows does.

It sounds like we just need to check if there are any actions, and if there aren't, remove that column (during edit mode)? 

<img width="1668" alt="a1" src="https://user-images.githubusercontent.com/21092343/116624167-1102d780-a90d-11eb-96e5-867d3239df46.png">

<img width="1668" alt="a2" src="https://user-images.githubusercontent.com/21092343/116624182-15c78b80-a90d-11eb-8d59-2340b5476d02.png">

**Comment by Llolow** [comment]
At first you'r PR @peacechen is to hide the detailPanelIcon and open it with a click on the line ?

**Comment by matthewoestreich** [comment]
I was just testing and noticed when the detail panel icon is not shown, you have to handle the opening of the detail panel yourself (eg. handle on row click to then open the detail panel)? @peacechen can you confirm?

It's hard for me to think of a use case for hiding the detail panel icon outside of wanting to open the detail panel via on row click.

**Comment by matthewoestreich** [comment]
I went ahead and published v2.3.35 with that fix in the meantime..

**Comment by matthewoestreich** [comment]
Just as a note - the root issue is solved. The remaining issue is more aesthetic than a bug.

I think we should hide the entire Actions column during edit mode - I don't really see why you'd want that in edit mode anyway

**Comment by peacechen** [comment]
Yes, opening the detail panel icon on row click is the primary use case. The reason for hiding it is because multiple actions plus the detail icon consumes a lot of space.

This example is just 1 action button with the detail panel icon. Imagine how much space they take when more are added.
![screenshot](https://user-images.githubusercontent.com/6295083/106336314-41769f00-6254-11eb-9412-fab482315afa.png)

**Comment by matthewoestreich** [comment]
@peacechen apologies I remember you saying that before - my fault, it slipped my mind.

**Comment by Domino987** [comment]
> @peacechen all we should have to do is this (I tested and it's working)..
> 
> @Domino987 just let me know and I'll merge/publish it..
> 
> https://github.com/material-table-core/core/blob/b96131562e95b07b64ac89775f92ebb2334b2314/src/components/MTableEditRow/index.js#L162-L166

This should work yes.

**Comment by matthewoestreich** [comment]
I also think we need a better way to add new props to documentation. For example, `onBulkEditOpen` is a new prop but it isn't documented anywhere. That is a huge issue. We haven't added many new props, so for existing props that I haven't gotten around to documenting yet, I've been using material-table.com as a reference.

We have [our website](https://github.com/material-table-core/website) for documentation, but it requires some knowledge of Docusaurus. 

I don't have much experience with GitHub Wiki - could it serve as a "quick and dirty" place to "stage" breaking changes/new props before we get around to adding them to the official docs/website?

I'll open a new issue for adding new props to documentation - I don't want that to slip through the cracks. #179

**Comment by peacechen** [comment]
Documentation is important. It would be nice if we could auto-generate the props documentation from the TS definition. Add comments for each prop in the def, and the generator spits out formatted markdown.

**Comment by Domino987** [comment]
Is this fixed?

**Comment by matthewoestreich** [comment]
It's more of an aesthetic issue. The problem here is we can't really use prop drilling here since a child needs to pass state up the chain to the parent versus drilling down. Which is one of the reasons I started that discussion about global state. 

Adding global state makes fixing issues like this (one that isn't really a bug but an inconvenience) a lot easier.

**Comment by peacechen** [comment]
You've probably already thought of this -- React context would be a good candidate since it's lightweight and this library shouldn't need complex global state management. That introduces no extra dependencies which is a big plus.

**Comment by Domino987** [comment]
Hi @peacechen 
yes we thought about it a lot actually and we checked out a few possibilities.
Our final approach was to use redux, since its already included in the dnd package.

This is quite a lot of work, since the datamanager is a quite complex zombie object. In combination with the prop drilling,  its a lot of work.

I am thinking of throwing the data-manager and options in a context, reduce the prop drilling and move stuff to custom hooks. And after that is done, slowly introduce redux by just exchanging the hooks from context and datamager to redux with its performance improvements.
What do you guys think?
@oze4

**Comment by peacechen** [comment]
I generally like redux and have used it in my projects, but not all projects need it. Redux is 170 kB, react-redux is an additional 278 kB, for a total of 448 kB. That's a hefty chunk that all apps are forced to use regardless of whether they want to or not. I understand that react-beautiful-dnd uses redux so it's already pulled in. Long-term, consider searching for a viable substitute that doesn't use redux. With that in mind, I recommend not locking this project into redux unless there's a compelling need for it that React context can't provide.

**Comment by matthewoestreich** [comment]
@peacechen we have a discussion going on [here](https://github.com/material-table-core/core/discussions/190) about this. I'm a big fan of native context as well.

As far as the actual bundle, though, redux/react-redux aren't too big of a hit. According to bundlephobia, [redux](https://bundlephobia.com/result?p=redux@4.1.0) is 4.3kB minified and [react-redux](https://bundlephobia.com/result?p=react-redux@7.2.4) is 14.6kB minified. 

We were planning on using redux-toolkit, which appears to be larger than redux + react-redux.

We haven't really started as far as introducing global state, but I agree - using Context is prob the best route.

Thoughts?

**Comment by peacechen** [comment]
sorry about that, I should've posted in the other thread. I'll move it over there.

**Comment by matthewoestreich** [comment]
No worries. It was more so you could see what has already been discussed, etc..

Appreciate your input!

**Comment by Domino987** [comment]
Can this be closed on favor of the discussion?
