### ISSUE TITLE
See Here For Documentation For New Props

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#179]
New props were recently added - these need to be documented.

New props include: 

- `editable.onBulkEditOpen`
- `options.showDetailPanelIcon`

@peacechen are those the only two new props or are there any more?

**Comment by peacechen** [comment]
One more: `renderSummaryRow`

It would be nice if we could auto-generate the props documentation from the TS definition. Add comments for each prop in the def, and the generator spits out formatted markdown.

**Comment by matthewoestreich** [comment]
Oh nice that's a great idea!

**Comment by matthewoestreich** [comment]
Is there any existing tool we could use to help? At a high level, what would that workflow look like? I can help get it started.  

I feel like our time is better spent progressing things vs figuring out how to automate documentation for now. The truth is docusaurus is so simple, and we should be trying to limit how many props we add, updating docs won't need to happen often. 

For now I think it's just easiest to update manually. Thoughts?

**Comment by matthewoestreich** [comment]
On the MTableEditRow component what are the possible values for the `mode` prop? `"add", "update", "delete", "bulk"`?

**Comment by peacechen** [comment]
I see references to add, update, and bulk, but not delete.

**Comment by peacechen** [comment]
A casual search for TS documentation generators turns up some promising candidates.
https://medium.com/@arnog/introducing-grok-95887f217873
https://github.com/TypeStrong/typedoc

It's a convenience thing so if you're ok with manual updating, stick with that.

**Comment by matthewoestreich** [comment]
Just trying to figure out how to get the generated docs into the website. They're two different repos. We would also need the generated docs to be in docusaurus format (just json, but it has to be specific). I really like the idea of automation.

**Comment by matthewoestreich** [comment]
Here is one of the references I saw for mode == delete

https://github.com/material-table-core/core/blob/3aa6640340208c29f5e187b7714641967477fb50/src/material-table.js#L507

**Comment by matthewoestreich** [comment]
@Domino987 someone please correct me if I'm wrong, but if we want to hide the actions column during edit mode we will need to pass/add a mode prop for the main material-table.js file as well as a mode prop in the header component? I tried to find existing props that would allow me to key on whether or not editing is occurring (on the header component) but couldn't find an existing props.

**Comment by Domino987** [comment]
This would be a great addition and needed for any long term support anyway. I think some automation should be used as well so we don't have to worry about it. 
I need to look into this specific usecase in how it's handled. I'll check it out.

**Comment by matthewoestreich** [comment]
Thoughts on the best way to hide the actions column during edit mode? Idk if there is a better way. I could be missing something.

Just wanted to make sure there isn't an easier way before I start adding the "mode" prop to a handful of components.

**Comment by matthewoestreich** [comment]
As a note - also need to document the new field that was added to the `actions` prop.

`actions.handlers` accepts an object. The 'key' is the event name, the 'value' is the event handler func. We pass the event as well as props to each handler. 

For example, 

```
<MaterialTable
    actions={[{
        // ...
        handlers: { onMouseEnter: (event, props) => console.log({event,props}) }
    }]}
// .....
```

**Comment by vizardkill** [comment]
@oze4  thanks for your hard work in this incredible library

**Comment by peacechen** [comment]
> @oze4 thanks for your hard work in this incredible library

Hear hear!
