### ISSUE TITLE
defaultGroupOrder throws warning

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#187]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**
I have a simple MT. By default upon display I want to group the data based on the first column. When I use the defaultGroupOrder: 0 option in my first column definition, I get the below warning ..

Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `MTableCell`, expected a single ReactElement.

**To Reproduce**

1. Visit [codeSandBox](https://codesandbox.io/s/tender-field-2ynfy?file=/src/App.js) for more details
2. In Chrome right mouse click and select "inspect" option then in the inspect, chose "Console" option to see the warning

**Expected behavior**

Having defaultGroupOrder shouldn't throw warning as there are no arrays supplied to any table cells

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOs
- Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by matthewoestreich** [comment]
Thank you very much for this!

**Comment by matthewoestreich** [comment]
I honestly don't understand why `children` is being validated by prop types. 

It's my understanding that `props.children` is a standard/default/reserved (whatever you want to call it) React prop. Please correct me if I'm wrong, but we should be able to just remove it, right?

**Comment by matthewoestreich** [comment]
It looks like the fix is to check if props.children is an array, and if it is, to just wrap it in a Fragment.

Like this: (tested and appears to work)

https://github.com/material-table-core/core/blob/cdc304173c67dff35cb312c371a2851deb395a66/src/components/MTableCell/index.js#L77-L87

@Domino987 thoughts?

**Comment by DewangS** [comment]
Thanks @oze4 . does that mean I have to manually fix it? or will it be released as a patch?

**Comment by matthewoestreich** [comment]
It should be patched and released once @Domino987 wakes up and takes a look (he may know of a better way to fix it).

As far as I can tell, it's just a warning and isn't breaking anything. Or is it breaking something on your end? Is it urgent?

**Comment by DewangS** [comment]
@oze4 correct, it's just a warning. Haven't seen page crashing even while reloading.

**Comment by Domino987** [comment]
Hi, looks like this originates from the group row. Could we just wrap the children there?

**Comment by matthewoestreich** [comment]
Ya @Domino987 fixing at the source is prob a better idea.

**Comment by matthewoestreich** [comment]
I'm not sure what I was thinking last night, the fix is so obvious now. Just had to add a fragment around the icon (lines 137 and 153)

https://github.com/material-table-core/core/blob/7fed6f476d5eb1265865a3608ba882382ba84784/src/components/MTableGroupRow/index.js#L137-L153

**Comment by matthewoestreich** [comment]
This fix has been published in v2.3.37.

On another note, @Domino987 I had to change some npm commands - the git push at the end of the new `release:x` command was causing issues on my end.

Now just have to do:

`npm run release:patch && npm run git:push:tags`

Just something minor to take note of.

**Comment by DewangS** [comment]
Thanks @oze4 . Much appreciated.

**Comment by Domino987** [comment]
@oze4 great. If this works now, it will be great

**Comment by DewangS** [comment]
Thanks @oze4 @Domino987 just upgraded the package to 2.3.37 and warning is gone.
