### ISSUE TITLE
Resizable

### ISSUE THREAD

**Issue by pouryapb** [material-table-core/core#191]
https://github.com/material-table-core/core/blob/9c2e755ac541b644d8d0f61761ba59366b37b50e/src/components/MTableHeader/index.js#L85

Ok I was playing around with resizable columns and find out this getCellStyles function does not use additionalWidth so what happens is when components rerender due to some changes, the size will reset and if you resize just a little it jumps to the size it should have.
And I don't understand the logic of resizing here so idk how to fix it

**Comment by matthewoestreich** [comment]
@pouryapb I can try to help but I'm with you - it's very hard for me to understand some of the logic (I'm not the original author).

Maybe we can knock this one out together?

**Comment by matthewoestreich** [comment]
Also thanks for spending the time looking into it!

**Comment by pouryapb** [comment]
I dig deep in my code and I found that data about column width is in columns `tableData` and I give table the columns in state and this `tableData` in columns objects I don't get back, so when any state in my component changes, table reads columns again and loses that `tableData`. and my component got complicated and I can't find a way to separate material table from the rest. there are some components that open with actions in table (popovers and other stuff) 😞

**Comment by matthewoestreich** [comment]
Would you mind creating a sandbox? So basically when you resize a column, the tableData field is reset?

**Comment by pouryapb** [comment]
https://codesandbox.io/s/staging-cdn-t4rcp?file=/src/App.js
a very simple demonstration

**Comment by pouryapb** [comment]
after a week I finally had time to dig in code a little more!
`tableData` is actually there and it has the correct `additionalWidth` value, I think it's just not considered in first calculations. I'm just trying to make sense of the behavior, I still don't know where I need to make changes...

**Comment by Domino987** [comment]
@pouryapb could you find the error?

**Comment by pouryapb** [comment]
@Domino987 No!

**Comment by pouryapb** [comment]
Could you look at `data-manager.js` in `setColumns` function? Not sure if that is the problem.

**Comment by pouryapb** [comment]
for some reasons I can't reproduce the error in demo file in the project, but I think at line 82 of `data-manager.js` this might fix the issue I have:

`const tableData = columnDef.tableData || {
        columnOrder: index,
        filterValue: columnDef.defaultFilter,
        groupOrder: columnDef.defaultGroupOrder,
        groupSort: columnDef.defaultGroupSort || 'asc',
        width,
        initialWidth: width,
        additionalWidth: 0,
        ...columnDef.tableData,
        id: index
      };`

so it checks if tableData is defined, if not makes it.

**Comment by Domino987** [comment]
@pouryapb  I cannot reproduce that with v3 of material-table.

Can you update the the latest version and see of the error persists?

**Comment by pouryapb** [comment]
@Domino987 I still have the problem. some of the actions on my table open a popover and some open a drawer and that causes react to rerender and when it happens columns sizes will reset.

**Comment by Domino987** [comment]
I am sorry, but since I cannot reproduce it in a sandbox with the latest version, there is no way I can help you with it, unfortunatly.
