### ISSUE TITLE
Error import { OnHandlers } from './helpers'

### ISSUE THREAD

**Issue by Therapychild** [material-table-core/core#199]
# Guidelines

**Describe the bug**
typo in import statement in index.d.ts

index.d.ts is looking to import { OnHandlers } from ./helpers.d.ts when the filename is actually .helper.d.ts (the import adds an "s" to the name)

**To Reproduce**

1. Upgrade to "@material-table/core": "^2.3.28"
2. Build project with babel
3. See error

**Expected behavior**
Babel builds properly with no typos.

**Comment by matthewoestreich** [comment]
Thank you! This should be fixed in 2.3.39 (which was just published).

**Comment by Therapychild** [comment]
Awesome! Great Job on the Module1 I look forward to actually contributing.

Jeremy.
