### ISSUE TITLE
Fix for hidden columns bug from main repo

### ISSUE THREAD

**Issue by charlesc32** [material-table-core/core#20]
Can we pull in this pull request from the main repo?

https://github.com/mbrn/material-table/pull/2655

Original issue here:
https://github.com/mbrn/material-table/issues/2654

**Comment by matthewoestreich** [comment]
@charlesc32 it was a quick fix so I just went ahead and added that line.

[v2.2.2](https://www.npmjs.com/package/@material-table/core) has been published.

**Comment by bva** [comment]
@oze4 Did you checked another PR, for the same issue?
https://github.com/mbrn/material-table/pull/2493

It looks like better fix for it.

**Comment by matthewoestreich** [comment]
@bva I would have to agree with you. [`v2.2.3`](https://www.npmjs.com/package/@material-table/core) has been published.

 - Reverted changes made in v2.2.2
 - Made these changes
