### ISSUE TITLE
Columns width is static value instead of dynamic

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [material-table-core/core#201]
**Describe the bug**
When we set a width ratio on column, it is only respected on first load. When we resize the component, is is ignored.

**To Reproduce**

1. Go to 'https://codesandbox.io/s/peaceful-faraday-olywv?file=/src/App.js&resolutionWidth=150&resolutionHeight=675'
2. Resize the window to be larger
3. Column 'A' is not 70%

Note : If you refresh the page once being set to larger size, then column 'A' have correct width.
It seems that width is computed once on load and set with 'px' value instead of the formula that was on the previous library.

**Expected behavior**
On original library, it is working as expected.

1. Go to 'https://codesandbox.io/s/festive-joliot-dyvrh?file=/src/App.js&resolutionWidth=150&resolutionHeight=675'
2. Resize the window to be larger
3. Column 'A' is 70%

**Screenshots**
Correct size: 
![image](https://user-images.githubusercontent.com/25615113/118650199-79dec080-b7e4-11eb-96f2-c2fafe230072.png)

Wrong size : 
![image](https://user-images.githubusercontent.com/25615113/118650282-8cf19080-b7e4-11eb-98e7-b431940e0eaf.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Firefox
- Version : 88.0.1

Is there something we are missing ?
Yours faithfully,
LCDP

**Comment by matthewoestreich** [comment]
@Domino987 thoughts on this?

**Comment by Domino987** [comment]
We change it since the original lead to an increase in the css width tag which eventually crashes die to memory issues. 
If anybody has a proposition to fix the reevaluation without introducing said bug, we would welcome a PR.

**Comment by LeComptoirDesPharmacies** [comment]
May found the PR from when this occurs : 
https://github.com/material-table-core/core/pull/5
https://github.com/material-table-core/core/pull/175

I dig a little in the PR/code but width management became a bit complex with "width", "initialWidth", "additionalWidth", "scrollWidth" and interaction between them.

Maybe @pouryapb, @peacechen or someone else could help us ?

**Comment by Domino987** [comment]
So I took a look and it seems that the old lib introduced it with the column resize feature.
The calculation will only be applied to the cells if columnResizing is set to active.

Should be fixed in 3.0.6.
