### ISSUE TITLE
Aborting row deletion with keyboard behaves unexpected

### ISSUE THREAD

**Issue by FalkF** [material-table-core/core#208]
**Problem**
When navigating with the keyboard and deleting a row the confirmation dialog deletes the row regardless of what button has focus when pressing Enter. Only pressing Escape cancels the dialog. 

Pressing enter in this situation deletes the row
<img width="823" alt="Screenshot 2021-05-27 at 14 35 09" src="https://user-images.githubusercontent.com/19377375/119826842-c028d380-bef8-11eb-9ece-0d40ddcee2aa.png">

**Expected behaviour:**
The confirmation dialog should abort when the abort button is focused while pressing enter.

I might have time to tackle this in the upcoming weeks, but wanted to keep this here for reference.

**Comment by Domino987** [comment]
Will be fixed with next release. Ty :)
