### ISSUE TITLE
hiddenByColumnsButton should hide in the table but show in the columnsButton selector

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#21]
**Describe the bug**

The prop `hiddenByColumnsButton` is documented on material-table.com along with the `hidden` prop. The latter completely removes the columns. They don't render either in the table or in the columnsButton selector.  Use case is that some columns should be hidden initially, but selectable if the user chooses to show them.

https://github.com/mbrn/material-table/search?q=hiddenByColumnsButton

**To Reproduce**
Create a `columns` array and pass it to material-table.  Any of the columns with the field `hidden` are not visible in the column selector menu that's enabled by `options.columnsButton`.  I hoped that `hiddenByColumnsButton` would allow them to remain in the menu and hide them in the table, but unfortunately it doesn't have any effect when set in the columns data.

```
      <MaterialTable
        columns={columns}
        options={{
          columnsButton: true,
        }}
      />
```

**Comment by peacechen** [comment]
Here's how those props work:
> `hidden`: When set, the column does not show in either the table or the columnsButton selector.
> `hiddenByColumnsButton`: This allows the column to show in the columnsButton selector, but it must be set in conjunction with the `hidden` prop. This has no effect if set by itself.

This is not documented well and isn't intuitive.  I propose that we change the behavior so that `hiddenByColumnsButton` set by itself hides it in the table but shows it in the columnsButton selector. `hidden` would remain the same and force the column to be removed everywhere (table and columnsButton selector).

Example of how it must be used today:
```
  const allColumns = [
    {
      title: "My Column",
      hidden: true,
      hiddenByColumnsButton: true,
    },
```

**Comment by matthewoestreich** [comment]
Let me know how I can help!

**Comment by peacechen** [comment]
I'll work on this as time permits. It's functional so this is a low priority issue. This project needs a detailed list of props like the one at:
https://material-table.com/#/docs/all-props

That's comprehensive but the prop definitions could be improved.

**Comment by peacechen** [comment]
I created a PR to address this.  See #24 for more details.

I suggest that we add the list of props to the main Readme. It's a hassle hunting for them on separate documentation pages. That will also free up the demo site to focus on examples.

**Comment by matthewoestreich** [comment]
@peacechen I agree. We need a better way to keep track of all props.

**Comment by matthewoestreich** [comment]
See here for more https://github.com/material-table-core/core/pull/24
