### ISSUE TITLE
When you open a dialog, hidden /revealed columns state is reset.

### ISSUE THREAD

**Issue by thpapei** [material-table-core/core#215]
**The bug**
When you open a dialog, hidden/revealed columns state is reset.

**To Reproduce**
1) Hide or reveal some table columns using the "Show Columns" menu. 
2) Then open a dialog using Actions (either free or inline)
3) The columns are reset. 

**Expected behavior**
Opening a dialog should not affect the state of hidden/revealed columns chosen by the user.

**Comment by matthewoestreich** [comment]
For now the work around is to memoize the table/column data before passing to MaterialTable. If you search closed issues you'll see where someone resolved it that way. We are currently working on a fix.
