### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#217]
Hey @Domino987 do you know why the newest release shows version 0.0.2?

**Comment by Domino987** [comment]
Ah yes, I missed one line in the release script.

I decided to release a next version which supports mui v5, but I missed a tag in the release script.
It is fixed but to show the correct version in the github page, we would need to release a new version of master.

The v5 branch is instabbalbe with `npm i @material-table/core@next` with its own versions.

But the next release will also tag it with `-next`.

Sorry for the confusion. Still working on the readme.

**Comment by matthewoestreich** [comment]
No worries at all! That's awesome actually. Nice work.

**Comment by matthewoestreich** [comment]
Hey @Domino987 version is broken again..

**Comment by Domino987** [comment]
Hi can you describe it in mir detail? What is broken.

**Comment by matthewoestreich** [comment]
It looks like it's fixed now. I was still showing release 0.0.2 but not any longer.. it's now showing correct.
