### ISSUE TITLE
README

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#218]
@Domino987 should we take the documentation you added to the README and merge it with what we have on the website? Just easier to keep everything in one spot imo (otherwise when something changes we'll need to update 2 places).

Thoughts?

**Comment by Domino987** [comment]
Hi yes i was thinking about it and I really like the website so far. The only problem is tagt most people just read the readme fiest without accessing the website . Can we automaticly inject the website readme to our readme or the other way around?

**Comment by matthewoestreich** [comment]
Totally agree. That's something I thought of when I only put links in the readme. Basically forcing the reader to the website. The first link is for the install. 

I think it's more trouble than it's worth trying to spend the time working out how to inject it vs just keeping in one place.

**Comment by Domino987** [comment]
Yes I agree. Lets move everything to the website then. I should be able to do it this weekend

**Comment by Domino987** [comment]
Moved to the website again
