### ISSUE TITLE
[next] Use 4.0.0-alpha.1 for pre-releases

### ISSUE THREAD

**Issue by FedeBev** [material-table-core/core#219]
Current pre-release is tagget `v0.0.2`, wich could lead into confusion and won't work properly with tools such as `yarn outdated`.

Why don't we use what [semver suggests](https://semver.org/#spec-item-9)? This way would also be consistent with MUI

**Comment by matthewoestreich** [comment]
Apologies - v0.0.2 release was created by accident. It has been deleted. Please let me know if you still have any issues.
