### ISSUE TITLE
onSelectionChange prop does not work correctly if rowStyle/cellStyle is a function 

### ISSUE THREAD

**Issue by kylenguyen1014** [material-table-core/core#223]
**Describe the bug**
onSelectionChange prop does not work properly if we set rowStyle/cellStyle as a function. Checkboxes will not get checked if row selected is a component's state

**To Reproduce**

1. Make a simple table
2. Set selection = true
3. Set onSelectionChange to handle component's state of which rows get selected
4. Pass in rowStyle/cellStyle as a function
5. See error

**Expected behavior**
Checkboxes should be checked correctly based on rows selected (rows selected must be link to component's state)

**Screenshots**
![image](https://user-images.githubusercontent.com/43191329/121532018-f708ea00-c9cc-11eb-82b1-cee15df444f9.png)

**Desktop (please complete the following information):**

- OS: Window 10 Pro
- Browser Chrome
- Version 3.0.5

**Additional context**
Sandbox sample : https://codesandbox.io/s/loving-pine-m0bgz?file=/src/App.tsx

**Comment by Domino987** [comment]
Thank you for catching this.

It seems like if options contains functions, these must be stable between renders to we don't assume that new that was added and the selection gets reseted.

So either wrapping the rowstyle in a React.useCalback or generating it outside of the render function/function component fixes this.

I as not aware this was a problem so I will add it to the docs.

**Comment by Domino987** [comment]
Closing in favor for it being added to the docs.

**Comment by joelcoronah** [comment]
> Thank you for catching this.
> 
> It seems like if options contains functions, these must be stable between renders to we don't assume that new that was added and the selection gets reseted.
> 
> So either wrapping the rowstyle in a React.useCalback or generating it outside of the render function/function component fixes this.
> 
> I as not aware this was a problem so I will add it to the docs.

Any code sample please?

**Comment by Domino987** [comment]
@joelcoronah https://material-table-core.com/docs/breaking-changes#functions-in-the-optionscolumns-props

**Comment by joelcoronah** [comment]
> @joelcoronah https://material-table-core.com/docs/breaking-changes#functions-in-the-optionscolumns-props

the checkbox its not checked if I select, I do not see the problem, when I use a function in the onSelectedChange this happens, even if the function has useCallback

**Comment by Domino987** [comment]
Can you share your code in a sandbox?
