### ISSUE TITLE
Inefficient rendering behavior

### ISSUE THREAD

**Issue by ifndefdeadmau5** [material-table-core/core#224]
### Issues from the original repository
https://github.com/mbrn/material-table/issues/1085
https://github.com/mbrn/material-table/issues/2581

### Context
Sorry for not following the template, I just thought above issues are kinda obvious to you guys.
As you might notice this table completely re-renders(or may have to say, *re-mount*, not sure) even nothing from rowData has changed. I'm curious if this community fork already has a fix? which I don't think it's true because when I tried with this package I was able to confirm same performance problem.

**Comment by Domino987** [comment]
Maybe using the React.memo wrapper around each row might improve the rendering. 

I don't have any problems with the performance yet, but maybe can you create a sandbox ?

**Comment by ifndefdeadmau5** [comment]
> Maybe using the React.memo wrapper around each row might improve the rendering.
> 
> I don't have any problems with the performance yet, but maybe can you create a sandbox ?

@Domino987 
Memoizing `Cell` and `Table` improved meaningful performance in my case(in ugly way), but still you can confirm that every rows are re-rendering with `selection: true` option whenever checkbox is toggled(with React Profiler).

![image](https://user-images.githubusercontent.com/8914311/121838336-8df9dd00-cd12-11eb-9e48-e5d7482f3aae.png)

This is also related to the problem(#1265) that material-table completely re-mount when parent hooks(or state) change, which is the reason why I had to memoize `Table` itself above.

**Comment by matthewoestreich** [comment]
Isn't that expected behavior? When a parent has props or state change it is rerendered along with all of it's children? Whether or not that's material table, it's outside of our control. 

We are working on a way to internally memoize columns and data so it's not so ugly for the consumer. 

We are also working on global state mgmt, which should help with unnecessary rerenders like you're seeing with the rows.

**Comment by ifndefdeadmau5** [comment]
> Isn't that expected behavior? When a parent has props or state change it is rerendered along with all of it's children? Whether or not that's material table, it's outside of our control.
> 
> We are working on a way to internally memoize columns and data so it's not so ugly for the consumer.
> 
> We are also working on global state mgmt, which should help with unnecessary rerenders like you're seeing with the rows.

Re-rendering is fine. But un-mounting is not something user would usually expect from the sane library. Unlike un-mounting, unnecessary renders could easily prevented with `React.memo` so that should be fine and natural.

Glad to hear that you guys are working on alternative state mgmt system, though. (I suspect that must be a `data-manager` utility) I appreciate guys working on this fork

**Comment by matthewoestreich** [comment]
Ah yes I must have misread "remount" as "rerender" in your comment. I agree.

Actually we are trying to get rid of that data-manager haha it's a mess..

**Comment by usahai** [comment]
@oze4 hey, great to see you're on this project! I've been using material table for a while now, since early last year, and remember reading some parts of the threads where you were requesting for your PRs to be accepted to the original repo. Glad to see the good work being carried forward.

**Comment by Domino987** [comment]
@ifndefdeadmau5 The main problem is the setup of the table itself, from the original author.

There is deeply nested prop drilling which results in up to 40 props in combination with on the fly generated objects and function which are not memoized/stable between renders so the React.memo does not do anything because the props change anyway.

Once we moved to context, we should be able to reduce the props and make them stable between renders, which in turn also us to do a React.memo wrapping around rows most likely.

**Comment by matthewoestreich** [comment]
Just as a status update, we have started to introduce `context` via the [context branch](https://github.com/material-table-core/core/tree/context).

It may take some time to resolve this issue as it's more of a systemic/engineering issue as opposed to lower level bug in code (if that makes sense).

Thanks again everyone for helping us move this project forward! ❤️ 👍

**Comment by matthewoestreich** [comment]
Hi @ifndefdeadmau5 would you mind trying out the latest version (4.0.0) to see if there is any improvement?

**Comment by testfileKing** [comment]
How do I test out this new version? I'm currently working on something and wanted to see if version 4.0.0 prevents multiple re-renderings on parent state update.

**Comment by matthewoestreich** [comment]
You'd run `npm install @material-table/core` or `yarn add @material-table/core` in order to upgrade to the latest version.

**Comment by testfileKing** [comment]
@oze4 I've just tested this out, and looks like the issue is still there:
![image](https://user-images.githubusercontent.com/47969014/128623655-d339079c-d4fb-4ebb-baef-d89a5ea435c6.png)

**Comment by alex-phillips** [comment]
Any update on this?
