### ISSUE TITLE
Handle a case that the previous sorted column doesn't exist in the new columns

### ISSUE THREAD

**Issue by ghyoo91** [material-table-core/core#228]
**Is your feature request related to a problem? Please describe.**

Sandbox : https://codesandbox.io/s/boring-allen-kgc9t?file=/src/App.js

Table crush under the following conditions;
Steps :
1. Table has the different 2(or more) states of columns and data.
2. The 1st column set has "A", "B", "C", "D" columns when the 2nd has "A", "B".
3. Sort by "C" or "D" column **asc** in the 1st column set. (That does not exist in the 2nd column set)
4. Change the data and column state into the 2nd.
5. Then the crush occur with the below Error message:

> Cannot read property 'customSort' of undefined
> material-table/core/dist/utils/data-manager.js:761:21
> material-table/core/dist/utils/data-manager.js:1034:34
> material-table/core/dist/utils/data-manager.js:161:15
> material-table/core/dist/material-table.js:710:40

![crash](https://user-images.githubusercontent.com/20279300/122358636-cb1ed300-cf8f-11eb-847e-5f4647b50067.gif)

**CAUTION : This error doesn't occur when the "desc" order is applied.**

**Describe the solution you'd like**
I don't know this is the intended behavior(and is there some options that control this feature?), but we can handle this issue with some error handling. 

Like desc case, just set the sorted column to the defaultSort column(or the first column if the defaultSort didn't defined) can be the solution when the previous sorted column doesn't exist in the new columns.

**Describe alternatives you've considered**
I'm not sure, but I think this is the side-effect of the https://github.com/material-table-core/core/pull/192.

**Comment by matthewoestreich** [comment]
Thank you for opening this! We will get to it ASAP (if you would like to submit a PR we will merge it ASAP as well).

Thanks again!

**Comment by Domino987** [comment]
Hi great first issue.

I guess changing of the columns is not really common, that's why it never surfaced. Thanks for catching this.

This is fixed with the new release 3.0.7.
