### ISSUE TITLE
is there any way to have Row Double click event?

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#229]
# Guidelines
I am using Material Table and upon Row click, I open the clicked row in another page for editing and this works fine though users want to copy\paste text from the row instead of opening it for editing. The moment they try to select any text, the rowClick event gets fired (as expected) and they get routed to the editing page.

Is there any way to route only when they double click the row? Can't see anything in the APIs for MTable.

**Comment by Domino987** [comment]
That is not supported out of the box.
You could remove the onClick, override the row component and implement your own on double click behavior for the rows.

**Comment by DewangS** [comment]
Thanks @Domino987 for now I went with 'Actions' and have a pen icon for user to click if they want to edit though would be nice to have both even handlers in the base npm package.. just a thought

**Comment by Domino987** [comment]
I added a PR to enable a double click. What do you think?

**Comment by DewangS** [comment]
Thanks @Domino987
