### ISSUE TITLE
Title for 'actions'

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#231]
noticed that when you add actions array to MT definition, the first column title always shows as 'Actions'. Is there any way to hide this title? so far I have tried title: '' and title: false but nothing works and there is nothing in the API to suggest if this can be customised. It would be nice to have a flag to show\hide it

e.g. 

```
<MaterialTable
                title="Search Results"
                icons={tableIcons}
                columns={columns}
                data={searchResults}
                actions={[
                  {
                    icon: EditIcon,
                    tooltip: 'Edit',
                    title: '',
                    onClick: (event, rowData) => {
                  
                      handleRowClick(
                        rowData.application_id,
                        rowData.changeRequestID,
                        searchCriteria
                      )
                    }
                  }
                ]}
```

**Comment by matthewoestreich** [comment]
I do not believe there is a workaround unfortunately. I believe this is related to another issue, but I can verify tomorrow. 

I'll let you know what I find.

**Comment by Domino987** [comment]
You can just set the localisation of header.sctions to be an empty string. So the header will have no text.

**Comment by Domino987** [comment]
Here is an example sandbox without the action title. https://codesandbox.io/s/clever-currying-4it1u?file=/src/App.js

**Comment by DewangS** [comment]
@Domino987  Legend mate... works like a charm. Thanks heaps.
