### ISSUE TITLE
Data modifications get erased inside material table core

### ISSUE THREAD

**Issue by edgar-arroyo-by** [material-table-core/core#236]
**Describe the bug**
My pardons because this bug report/question may look weird.

Lets say, I have an implementation of material table core in which I use an action. On that action, when its clicked, I modify the rowData object in order to add a property to it.

```tsx
const actions: any[] = [
    {
      icon: "save",
      tooltip: "Smth",
      onClick: (event: any, rowData: any) => {
        rowData["onSmth"] = true;
        setColumns(generateColumns());
      },
    },
  ];
```

You may ask, what do I did this?

At the columns, in a column, I render something if that onSmth is on true and something else if it is false:

```tsx

 const generateColumns = (): Column<IPerson>[] => {
    return [
      {
        title: "First Name",
        field: "firstName",
        render: (rowData: any) => {
          if (rowData.onSmth) return <>Smth</>;
          return <>{rowData["firstName"]}</>;
        },
      },
      { title: "Last Name", field: "lastName" },
      { title: "Birth Year", field: "birthYear" },
    ];
  };

```

So, what I achieve is something like this:

![material table row data](https://user-images.githubusercontent.com/79274227/123708741-89b0e200-d831-11eb-8987-29059b353fbd.gif)

_When the action is clicked, instead of the value I render Smth_

You can find a fully codesanbox implementation over here:
https://codesandbox.io/s/rowdata-missed-ct3zb?file=/src/App.tsx

This perfectly used to work on version 2.3.40 but then, I updated to the newest version and it stop working.
![material table row data erased](https://user-images.githubusercontent.com/79274227/123710043-a9e1a080-d833-11eb-93ff-c966a023c023.gif)

I know this example can be easily fixed saving the data on the state and then on the click event of the action, updating the state but, because on the real implementation I have the used approach is described I am just wondering:

1. Does this change of behavior was on porpoise or is a side-effect of other changes? or why is this happening?
2. If this is on porpoise, then well :), if not, do you have any idea of where (an approximation) is this happening so I can contribute with a PR  in order to fixed?

**To Reproduce**

1. Go to https://codesandbox.io/s/rowdata-missed-ct3zb?file=/src/App.tsx
2. Click on  the action icon, in the first name column, Smth should appear instead of the name
3. Scroll down to the list of versions, and change the @material-table/core version to the newest one v3.0.12. 
4. Try clicking on the action again an see the error.

**Expected behavior**
![material table row data](https://user-images.githubusercontent.com/79274227/123710848-0b563f00-d835-11eb-9c5f-f21b99bedbe0.gif)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] Chrome 
- Version [e.g. 22] Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by matthewoestreich** [comment]
> I know this example can be easily fixed saving the data on the state and then on the click event of the action, updating the state but, because on the real implementation I have the used approach is described I am just wondering:
> 
>     1. Does this change of behavior was on porpoise or is a side-effect of other changes? or why is this happening?

This behavior is expected behavior.

The reason why changing `rowData`, inside of the `onClick` callback, does not work is because of scope and the fact that `rowData` is a callback argument. It does not live in state.

Remember, if you want changes to reflect on screen in "real" time then the dynamic data (aka variable, etc..) has to live in state.

**Comment by matthewoestreich** [comment]
Also, the reason why this doesn't work in version 3.x is because this was actually a "bug" and you shouldn't be able to modify it like you were. You can see [this issue, which](https://github.com/material-table-core/core/issues/200) has a lot more details on why it was removed.

**Comment by edgar-arroyo-by** [comment]
Hello there, thanks for answering @oze4 :)
