### ISSUE TITLE
Pagination Override or Keeping Default Sorting with Remote Data

### ISSUE THREAD

**Issue by Vitorbnc** [material-table-core/core#238]
Hello!
I'd like to fetch paginated data from the server but still be able to use the built-in sorting and the same filter inputs (with custom fetch logic of course).
I thought about overriding the pagination component but I couldn't find a good example or the specific props.
What is the best way to do it?

**Comment by edgar-arroyo-by** [comment]
Hello there, if what you want is to override the pagination component, you can use material table prop `components`

https://material-table.com/#/docs/features/component-overriding

**Comment by matthewoestreich** [comment]
Per our guidelines, would you mind creating a reproducible sandbox? We have CodeSandbox and StackBlitz templates you can fork to make it easier on you.

In my opinion, since [you have control over the 'fetching function'](https://material-table-core.com/demos/remote-data/basic#usage), you should be able to just sort it yourself prior to returning.

```js
<MaterialTable
  // ...
  data={(query) =>
    new Promise((resolve, reject) => {
      let url = "https://reqres.in/api/users?";
      url += "per_page=" + query.pageSize;
      url += "&page=" + (query.page + 1);
      fetch(url)
        .then((response) => response.json())
        .then((result) => {
          // 
          // ** DO SORTING HERE **
          //
          const sortedData = functionThatSortsMyData(result.data);
          //
          resolve({
            data: sortedData,
            page: result.page - 1,
            totalCount: result.total,
          });
        });
    })
  }
/>;
```

**Comment by Vitorbnc** [comment]
Is there a prop for supplying a callback for sorting change?

Using the remote data feature completely disables the global `onFilterChange` calls, so the filter components will have to be reimplemented too (this was done already to add validation text).

I am using useSWR for data fetching and caching but it's a hook, so it doesn't seem to fit well with the remote data model.
It's working well without remote data, but it seems the table stales when fetching.

I'll try creating a sandbox soon.

**Comment by Vitorbnc** [comment]
Also, I believe I could push the new filter box with validation here. Basically, you supply an optional `filterValidation` function per column:
`filterValidation:(val)=>{(...) return {valid:false,text:'Inválido'}; return {valid:true,text:''}`

There's another arguably useful change that was made too.  By default `onFilterChange` isn't called if the filter box gets empty. I am checking the previous state to call it, but I think it would be more efficient if the source code were altered to call it by default.

What is the proper way to contribute? Just clone, branch, push, merge?

**Comment by matthewoestreich** [comment]
I'm not so sure I like adding the filterValidation prop for columns. I don't understand the use case for having such a prop. If I'm trying to filter a column, who's to say that what I'm looking for is invalid?

This seems like a niche edge case which I don't think should be added to this library.

With that being said, I am still open to adding this functionality if it is useful.  The only way to understand your use case for filter validation would be if you created a sandbox or at the very least some code.....

**Comment by matthewoestreich** [comment]
Also, retaining sorted/filtered (or selected rows), etc.. is a little tricky with remote data. That is because we don't cache any data for you. We only send a request to a URL with certain "pagination" params.. 

Like this:

```js
// Part of a demo that shows how to use pagination with remote data..
// It's all about the query params and how your backend is configured.
data={query =>
  new Promise((resolve, reject) => {
    let url = 'https://reqres.in/api/users?'
    url += 'per_page=' + query.pageSize
    url += '&page=' + (query.page + 1)
    fetch(url)
      .then(response => response.json())
      .then(result => {
        resolve({
          data: result.data,
          page: result.page - 1,
          totalCount: result.total,
        })
      })
  })
}
```

Retaining sorted data (caching) would need to be implemented in user land.

The link below has a demo which shows how to retain selected rows across pages when using remote data, which you can try to mirror if you would like.

https://github.com/mbrn/material-table/issues/1921#issuecomment-635049441

In my opinion, your backend should allow for you to supply query params for you to send a query requesting data in a certain order. That is the real fix here, imo.

**Comment by Vitorbnc** [comment]
@oze4  you are right, we are implementing this features in the backend. 

It is sort of a niche case, some of the fields are codes that need to be in a specific format, but the use for `filterValidation` is just reducing the number of requests. 

I managed to get the filter values by reimplementing the filter components. However, is there a way to reuse the default sorting arrows, or is that going to need a rewrite too? The callback `customSort` isn't called with remote data.

**Comment by Vitorbnc** [comment]
Nevermind, just found out not only sorting but all the filter data is available in the `query` object!

I don't believe this is properly documented though, it's really useful. This information should be made more visible.

Anyway, I'm closing this issue as the problem is solved.
