### ISSUE TITLE
Heading cells moving when dragging column

### ISSUE THREAD

**Issue by pedro-pool-by** [material-table-core/core#241]
Hi everyone.

I'm not sure if this a bug or an intended functionality. Here is a fork of material table core

https://codesandbox.io/s/material-table-starter-template-forked-kikgi?file=/src/index.js

I just added another column and the "draggable" prop. When I drag a column the header cells of the other columns move to the right. I inspected them and the cells are added a "transform: translate()". 

https://www.loom.com/share/4de7697ad7da4bf98acc2110023be89a

I'm dragging 'Id' column and the other 2 columns are moving to the right.

Is this a bug or a intended functionality? Is there a way I can remove this effect?

Thanks in advance.

**Comment by edgar-arroyo-by** [comment]
![material-table-starter-template (forked) - CodeSandbox](https://user-images.githubusercontent.com/79274227/124157844-d75e6200-da5e-11eb-9460-f9ef9bac8018.gif)

Gif of the behavior that is currently happening

**Comment by matthewoestreich** [comment]
Thanks for this! I do not believe that is intended behavior. I can dig more into this.

Thank you all!

**Comment by Domino987** [comment]
Thank you for finding this. It is fixed with 3.0.13.
The dragging style will now only be applied to the dragged item instead of all headers.

**Comment by pedro-pool-by** [comment]
Thanks a lot!
