### ISSUE TITLE
Opening dialog upon selected rows clears all row selections

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#242]
**Describe the bug**
Whenever I open a dialog on top of the table, all selection checkboxes reset themselves.
This is an unwanted behavior, because I let the user make selections in that dialog based on the selected rows.

**To Reproduce**

1. Create a new action that opens a dialog on click
2. Select any amount of rows through the checkbox
3. Click on that action
4. Now all selections disappear

**Expected behavior**
I expect the selections to stay when a dialog appears. I want to decide myself when I want to deselect the rows.

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.4
- Browser: Google Chrome
- Version: 91

**Comment by Domino987** [comment]
Can you create a sandbox for us?

**Comment by matthewoestreich** [comment]
Hi - [per our guidelines](https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#please-include-a-demo-of-the-issuebehaviorquestion-you-have) please include a sandbox.

**Comment by rjumatov** [comment]
I found the issue by trying to reproduce it in a sandbox. It was an anchor element I was creating for a menu-action that was misplaced.
