### ISSUE TITLE
Checkbox triggers onRowClick since v3.0.13

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#243]
**Describe the bug**

Since v3.0.13 I encounter the problem that clicking on a selection checkbox triggers the onRowClick-function.
I've created two sandboxes that illustrate the behavior.
- #### [Bug Illustration v3.0.13](https://codesandbox.io/s/material-table-starter-template-forked-pdims?file=/src/index.js)
- #### [Working copy v3.0.12](https://codesandbox.io/s/material-table-starter-template-forked-647p3?file=/src/index.js)

**To Reproduce**

1. Go to 'Bug illustration v3.0.13'
2. Click on any row checkbox
3. OnRowClick gets triggered

**Expected behavior**

1. Go to 'Working copy v3.0.12'
2. Click on any row checkbox
3. Checkbox gets selected and nothing else

**Desktop:**

- OS: MacOS Big Sur 11.4
- Browser: Google Chrome
- Version: 91

**Additional context**

My application relies on selecting checkboxes and performing certain actions through the toolbar. Triggering onRowClick makes the application unusable in my case.

**Comment by Domino987** [comment]
Nice catch. This is connected to how react handles synthetic and native events. Moved the click logic back to react synthetic event loop and this should be fixed with 3.0.14.
