### ISSUE TITLE
Support export all data (currently only the current page is exported)

### ISSUE THREAD

**Issue by bva** [material-table-core/core#25]
PR: https://github.com/mbrn/material-table/pull/2344

This PR fixes exporting of remote data when exportAllData property is set.

**Comment by peacechen** [comment]
That's a useful feature. What happens if the remote data is very large? There are some data sets with hundreds of thousands of rows, and fetching all of them would consume a lot of memory.

Our app uses the server to generate the CSV, returning a link to the file stored on the server. The client then does the `<a>` click trick to automatically start the download. I would like to see that capability supported.

```
  const autoDownload = link => {
    if (!link) {
      console.warn("No link available.")
      return;
    }
    let a = document.createElement('a');
    a.href = link;
    a.click();
  }
```

**Comment by peacechen** [comment]
This is a valuable feature to incorporate. It could have issues with large data sets (see above). Those cases would require back end support, so users would need to roll their own file download solution.

Some notes on improving the PR:

- `remoteDataGetter` is a new prop that would need to be added to the documentation.
- The prop passed internally to material-table should be created outside of the JSX to make maintenance easier.
  https://github.com/mbrn/material-table/pull/2344/files#diff-9a3982db9efabfd577b96de4d6949e3f608ac75defb3e1c99fd5294e465cbfa5R994


@oze4 What are your thoughts?

**Comment by matthewoestreich** [comment]
The way data is exported has changed. We now use the [exportMenu](https://material-table-core.com/docs/api/props/options#exportmenu).

I am not sure if we are still only exporting visible data, but I think by default we should export all data by default, and the consumer should have to specify if they want just the current page exported.

We can add it as a field on the object that gets passed..

```js
exportMenu={[
  {
    label: string
    exportFunc: (columns, data) => void,
    // add the field below
    currentPageOnly: boolean, // or whatever we want to call it
  },
]}
```

**Comment by matthewoestreich** [comment]
Keep in mind, this would be considered a "feature" and we are currently not adding features. We are trying to get everything refactored into functional components, add support for the newest version of material-ui, as well as resolve structural issues within this code base, before adding anything new.

**Comment by peacechen** [comment]
It looks like exportMenu only works on local data. This PR is to export remote data. When material-table is used in remote data mode, the client doesn't have the full set of data available to export.

**Comment by matthewoestreich** [comment]
Right now it only works on local data, that is correct, but we are changing that... 

Part of the issue with this code base is props everywhere. The last thing we need to do is add another prop. There are ways we can handle remote data and local data via an API that is more intuitive.

**Comment by peacechen** [comment]
Is there a discussion or issue we can link to here? Should this issue be closed?

**Comment by matthewoestreich** [comment]
We can keep it open, as well as add a discussion - whichever you prefer.

I think starting a wiki or something for proposed changes is a good idea.

I have also tagged this issue accordingly.

**Comment by matthewoestreich** [comment]
@bva @peacechen technically, you could accomplish this right now ~~(just a little hacky)~~ actually, I don't think this is hacky at all.. I think this is how it should be handled...

```js
<MaterialTable
  options={{
    exportMenu: [{
      label: "Export All Data",
      exportFunc: (cols, datas) => {
        // do whatever you need to do here - you can send an API request to 
        // get all remote data, then export however you wish, completely ignoring
        // the `(cols, data)` params.
      }
    }]
  }}
/>
```

**Comment by webark** [comment]
@oze4 are we still open to this "all pages" flag potentially?

**Comment by webark** [comment]
nevermind. I just found the `exportAllData` flag!

**Comment by webark** [comment]
I might open up an issue for discussion around that it would be nice to be able to choose to export hidden columns if one wanted to.

**Comment by webark** [comment]
ohhhh... you can set the "export" to true on the column.. sorry. 😬
