### ISSUE TITLE
Date filter error

### ISSUE THREAD

**Issue by vizardkill** [material-table-core/core#251]
Colleagues I hope you are very well, I would like to report an error that I found when using the library in its version 0.0.4, because I use @ material-ui v5.

The error turns out to be when I apply the filter property and the elements are of type date

-----
` columns={[
                        {
                            title: "Fecha inicio",
                            field: "dtFechaInicio",
                            type: "date",
                        },`

------
`  options={{
                        grouping: true,
                        title: true,
                        rowStyle: {
                            fontSize: 12,
                        },
                        filtering: true,
                    }}`

`Failed prop type: The prop `renderInput` is marked as required in `ForwardRef(DatePicker)`, but its value is `undefined`.`

**Comment by matthewoestreich** [comment]
Hi! Thanks for this. Per our guidelines, would you mind creating a CodeSandbox that reproduces this issue?

**Comment by matthewoestreich** [comment]
https://github.com/mui-org/material-ui-pickers/issues/1750

Looks like this was a new prop added on mui's side. @Domino987 are you aware of this?

**Comment by Domino987** [comment]
Hi no I am not but I will look into it this weekend. I wanted to look at the issues and PRs tomorrow.

**Comment by vizardkill** [comment]
@oze4  If you want I can help you to review and send you the corrections so that you can work the branch.

**Comment by vizardkill** [comment]
I will create a sandbox later so that we can check the error, as  @oze4  mentions, it may be due to the new MUI accessories in version 5, since this version uses the date library within its core

**Comment by Domino987** [comment]
This should be fixed with the newest next version v0.0.7
