### ISSUE TITLE
Possible memory leak when data updates frequently

### ISSUE THREAD

**Issue by RomaBogatikov** [material-table-core/core#253]
# Material-table/core v.3.0.6.
# Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)

I need to update table frequently (every second), and I need to have multiple tables rendered on the same page that render the same data (I apply different filters to this data in my use case, but this doesn't seem to matter for the issue that I have).
I put data in React Context, and tables reference data from the context (this works since data objects are not modified anymore by appending 'tableData').

If my setup is left running for a few hours, we can observe a significant increase in a JS heap size.

Original state, when app first started:
![image](https://user-images.githubusercontent.com/40308050/125087829-d353c500-e09a-11eb-985e-6222629cfc39.png)

After about 8 hours:
![image](https://user-images.githubusercontent.com/40308050/125087963-f7afa180-e09a-11eb-86e4-2bd9c051831b.png)
![image](https://user-images.githubusercontent.com/40308050/125088040-0c8c3500-e09b-11eb-8ff2-66c8c9f7295b.png)

After 30 hours:
![image](https://user-images.githubusercontent.com/40308050/125087996-0007dc80-e09b-11eb-8cd8-cb14f54423a6.png)

The memory heap size after 30 hours swings anywhere from 150MB to over 500 MB.

Is this a bug or am I doing something wrong?

In the demonstrations below I update data every 300ms.
Sandbox: https://codesandbox.io/s/material-table-starter-template-forked-ejfk7?file=/src/index.js
Project repo: https://github.com/RomanBogatikov/material-table-memory-leak (easier to see the heap size increase when not in a sandbox)

**Comment by matthewoestreich** [comment]
Does the data in the table change at all during that time or does it remain the same?

**Comment by RomaBogatikov** [comment]
New data is generated every 300ms in my example, if this is what you mean. And we can see that table gets and renders this data.

**Comment by matthewoestreich** [comment]
Sorry I am on mobile, haven't checked out the demos. But if that new data is added to existing data (and not replacing it) then it makes sense why you're seeing that behavior.

**Comment by RomaBogatikov** [comment]
The new data replaces the old one completely as I am generating a new array of users and replace the old array with the new one. I at first thought it might be because of a useMemo that I wrapped the material table into (this hook doesn't doo anything in my particular example since data references a new array each time new data is generated). But the heap size increases without useMemo() also.

**Comment by matthewoestreich** [comment]
Yes that's def interesting. Sounds like a bug somewhere. I'll need some more time to dig through things. 

Thanks for this!

**Comment by RomaBogatikov** [comment]
I spent a lot of time trying to find out what causes such a behavior. If you have at list some assumptions at any moment on what may cause such a behavior and where to look at let me know, please, and I will try to investigate.

**Comment by matthewoestreich** [comment]
The first thing I'd like to test is just making sure that `webpack-dev-server` (which is what `yarn start` ultimately uses) isn't doing anything funny in the middle. 

I forked your repo and wrote a small Express server that serves our built React app. If you wouldn't mind adding this logic (or I can send you a PR if you want) to your test repo, and then testing again that would be awesome!

https://github.com/oze4/material-table-memory-leak

I think that will help us rule out any weird server side caching they may do.

If that doesn't work, then I want to test this same logic but without React Context. I do not think this is how Context is meant to be used. Meaning, if you wanted data updated every N milliseconds, you should be dispatching that new data versus feeding it to the root provider, if that makes sense.

Eventually we will get it figured out though! Again, can't thank you enough.

**Comment by RomaBogatikov** [comment]
Great, thank you. I will add the server logic that you wrote and test it again. I will let you know how it goes.
I will then try to use it without React Context. Will just render 5 tables, each generating and rendering its own data.

As for React Context, I understand what you mean by 'dispatching' (I had a look at a 'context' branch and how you use Context there). I will read more about it as I am not 100%  sure that I do it correctly. Although it seems to me that 'dispatching' with useReducer() works the same way as updating state with useState().

Thank you once again for your help.

**Comment by matthewoestreich** [comment]
Yea I agree. It is highly unlikely that either of those things are the root issue, but they're easy to test (almost as easy to test as assuming they're not the issue) and could be easily overlooked. 

Trying to remove as many peripherals as possible. If we are testing whether or not material table has a memory leak then we should remove all variables outside of material table, imo. And then slowly add them back to see what happens. 

I started profiling for a little bit and it does seem that Context is the object that grows. Idk. Weird one for sure.

**Comment by matthewoestreich** [comment]
Also just to note, I doubt it has anything to do with it but I've had an open issue for react beautiful DND for a while. They create many unnecessary redux instances. This could be one avenue to explore. Just wanted to note that.

**Comment by RomaBogatikov** [comment]
I created a withoutContext branch in the demonstration and added the Express server that you wrote. I tested both of them and JS heap size still increases over time. I am not sure though how you can tell that this is the Context object that grows.

**Comment by matthewoestreich** [comment]
I was using Chrome and went into the dev tools under memory - I can't recall which setting I used but you can view the callstack and objects. The object with the largest increased of retained growth was related to react context.

I did some research on setInterval and it looks like it slowly increases memory consumption over time. See [here](https://stackoverflow.com/questions/14034107/does-javascript-setinterval-method-cause-memory-leak) and [here](https://stackoverflow.com/questions/52647183/setinterval-causes-memory-leak), but Googling "setInterval memory leak" shows much more on this. 

In order to test this, I wrote a small .html file with some js but no React.. I want to see if this shows the same behavior.

https://github.com/oze4/mtc-memleak-no-react

If you run open that html file in a browser, do you see the same memory increase over time?

I think this is going to be a tricky one to diagnose, as I don't think we are doing any caching anywhere. Thanks for your patience!

**Comment by RomaBogatikov** [comment]
Thank you for your prompt replies. I read the articles about setInterval() and they go pretty deep. SetInterval might be an issue here. I can also create an example without setInterval. I may generate data on the server and push it to the client via websockets frequently. Data in React Context will be updated, and the components that are subscribed to Context (via useContext) will be re-rendered. This will help us eliminate the setInterval problem. I am pretty sure we will still observe the heap size increase. Do you think this would be helpful?

**Comment by matthewoestreich** [comment]
Personally, I think that's a great idea. Imo it's easier to troubleshoot that way (making sure the problem is for sure with material table). Most of the time you can test the idea rather quickly. Love the websockets idea as it removes set interval from the client side. Nice!

**Comment by Domino987** [comment]
I ran a few tests on my machine.

It seems like that the memory build up is caused by the context. If I remove the context and pass the data manually, I do not see an increase in memory, but as soon as I add the context, it slowly increases.

Could this be caused by a slow garbage collection of the context values due to the rapid update frequency?

@RomanBogatikov Can you verify that on your machine?

**Comment by matthewoestreich** [comment]
Nice find @Domino987

**Comment by RomaBogatikov** [comment]
There is a branch in the demonstration called 'withoutContext' where no context is used. When I ran code from this branch for extended periods of time, I still saw the JS heap size increase. I will leave it running overnight again just to double check and will let you know (I don't know how else to see the heap size increase). As of now the code has been running for 3 hours already and the heap size swings from 65-110Mb, while it started with something like 40-80Mb.
I also created a 'websocket' branch in the demonstration that generates data on the server and pushes it to the client. This branch uses Context. I haven't tested it yet though (I mean I haven't left it running for a long time yet).

**Comment by matthewoestreich** [comment]
Putting this here for reference. https://github.com/mbrn/material-table/issues/2650#issuecomment-879445038

**Comment by RomaBogatikov** [comment]
So, I ran the 'withoutContext' branch for 12 hours and JS heap size swings from 175-250Mb. So, it definitely grew. I haven't tested 'websocket' branch though. When I finish testing it, I will share the results.

**Comment by Domino987** [comment]
So it does not grow indefinitely. Good to know. Memory is so inaccurate, maybe it increased for me and it was just too low to be detected. Next step after checking everything would be to remove certain components to Soo which part triggers it.

**Comment by RomaBogatikov** [comment]
@Domino987  Can you, please, give me a bit more details about that next step 'to remove certain components'? I would appreciate if you guide me on what to do.

**Comment by matthewoestreich** [comment]
I also don't think growing 175 to 250mb is enough to classify this as a memory leak. Especially if it swings (meaning it doesn't steadily grow - it grows then shrinks, etc...).

**Comment by matthewoestreich** [comment]
Also, does this happen on all browsers or just a specific browser?

**Comment by Domino987** [comment]
@RomanBogatikov So I am still not sure if that is a leak or jsut a slow garbage colelction process. What you could to is to clone the repo and remove all components that are rendred below the table itself. Like the rows. If that changes the behavoir, you could add the back in and see what tiggers the leak.

**Comment by RomaBogatikov** [comment]
I tested it on Google Chrome only. I see from the articles that @oze4 referenced in the previous posts that the behavior that is observed can not be classified as a memory leak because the garbage collection is working. I will try to render the table without rows as @Domino987 suggested, and probably without some other components (like pagination row) and see if it helps. I will let you know how it goes. Thank you very much for helping me with my issue, I very appreciate it.

**Comment by RomaBogatikov** [comment]
It seems that the problem is with Pagination component. When I comment out the highlighted lines of code in the screenshot below the JS heap size doesn't grow (I left it running for a few hours today and it started with 25-75MB, and stabilized later on to 25-50MB). I will keep you updated.
![image](https://user-images.githubusercontent.com/40308050/126213977-e946b9f2-ab3b-41a9-bb25-5eab5fe5c3e9.png)

**Comment by RomaBogatikov** [comment]
It seems that this JS heap size increase that I observed has nothing to do with material-table. Before I started to exclude material-table components from rendering I switched off the 'sleep' mode on my laptop. After that I don't observe the heap size increase anymore. Thank you @oze4  and @Domino987 for your help.

**Comment by matthewoestreich** [comment]
Nice find! Never would have guessed that.

**Comment by Domino987** [comment]
Thats interesting. Did you find anything more about it? Why this happens. I will close this since its not connected to MT directly, but if you find anything, please let us know.
