### ISSUE TITLE
Cell editing broken

### ISSUE THREAD

**Issue by klassm** [material-table-core/core#254]
Hey there,

I just tried to upgrade to the new major 3 version. However, when trying to edit a cell it looks like the approve button is always disabled. 
You can find an example here: https://codesandbox.io/s/material-table-starter-template-forked-xb2n6

Am I doing something wrong? Maybe I missed adding an additional function?

Thanks
Matthias

**Comment by Domino987** [comment]
This is fixed in code but the release is not yet through. Will be fixed with the next release

**Comment by klassm** [comment]
Great thanks :-)
