### ISSUE TITLE
Date editing does not follow given date locale

### ISSUE THREAD

**Issue by JGioia** [material-table-core/core#255]
When you are editing a row that contains a date, the format of the date is always dd.mm.yyyy, even when the date locale is set. This bug does not exist when you are not in the middle of editing the date. I found this issue on the original material table repository that poses a potential fix for bug, but I have not looked into it enough to determine whether it is valid. https://github.com/mbrn/material-table/issues/2094

Here is an example to reproduce the bug
```
function Editable() {
  const { useState } = React;

  const [columns, setColumns] = useState([
    { title: 'Date', field: 'date', type: 'date', dateSetting: 'en-US' }]);

  const [data, setData] = useState([{date: new Date()}]);

  return (
    <MaterialTable
      title="Editable Preview"
      columns={columns}
      data={data}
      editable={{
        onRowAdd: newData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              setData([...data, newData]);
              
              resolve();
            }, 1000)
          }),
        onRowUpdate: (newData, oldData) =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataUpdate = [...data];
              const index = oldData.tableData.id;
              dataUpdate[index] = newData;
              setData([...dataUpdate]);

              resolve();
            }, 1000)
          }),
        onRowDelete: oldData =>
          new Promise((resolve, reject) => {
            setTimeout(() => {
              const dataDelete = [...data];
              const index = oldData.tableData.id;
              dataDelete.splice(index, 1);
              setData([...dataDelete]);
              
              resolve()
            }, 1000)
          }),
      }}
    />
  )
}

```

**Comment by matthewoestreich** [comment]
Demo of issue

[![Edit material-table-starter-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-starter-template-forked-ost1g?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matthewoestreich** [comment]
So it looks like you are using the `dateSetting` incorrectly. It is an object, not a string: `dateSetting: { locale: "en-US" }`.. But even after I made those changes, I still had issues.

While this is an issue, we are currently refactoring this code to use Context. This is something we can fix for good in the refactor.

For now, if you change the columns object to below, it should work for you.

```js
  const [columns, setColumns] = useState([
    { title: 'Date', field: 'date', type: 'date', dateSetting: { locale: "en-US", format: "MM/dd/yyyy" } }]);
```

**Comment by JGioia** [comment]
Thanks for the help. It seems like you're right. I'm fine with closing this if you want to

**Comment by matthewoestreich** [comment]
Nice! Glad that fixes it for you.

**Comment by Irian-Adappty** [comment]
> So it looks like you are using the `dateSetting` incorrectly. It is an object, not a string: `dateSetting: { locale: "en-US" }`.. But even after I made those changes, I still had issues.
> 
> While this is an issue, we are currently refactoring this code to use Context. This is something we can fix for good in the refactor.
> 
> For now, if you change the columns object to below, it should work for you.
> 
> ```js
>   const [columns, setColumns] = useState([
>     { title: 'Date', field: 'date', type: 'date', dateSetting: { locale: "en-US", format: "MM/dd/yyyy" } }]);
> ```

It's not working form with `type: 'datetime'` sadly.
