### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by klassm** [material-table-core/core#256]
Hey,

not really a bug, also not really a feature request - I was wondering whether it is possible to have the search bar and the table header to be sticky, so to remain on the top while scrolling. I could not find anything in the docs, but maybe I looked at the wrong place?

Thanks :-)
Matthias

**Comment by Domino987** [comment]
I think that could be possible. Have you tried to override the table header with a sticky css position? I dont think this was aksed yet AFAIK.

**Comment by klassm** [comment]
Hm it nearly works using just sticky - it's just that every position relative and overflow whatever breaks it. I guess this needs an adaption in material-table code to make this work, as those positioning stuff has to go - maybe I find some time tomorrow :-)

**Comment by matthewoestreich** [comment]
I think this has been resolved - @klassm can you verify?

**Comment by klassm** [comment]
Yes sure :-) BTW: The solution was: 
* Material-table already has sticky headers
* You need to watch out that you restrict the space of the table, then the headers will work (otherwise they don't). But I guess that's just how sticky works - so I got it working without any adaptions.

**Comment by LuchoTurtle** [comment]
@klassm @oze4 Are you sure this is resolved? Having updated to the latest version, I noticed the header is no longer sticky, which is kind of a bummer :( . This is perhaps related with #262  (the code is [here](https://github.com/material-table-core/core/blob/master/src/components/MTableHeader/index.js#L406)). Should we bring the sticky property back? 🤔

**Comment by LuchoTurtle** [comment]
Oop, nevermind! I forgot I could use ```headerStyle``` in the 'options' props to circumvent this. Just adding `position: sticky` solved it!

**Comment by bailor1** [comment]
The original mbrn version of material-table didn't require a sticky headerStyle. The header always remained at the top. Why is this not the case here?
