### ISSUE TITLE
Problem with detail panel animation

### ISSUE THREAD

**Issue by appukuttan-shailesh** [material-table-core/core#258]
@oze4, @domino987 The PR in #257 fails when the `render` of detailpanel isn't simple static content, and handles some API calls. All the calls are currently being pre-executed. This is because `Collapse` seems to run the content in its child elements, even though it doesn't get populated in the DOM unless when displayed.

See an example of `Collapse` that shows this problem:
https://codesandbox.io/s/material-demo-forked-7bpfy?file=/demo.js

So #257 needs to be updated to ensure that there is no execution of the detailpanel content except when being displayed.
My first attempts at fixing this, such as:

```
  {(typeof props.detailPanel === 'object') &&
    props.detailPanel.map((panel, index) => {
      return (
        <Collapse key={index} in={Boolean(props.data.tableData && props.data.tableData.showDetailPanel) && (props.data.tableData.showDetailPanel || '').toString() ===
        panel.render.toString()} timeout="auto" unmountOnExit>
          {Boolean(props.data.tableData && props.data.tableData.showDetailPanel) ?
            panel.render(props.data) : null}
        </Collapse>
      )
    })
```
only work for the slide-in effect. As discussed yesterday, it is much more difficult to handle the slide-out.

I am not so sure how trivial it is to fix this. I will try working a bit more on this to see what can be done, else we might need to consider a rollback I suppose.

**Comment by Domino987** [comment]
I think we should add this should at least do the slide in animation:
```
TransitionProps={{ unmountOnExit: true }}
```

**Comment by appukuttan-shailesh** [comment]
I believe we are are already achieving that with 
`<Collapse .... unmountOnExit>..... </Collapse>`
right?

**Comment by Domino987** [comment]
The docs write it differently but they are supposed to be passed down. But if they are pre executed it seems like it does not work.

**Comment by appukuttan-shailesh** [comment]
True... I was trying to understand how `mountOnEnter` should work. 
As per docs...
> The Transition component's mountOnEnter property prevents the child component from being mounted until in is true. This prevents the relatively positioned component from scrolling into view from it's off-screen position. Similarly the unmountOnExit property removes the component from the DOM after it has been transition off screen.

https://material-ui.com/components/transitions/

This should have resolved the problem, but doesn't seem to be working as expected.

**Comment by Domino987** [comment]
We could write a new component just for the panel. Use a local state for the open state and listen to the table data Detailpanel with a use effect. Of the function is passed, call it and set a timeout to change the open state to true and expand it after a few sec. Would that work? I could try this maybe tomorrow after I finish something else I am writing on to provide a more stable experience between renders.

**Comment by appukuttan-shailesh** [comment]
That would be great (to have a separate new component that handles the detail panel). I was a bit wary of attempting that, as I wasn't sure what all parts would need to be modified. The current lack of a state parameter to identify if the detail panel is expanded or not, certainly makes the code a bit more bulky for such changes, so I am in favor of your proposal. I will be happy to help/test.

**Comment by Domino987** [comment]
I will close this in favor for the PRs.
