### ISSUE TITLE
Customizing toolbar icons

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#26]
Update: Not a bug, but a duplicate `icons` prop passed to `MaterialTable`.

**Describe the bug**
In a TS environment, the `icons` prop rejects all attempts to pass it an icon to replace 

> No overload matches this call.
>   Overload 2 of 2, '(props: MaterialTableProps<any>, context: any): MaterialTable<any>', gave the following error.
>     Type '{ ViewColumn: JSX.Element; }' is not assignable to type 'Icons'.
>       Types of property 'ViewColumn' are incompatible.
>         Type 'Element' is not assignable to type 'ForwardRefExoticComponent<RefAttributes<SVGSVGElement>>'.
>   Overload 2 of 2, '(props: MaterialTableProps<any>, context: any): MaterialTable<any>', gave the following error.
>     Type 'Element' is not assignable to type 'ForwardRefExoticComponent<RefAttributes<SVGSVGElement>>'.ts(2769)
> index.d.ts(42, 3): The expected type comes from property 'icons' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<MaterialTable<any>> & Readonly<MaterialTableProps<any>> & Readonly<...>'
> index.d.ts(289, 3): The expected type comes from property 'ViewColumn' which is declared here on type 'Icons'
> 

**To Reproduce**
Example:
```
      <MaterialTable
        ...
        icons={{ViewColumn: <div/>}}
      />
```
The same error happens regardless of what's passed in place of `<div/>`.  I've tried `<Icon/>` and even what's in the original source code `forwardRef((props, ref) => <ViewColumn {...props} ref={ref} />`.

The TS definitions look overly restrictive. It would be much more useful if it accepted any component:
https://github.com/material-table-core/core/blob/master/types/index.d.ts#L256

**Expected behavior**
Replace the given toolbar icon with supplied component.

**Comment by matthewoestreich** [comment]
I'm not sure I follow. Would you mind creating a reproducible demo of the issue?

**Comment by peacechen** [comment]
There was an error in my implementation. I had passed in the `icons` prop twice, once with the default set of icons that I overlooked, and again with a customized one.
