### ISSUE TITLE
Z-index issue when dragging column

### ISSUE THREAD

**Issue by pedro-pool-by** [material-table-core/core#262]
**Describe the bug**
When you add "draggable" prop to material table and you try to drag a column, the header is hiding behind the other header cells. This behavior only happens when you drag to right. If you try to drag to left, the dragging header is not hiding.

**To Reproduce**

1. Go to https://codesandbox.io/s/material-table-starter-template-forked-kikgi?file=/src/index.js
2. Drag column 'Word long header' to the right.
3. When the header is over column 'Word2 long header' it hides behind.

**Expected behavior**
It should behaves as when you drag to the left, the dragging column should be above the other columns.

**Screenshots**
![2021-07-16T17-21-54D0-14](https://user-images.githubusercontent.com/85236123/125985945-36b0987c-3fd9-4d0a-bc79-a120530c662f.gif)

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Enterprise
- Browser: Google Chrome
- Version: 91.0.4472.164

**Additional context**
I think the issue is related to styles given to the dragging cell. Maybe with z-index property.

**Comment by Domino987** [comment]
This seems to be caused by the sticky style [here](https://github.com/material-table-core/core/blob/master/src/components/MTableHeader/index.js#L406).

@oze4 You added this 7 months ago. Do you know the reason for that and if we can remove it?

**Comment by matthewoestreich** [comment]
Honestly, I do not recall. I will uncomment and publish a new version. If we get new issues, then we will know I did it for some reason lol. Next time I should comment, at least. I apologize.

**Comment by matthewoestreich** [comment]
Actually, it looks like this was brought over from [mbrn](https://github.com/mbrn/material-table/blob/master/src/components/m-table-header.js#L395) (it is currently in mbrn).

I will remove the sticky, and add back the comment to the line above it.

**Comment by matthewoestreich** [comment]
@pedro-pool-by would you mind giving version 3.1.2 a try?

**Comment by pedro-pool-by** [comment]
@oze4 , now it's working fine. Thanks a lot! 
Just a thing, few versions ago when you drag a column the column where is landing was like swaping, I mean there was an animation. Now there isn't. Is this a bug or is it a change expected?

**Comment by matthewoestreich** [comment]
I'm not sure we've changed anything in regards to dragging. It may be an actual bug. 

I would suggest opening a new issue and providing an example/Sandbox of the issue.

**Comment by pedro-pool-by** [comment]
thanks a lot!

**Comment by Domino987** [comment]
We did to remove the weird jumping on drag start if all headers. Maybe that removed this Animation as well. Interesting
