### ISSUE TITLE
Extra row added automatically after every data row

### ISSUE THREAD

**Issue by nauman-matloob** [material-table-core/core#265]
# Guidelines
I am having an extra row on every table everytime like you see below in the image. i have recently changed to this project from material-table.

![image](https://user-images.githubusercontent.com/22856599/126171758-c39ac263-e6ab-41f2-b2c3-0b8f52259836.png)

Here what I see in React Extension, there is 2 TableRow in MTableBodyRow for every row:
![image](https://user-images.githubusercontent.com/22856599/126175264-66e927bd-3cf4-424c-8bfd-b1a3fd002e5b.png)

Can you fix this please.

Thanks.

**Comment by eslambasher** [comment]
+1

**Comment by matthewoestreich** [comment]
@Domino987 was something recently changed?

**Comment by matthewoestreich** [comment]
Did this just start happening after you switched? Or have you been using this library just fine, and it just started happening?

**Comment by matthewoestreich** [comment]
Also, per our guidelines you will need to create a reproducible sandbox if you want this addressed.

**Comment by kdoda** [comment]
+1 @oze4  For me it happened after the last release (3.0.17). I am currently using v 3.0.16 and it works fine.

**Comment by Domino987** [comment]
I might be connect to the detail panel i guess

**Comment by matthewoestreich** [comment]
Thank you. That helps a ton. I will look into what changed.

**Comment by matthewoestreich** [comment]
Good call. I think that implementation needs to be reworked anyhow.

**Comment by Domino987** [comment]
I already opened a PR, we might be able o work that in.

**Comment by nauman-matloob** [comment]
> @Domino987 was something recently changed?

I was on 3.0.16 when I got this bug I tried to changed it to 3.0.17 but the bug it's still there.
Now I came back to 3.0.14 it working fine.

**Comment by Domino987** [comment]
I updated #260 and once this is merged it should work again as previously. Just with small breaking change: detail :({rowData}) => for the detail panel

**Comment by appukuttan-shailesh** [comment]
I believe above is #260 (not #261)

**Comment by Domino987** [comment]
So we just released 3.1. Can the people finding the errors check it out and see if the errors persist?

**Comment by eslambasher** [comment]
Yes perfect, I just tested with the new version and all working good, thank's

**Comment by Domino987** [comment]
Closing this since it should be fixed now
