### ISSUE TITLE
Column prop render functions

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#269]
See https://github.com/material-table-core/core/discussions/267

_Adding this line for searchability_... I'm encountering the new warning message "The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss."

@dalemarchand

**Comment by Domino987** [comment]
I added that to prevent the state loss that is associated with the deep compare of the options and columns.

If they change, the state of the table will be reset. The problem with putting fat arrow functions within the columns and recreating those on every render will lead to the aforementioned state lose.
This was encountered in several issues and this warning should reduce the problems.

I added this message to it to tell the devs that they might want to create either stable columns or function references to prevent that. It might be that the warning is triggered too easily and we might be able to fine tune it to improve it.

**Comment by dalemarchand** [comment]
I tried recreating what I'm seeing using the codesandbox.io template but can never get the warning message to fire there.  I don't think I can comply with the recommendations by since the render functions depend on the rowData contents, specifically the column data?  For example, one of my column defs is:

          title: 'Detail', field: 'detail', render: (rowData) => <ItemList list={rowData.detail} />


where the ItemList is:

  const ItemList = (props) => {
    return (
      <List dense={true}>
        {props.list.map((text) => {
          const t = text.replace('\n', '; ');
          return (
          <ListItem key={t}>
            <ListItemText key={t+'_text'} primary={t} />
          </ListItem>
        )})}
      </List>
    );
  }

Is there a way for me to refactor this to avoid getting the error?  If not, is the intent to drop support for these kinds of render functions?

**Comment by Domino987** [comment]
@dalemarchand This would work by creating a stable reference with either useMemo or putting it outside the function so its not created on every render.
The return value of the function is depended on the rowData but the function itself is not. So the function will be called for each row and the correct item will be rendered, but you are creating a new function on every render making the tracking of the table state difficult.

```
const columns = [{title: 'Detail', field: 'detail', render: (rowData) => <ItemList list={rowData.detail} />}]
....

function Table() {
...
return <MaterialTable columns={columns}... />
}

```

**Comment by jeanatpi** [comment]
Hi guys,

Just switched from the original repo to this one. Great job!

I'm having the same warning issue.

My scenario is


```
class MyTable extends React.PureComponent {
  [...]

  getColumnsConfiguration() {
  
  const {somevar} = this.state
  return [....] // Columns render and edit depends on some component props and state
  }

  render() {
    return <MaterialTable columns={this.getColumnsConfiguration()} ... />
  }
}

```

As my React level is not too high, I'm wondering how to fix this as I'm not really understanding what this warning means exactly.

If needed I can try to create a code sandbox that reproduce the issue.

Best regards

Jean

**Comment by matthewoestreich** [comment]
Hello, please [see here](https://github.com/material-table-core/core/pull/259#issuecomment-889265184). If you still need assistance, just let us know!

**Comment by jeanatpi** [comment]
@oze4 thanks. I already read this but I don't understand completely what that means.

In my case that would mean something like this?

```
const columns = getColumnsConfiguration(); // Declared in another file for example


class MyTable ... {

  render() {
    return <MaterialTable columns={columns} ... />
  }
}
```
Issue here is how to pass state and props to getColumnsConfiguration() ??

I'm pretty sure that I don't understand something "trivial" :)

**Comment by matthewoestreich** [comment]
If you wouldn't mind creating a reproducible sandbox (we have CodeSandbox starter templates listed in our guidelines https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#guidelines), I think that would make it easier to assist.

**Comment by jeanatpi** [comment]
@oze4 here it is: https://codesandbox.io/s/static-warning-issue-gb86z

Just change selected value of the`<Select>` to see the warning.

**Comment by tamilarasu602** [comment]
@jeanatpi Check the [comment](https://github.com/material-table-core/core/pull/259#issuecomment-906657198) in the PR for the logic behind this warning check.

In your case the warning shows up because you update the column prop (potentially updating only the `render` key's values) in every render. 
When you change the select item, a state changes, causing re-render, hence the warning check is run.

The solution to your problem would be to ensure the columns prop is fixed and at the same time ensuring the render is dynamic with the state.
```
  carrierRender = (rowData) => {
    const { selectedShop } = this.state;
    return (
      <>
        <div>{rowData.carrier}</div>
        <small>{selectedShop}</small>
      </>
    );
  };

  columns = [
    {
      title: "Id",
      field: "id"
    },
    {
      title: "Carrier",
      field: "carrier",
      render: this.carrierRender.bind(this)
    },
    {
      title: "Weight",
      field: "weight",
      render: (rowData) => rowData.weight + "kg"
    }
  ];

  render() {
    ...
    <MaterialTable
      tableRef={this.tableRef}
      data={data}
      columns={this.columns}
      title="Static column issue"
    ...
  }
```

Hope this helps

**Comment by jeanatpi** [comment]
@tamilarasu602 many thanks for your help. Solved my issue.
