### ISSUE TITLE
v0.0.8 & v3.1.0 changes returned rowData object in unwanted way

### ISSUE THREAD

**Issue by ShotSkydiver** [material-table-core/core#270]
Seems like this commit: [https://github.com/material-table-core/core/commit/2cf32a6466837c38c184c0addf5039b7427a8689#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccce](https://github.com/material-table-core/core/commit/2cf32a6466837c38c184c0addf5039b7427a8689#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccce) changed the way the detailPanel option exports the rowData, such that now, you have to access rowData.rowData in order to get to the actual row's data, whereas previously, the row's data was accessible via the root rowData object.

**Comment by flora8984461** [comment]
I guess they made it intentionally? In the doc: https://material-table-core.com/docs/breaking-changes#detail-panel

**Comment by Domino987** [comment]
Yes it is since it it now rendered as a true react component to enable animation and the usage of hooks in the panel. Closing this.
