### ISSUE TITLE
What material-ui version are you using?

### ISSUE THREAD

**Issue by Domino987** [material-table-core/core#275]
We wanted to get a rough overview of which material-ui version is used the most.

For that, we wanted to create a poll to see what needs to be supported the most.

Please reply with an emote:

🎉 Material ui v5 > beta.0
:+1: Material ui v4 > 4.12.x
:heart: Material ui v4 < 4.11.x

**Comment by iamchathu** [comment]
We upgraded to @mui/material the version 5

**Comment by LuchoTurtle** [comment]
@Domino987 This relates to quite the interesting scenario I'm in. The PRs that are being merged into master, I assume they're not being merged also in the `next` branch (the one that has MUI 5), right? I'm asking this because I'm in the middle of migrating from MUI v4 to v5 and it'd be amazing if new PRs (such as #343 ) would also be available on this `next` branch so new `material-table-core` features wouldn't get lost by migrating from v4 to v5. 

Is this possible or what can we do to fix this? 🤔

**Comment by Domino987** [comment]
Hi
Yes the changes from master are regularly merged into next so nothing is lost.
And we do regular release of both branches.

**Comment by LuchoTurtle** [comment]
> Hi
> Yes the changes from master are regularly merged into next so nothing is lost.
> And we do regular release of both branches.

Proper stuff, awesome! Without wanting to nag, do we have an ETA for the next release on the `next` branch? 👀

**Comment by Domino987** [comment]
I just did 😃

**Comment by LuchoTurtle** [comment]
@Domino987 It's unfair how good you are, mate haha! Cheers, thank you so much!

**Comment by b3ni** [comment]
When is the _next_ tag updated with the latest changes?

**Comment by Domino987** [comment]
I try to do that at regular intervals but I am still waiting for one PR to be merged.

Update:
I just released a new version for both.

**Comment by Gzbox** [comment]
We upgraded to @mui/material the version 5

**Comment by bhkangw** [comment]
Hi we are using MUI v5! Any idea when the prerelease version will be finished testing and officially released?

**Comment by Domino987** [comment]
It is always on par with the master version so you can expect the same code for each branch. Since about half of the downloads are still for v4, maybe we wait a bit more. But again, it's the same code just adjusted for now.

**Comment by edencorbin** [comment]
Is it still the case that for V5 we should use 0.2.62?, I don't see it updated often but the docs say its needed.

**Comment by Domino987** [comment]
@edencorbin No we updated the version and every version past 4 uses v5 with the current version of MT is 6.2.3.
Ill update the website. Thanks

**Comment by edencorbin** [comment]
Great yeah its working for me now, the documentation still references the next version, that should be updated.
