### ISSUE TITLE
onRowClick is triggered when clicking a button in a row

### ISSUE THREAD

**Issue by animaonline** [material-table-core/core#277]
What the title says, the problem started happening in version 3.0.14

**Comment by matthewoestreich** [comment]
Thank you for this! [Per our guidelines](https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#guidelines) you will need to create a sandbox for this issue if you want it addressed, otherwise please submit a PR that resolves this issue.

**Comment by animaonline** [comment]
Here's a reproducible demo:

https://codesandbox.io/s/material-table-starter-template-forked-3uzt9?file=/src/index.js

**Comment by Domino987** [comment]
Did you try https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation?

**Comment by animaonline** [comment]
Yes, you can see it in my sample.

**Comment by Domino987** [comment]
I saw you used prevent Default.

**Comment by animaonline** [comment]
tried it out and does indeed work, thanks!
