### ISSUE TITLE
onRowClick returns event.target as null

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#278]
# After upgrading to @material-table/core we are facing an issue with row click, we use row click to select row

- #### Here is a sandbox link [CodeSandbox](https://codesandbox.io/s/intelligent-sutherland-zln9m?file=/src/table.tsx:1045-1055) 

- #### Try to click on a row and see warning in console regarding "This synthetic event is reused for performance reasons" and event.target as null

**Describe the bug**
onRowClick(event,rowData) returns event.target as null with react 16.13.1

**To Reproduce**

1. Go to 'table'
2. Click on 'any row'
3. Scroll down to 'console'

**Expected behavior**
event.target should return clicked target element

**Screenshots**
![image](https://user-images.githubusercontent.com/25742857/127163784-53a79589-d540-47c9-909f-93d7d8017eac.png)

**Desktop (please complete the following information):**

- OS: [windows 10]
- Browser [Chrome]

**Additional context**
We are ussing 
react 16.13.1
material-ui/core 4.12.0

**Comment by matthewoestreich** [comment]
Thank you!!

**Comment by matthewoestreich** [comment]
When did this start happening to you? I wonder if we persist the event internally if that would make a difference?

Thoughts? Open to ideas on how to resolve.

**Comment by matthewoestreich** [comment]
So it doesn't look like you need access to the event in order to programmatically select a row (although the logic could be improved, it is still possible).

[![Edit zen-mountain-xbpew](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-mountain-xbpew?fontsize=14&hidenavigation=1&theme=dark)

```js
import MaterialTable from "@material-table/core";
import React, { useEffect } from "react";

export default function Table(props) {
  const [data, setData] = React.useState(props.dataSource || []);
  const tableRef: any = React.createRef();

  useEffect(() => {
    tableRef.current.state.data.forEach((element: any) => {
      if (props.selectedRows && props.selectedRows instanceof Array) {
        const selectedRows = props.selectedRows.find((a: any) => a === element);
        if (selectedRows !== undefined) {
          element.tableData.checked = true;
        } else if (element.tableData) {
          element.tableData.checked = false;
        }
      }
    });
  }, [props.selectedRows, tableRef, props.dataSource]);

  const onRowSelectionChanged = (rows) => {
    props.onSelectionChange(rows);
  };
  const onRowClicked = (evt: any, rowData: any) => {
    const rowDataCopy = { ...rowData };
    // This logic will need to be refined.
    // Can't always just set to 'true'.
    rowDataCopy.tableData.checked = true;
    const dataCopy = [...data];
    dataCopy[rowDataCopy.tableData.id] = rowDataCopy;
    setData(dataCopy);
  };

  return (
    <div>
      <MaterialTable
        tableRef={tableRef}
        columns={props.columns}
        data={data}
        onSelectionChange={onRowSelectionChanged}
        onRowClick={onRowClicked}
        options={{
          selection: true
        }}
      />
    </div>
  );
}
```

**Comment by pratik-nagpure** [comment]
> When did this start happening to you? I wonder if we persist the event internally if that would make a difference?
> 
> Thoughts? Open to ideas on how to resolve.

It started happening after upgrade. I tried to persist as you see in sandbox but no help.
I think solution would be to add event.persist() in material-table/core files

**Comment by pratik-nagpure** [comment]
> So it doesn't look like you need access to the event in order to programmatically select a row (although the logic could be improved, it is still possible).
> 
> [![Edit zen-mountain-xbpew](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/zen-mountain-xbpew?fontsize=14&hidenavigation=1&theme=dark)
> 
> ```js
> import MaterialTable from "@material-table/core";
> import React, { useEffect } from "react";
> 
> export default function Table(props) {
>   const [data, setData] = React.useState(props.dataSource || []);
>   const tableRef: any = React.createRef();
> 
>   useEffect(() => {
>     tableRef.current.state.data.forEach((element: any) => {
>       if (props.selectedRows && props.selectedRows instanceof Array) {
>         const selectedRows = props.selectedRows.find((a: any) => a === element);
>         if (selectedRows !== undefined) {
>           element.tableData.checked = true;
>         } else if (element.tableData) {
>           element.tableData.checked = false;
>         }
>       }
>     });
>   }, [props.selectedRows, tableRef, props.dataSource]);
> 
>   const onRowSelectionChanged = (rows) => {
>     props.onSelectionChange(rows);
>   };
>   const onRowClicked = (evt: any, rowData: any) => {
>     const rowDataCopy = { ...rowData };
>     // This logic will need to be refined.
>     // Can't always just set to 'true'.
>     rowDataCopy.tableData.checked = true;
>     const dataCopy = [...data];
>     dataCopy[rowDataCopy.tableData.id] = rowDataCopy;
>     setData(dataCopy);
>   };
> 
>   return (
>     <div>
>       <MaterialTable
>         tableRef={tableRef}
>         columns={props.columns}
>         data={data}
>         onSelectionChange={onRowSelectionChanged}
>         onRowClick={onRowClicked}
>         options={{
>           selection: true
>         }}
>       />
>     </div>
>   );
> }
> ```

It selects only one row. I want to make it multiselect and also I want to use event.target to have double click event assigned to the row.

**Comment by matthewoestreich** [comment]
I believe we just added a doubleClick prop (I believe we actually added a way to handle any event you want via an events prop). Let me double check that.

The issue isn't with this library, it's just how synthetic events work.

**Comment by matthewoestreich** [comment]
@Domino987 any suggestion on the double click?

**Comment by matthewoestreich** [comment]
So if you wanted to select all rows you would do something like this:

```js
  const onRowClicked = (evt: any, rowData: any) => {
    const dataCopy = data.map(d => {
      const dc = {...d};
      dc.tableData = { checked: true };
      return dc;
    });
    setData(dataCopy);
  };
```

[![Edit frosty-cherry-o9cbz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-cherry-o9cbz?fontsize=14&hidenavigation=1&theme=dark)

To handle doubleClick you would just use the `onDoubleRowClick` prop the same way you are using the `onRowClick` prop.

**Comment by Domino987** [comment]
We have the onRowDoubleClick prop which already tracks Double clicks. So you would not need to implement it yourselves. Check out the types file for a more detail api reference. Just as @oze4 said .

**Comment by matthewoestreich** [comment]
Hey @Domino987 I noticed in the source it's called `onDoubleRowClick` but to me, `onRowDoubleClick` (like you mention) makes more sense.

Should we change the way that is named? I think so, what do you think? @pratik-nagpure thoughts? Which makes more sense to you?

**Comment by pratik-nagpure** [comment]
I think onRowDoubleClick makes more sense

**Comment by matthewoestreich** [comment]
I think we should publish as a new minor version as well (since some may already be using `onDoubleRowClick`).

**Comment by Domino987** [comment]
Yes we should. I'll create a PR.

**Comment by pratik-nagpure** [comment]
> So if you wanted to select all rows you would do something like this:
> 
> ```js
>   const onRowClicked = (evt: any, rowData: any) => {
>     const dataCopy = data.map(d => {
>       const dc = {...d};
>       dc.tableData = { checked: true };
>       return dc;
>     });
>     setData(dataCopy);
>   };
> ```
> 
> [![Edit frosty-cherry-o9cbz](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/frosty-cherry-o9cbz?fontsize=14&hidenavigation=1&theme=dark)
> 
> To handle doubleClick you would just use the `onDoubleRowClick` prop the same way you are using the `onRowClick` prop.

Thanks. But I can't use dataSource as a state because I want to pass it from props and it can be an async(api url to load data from server)

**Comment by matthewoestreich** [comment]
If you want to programmatically select any row at all you need to have data in state because how else are we supposed to know that you want to select a row on click? Events will not work due to them being synthetic. You should still be able to accomplish what you want, it just takes more code. For example if you're checking rows from an API you'll need to somehow cache which rows were checked. That is outside of the scope of this library. We have no opinion in caching selected rows and leave that up to you. 

Witt that being said there are examples that exist which show how to accomplish caching selected rows using cookies. 

Any suggestions on how to resolve it? Otherwise I'm not really sure how to help.

**Comment by pratik-nagpure** [comment]
> If you want to programmatically select any row at all you need to have data in state because how else are we supposed to know that you want to select a row on click? Events will not work due to them being synthetic. You should still be able to accomplish what you want, it just takes more code. For example if you're checking rows from an API you'll need to somehow cache which rows were checked. That is outside of the scope of this library. We have no opinion in caching selected rows and leave that up to you.
> 
> Any suggestions on how to resolve it? Otherwise I'm not really sure how to help.

Yes true. I am trying to achieve this using tableRef. You can see useEffect in sandbox.

**Comment by Domino987** [comment]
@pratik-nagpure I agree with @oze4 . This is not a problem with the project itself and more a usecase. Could you move this to Stackoverflow?

**Comment by pratik-nagpure** [comment]
> @pratik-nagpure I agree with @oze4 . This is not a problem with the project itself and more a usecase. Could you move this to Stackoverflow?

I think it can be solved if we add event.persist() in material-table.js as you see its throwing error in the same file
![image](https://user-images.githubusercontent.com/25742857/127448275-82340a3a-68bc-4ee5-9daa-add1981e6627.png)

**Comment by matthewoestreich** [comment]
I'm not sure what side-effects that would have. Would it persist the event through to the consumer?

**Comment by matthewoestreich** [comment]
@Domino987 should we do something here like we did for Actions? So the consumer can handle any event they wish?

https://github.com/material-table-core/core/blob/0bb41291f83a737b884fca1c9de5dcced7ea0c22/src/components/MTableAction/index.js#L39-L45

**Comment by Domino987** [comment]
Yes I think that would be good. But for the side effects with being null. Can this be again created in a codesandbox, because I cannot seem to reproduce that?

**Comment by matthewoestreich** [comment]
Hey @Domino987 it does look like persisting the event inside of material-table/core fixes this issue.

I am working on a PR but noticed something I had a question on..

In the `useDoubleClick` hook signature, there are 2 possible params - 

```js
function useDoubleClick(singleCallback, dbCallback)
``` 
but when it is being used, there are 3 params supplied? Can I remove the last one `onClick`? Unless I'm missing something, I don't understand why it's there (line 57).

https://github.com/material-table-core/core/blob/0bb41291f83a737b884fca1c9de5dcced7ea0c22/src/components/m-table-body-row.js#L54-L58

When I comment `onClick` I don't get any errors and nothing seems to break.

**Comment by matthewoestreich** [comment]
Hey @pratik-nagpure our final solution for this was to provide a `persistEvents` prop on the `MTableBodyRow` component.  This means that you are now able to override the Row and provide the `persistEvents` prop yourself.

To accomplish this you would do something like:

```js
import MaterialTable, { MTableBodyRow } from '@material-table/core';

//....

    <div>
      <MaterialTable
        title={'EventTargetErrorOnRowClick'}
        tableRef={tableRef}
        columns={cols}
        data={datas}
        /** The two props below that are commented out are no longer needed when overriding like this */
        // onSelectionChange={onRowSelectionChanged}
        // onRowClick={onRowClicked}
        components={{
          Row: (props) => {
            return (
              <MTableBodyRow
                {...props}
                persistEvents={true}
                onRowClick={onRowClicked}
                onRowSelected={onRowSelectionChanged}
              />
            );
          }
        }}
        options={{
          selection: true
        }}
      />
    </div>
```

We should have these changes published sometime tomorrow.

**Comment by matthewoestreich** [comment]
You should see these changes in `v4.1.0`. Thanks for your help @Domino987!

**Comment by pratik-nagpure** [comment]
Thanks @Domino987  and @oze4. appreciate your efforts. I will check this out.
