### ISSUE TITLE
Removing the detailsPanel prop while using components overriding breaks the component

### ISSUE THREAD

**Issue by josue-uitzil-by** [material-table-core/core#282]
Hi, here is a codesandbox in which the issue can be reproduced: [https://codesandbox.io/s/material-table-starter-template-forked-uvmpq?file=/src/index.js](https://codesandbox.io/s/material-table-starter-template-forked-uvmpq?file=/src/index.js). 

If you remove the detailsPanel prop (for example for hiding it) while it is open and you are using component overriding for the Row, the MaterialTable breaks and shows the following error:

<img width="726" alt="Screen Shot 2021-07-29 at 15 17 25" src="https://user-images.githubusercontent.com/87137177/127559956-c1e9ae14-7c9a-46cb-a5de-bc3c783b06d8.png">

The issue seems to have first appeared in release 3.1.0; if you change the version in codesandbox to 3.0.17 the component will work correctly.

**To reproduce:**

1. On the codesandbox demo expand the details panel of any row
2. Click on the button 'Toggle details panel visibility'
3. The table will break

![Screen Recording 2021-07-29 at 15 29 48](https://user-images.githubusercontent.com/87137177/127561681-fbaa8e55-8e37-4251-a5f3-cb11a4a64d4c.gif)

**Expected behavior**
The details panel should disappear without breaking the component.

**Desktop:**

- OS: macOS Big Sur
- Browser: Chrome
- Version: 92.0.4515.107

**Comment by matthewoestreich** [comment]
I believe this is known. Would you mind trying the latest release?

**Comment by josue-uitzil-by** [comment]
Hi, thanks for your reply. I tested with the latest release (3.2.4) and also with 3.1.2 and in both versions the issue appears, only after downgrading to 3.0.17 the issue disappears.

**Comment by matthewoestreich** [comment]
Interesting. I'll take a look here in a few. If you already know a fix, we would be happy to merge a PR.

Thanks again!

**Comment by matthewoestreich** [comment]
This should be resolved in `v3.2.5` - would you mind giving that version a try and letting us know the result?

Thank you!

**Comment by matthewoestreich** [comment]
#285 please let me know if this is still an issue after upgrading! Thank you.

**Comment by josue-uitzil-by** [comment]
Hi, the issue is solved in the new release. Thanks a lot!
