### ISSUE TITLE
headerStyle option is not being applied to spacing cell when grouping

### ISSUE THREAD

**Issue by Lil-Strudel** [material-table-core/core#283]
**Describe the bug**
Styles provided with the headerStyles option are not being applied to the spacing cell when using grouping. 

**Demo**
[Demo](https://codesandbox.io/s/material-table-starter-template-forked-hclk7?file=/src/index.js)

**To Reproduce**

1. Make a table with that uses the headerStyle option.
2. Make sure the table is using grouping.
3. Inspect the element to see if styles are being applied to the left-most cell in the header.

**Expected behavior**
Styles provided with the headerStyle option should be applied to the cell.

**Screenshots**
![image](https://user-images.githubusercontent.com/42657503/127576402-2bf3dba9-66d4-4ce1-9dcc-291b93eb0320.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 

**Additional Notes**
I have found the issue and have fixed it in a fork. I'll submit a PR for it.

**Comment by matthewoestreich** [comment]
#284 Thank you for your contribution!
