### ISSUE TITLE
The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss.

### ISSUE THREAD

**Issue by sufius** [material-table-core/core#286]
As soon as I'm using the render option in the columns object I'm getting following console message:

> _The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss._

Here is an example similar to my configuration:
```

import Reactfrom "react";
import MaterialTable from "@material-table/core";

const columns = [
  { title: "Id", field: "id", type: "numeric" },
  { title: "Email", field: "email" },
  { title: "First Name", field: "first_name", render: rowData => (<div>{rowData.companion1}</div> }
];

const App = () => {
  const [data, setData] = useState([]);

  return (
    <MaterialTable
      data={getData}
      columns={columns}
    />
  );
};
```

I'm using material-ui 5@beta.2

Any help welcome

**Comment by matthewoestreich** [comment]
Please [see here](https://github.com/material-table-core/core/pull/259#issuecomment-889265184).

**Comment by sufius** [comment]
@oze4 Thank you for pointing me into the right direction - and that so fast.

**Comment by matthewoestreich** [comment]
Cheers!
