### ISSUE TITLE
Freetext instead of drop-down when a 'lookup' object is defined

### ISSUE THREAD

**Issue by neilbags** [material-table-core/core#287]
Hi i'm currently using filtering and lookup on my columns. I notice that as soon as I define a lookup object, the filter box changes from a text entry field to a drop-down menu populated with checkboxes. Is there any way to keep to retain free-text filtering but also use a lookup object? 

Or do I need to manipulate my data separately before rendering the table?

**Comment by matthewoestreich** [comment]
If I understand correctly, this may be something we should integrate (the ability to filter & lookup).

Just to make sure, would you mind creating a Sandbox for this? You can fork [one of the templates from here](https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#guidelines) to help get you started.

Thank you for this!

**Comment by neilbags** [comment]
Here: 
https://codesandbox.io/s/lookup-and-filter-ljlv3

So the first column has no lookup object, and the filter is a text-field. The second column has a lookup object and it filter becomes a dropdown+checkboxes. I'd like to be able to use a lookup, but retain the text-field instead of the dropdown+checkboxes. The dropdown gets out of hand when there are lots of values, and I'm also unsure of how to order it (e.g. alphabetically)

Here  is the relevant code (I think) that decides what type of filter is used:
https://github.com/material-table-core/core/blob/master/src/components/MTableFilterRow/index.js

**Comment by matthewoestreich** [comment]
I do like this idea - I'm just trying to figure out how to make it look visually appealing still. I think stacking the text field and the dropdown would look ugly..

What do you think about moving the dropdown button to the left hand side of the column and showing the text to the right of it?

<img width="378" alt="Screen Shot 2021-08-01 at 10 57 47 AM" src="https://user-images.githubusercontent.com/21092343/127777546-edcfb71c-5661-4ee6-a35a-7c342d89701c.png">

1. Would be the button you click that shows the dropdown
2. Text field

@Domino987 thoughts?

**Comment by Domino987** [comment]
Currently this is on purpose, because if the items are know, that makes it a lot easier.
You could simply override the filter component for this column itself. I think that would make it a lot easier for this one use case.
But I would be intrigued on how a combination would look like.

**Comment by matthewoestreich** [comment]
Yea @Domino987 makes a good point. I'm not sure how the filtering+dropdown logic would pan out in the long run. In order to be flexible we allow overriding, which is perfect for this scenario.

**Comment by matthewoestreich** [comment]
Please let us know if you need help overriding these components. You should be able to accomplish this, albeit with more code.

**Comment by neilbags** [comment]
@oze4 Thanks, I'm trying to do this now - I'm new to MaterialTable as well as react and JS.
I'm trying to get at the DefaultFilter component, but not sure that its exported. I would love an example if its not to much trouble!

**Comment by matthewoestreich** [comment]
So I think you're going to have to integrate the logic yourself when you override. I don't think the filter and drop down were meant to be used in tandem.

**Comment by neilbags** [comment]
Thanks for looking into it. I think at this point for me it's easier to just manipulate the data (do the lookup) out-of-band.

I still think this would be a nice feature to have, but I don't have the time or expertise to implement it myself rn. The checkboxes get out of hand if there are more than a few things in the lookup, and I still can't see a way to define the order of them.
