### ISSUE TITLE
Add forwardRef to MTableBodyRow

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#295]
@Domino987 

Does MTableBodyRow need forwardRef added to it? I'm only asking because I'm unsure if it was left off for a reason or not.

**Comment by Domino987** [comment]
I am not sure, but I don't think this was on purpose. Was this a Problem as of yet?

**Comment by matthewoestreich** [comment]
Not to my knowledge, just wanted to make sure! Thanks.

**Comment by Adphi** [comment]
Sorry to comment in a closed issue, but a forwardRef is indeed missing.  I have just been hit by this problem while trying to implement rows drag and drop using react-dnd.
