### ISSUE TITLE
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined

### ISSUE THREAD

**Issue by sufius** [material-table-core/core#298]
When I have `search: true` and pressing on "export pdf" following error appears:

> Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined

```
        options={{
          search: true,
          exportMenu: [{
            label: 'Export PDF',
            exportFunc: (cols, datas) => ExportPdf(cols, datas, 'myPdfFileName')
          }, {
            label: 'Export CSV',
            exportFunc: (cols, datas) => ExportCsv(cols, datas, 'myCsvFileName', ";")
          }],
```

![image](https://user-images.githubusercontent.com/1421570/127909466-36e571e7-04e3-4d68-868a-ed0f533569d1.png)

no error when `search: false`

**Comment by matthewoestreich** [comment]
Nice catch. Seems like an interesting error! I will have some time to look this over later today, but if you wish, you can send a PR and I'll merge it. 

Thanks again!

**Comment by sufius** [comment]
Thank you for answering so fast, I tried to come closer, but that's all for now how I was able to help - it has something to do with the search ^^ good luck

**Comment by matthewoestreich** [comment]
Hey @sufius [per our guidelines](https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#guidelines), would you mind creating a sandbox for this?

**Comment by matthewoestreich** [comment]
For example, if I go here https://material-table-core.com/demos/export/basic#live-demo

And add the `search: true` to `options` (which, search is true by default), I don't get that error after exporting to CSV or PDF.

Would you mind updating to the latest `@material-table/core` version?

**Comment by sufius** [comment]
here a link:

https://codesandbox.io/s/create-react-app-forked-j6p9q?file=/src/App.js

good luck

**Comment by matthewoestreich** [comment]
Ohh are you using the @next branch?

**Comment by sufius** [comment]
Which branch else is working in combination with react 17?

**Comment by matthewoestreich** [comment]
I think the next branch is for material UI 5 support, I'm not exactly sure because I wasn't too involved. @Domino987 can you confirm?

**Comment by sufius** [comment]
yes, and material-ui 5 needs react 17

**Comment by matthewoestreich** [comment]
Gotcha. Thank you. At least now I know which branch to look at :) I will keep you posted.

**Comment by Domino987** [comment]
Yes the next has v5 and react 17. This seems like its connected to the search input being undefined initially and set to a string afterwards. I'll look into it.
