### ISSUE TITLE
Row selection shows delay

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#299]
- #### Row selection shows some delay in selection
Here is the demo
  - #### [CodeSandbox](https://codesandbox.io/s/stoic-tree-0cus7?file=/src/table.tsx)

**Describe the bug**
I am trying to implement row selection and highlighting the row if it is selected and I noticed there is a delay in the selection of a row.
**To Reproduce**
I have attached sandbox link

**Expected behavior**
It shouldn't take much delay to select row and highlight

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Comment by matthewoestreich** [comment]
<img width="794" alt="Screen Shot 2021-08-04 at 3 45 59 PM" src="https://user-images.githubusercontent.com/21092343/128252435-c864c6db-c44d-45b0-9230-ef02c9446193.png">

I think it may have something to do with this error.

With that being said, wanting to select a row on click is a popular feature, so I wonder if we should just create a prop like `selectOnRowClick` vs [handling it like in our demos](https://material-table-core.com/demos/selection/on-row-click).. It does seem a little less efficient both LOC wise and performance wise to do it like that.

@Domino987 thoughts?

**Comment by matthewoestreich** [comment]
@Domino987 it looks like the `useDoubleClick` hook causes a delay (I'm not saying it's the root of this issue, but it def causes a delay). 

When I remove the `useDoubleClick` hook and just pass the `onRowClick` func to the `Row`'s `onClick` prop (and not wrapping it in `useDoubleClick` first) the delay goes away.

I wonder if there is a better way to handle the double click?

Perhaps we let the consumer override and implement their own doubleClick handlers?

**Comment by Domino987** [comment]
Yes this might be the reason but I don't think the delay is so visible, and needed for the double click.
Maybe set the delay to zero if not double click is passed?

**Comment by matthewoestreich** [comment]
I agree. I think we need to fix the error that OP provided with their Sandbox. I feel like that's the root cause of this issue. 

I did have to focus really hard to notice any delay after removing useDoubleClick in testing.

**Comment by matthewoestreich** [comment]
It looks like doing this check beforehand does resolve the delay, but does not interfere with the `onRowDoubleClick` prop (which I also renamed from `onDoubleRowClick`).

https://github.com/material-table-core/core/blob/dc3865b5cf3877c02ef919ce1fa80e0d48162824/src/utils/hooks/useDoubleClick.js#L24

@pratik-nagpure would you mind updating to `v4.2.1` and trying again?

**Comment by pratik-nagpure** [comment]
> It looks like doing this check beforehand does resolve the delay, but does not interfere with the `onRowDoubleClick` prop (which I also renamed from `onDoubleRowClick`).
> 
> https://github.com/material-table-core/core/blob/dc3865b5cf3877c02ef919ce1fa80e0d48162824/src/utils/hooks/useDoubleClick.js#L24
> 
> @pratik-nagpure would you mind updating to `v4.2.1` and trying again?

Sure @oze4 ,Let me upgrade and see how it works. Thanks for the support.

**Comment by pratik-nagpure** [comment]
Hi @oze4 , @Domino987 
Just tested with `v4.2.1`. I still feel some delay. as we increase columns and rows on the table delay is noticeable.
Here is the updated version [SandBox](https://codesandbox.io/s/stoic-tree-0cus7?file=/src/table.tsx).
Thanks.

**Comment by Domino987** [comment]
So this is just connected to too many renders and is tracked here #224 .

**Comment by pratik-nagpure** [comment]
> So this is just connected to too many renders and is tracked here #224 .

Thank you!

**Comment by matthewoestreich** [comment]
Also, you are still getting that warning in the console. The fact you are providing an out of range value may be causing renders to take forever when you try to select.

If I were you I would fix the warning in the console first. @pratik-nagpure

**Comment by pratik-nagpure** [comment]
> Also, you are still getting that warning in the console. The fact you are providing an out of range value may be causing renders to take forever when you try to select.
> 
> If I were you I would fix the warning in the console first. @pratik-nagpure

@oze4 I did try with values in a range like 20. I still found a delay.

**Comment by matthewoestreich** [comment]
Did you still get that error though? If you look at the demo on our website for selecting in row click, you can see there is no lag. Prior to making that change, you could see a noticable difference in our website. 

Can you make a clean, simple demo with bare bones code to try and reproduce? If that fixes it, slowly start adding your code back to see when the issue reveals itself.

**Comment by matthewoestreich** [comment]
If you still get lag when using 20 rows, but the error still shows, I'd be willing to bet the error in the console is the root of your issue.

**Comment by oze4** [comment]
If I recall correctly we had to do the same thing because one of our deps was using modules (same situation you're in).

Jest doesn't understand es6 by default, so you have to run it thru babel first.

https://stackoverflow.com/a/64223627/10431732

**Comment by pratik-nagpure** [comment]
> If you still get lag when using 20 rows, but the error still shows, I'd be willing to bet the error in the console is the root of your issue.

We don't see errors. but there is still noticeable lag. The issue starts to reveal when we add more columns and rows.

**Comment by Domino987** [comment]
As already mentioned this is simply caused by too many rows and a too expensive render. #224

**Comment by pratik-nagpure** [comment]
> As already mentioned this is simply caused by too many rows and a too expensive render. #224

Thanks @Domino987 .

**Comment by matthewoestreich** [comment]
20 rows is too many?

**Comment by matthewoestreich** [comment]
In a fresh bare bones demo with 20 rows, using row click to select a row, I don't see any lag. I should have some time in a little to review the Sandbox that shows the lag. 

I still think there's something in the demo causing it, not so much the render issues we've been having. This particular issue at least (I'm not saying we don't have render issues).

**Comment by aclave1** [comment]
I think i'm seeing this in my automated tests. I was using material-table and tried switching to @material-table/core 4.3.0. We are using react-testing-library and the tests look something like this:

```javascript
const {getByText} = render(<MyTable onRowClick={() => { console.log('Row clicked'); }}/>)
act(() => {
  fireEvent.click(getByText('my row'))
});
console.log('After row clicked');
```

What we're seeing is this timing delay is causing the logs to run out of order "After row clicked", "Row clicked". Is it possible to disable the timing for onRowDoubleClick?

**Comment by matthewoestreich** [comment]
It looks like you're using the "single click" (onRowClick) - are you still seeing lag? We did decrease the timeout to 0 when using single click in 4.3.0.

https://github.com/material-table-core/core/blob/3bf054ff0f77f28f59c7723c54466e949805f994/src/utils/hooks/useDoubleClick.js#L24

I'm def open to suggestion on how to resolve this issue.

**Comment by aclave1** [comment]
@oze4 When I downgrade @material-table/core to v2.3.40, the issue does not occur. I'm assuming that even with a 0 timeout, it's pushing the callback onto the event loop to be resolved in the next iteration and thus clicking the row then checking for the result syncronously won't work. For example when I do this:

```javascript
const {getByText} = render(<MyTable onRowClick={() => { console.log('Row clicked'); }}/>)
act(() => {
  fireEvent.click(getByText('my row'))
});
await new Promise(res => setTimeout(res,0));
console.log('After row clicked');
```

the order is correct. This is only an issue in automated testing.

**Comment by aclave1** [comment]
> I'm def open to suggestion on how to resolve this issue.

I looked at the useDoubleClick code and the setTimeout is called for both single and double-click and either way, the callback is called after this timeout. In the current implementation, it uses a setTimeout to invoke the callback handlers. The only thing I can think of is to measure the time-difference between 2 clicks and instead of using setTimeout to invoke the callback, use it to call reset if the timeout finishes.

**Comment by Domino987** [comment]
I would appreciate an example on how you would do this. But I don't think this would work. When would you call the single click? Still after some time out? Or directly. And how would you differentiate between the single and double click?

**Comment by matthewoestreich** [comment]
Where do you see it using the 250 timeout whether single click or double click is used? The timeout is 0 if it isn't double click (as shown in the code). It may still be causing issues even if it using 0 though. I think even if it is 0 it will still get put on the event loop as you said and not get called until the event loop makes it's way back around (as you said).

**Comment by aclave1** [comment]
> But I don't think this would work

@Domino987 you could be very correct! This was just a rough guess at an approach. My suggestion was to not call the callbacks inside of the timeout and instead use a time-delta approach and use a timeout only for clearing the time-delta. I can try to develop an example.

> Where do you see it using the 250 timeout whether single click or double click is used?

I don't see it using 250 whether single/double is used, sorry if I described the problem wrong. What i'm seeing is the callback being pushed to the back of the event loop.

**Comment by matthewoestreich** [comment]
That makes sense. I'm going to mess around with it to see if I can come up with something feasible.

**Comment by aclave1** [comment]
@oze4 i've written some failing unit-tests for the hook. https://github.com/aclave1/core/commit/d809843d9d500db943d7c76baf5a852d377920b6

There's 3 failing tests, 2 of which test the single-click behavior. I left a line to uncomment to make the test pass(to demonstrate the event-loop). 

The third failing test is a bit strange to me. In the "handles double-click when user clicks twice within the interval" test, we click, advance a fake timer, then click again. I'd expect this test to trigger the double-click. When I look more into the useDoubleClick hook, it seems that the initial 0ms timeout is clearing the timer before a double-click could ever be registered. Can you run my tests and see if they make any sense?

**Comment by matthewoestreich** [comment]
Nice! I'll check it out. Thanks for doing that!

**Comment by matthewoestreich** [comment]
Hey @aclave1 would you mind sending over a PR with those tests? I'll get it merged, that way we can both use this repo to test with. How's that sound?

**Comment by Domino987** [comment]
This should be fixed now :)
