### ISSUE TITLE
Cannot find module './utils/polyfill'

### ISSUE THREAD

**Issue by JuanDeDiosGonzalezSalazar** [material-table-core/core#307]
# Guidelines

- #### import MaterialTable from '@material-table/core';

- #### installed packages
@material-table/core@4.2.3
@material-ui/core@^4.12.3
material-table@^1.69.3

**Describe the bug**
Just installing and importing @material-table/core;
gives this error Cannot find module './utils/polyfill'

**Expected behavior**
It should load the package without problems

**Screenshots**
![image](https://user-images.githubusercontent.com/13774361/128602736-081e333d-16d6-48f5-ada4-4328930d9c91.png)

- OS: Windows 10
- Browser Chrome Version 92.0.4515.131
- 4.2.3

**Comment by matthewoestreich** [comment]
@Domino987 more issues with the new transpiler. I would love to save on some size, but it looks like it has been causing more harm than good, so I will be reverting back to how it was before until I can work out some of these kinks.

**Comment by matthewoestreich** [comment]
@JuanDeDiosGonzalezSalazar I can't seem to reproduce this issue, though?

**Comment by matthewoestreich** [comment]
See #306 (this is a duplicate issue)

**Comment by Domino987** [comment]
> @Domino987 more issues with the new transpiler. I would love to save on some size, but it looks like it has been causing more harm than good, so I will be reverting back to how it was before until I can work out some of these kinks.

Yes let's do that. I will merge it in next as well since it also use the new bundler. Not sure on how to fix it yet

**Comment by matthewoestreich** [comment]
@Domino987 it's really odd. I even have an issue open on the esbuild repo for this.
