### ISSUE TITLE
Warning when overriding detail panel icon

### ISSUE THREAD

**Issue by matthewreiter** [material-table-core/core#312]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

https://codesandbox.io/s/material-table-detail-panel-icon-bug-f1g8j?file=/src/index.js
Open the developer tools and you will see the warning in the console.

**Describe the bug**
The following warning is logged when overriding the detail panel icon:
```
index.js:27 Warning: Failed prop type: Invalid prop `icon` of type `object` supplied to `MTableCustomIcon`, expected a single ReactElement.
    at MTableCustomIcon (https://f1g8j.csb.app/node_modules/@material-table/core/dist/components/MTableCustomIcon/index.js:23:19)
    in MTableBodyRow (created by MTableBody)
    in tbody (created by ForwardRef(TableBody))
    in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
    in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
    in MTableBody (created by Droppable)
    in table (created by ForwardRef(Table))
    in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
    in WithStyles(ForwardRef(Table)) (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in div (created by Droppable)
    in Droppable (created by Connect(Droppable))
    in Connect(Droppable)
    in Connect(Droppable) (created by MaterialTable)
```

**To Reproduce**

Override the icon for expanding/collapsing the preview panel using a component:
```
import { Loupe } from '@material-ui/icons';

    <MaterialTable
      detailPanel={[
        {
          icon: Loupe,
          render: row => {
            return <div />;
          },
        },
      ]}
    />
```
or a string:
```
    <MaterialTable
      detailPanel={[
        {
          icon: 'loupe',
          render: row => {
            return <div />;
          },
        },
      ]}
    />
```

**Expected behavior**
There should not be a warning.

**Additional context**
The newly added MTableCustomIcon component (https://github.com/material-table-core/core/blob/master/src/components/MTableCustomIcon/index.js) has the wrong prop type specified for the icon. It should allow strings and react components, not react elements.

**Comment by matthewoestreich** [comment]
The newer created component was nothing more than a copy and paste. It used to live inside a diff file. Functionally nothing has changed around that component. It's for internal use anyway and is not exported (or it shouldn't be exported publicly if it is).

**Comment by matthewreiter** [comment]
The original component didn't have prop types defined, so it didn't experience the issue.

**Comment by matthewoestreich** [comment]
Right on. We can get those tweaked for sure. Thank you!

**Comment by Domino987** [comment]
@matthewreiter A PR for this would be welcome as well. Thanks for getting this warning.

**Comment by Domino987** [comment]
This will be fixed with the next release
