### ISSUE TITLE
Not able to get latest state value in custom render for columns when columns are dynamic

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#314]
**Describe the bug**
I have dynamic columns which change as per conditions, what I have observed is that after upgrading to @material-table/core  I am not getting the latest state value in the render method callback for columns

**To Reproduce**
 I have attached the sandbox - [link ](https://codesandbox.io/s/competent-cray-fjqy6?file=/src/tableWrapper.tsx:1010-1023)
1. Click on a row 
2. Columns will change
3. Also, there is a dummy state which will change
4. Dummy state is printed in render method in console
5.Observe that it still has an old state value
and getting a warning
"The columns provided to the material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or a row id to prevent state loss. "

**Expected behavior**
I want to access the latest state inside a render method for columns, Not sure what I need to change. Could you please guide me?

**Comment by pratik-nagpure** [comment]
[#2971](https://github.com/mbrn/material-table/issues/2971)

**Comment by matthewoestreich** [comment]
This is expected behavior. The demo is a little long to read and digest but from what I can tell you are setting the state within the Table component, which is what is overriding the dummy state when you pass it in.

Please create a *minimal reproducible example* of the issue - otherwise it will take me longer to help since I first have to understand your demo.

Alos, it looks like you're setting the `checked` property incorrectly. You don't have to do it via a ref (that is prob why handling onRowSelect takes forever as well).

Again, I think it would be best to remove as much code as possible to just have a minimal demo of the issue. That helps rule out many variables and makes it easier on everyone to help you.

**Comment by pratik-nagpure** [comment]
> This is expected behavior. The demo is a little long to read and digest but from what I can tell you are setting the state within the Table component, which is what is overriding the dummy state when you pass it in.
> 
> Please create a _minimal reproducible example_ of the issue - otherwise it will take me longer to help since I first have to understand your demo.
> 
> Alos, it looks like you're setting the `checked` property incorrectly. You don't have to do it via a ref (that is prob why handling onRowSelect takes forever as well).
> 
> Again, I think it would be best to remove as much code as possible to just have a minimal demo of the issue. That helps rule out many variables and makes it easier on everyone to help you.

sure @oze4 .Thanks for the reply.

**Comment by pratik-nagpure** [comment]
@oze4  Made minimal reproducible demo, sandbox updated.

**Comment by pratik-nagpure** [comment]
> >  "I can tell you are setting the state within the Table component, which is what is overriding the dummy state when you pass it in."


@oze4 I am not setting the state within the table component, I am setting it in the wrapper component.

**Comment by matthewoestreich** [comment]
I meant here. You are changing state via the ref (aka making them checked/unchecked - that requires a state change).. 

```js
if (tableRef.current?.state.data) {
      tableRef.current.state.data.forEach((tableElement: any) => {
        if (tableElement.tableData) {
          tableElement.tableData.checked = false;
        }
      });
    }
```

**Comment by matthewoestreich** [comment]
Do you have a link to the new demo? The original link is still the same code.

**Comment by pratik-nagpure** [comment]
> I meant here. You are changing state via the ref (aka making them checked/unchecked - that requires a state change)..
> 
> ```js
> if (tableRef.current?.state.data) {
>       tableRef.current.state.data.forEach((tableElement: any) => {
>         if (tableElement.tableData) {
>           tableElement.tableData.checked = false;
>         }
>       });
>     }
> ```

This is removed.

**Comment by pratik-nagpure** [comment]
> Do you have a link to the new demo? The original link is still the same code.

Its a same [link](https://codesandbox.io/s/competent-cray-fjqy6?file=/src/table.tsx). Removed unnecessory code

**Comment by matthewoestreich** [comment]
Something like this is a *minimal demo*... 

I honestly don't understand why you're doing the things you're doing. There is lag due to your column renderer.. For every single column, you are logging the entire data object... And I'm not sure what doing this `return <div>{rowData[field]}</div>;` gets you? What's the point of doing that?

[![Edit material-table-starter-template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-starter-template-forked-mw459?fontsize=14&hidenavigation=1&theme=dark)

```js
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "@material-table/core";
import SaveAltIcon from "@material-ui/icons/SaveAlt";
import tableIcons from "./TableIcons.js";

const rando = (max) => Math.floor(Math.random() * max);

const words = [
  "Paper",
  "Rock",
  "Scissors",
  "Joe",
  "Debbie",
  "Apple",
  "HighFive"
];

const rawData = [];
for (let i = 0; i < 100; i++) {
  rawData.push({ random: rando(300), word: words[i % words.length] });
}

const App = () => {
  const [data, setData] = useState(rawData);
  const [columns, setColumns] = useState([
    {
      title: "Random Number",
      field: "random",
      render: (rowData) => custmColumnRenderer(rowData, "random")
    },
    {
      title: "Word",
      field: "word",
      render: (rowData) => custmColumnRenderer(rowData, "word")
    }
  ]);

  const custmColumnRenderer = (rowData, field) => {
    console.log("dummy state - ", data);
    return <div>{rowData[field]}</div>;
  };

  const handleOnRowSelected = () => {
    setData([{ a: "test" }]);
    const newColumns = [...columns];
    setColumns(newColumns);
  };

  return (
    <MaterialTable
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
      onRowClick={handleOnRowSelected}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

And what happens is the expected behavior. You set columns that don't align with the shape of your data. So nothing is shown.... 

```js
  const handleOnRowSelected = () => {
    // Now your data has one object with a single field, called "a"
    // but your columns object has no such entry for a field called "a"...
    setData([{ a: "test" }]);
    const newColumns = [...columns];
    setColumns(newColumns);
  };
```

Would you mind explaining your end goal? Not necessarily the issue, but what you are trying to accomplish...

**Comment by pratik-nagpure** [comment]
> Something like this is a _minimal demo_...
> 
> I honestly don't understand why you're doing the things you're doing. 

What I want is for my `custmColumnRenderer` to always have access to the latest state it might be a local state or a redux state. In the demo which I shared `dummyState` is just a dummy state, it is not data for the table.
I am just trying to show you that even after changing the `dummyState` from `[]` to `[{ a: "test" }]` it still shows the old state value in the `custmColumnRenderer` when the table rerenders.

> And I'm not sure what doing this return `<div>{rowData[field]}</div>`
>

this is just a custom render which returns the value this can be a `<input />` or a dropdown or a checkbox or anything I want to show in a row.

I hope I am able to explain this time.

**Comment by matthewoestreich** [comment]
The demo I provided shows how you can do that. Check your console in the demo. Now the objects are logged vs empty arrays. 

You'd gain access to state the same way you would in any component.

**Comment by pratik-nagpure** [comment]
> The demo I provided shows how you can do that. Check your console in the demo. Now the objects are logged vs empty arrays.
> 
> You'd gain access to state the same way you would in any component.

It is changing the data but still printing old data in the console
![image](https://user-images.githubusercontent.com/25742857/129287268-aded2e68-bd33-43d0-9f6f-a56db602a226.png)

**Comment by pratik-nagpure** [comment]
@oze4  this is something I have come up with where I want to show icon based on the external state `showIcon` .
[Demo](https://codesandbox.io/s/naughty-field-iseek?file=/src/table.tsx)

**Comment by sachin-agarwal-by** [comment]
@oze4 I do agree with @pratik-nagpure  and facing similar issue when we want to update any state from the event like row selection call back from material table then doing state change then this updated state data is not getting reflecting in any of the table render function.

**Comment by matthewoestreich** [comment]
Can someone provide a working demo of the issue? The original issue has nothing to do with accessing state. My demo shows you how to access state from there.

**Comment by pratik-nagpure** [comment]
> Can someone provide a working demo of the issue? The original issue has nothing to do with accessing state. My demo shows you how to access state from there.

@oze4 Did you see [this](https://codesandbox.io/s/naughty-field-iseek?file=/src/table.tsx)

**Comment by matthewoestreich** [comment]
I did not. I am looking at it now.

**Comment by matthewoestreich** [comment]
If I understand this correctly, you want to do something like this... 

In my opinion this is the easiest way to handle it.

[![Edit serverless-snowflake-jg9ku](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serverless-snowflake-jg9ku?fontsize=14&hidenavigation=1&theme=dark)

```js
import MaterialTable from "@material-table/core";
import React, { ReactElement, useState } from "react";
import DoneOutlineIcon from "@material-ui/icons/DoneOutline";
import CloseIcon from "@material-ui/icons/Close";

const Table = (props: any): ReactElement<any> => {
  const [data, setData] = useState([
    {
      id: 1,
      name: "Jon",
      city: "NYC",
      district: "first",
      isVaccinated: true
    },
    {
      id: 2,
      name: "May",
      city: "TX",
      district: "nine",
      isVaccinated: false
    }
  ]);

  const [columns, setColumns] = useState([
    {
      field: "isVaccinated",
      title: "Vaccinated",
      render: (rowData: any) => {
        if (rowData.showIcons) {
          return rowData.isVaccinated ? <DoneOutlineIcon /> : <CloseIcon />;
        }
      }
    },
    {
      field: "name",
      title: "Name"
    },
    {
      field: "city",
      title: "city"
    }
  ]);

  const onRowSelected = (_evt: any, rowData: any) => {
    const newColumns = [...columns, { field: "district", title: "District" }];
    rowData.showIcons = true;
    const copy = [...data];
    copy[copy.findIndex((i) => i.id === rowData.id)] = rowData;
    setColumns(newColumns);
    setData(copy);
  };

  return (
    <div>
      <div>
        <MaterialTable
          options={{
            pageSize: 20
          }}
          columns={columns}
          data={data}
          onRowClick={onRowSelected}
        />
      </div>
    </div>
  );
};

export default Table;
```

**Comment by pratik-nagpure** [comment]
> If I understand this correctly, you want to do something like this...
> 
> In my opinion this is the easiest way to handle it.
> 
> [![Edit serverless-snowflake-jg9ku](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/serverless-snowflake-jg9ku?fontsize=14&hidenavigation=1&theme=dark)
> 
> ```js
> import MaterialTable from "@material-table/core";
> import React, { ReactElement, useState } from "react";
> import DoneOutlineIcon from "@material-ui/icons/DoneOutline";
> import CloseIcon from "@material-ui/icons/Close";
> 
> const Table = (props: any): ReactElement<any> => {
>   const [data, setData] = useState([
>     {
>       id: 1,
>       name: "Jon",
>       city: "NYC",
>       district: "first",
>       isVaccinated: true
>     },
>     {
>       id: 2,
>       name: "May",
>       city: "TX",
>       district: "nine",
>       isVaccinated: false
>     }
>   ]);
> 
>   const [columns, setColumns] = useState([
>     {
>       field: "isVaccinated",
>       title: "Vaccinated",
>       render: (rowData: any) => {
>         if (rowData.showIcons) {
>           return rowData.isVaccinated ? <DoneOutlineIcon /> : <CloseIcon />;
>         }
>       }
>     },
>     {
>       field: "name",
>       title: "Name"
>     },
>     {
>       field: "city",
>       title: "city"
>     }
>   ]);
> 
>   const onRowSelected = (_evt: any, rowData: any) => {
>     const newColumns = [...columns, { field: "district", title: "District" }];
>     rowData.showIcons = true;
>     const copy = [...data];
>     copy[copy.findIndex((i) => i.id === rowData.id)] = rowData;
>     setColumns(newColumns);
>     setData(copy);
>   };
> 
>   return (
>     <div>
>       <div>
>         <MaterialTable
>           options={{
>             pageSize: 20
>           }}
>           columns={columns}
>           data={data}
>           onRowClick={onRowSelected}
>         />
>       </div>
>     </div>
>   );
> };
> 
> export default Table;
> ```

I know I can do adding or updating property in rowData but I have a usecase where I want to take the decision to showIcon based on external state value.

**Comment by matthewoestreich** [comment]
But that's what I showed. It's not an exact demo that shows how to accept data from external. You could very easily add that logic....

**Comment by matthewoestreich** [comment]
The data is in React state. Just pass data from your prop into state.

**Comment by pratik-nagpure** [comment]
> But that's what I showed. It's not an exact demo that shows how to accept data from external. You could very easily add that logic....

problem is not accessing data, the problem is not getting the latest or updated state data in a custom render.

**Comment by matthewoestreich** [comment]
But... I also just showed how you can do that too..?

**Comment by pratik-nagpure** [comment]
> But... I also just showed how you can do that too..?

Correct. You showed by updating rowData. I want by accessing different state value.

**Comment by oze4** [comment]
I think in order to do that you'll need to override the row component. I believe the column doesn't respect the `showIcons` state because we track each row with it's own UUID internally in the table. This prevents unnecessary rerenders. I think that may be messing with it..

**Comment by matthewoestreich** [comment]
@Domino987 any input? I need a second pair of eyes.. My gut tells me that columns are not meant to be dynamic in state like that - I think there are a number of issues with the logic in the demo, which manifest as "state" issues. I can't think of a reason why you'd need columns in state.. Especially considering we have the `hidden` prop for each column..

**Comment by matthewoestreich** [comment]
Actually I think it may be because we need to use a UUID for each cell just like we did for each row.. It doesn't look like the table thinks that cell has changed, so it doesn't update it (to show or hide the JSX, in this case an icon)..

**Comment by pratik-nagpure** [comment]
>I can't think of a reason why you'd need columns in state.. 

We have more than 70 columns we give the user option to select which columns he wants to see so that he can pick columns and add them to the table.

**Comment by matthewoestreich** [comment]
Right, we provide props for that so you don't have to keep columns in state..

https://material-table-core.com/demos/columns/hide#live-demo

See `options.columnsButton` prop for more info.

```js
      options={{ 
        // Allow user to hide/show 
        // columns from Columns Button
        columnsButton: true
      }}
```

**Comment by Domino987** [comment]
Ok this is a react problem, not a MT problem.
So here is the flow:

1. You create a function custmColumnRenderer with the reference to the current dummy state.
2. You pass this function to the columns, which are saved within the useState as well.
3. On every render you create a new custmColumnRenderer, but you do not update the reference of the columns. The columns still point to the old custmColumnRenderer which in turn reference the inital dummy state.
4. Since functions, being objects internally, the same initial function is refernce for all calls and the new custmColumnRenderer will be discareded. And thus they will always point to the initial state.
See here without MT: https://codesandbox.io/s/hardcore-monad-qkxkf?file=/src/tableWrapper.tsx

You need either to generate new columns for every dummy state update or use a ref to get the current state.
Regarding the warning, this will be improved in the future.
I will be closing this, since it not connected to MT at all.

Additional link: https://stackoverflow.com/questions/54069253/usestate-set-method-not-reflecting-change-immediately

**Comment by pratik-nagpure** [comment]
> Ok this is a react problem, not a MT problem.
> So here is the flow:
> 
> 1. You create a function custmColumnRenderer with the reference to the current dummy state.
> 2. You pass this function to the columns, which are saved within the useState as well.
> 3. On every render you create a new custmColumnRenderer, but you do not update the reference of the columns. The columns still point to the old custmColumnRenderer which in turn reference the inital dummy state.
> 4. Since functions, being objects internally, the same initial function is refernce for all calls and the new custmColumnRenderer will be discareded. And thus they will always point to the initial state.
>    See here without MT: https://codesandbox.io/s/hardcore-monad-qkxkf?file=/src/tableWrapper.tsx
> 
> You need either to generate new columns for every dummy state update or use a ref to get the current state.
> Regarding the warning, this will be improved in the future.
> I will be closing this, since it not connected to MT at all.
> 
> Additional link: https://stackoverflow.com/questions/54069253/usestate-set-method-not-reflecting-change-immediately

Thanks @Domino987  and @oze4
