### ISSUE TITLE
Fixed column disturbing table row layout

### ISSUE THREAD

**Issue by sachin-agarwal-by** [material-table-core/core#316]
# Guidelines

**Describe the bug**
I have a simple table where I want to make first column as fixed , after making column as fixed if we will try to adjust the resolution of browser table row is getting messed up.

**To Reproduce**

1. Go to sandBox Env [Link](https://codesandbox.io/s/sachin-material-test-rdir6)
2. Adjust browser Resolution
3. observe the ROW its getting messed up
![image](https://user-images.githubusercontent.com/69183793/129313871-58d9dea0-8973-4eb9-ac6a-4a78f7224dfb.png)

**Comment by matthewoestreich** [comment]
Well that's not good. 

Has anybody looked under the hood yet? I don't mind taking a look in a bit but this seems more aesthetic than a bug in code so I'm going to change the tags.

Thank you!

**Comment by sachin-agarwal-by** [comment]
@oze4  because of this data is getting messed up and its looking too bad as for each fixed row other columns are getting unequal alignment.

**Comment by Domino987** [comment]
This is most likely connected to [this](https://stackoverflow.com/a/58667939/11599909), but I am not sure on how this would affect the rest of the table. @oze4 any ideas?

**Comment by matthewoestreich** [comment]
Hmm... I would have to do some digging but that does seem promising!

**Comment by sachin-agarwal-by** [comment]
@oze4  any update on this ?

**Comment by sachin-agarwal-by** [comment]
@oze4 @Domino987  any update on this please ?

**Comment by Domino987** [comment]
No unfortunately i had no time to look into it and it seems like a complex problem. Maybe next week.

**Comment by dcods22** [comment]
> No unfortunately i had no time to look into it and it seems like a complex problem. Maybe next week.

Any update on this?

@Domino987

**Comment by matthewoestreich** [comment]
@dcods22 this fork is meant to be a community repo. We wanted to help keep this project alive.

**_Please, do not rely on us for a fix_. If you need something resolved urgently, we are actively accepting and merging pull requests.** This does seem like an edge case or "rare" issue to encounter, meaning for such a complex rare issue you will most likely have to resolve this yourself. 

@Domino987 and myself have been super busy lately, so thank you for understanding.

Please let us know if you have any questions.

**Comment by fagom** [comment]
Not stale.

**Comment by Domino987** [comment]
@fagom Can you check with the latest version?
