### ISSUE TITLE
State Update Not Triggering Rerender

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#321]
@bessoltsev I moved this here. If you check out our guidelines under the `.github` directory at the root of this project you'll find templates you can fork from code sandbox to help you with making a demo of this issue.

---

Hi everyone! First, thanks to everyone for the effort put into this project. I have a question of the following kind - when the component state is updated (for example, the number of rows on the page) and the new value is passed to the options, the rerender does not occur. Why can this happen?

**Comment by bessoltsev** [comment]
> @bessoltsev I moved this here. If you check out our guidelines under the `.github` directory at the root of this project you'll find templates you can fork from code sandbox to help you with making a demo of this issue.
> 
> Hi everyone! First, thanks to everyone for the effort put into this project. I have a question of the following kind - when the component state is updated (for example, the number of rows on the page) and the new value is passed to the options, the rerender does not occur. Why can this happen?

I tried to show the idea superficially with a timer. Thank you)

https://codesandbox.io/embed/quirky-smoke-zmr0h?fontsize=14&hidenavigation=1&theme=dark

**Comment by Domino987** [comment]
This is actually how the table behaves, you can only set the initial page size.

Maybe we should either rename it or make it possible to react to new page sizes.

For now you can set the key to trigger a remount on change of the page size:
[Link](https://codesandbox.io/s/zealous-galois-6c5pi?file=/src/App.js)
