### ISSUE TITLE
Cannot use anchorEl on custom Toolbar component 

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#322]
**Describe the bug**
I am using the menu component from MUI as an action on toolbarSelect which relies on anchor-elements to detect at which place the menu should be displayed.
Whenever I provide my own toolbar to MaterialTable (MTableToolbar) the anchor-element seems to be gone. 
The default toolbar behaves differently even though I passed in all props. Any help appreciated.

**To Reproduce**

1. Go to https://codesandbox.io/s/material-table-starter-template-forked-f73cp?file=/src/index.js
2. Select any row
3. Click on action
4. The menu appears on the top left instead of the element that has been clicked on

**Expected behavior**
Comment out line 60 to use the native Toolbar. Follow steps 2-3.
The Menu opens at the exact position of the action icon.

**Screenshots**
![Custom toolbar](https://user-images.githubusercontent.com/39101755/130575646-05b92bcd-a39e-4150-a2e7-097a2babf34e.png)
![Default toolbar](https://user-images.githubusercontent.com/39101755/130575670-646c2886-f51a-4bdc-b463-de893b511d1f.png)

**Desktop**
- OS: macOS BigSur 11.5.1
- Browser: Google Chrome
- Version: 92

**Comment by matthewoestreich** [comment]
I'm confused. Why not just use the regular actions for each row? Specifically the actions prop (array) : https://material-table-core.com/demos/actions/basic

**Comment by matthewoestreich** [comment]
Also, what if someone selects 2 or more rows and then clicks the toolbar button? Which row should the anchorEl go to? I don't think what you're trying to do makes much sense or is feasible.

**Comment by rjumatov** [comment]
I think you misunderstood me. My use case is the following:
I have built a mailtable and each row represents a single mail message. One of the common operations is selecting multiple mails and then moving or copying them to another folder.
Every menu-item in the menu represents a mail-folder (inbox, userfolder, etc.).
It does not make sense to put these operations in a separate action-column.

What I was asking is: Why is the custom toolbar behaving differently than the default one?
What I am trying to do is indeed feasible, it's just not working whenever I provide my own Toolbar like in the sandbox.

**Comment by rjumatov** [comment]
The anchorEl should stay with the action that has been clicked. Screenshot No.1 shows the unexpected behavior, where the menu opens at the top left. It is being caused by toolbar that has been passed in through `components`-prop.
Screenshot No.2 does not use the custom toolbar and works just as expected.

**Comment by matthewoestreich** [comment]
I got you now. That makes sense. Why not just use the default if it works? It looks like setting the anchor element throws an error in the console. I'm not sure this is possible with this library =/

**Comment by rjumatov** [comment]
I could but I want to adjust the height of the toolbar. I wonder what the difference is. If I pass in the component as MTableToolbar and pass in all the props shouldn't it behave exactly as the default toolbar?
My guess would be there is something under the hood that wraps it and prevents the use of anchorEl.

**Comment by matthewoestreich** [comment]
Yes the way it's handled under the hood is diff than if you override it (because you're overriding it). Passing in the same props doesn't mean the same behavior will happen.

The issue here is that the Element you're trying to use as the anchorEl is not allowed (check your console - your example throws and error about this). That is why the menu gets put in the top left of the table. It can't find an anchorEl that is valid so it sticks it a (0,0) aka top left.

**Comment by matthewoestreich** [comment]
You're prob going to have to use a `ref` in order to set the anchorEl like that. FYI.

**Comment by rjumatov** [comment]
I was thinking the same thing but I don't know how to pass a `ref` to an action.

**Comment by matthewoestreich** [comment]
Unfortunately, what you are trying to do is not supported in this library.

**Comment by matthewoestreich** [comment]
@Domino987 any suggestions here? I'm not sure how a consumer would achieve something like this.

**Comment by rjumatov** [comment]
Bump - I am still looking for a way to have anchorEl on custom Toolbar component.
Alternatively I would need a way to style the Toolbar in terms of height, margin, padding, color, ... without a custom component.

I tried css-selectors for `MuiToolbar-regular` but the problem here is that the pagination component has the same parent, leading to styles being applied to both, the toolbar and pagination component.

**Comment by rjumatov** [comment]
I ended up using css-classes like ?MuiToolbar-regular` to adjust the toolbars height and then `MuiTablePagination-toolbar`to compensate that change due to the pagination toolbar being a child of `MuiToolbar-regular`.
