### ISSUE TITLE
After using MTableCell typing in input field loses focus from input

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#323]
I want to give column ids to each table cell so I am using `MTableCell`.
I have a table in which rows are input fields
What I have noticed is that if I use `MTableCell` and try to type in the input field it loses focus and then I need to reselect the field and type it again.

**To Reproduce**

1. Go to [sandbox](https://codesandbox.io/s/magical-meitner-j3ljp?file=/src/table.tsx:1128-1138)
2. Try to type in input fields from a table and see that it loses focus after every type

Also try without `MTableCell` by commenting out and see that it works

**Expected behavior**
It should not lose focus on typing in the input fields if `MTableCell` is used.

**Comment by matthewoestreich** [comment]
Per the warning in the console. you will need to use something like memo or useCallback in order to produce a stable function.

Please see [here](https://github.com/material-table-core/core/pull/259#issuecomment-889265184) for more info.

Warning in console:

```
The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss. 

    in MaterialTable (created by Anonymous)
    in Anonymous (created by WithStyles(Component))
    in WithStyles(Component) (at table.tsx:51)
    in Table (at App.tsx:8)
    in App (at src/​index.tsx:7) 
```

**Comment by pratik-nagpure** [comment]
@oze4 I see the same issue even after using `useCallBack`.
`const customCellRenderer = useCallback((rowData: any, field: string) => {
    return (
      <input
        type="text"
        value={rowData[field]}
        onChange={(e) => onCellValueChange(e, rowData, field)}
      />
    );
  }, []);`
[sanbox](https://codesandbox.io/s/magical-meitner-j3ljp?file=/src/table.tsx) updated.

**Comment by matthewoestreich** [comment]
The warning is still there, which means the function you are passing is not stable. That is why it rerenders and causes to lose focus. You need to find the function you are passing that is not stable and make it stable.

**Comment by matthewoestreich** [comment]
@Domino987 should be able to assist you more here than me. I'm not sure why we need to wrap in useCallback when we did not need to before (I have not worked on that part or dug into it like Domino has). 

I need to brush up on what changes were made to make it so we have to memoize functions so I can better assist down the line. I've just been a little busy lately =/

**Comment by matthewoestreich** [comment]
@Domino987 even when assigning an ID to each column it rerenders - I thought that was supposed to prevent rerendering?

**Comment by Domino987** [comment]
Hi

1. The id does not prevent rerenders, but instead persists the data better between rerenders.
2. The loss of focus us caused by react and not the table because you are creating a new function on every render so react cannot keep track of the current state and will create a full new input on every render.
3. Here is an example on how to do it correctly: https://codesandbox.io/s/condescending-tess-u079f?file=/src/table.tsx
I will be closing the issue

**Comment by pratik-nagpure** [comment]
Thanks @Domino987 . It worked.
