### ISSUE TITLE
On edit bulk - all columns move to the left

### ISSUE THREAD

**Issue by ItzikHendelKahun** [material-table-core/core#328]
I have a @material-table/core in my project with an actions column.

<img width="1354" alt="Screen Shot 2021-08-29 at 11 01 34" src="https://user-images.githubusercontent.com/77571549/131243285-5d2ea4a5-98db-4440-ac1f-29c0749a767f.png">

And when I select edit bulk (from the up-right corner), all columns move to the left.

<img width="946" alt="Screen Shot 2021-08-29 at 11 05 55" src="https://user-images.githubusercontent.com/77571549/131243370-e0da53e2-ce2f-4d39-b643-e6e5f8c4b186.png">

(The first column places under the select box header).

**Comment by matthewoestreich** [comment]
Per our guidelines you will need to provide a reproducible example if you want this addressed.

**Comment by rjumatov** [comment]
@ItzikHendelKahun could you please provide a codesandbox with your problem? It would be interesting to see what operations the edit action performs to cause that behavior.

**Comment by ItzikHendelKahun** [comment]
@sm3sher, I created a codesandbox example and the problem does not reproduce. 
I removed from the package.json in my project the line: "@material-table/core": "^4.1.0" because I had a dependency in another project to  "@material-table/core": "^2.3.28" and I was worried that it causes a mismatch.
Anyway, I'm not sure what was the reason but now it is fixed in my project.
