### ISSUE TITLE
`render` in column definition is lost during JSON parse/stringify copy

### ISSUE THREAD

**Issue by peacechen** [material-table-core/core#331]
**Describe the bug**

@oze4 @Domino987 @FalkF
Commit 53f32fe89581b037d67d62db44790ecc7f6356db introduced a regression by using `JSON.parse(JSON.stringify(...))` in an attempt to deep copy the columns. That nerfs any functions in the object (render, editComponent, etc). 

I will roll a fix into PR #327 

**To Reproduce**
Add a render method to a column definition. The value must be non-scalar (e.g. object).

**Expected behavior**
Table should render without errors.

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version 9x (doesn't matter)

**Comment by matthewoestreich** [comment]
I think this might be why we've been having to use stable functions? I feel like this is a really nice find. I could be wrong though @Domino987 

Thank you!

**Comment by Domino987** [comment]
Oh yes, i did not see that. The obviously this breaks the functions. This needs to be fixed

**Comment by matthewoestreich** [comment]
Excellent find @peacechen thank you so much

**Comment by Domino987** [comment]
Is this fixed with the merged PR?

**Comment by peacechen** [comment]
yes it's fixed
