### ISSUE TITLE
Detail Panel does not auto close when a new Detail Panel is open despite setting detailPanelType to single

### ISSUE THREAD

**Issue by joeflatt** [material-table-core/core#332]
Hi, thanks for your work on this project!

**Describe the bug**
An open detail panel does not always auto close when opening a new detail panel even though the detailPanelType is set to single.

I hacked the code locally to fix it but I'm not so sure it's in the best spot or even the right approach.  Here in `data-manager.js` I've modified a few lines in `setData` starting with `const newRow` that fixes the issue for me...
```javascript    
this.data = data.map((row, index) => {
      const prevTableData = prevDataObject[row.id] || {};
      const tableData = {
        id: row.id || index,
        // `uuid` acts as our 'key' and is generated when new data
        // is passed into material-table externally.
        uuid: row.uuid || uuid.v4(),
        ...prevTableData,
        ...row.tableData
      };
      if (tableData.checked) {
        this.selectedCount++;
      }
      const newRow = {
        ...row,
        tableData
      }
      if (this.lastDetailPanelRow && this.lastDetailPanelRow.tableData && this.lastDetailPanelRow.tableData.id === tableData.id) {
        this.lastDetailPanelRow = newRow
      }
      return newRow;
});      
```

I believe the problem is that `this.lastDetailPanelRow` can hold on to a copy of tableData that is equivalent to, but not the same object in memory, as held by `this.sortedData[n]`.  So when `this.lastDetailPanelRow.tableData.showDetailPanel = undefined` is executed to close the last detail panel in the `changeDetailPanelVisibility` function, it doesn't actually undefine `this.sortedTable[n].tableData.showDetailPanel`  (BTW  I'm **guessing** this same problem exists with `this.lastEditingRow` too)

**To Reproduce**
Auto close works fine until my open detail panel gets remounted (maybe re-render too?).  I moved to this fork because the original code would always close my detail panel during redux update.  This fork fixed that which is great, the user is now unaware of a remount (I've tried to prevent remounts but no luck).

1. Open a detail panel component which contains an embedded MaterialTable for editing.  The detail panel component is passed an onEdit function and the row data via props.
2. User edits some data and saves it
3. detail panel component calls the passed in onEdit function that hits a saga which submits data to server
4. Redux is updated with server response. 
5. Since the state is passed from parent container to detail panel component, the detail panel component gets the new data and the embedded table is updated with the users changes
6. Click on a different row.  Its detail panel opens fine but the previous detail panel remains open. 

**Expected behavior**
Any open detail panel should close when another one opens if detailPanelType is set to single

**Desktop (please complete the following information):**
- OS: MacOS Big Sur
- Browser: chrome
- Version: 92.0.4515.159

**Comment by joeflatt** [comment]
This bug is related to https://github.com/material-table-core/core/issues/334 as it's caused by remounts.  But even if remount is fixed I think it should still be addressed as refs to rows should be updated in all locations holding it.

Here's a code sandbox showing this issue forked from 334's sandbox...
https://codesandbox.io/s/material-table-starter-template-forked-fo8nj?file=/src/index.js

1. Click a row, the detail panel is displayed
2. Click a different row, a new detail panel is displayed and the old one closes as expected
3. Now edit the table in detail panel
4. Click a different row, now 2 detail panels are open

**Comment by Domino987** [comment]
That's weird. I cannot reproduce this in the sandbox. Can you maybe create a gif for me to see it?

**Comment by joeflatt** [comment]
Sure. Take a look at the gif, to create I...

1. clicked on row 1 (id 77 in gif)
2. clicked on row 2 and watched row 1 close it's detail panel automatically
3. clicked on row 2's detail panel action button then changed the name from Rock to Rock2 and then saved it
4. clicked on row 1... row 2's detail panel remains open

Thanks

![Screen Shot 2021-09-22 at 10 21 35 AM](https://user-images.githubusercontent.com/29818181/134375845-7052d60a-5d0e-4603-8fbb-ad8f476ce686.png)

**Comment by Domino987** [comment]
So I still cannot reproduce it unfortunately. Can you make a video? Or maybe try a different browser, e.g. chrome to narrow down the problem?
