### ISSUE TITLE
initialPage is not working with remote data

### ISSUE THREAD

**Issue by dohomi** [material-table-core/core#335]
**Describe the bug**
initialPage is breaking example with remote data

**To Reproduce**
set option initialPage in combination with remote data

**Expected behavior**
support initialPage 

**Additional context**
This is a long lasting issue on material-table, thats why I tried to use this package. But it seems to have the same issue, as soon initialPage is present it does work as expected.

<img width="790" alt="Screenshot 2021-09-01 at 23 21 58" src="https://user-images.githubusercontent.com/489221/131698619-25e54740-4d36-4b12-bd23-2b4b86a9b5a6.png">

**Comment by matthewoestreich** [comment]
Thank you for this! I'll get a demo started using a free public API (https://jsonplaceholder.typicode.com/), but from what I remember about using remote data - you shouldn't need to use initialPage since you can control query params but it's been a while since I've used remote data so I could be missing something.

**Comment by dohomi** [comment]
@oze4 the problem is: If you set initialPage inside the options of MaterialTable then its just not available as page prob inside of remote data arguments, it always starts at "0". I might move away from remote data and try a different approach because this is bugging me for quite some time now but its not life threatening :-)

**Comment by Domino987** [comment]
Can you try to set up a local version on your computer and change `page: props.options.initialPage || 0,` in line 46 in the query of material-table.js and see if that works for you? @dohomi

**Comment by christofboehm** [comment]
I guess I have the same problem. I try to make the material-table more or less a controlled component (search-text, sorting, pagination) stored together with the data in a redux store, while the data are fetched from an api. I tried to apply the above suggestion by @Domino987 , but I struggled to set up a local version (I am just getting started with JS in general). I tried using yalc and npm-pack-here but when I try to compile the app, I always get the error: 'Module not found: Can't resolve '@material-table/core'.

However, what I noticed was that when I set a page number bigger than the maximum number of pages - it throws an error - but alsothe last page is selected.

**Comment by Domino987** [comment]
So everybody. @dohomi @christofboehm 

I tried to fixt he remote data Initial page thing and I would like for you all the check it out if it works for you [here](https://github.com/material-table-core/core/pull/367).

@christofboehm to run the lcoal code, you have to pull it via git, open the folder and execute `npm i` and `npm start`. 
That should start a local version on your computer.

**Comment by christofboehm** [comment]
thanks @Domino987 for your effort!

`npm i` and `npm start` are working inside the local material table git folder. My problem is that I don't get the local version to work in my react app where I am using the material-table. I guess I await for the merge then.

**Comment by Domino987** [comment]
Ah I see. That's a bit difficult. But maybe port your table into the test of mt-core for testing?

**Comment by Domino987** [comment]
This should work now
