### ISSUE TITLE
provide option for remote data "initialOrderBy"

### ISSUE THREAD

**Issue by dohomi** [material-table-core/core#336]
**Is your feature request related to a problem? Please describe.**
To persist the material-table between router changes (like historyBack) it would be great if the current orderBy could be persisted for example with a localStorage or query param

**Describe the solution you'd like**
Beside the option `searchTerm, initialPage` provide a option `initialOrderBy` prop to pre-set the order.

**Comment by matthewoestreich** [comment]
Hi can you please create a discussion for this? There isn't really an issue here necessarily. Thank you!

**Comment by dohomi** [comment]
@oze4 currently I don't see a way to pre-set the `orderBy` on page load, especially on remote data. Did I miss an option in this library?
