### ISSUE TITLE
Table with group does not return to unsorted order after third header click

### ISSUE THREAD

**Issue by tberkane** [material-table-core/core#339]
**Describe the bug**
In a table with a group, clicking three times on the header to sort a column does not return it to unsorted order but instead leaves it in descending order.

**To Reproduce**

1. Go to https://codesandbox.io/s/material-table-starter-template-forked-4tp7h?file=/src/index.js
2. Expand 'Paper' group -> 'Id' column is unsorted
3. Click on 'Id' header -> 'Id' column is now sorted in increasing order
4. Click on 'Id' header again -> 'Id' column is now sorted in decreasing order
5. Click on 'Id' header again -> 'Id' column is still sorted in decreasing order but should have become unsorted again

**Expected behavior**
The column is supposed to return to unsorted order after 3 header clicks (cf. "thirdSortClick" option in material-table).
The expected behavior can be seen here https://codesandbox.io/s/material-table-starter-template-forked-7g7yt because there are no groups.

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome 93

**Comment by matthewoestreich** [comment]
Thank you for this!

**Comment by Domino987** [comment]
This will be fixed with 4.3.2
