### ISSUE TITLE
Fixed columns are not working and getting double scrollbar in version 4.3.1

### ISSUE THREAD

**Issue by debajit-saha** [material-table-core/core#340]
- Issue 1: When I drag the horizontal scrollbar, all the columns are being dragged even if I have provided "fixedColumns" property. Fixed columns functionality was working fine in v4.3.0.
- Issue 2: When I provide "fixedColumns" prop, a double horizontal scrollbar is coming which was not coming earlier.

- #### Demo Link
- https://codesandbox.io/s/sharp-leavitt-ewvzo?file=/src/table.tsx
- Change the package version to 4.3.0 and see it works. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22059269/132360107-45bef69c-9f21-469a-b290-d7637fa22a63.png)

- Package version [4.3.1]

**Comment by matthewoestreich** [comment]
Thank you for this. That's def not right. @Domino987 didn't we recently make some changes to `fixedColumns`? @debajit-saha if you already know where the issue is in our codebase I can get a PR merged ASAP.

**Comment by debajit-saha** [comment]
@oze4 I am not sure about the fix. There is a chore for "create MTableScrollbar" added in v4.3.1 which might be where the problem lies. https://github.com/material-table-core/core/commit/07434b407f8b6dbe102746c9bb8a6e1869f6396c

**Comment by matthewoestreich** [comment]
That was me just moving the component to it's own file. I didn't change any "business-logic". But it's worth checking out, I suppose. Thank you!

**Comment by debajit-saha** [comment]
@oze4 @Domino987, Any update on this?

**Comment by matthewoestreich** [comment]
Nope. I haven't had time to dig into it. Please keep in mind one of our goals here is to actively merge PRs, etc... Essentially, since mbrn has not been allowing others access to merge PRs and he has become busy, we wanted to create a fork that actively merged fixes. 

Basically, if you find some time to look into this and submit a PR that would be awesome! Otherwise, you'll be waiting on two people that tend to this repo when we can.

**Comment by debajit-saha** [comment]
@oze4  I found that "getColumnWidth()" method inside material-table.js file is not returning any value. And that's because we are iterating over props.columns.tableData and checking its width, but it doesn't have tableData property in it. 

There were some recent changes in the "setDataManagerFields()" method related to table grouping where columns were cloned.

So, there could be two solutions:
1. The columns field inside dataManager.js file has the updated data and we can iterate over it and not props.columns to get column width.

2. We can iterate over props.columns as we doing currently and directly check its width instead of first checking tableData since props.columns will have width property at parent level not nested inside tableData.

In the 1st solution, we would have to export a method returning columns array from dataManager file and then use it for looping. If that's fine, I will go with the first approach.

I feel like this would fix the issue. I will test it and most likely raise a PR tomorrow.

**Comment by Domino987** [comment]
Hi sorry I was on vacation. I think there is a PR right now that might fix this and i will merge it today. Can you check afterwards of this fixes this?

**Comment by debajit-saha** [comment]
Yes, the issue is fixed in latest version.
