### ISSUE TITLE
Enabling signed commits

### ISSUE THREAD

**Issue by janderson215** [material-table-core/core#341]
Hi, since there are multiple people contributing to this awesome project and it is a public repo, shouldn't this repo require signed commits? https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification

If you do plan on doing it, I recommend enabling signed commits first for a week or so, then checking the box to require signed commits to the `master` branch.

Thank you to the group who took the initiative of maintaining mbrn's project to plug holes and improve the dependencies situation!

**Comment by matthewoestreich** [comment]
What does this mean for the contributor? Will we need to change how we push/merge/etc.. ?

Thank you for mentioning this. I think this is critical.

**Comment by janderson215** [comment]
Generally speaking, the workflow will be the same. The only thing that needs to change is that contributors need to create a GPG key associated their individual accounts, and add that GPG key to their local environments. This is basically another step to verify that a commit isn't being spoofed so a bad actor can't sneak code in that others think is legit.

Edit: I should say the workflow will be the same if you have been working on a separate branch and merging changes from the working branch into the `master` (or `main`) branch.

Once done, commits pushed by valid entities will be marked with a **Verified** tag as pictured below
![image](https://user-images.githubusercontent.com/1614038/143313693-673026b9-f4f8-4901-8d97-7f6fcd6db678.png)

This requirement can be enforced at the repo-level with a Branch Rule. Here's an example of one of our Org repos that has this setting in place:
![image](https://user-images.githubusercontent.com/1614038/143314159-fb7e8524-8273-4649-961d-4cd4b5a117b0.png)


Thank you for picking up this issue. I agree that this is critical.

Jon

**Comment by matthewoestreich** [comment]
@Domino987 what do you think about this?

**Comment by kkirsche** [comment]
As someone who normally uses signed commits themselves, I'd push back and ask what value does it actually provide in practice?

Linus Torvalds (creator of `git`) said:

> Signing each commit is totally stupid. It just means that you automate it, and you make the signature worth less. It also doesn't add any real value, since the way the git DAG-chain of SHA1's work, you only ever need one signature to make all the commits reachable from that one be effectively covered by that one. So signing each commit is simply missing the point.

- [Quote Source](https://softwareengineering.stackexchange.com/questions/212192/what-are-the-advantages-and-disadvantages-of-cryptographically-signing-commits-a)
- [Original Source](http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html)

If you won't be auditing everything at the changes, what is this actually verifying for the users?

**Comment by matthewoestreich** [comment]
@kkirsche that's a good question that I unfortunately can't answer. I am not familiar with signed commits, and the benefits (or lack thereof) which they may provide.

I was under the impression this will verify the user pushing code, not the code itself - that it was meant to help prevent malicious actors from pushing code.

**Comment by janderson215** [comment]
Thanks for the comment and sources, @kkirsche.

That was my impression as well, @oze4. If I'm understanding correctly, after reading the Answer on the SO Quote Source, it looks like Linus endorses signing of tags, which encompasses all commits as well. The only way I can see this happening in practice is if he doesn't have any automated signing in place and manually signs the tags; if that doesn't make sense to you, you are in good company.

I believe auto-signing will sign all commits and all tags, so even if it's unnecessary to sign commits, autosigning all git activity is beneficially operationally since you don't have to sign tags manually. I suppose there may be some contributors for whom turning on autosigning would be initially more onerous than not requiring it until it is configured. If I get a vote (I'm not an active contributor), my vote is still in favor of requiring signed commits, but it would be good to get the input of active contributors to ensure requiring signed commits would not hamper their contributions.

Thanks for being thoughtful, gentlemen.
