### ISSUE TITLE
Optional/conditional detail panel

### ISSUE THREAD

**Issue by szolen** [material-table-core/core#345]
Hi, since redesigning the detail panel (so far I have been using version 3.0.6) I have not found a solution to conditional/optional display  detail panel by rowData content.

Previously this is work fine:

```javascript
detailPanel={[
            (rowData) => ({
              icon: () => (rowData.hasParam? <ArrowRightIcon /> : <></>),
              openIcon: () => (rowData.hasParam? <ArrowDropDownIcon /> : <></>),
              disabled: !rowData.hasParam,
              render: (rowData) => {
                let data= rowData.param2?.split(/[\r\n]+/g)[0];
                return (
                  <div>rowData.data[0]</div>
                );
              },
            }),
          ]}
```
I've tried the newest version (4.3.1), but this is not work, i get the following exception:

> node_modules/@material-table/core/dist/components/m-table-detailpanel.js:46
 > 43 |   renderFunction = props.detailPanel;
  44 | } else {
  45 |   renderFunction = props.detailPanel ? props.detailPanel.find(function (panel) {
  >46 |     return panel.render.toString() === (props.data.tableData.showDetailPanel || '').toString();
    47 |   }) : undefined;
  48 |   renderFunction = renderFunction ? renderFunction.render : null;
  49 | }

any suggestion on how to make work it this?

**Comment by Domino987** [comment]
This will be fixed with the next release. Seems like we got a regression while working on the panel.
