### ISSUE TITLE
How to override search text field

### ISSUE THREAD

**Issue by iamchathu** [material-table-core/core#347]
- #### Please include a demo of the issue/behavior/question you have
Current search is not outlined text field I want to customise it .

**Additional context**
  "@material-table/core": "^0.2.0",

**Comment by Domino987** [comment]
I dont think this is currently possible. So if you like to create a PR, that would be awesome.

**Comment by Domino987** [comment]
You can use options={{searchFieldVariant: 'outlined'}} to change the variant.

**Comment by iamchathu** [comment]
Thanks @Domino987
