### ISSUE TITLE
Lookup filter (select list) width issuse

### ISSUE THREAD

**Issue by szolen** [material-table-core/core#348]
Hi, if I use a "lookup" for filtering (select list), the width of the drop-down list does not match the items in the list. If the list items are short, the width is still 250 px, but if they are long (longer than 250px), the ends of the list items are not visible. I couldn't find an option to adjust the size to fit the content or increase the size. (I don't want to change the width of the column. )

**Comment by Domino987** [comment]
Can you create a sandbox on your setup so we can look at it?

**Comment by szolen** [comment]
Hi, I did it in a sandbox I tried to reconstruct. In the filter in the first column, if the data is too long, the width of the drop-down list will not match. (Regardless of the style settings).

For the second column, if the width of the available options is smaller, the width of the drop-down list also does not adjust. (Regardless of style settings)

[https://codesandbox.io/s/lookup-filter-cnevt?file=/src/App.js](url)

I don't know how I can align the list item size to the content.

**Comment by Domino987** [comment]
Seems like this is a problem with mui and not the table: https://github.com/mui-org/material-ui/issues/8778 so I will close this in favor for the other issue

**Comment by ghost** [comment]
What is the latest on this one?

**Comment by Domino987** [comment]
Can you create a sandbox with your setup?

**Comment by TatyanaVl** [comment]
Has this ever been resolved. I get this issue.
Thank you

**Comment by Domino987** [comment]
Not from my side. Because its a mui issue and I have no way to reproduce this.
You are welcome to add asandbox. @TatyanaVl
