### ISSUE TITLE
When will you release support for mui v5.0 

### ISSUE THREAD

**Issue by animaonline** [material-table-core/core#349]

**Comment by doctorallen** [comment]
There is support for MUI v5.0 in the prerelease branch. You can install it with:
# Yarn
`yarn add @material-table/core@next`

# NPM
`npm install @material-table/core@next`

Read more [here](https://material-table-core.com/docs/material-ui-v5).

**Comment by animaonline** [comment]
thanks a bunch!

**Comment by LuchoTurtle** [comment]
@doctorallen Are new PRs made in the master branch merged into the `next` branch? For example, I recently made a PR that was merged yesterday and I'm needing to migrate to MUI v5 and it would be amazing if the PR would also be available in the `next` branch!

**Comment by rjumatov** [comment]
Yes, the `next` branch seems to be up-to-date with the `master` branch.
I'm also migrating and hoping that the master branch will support MUI 5 very soon.

**Comment by Domino987** [comment]
So just fyi so everybody is on the same level. Yes as already mentioned the master and next branch are kept up to date with each other. 
Regarding supporting v5: we are currently in the spot of supporting either or. So the master is V4 and next is v5. Until a large enough number of people moved to v5, merging next into master would prevent all V4 users from receiving more updates. So I am not sure when a good time would be to force this but also how long we should await the migration from others users. Do you guys have a good idea about this?

**Comment by LuchoTurtle** [comment]
According to [MUI's blogpost](https://mui.com/blog/mui-core-v5/), they have stopped supporting MUI v4 themselves and seem to be fully focused on v5 onward.

> "we stopped all development on v4 as soon as we started to work on v5"

So, it would make sense pragmatically to keep in line with what they're doing and focus on MUI v5 and stop supporting v4. However, it wouldn't hurt to wait a wee so more users migrate to v5. I can't really tell how much time you should wait but, to me, it isn't insensitive to merge `next` into `master` right now.
