### ISSUE TITLE
Row's path on the table won't update after sorting

### ISSUE THREAD

**Issue by lisandro52** [material-table-core/core#358]
I've created a sandbox where this issue can be tested:

https://codesandbox.io/s/react-playground-forked-9heg5?file=/Table.js

**Describe the bug**
The issue happens when you want to use an `onRowClick` with a `tableRef` to expand the tree-data of the clicked Row.
If the data is exactly as it was before any sorting, the `onRowClick` works as expected but as soon as you change the order of the rows by using the ColHeaders, clicking on a Row actually opens the one that's sitting on the same place the clicked Row was before sorting. This happens because the `onTreeExpandChanged` function works using the `tableData.path` of the Row, but this path isn't updated when you sort the table.

**To Reproduce**
- Open the sandbox linked above, and try to expand/contract the tree-data by clicking on the Rows - it should work as expected.
- Order the table by any Column, for example male/female.
- Try to expand/contract the rows by *clicking on them*. The other row should be expanding/contracting, not the one you're clicking.

**Expected behavior**
The current Row should be the one closing/opening.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser:  Chrome
- Version 93

**Comment by Domino987** [comment]
Yes,  I looked into the whole tree/grouping thing for the first time and its super weird that the index is used for this.

Obliviously, the id of the child should be used instead. Maybe I can take a look this week to fix this.

**Comment by Domino987** [comment]
Hi I changed the tree data to use the the id instead of the index. So this should work now.
Could you try out the [tree branch](https://github.com/material-table-core/core/tree/tree_with_id) to see if this works for you?

**Comment by lisandro52** [comment]
That looks great! I just tested the branch and it works just like I expected. And the code you used for the demo is like the code I used on the sandbox/my app so it should work exactly the same.
Thanks for taking the time and fixing it!

**Comment by Domino987** [comment]
Perfect I'll merge it tomorrow

**Comment by Domino987** [comment]
Perfect I'll merge it tomorrow

**Comment by Domino987** [comment]
This should be fixed with the latest release
