### ISSUE TITLE
Page crashes when column title is passed as HTML

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#369]
**Describe the bug**
After upgrading to v4.3.5 from v4.3.0
I noticed that if we pass title as  HTML inside col definitions
` const columns = [{
        title: <StatusHeader />,
        field: "status"
      }]`
web page gets crashed,it gives out of memory error
![image](https://user-images.githubusercontent.com/25742857/136957101-4f777a8c-6bf0-423b-8727-72c797dfdee4.png)

**To Reproduce**
Open Sandbox  [Link](https://codesandbox.io/s/green-breeze-cu8xp?file=/src/App.js:187-197) in a new page
Try to click on each row do it multiple times
see that web page gets crashed

**Expected behavior**
Webpage should not crash

**Comment by Domino987** [comment]
Can you check if this still happens in the newest version?

**Comment by pratik-nagpure** [comment]
Hi @Domino987 , It worked in the latest version. Thanks
