### ISSUE TITLE
Missing Position sticky with MaxHeightBody option

### ISSUE THREAD

**Issue by manolo-battista** [material-table-core/core#370]
**Describe the bug**
When set the MaxBodyHeight options, the Header is not sticky. As workaround I set the  ` position: sticky` on <th/> cells.

**To Reproduce**

1. Set the maxBodyHeight option to 100
2. Scroll the rows on table
3. See that Header is not sticky, it goes out of viewport

**Additional context**
I test it on `next` version v0.2.5.

**Comment by matthewoestreich** [comment]
I'm not sure I follow. Would you mind creating a code sandbox that shows the issue? It's just easier on everyone that way.

Thanks!!

**Comment by manolo-battista** [comment]
@oze4 
Here the sandbox: https://codesandbox.io/s/vibrant-dawn-2z8cw?file=/src/App.js

I think could be useful if definining the `maxBodyHeight` option the default header is sticky, to avoid to scroll the body to see the columns name and use the sort functionality.

As you can see on sandbox with `maxBodyHeight` option the header is not sticky, disappear on scroll.
