### ISSUE TITLE
Cannot bulk edit non-root table entries when using tree features

### ISSUE THREAD

**Issue by dalemarchand** [material-table-core/core#372]
# Guidelines

When attempting to use the tree functionality in the table in conjunction with the bulk edit features, I discovered the only rows you can bulk edit are the top level rows.  For a demo, see the code sandbox here:  https://codesandbox.io/s/material-table-starter-template-forked-f3ysn?file=/src/index.js

I would expect that when entering bulk edit mode, either the open/close buttons would be available which would open/close the non-root nodes for bulk editing *or* all rows would be listed for bulk editing by default.

**Comment by Domino987** [comment]
That sounds like a good idea on how it should behave.
I think the tree feature is not used as much, so stuff like this does not come up often.

Would you mind creating a PR fo this?

**Comment by dalemarchand** [comment]
My JS kung-fu is weak and I'm not sure this is something I could fix myself very easily
