### ISSUE TITLE
Compatibility with Office 365 SPFx webpart react component 

### ISSUE THREAD

**Issue by e1omvy** [material-table-core/core#373]
I was using material-table in my office 365 SPFx webpart (React component) . It is working fine. I have upgraded material-ui and tried to use material-table-core,. 
When I am importing the module ,using import MaterialTable  from '@material-table/core';  and tried to build the project, build stopped and throwing me error as below 

# Build Error
Finished subtask 'tslint' after 7 s
[tsc] node_modules/@material-table/core/types/helper.d.ts(23,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@material-table/core/types/helper.d.ts(23,13): error TS1005: ';' expected.
Error - 'tsc' sub task errored after 8.35 s 
exited with code 2
 Finished '_runWatch' after 8.55 s
serve' errored after 30 min

By removing import or using material-table , I am able to build the project except issues due to updated material-ui . 

Could you please suggest that if I am missing any dependency or something else required to remove this error.

**Comment by Domino987** [comment]
Hi
Which versions are you using currently. Both mui and material-table.
Could you maybe create a sandbox for this?

**Comment by matthewoestreich** [comment]
Hi @e1omvy this issue appears to have gone stale. If it is still a problem for you, please let me know and I will reopen.
