### ISSUE TITLE
filter cell style broken after upgrade to mui5

### ISSUE THREAD

**Issue by neilbags** [material-table-core/core#374]
Hi all I just upgraded my project to mui5 and everything seems to working except that my filter cells look horrible.

Before:
![Screenshot_2021-10-15_15-50-46](https://user-images.githubusercontent.com/2738833/137434391-0f1a4065-cd85-41b2-80db-822392826a59.png)

After:
![Screenshot_2021-10-15_15-50-24](https://user-images.githubusercontent.com/2738833/137434411-a9290081-b014-48b4-8168-f84e5b867f3e.png)

I believe this is due to mui changing the default textfield style from standard to outlined but don't know how to fix this in the context of material table. Can anyone point me in the right direction?

Many thanks

**Comment by neilbags** [comment]
I found a workaround for this. But the default probably needs to be changed because it looks awful as-is
```js
const theme = createTheme({
    components: {
        MuiTextField: {
            defaultProps: {
                variant: "standard",
            },
        },
    },
});
```

**Comment by andremantaswow** [comment]
@neilbags this issue still occurs... can you detail a bit more how to apply that theme variable to the table? thanks

**Comment by neilbags** [comment]
```js
const theme = createTheme({
    components: {
        MuiTextField: {
            defaultProps: {
                variant: "standard",
            },
        },
    },
});
```

**Comment by neilbags** [comment]
@andremantaswow I changed the MUI default back to standard variant, as per the code above. That createTheme call goes in  App.js, as per the MUI 4 -> 5 migration guide

**Comment by andremantaswow** [comment]
For anyone else reaching this issue... if you use `lookup` columns you want to add
```
MuiSelect: {
  defaultProps: {
    variant: "standard",
  },
},
```
to your theme as well
