### ISSUE TITLE
Add donation option: GitHub Sponsors

### ISSUE THREAD

**Issue by wgehring** [material-table-core/core#376]
Hello,
I am writing to you on behalf of Daimler / Mercedes-Benz AG. We would like to sponsor you, but we can currently only do this through GitHub Sponsors (at least not yet through opencollective). I have asked GitHub to reach out to you in this regard - have they? And is this an option for you at all? (If currently not, no worries, we will keep you on our list, but probably can only make it happen next year).

**Comment by wgehring** [comment]
Sorry, I just found our other issue here https://github.com/material-table-core/core/discussions/274 
I had forgotten about that one at first, but I suppose it is sufficient to keep one of the two open. :-)

**Comment by Domino987** [comment]
Hi.
This is much appreciated.
Unfortunately the github sponsor progress is slow currently because they have too many requests.
But I'll let you know here, once the progress came through.

**Comment by wgehring** [comment]
Ok perfect. Thank you!
