### ISSUE TITLE
Table column override with custom component throws warnings

### ISSUE THREAD

**Issue by shaliake** [material-table-core/core#381]
**Description**
When using columns definition to override column with custom component I get these warnings:

1. The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss.
2. The table requires all rows to have an unique id property. A row was provided without id in the rows prop. To prevent the loss of state between renders, please provide an unique id for each row. 

**To Reproduce**

1. Create new table with data and column definition
2. Override any column with render: 
`        {
            title: 'Status',
 field: 'code', align: 'center',
            render: rowData => <ReportStatusChip code={rowData.code} status={rowData.status} />,
            lookup: reportStatusLookup
        },
`
3. Open console
4. Refresh page
5. Check yellow warnings

**Expected behavior**
Some warning messages are logged in console

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Firefox
- Version: 94.0b4

**Comment by matthewoestreich** [comment]
Hi can you please provide a reproducible demo?

**Comment by carolrenna** [comment]
I'm getting the same warning.  I even took out the render for the column definition and I still get the warning.  I'm using material-ui 4.12.3, material-ui/icons 4.11.2 react 16.14.0

I'm new to this not sure how to do reproducable-demo

**Comment by Domino987** [comment]
Can you check if this is still the case?

**Comment by chris-jalon** [comment]
@Domino987  @oze4 Here is a demo that reproduces this warning. It renders \<Checkbox>es in the columns, which i'm doing for advanced toggling of properties in a table.  The `SubTable` detailPanel isn't necessary, but if you expand and collapse it, the warning can re-appear many times. 

https://codesandbox.io/s/stable-function-warning-oqeiq?file=/src/index.js

**Comment by Domino987** [comment]
Because each table instance is tracking it. And due to the remount, a new instance ist created. I will check it out.
