### ISSUE TITLE
Delay on Search

### ISSUE THREAD

**Issue by edencorbin** [material-table-core/core#383]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
Question suffices with no demo.
- #### Please try to be as detailed as possible
I have a working server side data table with search, however every letter typed triggers a search, I woul dlike to add a 1-2 second delay after typing for the search to trigger an update for performance.
- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by Domino987** [comment]
Setting the `debounceInterval` in options to 2000 - 3000 will result in a delay. Does that work for you @edencorbin
