### ISSUE TITLE
[Regression] Server side column sorting

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [material-table-core/core#384]
# Guidelines

**Describe the bug**
On previous library, we can disable the internal state sort mechanism in order to use external managed one.
This can be done by setting a no-op `customSort` method on columns definition.
See : 
https://github.com/mbrn/material-table/issues/64
https://github.com/mbrn/material-table/issues/1798
And PR Proposal for a new dedicated property : https://github.com/mbrn/material-table/pull/2480

**To Reproduce**

1. Go to 'https://codesandbox.io/s/charming-blackwell-8vz3d?file=/src/App.js'
2. Table is sorted on 'Pants'
2. Click on 'RESET SORT'
3. Nothing happen

Working sandbox (with previous library) : 
https://codesandbox.io/s/autumn-microservice-hb1xu?file=/src/App.js

**Expected behavior**
If `customSort` is a no-op, internal sort state should not be used.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 94.0.4606.81

Yours faithfully,
LCDP

**Comment by matthewoestreich** [comment]
I believe this is due to when we added the `id` prop for internal tracking of rerenders. Which may need to be removed? @Domino987 thoughts?

**Comment by matthewoestreich** [comment]
Also, would you mind trying to find the last @material-table/core version that worked? That would be a huge help.

**Comment by Domino987** [comment]
Hi @oze4 great to see you again😃
I think this was caused by the removal of the column mutation and now we check if the current sort order is not undefined. But since it does in this case, it does not register it. Maybe we need to check for the column as well?

**Comment by matthewoestreich** [comment]
Likewise, my friend!!! :smile: Apologies. Things got a little hectic over the past month or so. 

Great idea! I'll take a look.

**Comment by Domino987** [comment]
I feel you. I just finished my masters, so this was quite stressful as well. But glad to see you are back. No pressure though 😄

**Comment by matthewoestreich** [comment]
Nice bro!!!!! So happy for you! I'm glad to hear that. Incredible accomplishment.

**Comment by Domino987** [comment]
@LeComptoirDesPharmacies hi i was looking into it and you are changing two things at once. Which is the default order and the custom sort. Could you narrow it down what you want to be the result. If it the combination or just one of the params

**Comment by LeComptoirDesPharmacies** [comment]
Hi @oze4,

It look like that regression occurred on v2.3.6 (https://codesandbox.io/s/zealous-grothendieck-hu841) because v2.3.5 (https://codesandbox.io/s/dank-wildflower-c7371?file=/src/App.js) is O.K.

Hi @Domino987,

`customSort` is used to indicate material table to not use the sort mechanism of the library.
`defaultSort` is used in combination with `customSort` to set the current sort to render.

So I think that we need the combination of both in order to have the feature working.

P.S : GG for your master. 👍 

Yours faithfully,
LCDP

**Comment by matthewoestreich** [comment]
Excellent find @LeComptoirDesPharmacies!

**Comment by LeComptoirDesPharmacies** [comment]
This issue is still alive

**Comment by Domino987** [comment]
A PR would be most welcome. But I will take a look today.

**Comment by r0binxp** [comment]
I have a problem, I need to sort columns by server-side data, but don't have a function or parameter to show the current sort that came from the server, any suggestions?

**Comment by AntoineDuComptoirDesPharmacies** [comment]
> A PR would be most welcome. But I will take a look today.

Hi @Domino987,
If we get some free time one day we will try to do a Pull Request but hard to find yet.

@bot : Problem is still there.

Yours faithfully,
LCDP
