### ISSUE TITLE
Groupping with FreeAction results in empty column / large placeholder

### ISSUE THREAD

**Issue by szolen** [material-table-core/core#386]
Hello! I would like to ask for help.

If I use a grouping with free actions, a large empty area appears after the last column of the table. If I don’t use actions, everything is fine. (picture below)

![kép_2021-10-22_101917](https://user-images.githubusercontent.com/31951198/138419468-a7289cc7-6e74-4a11-9d31-0b1ce4abfbce.png)

Actions: `actions={[
            {
              icon: ()=> <CallMergeIcon />,
              tooltip: "Edit Index",
              isFreeAction: true,
              onClick: (event, rowData) => {
                this.onEditClick(null, rowData._id);
              },
            },
          ]}`

Settings: `options={{
            ...Settings.tableOptions(tableRef),
            paging: false,
            maxBodyHeight: "calc(100vh - 160px)",
            grouping: false,
            defaultExpanded: true,
          }}`

Grouped column: `{
            title: "Rack típus",
            field: "rackType",
            defaultGroupOrder: 0,
          },`

Another question is how can I reduce the amount of left side shifting/margin when I use grouping?

![image](https://user-images.githubusercontent.com/31951198/138420075-bb74dd49-a3f5-4550-b558-9400e9b3f89e.png)

**Comment by matthewoestreich** [comment]
Hello! Thank you for this. Would you mind creating a reproducible demo? It's just easier on everyone overall.

**Comment by szolen** [comment]
Sure! This is the link to the demo: [https://codesandbox.io/s/grouping-bug-me8cr?file=/src/App.jsx](url)
