### ISSUE TITLE
Cannot switch between editable cells using tab

### ISSUE THREAD

**Issue by Nirmalsv007** [material-table-core/core#387]
Tab for switching between editable cells not working 

I'm using v4.3.6 and this problem does not seem to exist in the older version of material table ([Material-table](https://github.com/mbrn/material-table), the one not in development now) 

I used to use tab to navigate to the next editable cell which was working perfectly and after i migrated from the old mat table to here, this seems to be not working now given there was no other code changes.

Can someone please look into this and suggest solution or a way around?

**Comment by matthewoestreich** [comment]
I wonder what the last working version is.

@Domino987 does anything come to mind on this? Any changes that may have caused it?
