### ISSUE TITLE
Rows require unique id property

### ISSUE THREAD

**Issue by jetro4u** [material-table-core/core#391]
**Describe the bug**
I have a table that have unique userId but no id in the row. When I load the page I got the error:

```The table requires all rows to have an unique id property. A row was provided without id in the rows prop. To prevent the loss of state between renders, please provide an unique id for each row.```

The error come from the ```data-manager.js:351``` file

**Expected behavior**
I was expecting the MT to accept the userId as the unique key

**Desktop (please complete the following information):**

- OS: Window 10
- Browser chrome

**Comment by Domino987** [comment]
Can you share your data structure?

**Comment by jetro4u** [comment]
Sorry for the late reply. As per the requirement, I added an id field but still continue to get the error message with the unusual behavior explain below. More like the state of my component was changing. The component where I render MT/Core uses Class and receive props (rows) from a parent component. In MT I design the page as below and it was working fine. I am using MUI/v5 and MT/Core@next

```
class SectionTable extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			sections: [],
			activeTab: 'detail',
		}
		this.tableRef = React.createRef();
		this.columnStruct = [
			{
				title: 'Question',
				render: (row) => {
					return <div className="td-element"><div className="truncate">{row.text}</div></div>
				},
				sorting: false,
			},
			{
				title: 'Score',
				field: 'responses.0.score',
				sorting: false,
			}
		];
	}

	fetchQuestions = (query) => {
          ...fetch logic
	}

	handleTextChange = (e, row) => {
           ...
	}

	handleOptionChange = (e, row) => {
		....
	}

	detailPanel = (row) => {
		let qId = row.questionTypeId === QuestionTypes.CUSTOM
			&& Array.isArray(row.options) && row.options[0] ? row.options[0].text : '';

		switch(qId) {
			case 'sec-5':
				return (
					<div className="detail-panel">
						<Section5
							q={row}
							disabled={this.state.disabled}
							saveAnswer={this.saveAnswers}
							update={this.update}
						/>
					</div>
				);
			default:
				return (
					<div className="detail-panel">
						<QuestionBlock
							q={row}
							result={row.responses[0] || { value: {} }}
							handleTextChange={(e) => this.handleTextChange(e, row)}
							handleOptionChange={(e) => this.handleOptionChange(e, row)}
							handleCheckboxChange={(e) => this.handleCheckboxChange(e, row)}
							disabled={this.state.disabled}
						/>
						{row.questionTypeId === QuestionTypes.DESCRIPTIVE
							? <Button className="save-btn" onClick={() => this.saveResponse(row)} disabled={this.state.disabled}>Save</Button>
							: null}
					</div>
				);
		}
	}

	render() {
		return (
			<div className="overview-container">
				<MaterialTable
					data={this.fetchQuestions}
					title=" "
					tableRef={this.tableRef}
					columns={this.columnStruct}
					detailPanel={this.detailPanel}
					options={...}
					icons={tableIcons}
					style={{ width: '100%' }}
				/>

			</div>
		);
	}
}
export default SectionTable;
```

The section5 component is a child component inside the detail panel that has an html table. The table accept input in some cells and automatically sum it through a local function to show the result in another cell. Now two things are happening

1. If I enter a value into the input field, the field becomes disabled until I click inside to enter another value.
2. The tables that were automatically calculating values are no longer doing so. Sometimes  I have to unmount the component and remount before the value will appear. This was working fine in MT.

**Comment by Domino987** [comment]
Yes this was caused by the mutation of the data and columns. We are still trying to fix this without mutating your user data. I will look into this.

**Comment by jetro4u** [comment]
Thank you for the promise. I use the detail panel a lot for even more complicated uses. I look forward to the fix

**Comment by Domino987** [comment]
> Thank you for the promise. I use the detail panel a lot for even more complicated uses. I look forward to the fix

@jetro4u  To help me debug this, could you add a sandbox with a describiton to see the error?

**Comment by matthewoestreich** [comment]
@jetro4u please let me know if this is still an issue for you - if it is, would you mind creating a code sandbox?

**Comment by adamTarr** [comment]
@oze4 here is a code sandbox. Seems the issue is if the row data doesn't have a prop `id`, the error message about unique row ids shows in the console. 

https://codesandbox.io/embed/elated-torvalds-qpns3?fontsize=14&hidenavigation=1&theme=dark

I've also seen this suggested to try and set the row ID but haven't had success setting it dynamically based on data from the data used for the rows.

```
<MaterialTable        
    components={{
        Row: props => <MTableBodyRow id="SOME-ROW-ID-HERE" {...props} />
    }}

  // other props

/>
```
