### ISSUE TITLE
Page style is being overridden by material-table

### ISSUE THREAD

**Issue by Anboias** [material-table-core/core#392]
Whenever I load a page containing a material-table, the style of some of the other Mui v5 elements on the page are being overwritten.

The issue seems to be that since material-table style is loaded after the Mui elements, the values from some of the classes is being replaced with values that seem to come from older versions of Material-Ui.

**Comment by Domino987** [comment]
Which version are you using of MT?

**Comment by Anboias** [comment]
> Which version are you using of MT?

These are the material packages used:

    "@emotion/styled": "^11.3.0",
    "@material-table/core": "^4.3.8",
    "@mui/icons-material": "^5.0.5",
    "@mui/lab": "^5.0.0-alpha.53",
    "@mui/material": "^5.0.6",
    "@mui/styles": "^5.0.2",

**Comment by Domino987** [comment]
To use it with Mui v5 please install the next branch of material table

**Comment by Anboias** [comment]
Thanks, Domino987! My issue is solved now.
