### ISSUE TITLE
Sorting on currency columns not working as expected

### ISSUE THREAD

**Issue by Gero-B** [material-table-core/core#395]
**Describe the bug**
Strange sort behavior on currency column type

**To Reproduce**
see sandbox example:
https://codesandbox.io/s/material-table-starter-template-forked-rhhs5?file=/src/index.js

**Expected behavior**
Expect order of sorted currency column to be in numerical desending/ascending order (2,1,0,-1,-2), instead results are (2,1,-1,-2,0)

**Screenshots**
![image](https://user-images.githubusercontent.com/6266793/140828291-d4debdd2-76e8-48d7-961a-a59b244ea08a.png)

**Comment by Domino987** [comment]
The type is currently `numeric` to work for numbers: https://github.com/material-table-core/core/blob/master/types/index.d.ts#L239
