### ISSUE TITLE
showDetailPanelIcon Filter Row alignment is off

### ISSUE THREAD

**Issue by KippWade** [material-table-core/core#397]
When utilizing the new showDetailPanelIcon and setting it to false on a table that has filtering, the filtering row remains in the original alignment.  This makes the appearance that the first column doesn't have a filtering header, and there is now a filtering header outside to the left of the table.

	options={{
		actionsColumnIndex: -1,
		debounceInterval: 500,
		draggable: false,
		emptyRowsWhenPaging: false,
		filtering: true,
		initialPage: 0,
		pageSize: 10,
		pageSizeOptions: [10, 20, 40],
		paging: true,
		search: true,
		showDetailPanelIcon: false,
		showTitle: false,
		toolbar: true,
		toolbarButtonAlignment: "left",
	}}

**Expected behavior**
When hiding the Detail panel Icon, we expect all columns to line up.

![2021-11-09_15h32_07](https://user-images.githubusercontent.com/43067502/141000410-c2d45c3b-f33d-4fa5-b9fb-d58f1b52fb55.png)

- OS: Windows 10
- Browser: Chrome
- Version: 4.3.9

.

**Comment by Domino987** [comment]
Could you add a sandbox so we can look at your setup?

**Comment by KippWade** [comment]
This should do it.  The filter row doesn't shift when hiding the icon.  So the ID col sorts from the input under Name
[https://codesandbox.io/s/compassionate-euler-c50y6?file=/src/App.tsx](https://codesandbox.io/s/compassionate-euler-c50y6?file=/src/App.tsx)
![2021-11-12_11h28_14](https://user-images.githubusercontent.com/43067502/141500781-c5fa63ae-83e5-46ad-9cca-73cd01ad8098.png)

**Comment by KippWade** [comment]
Okay, it seems I forgot to save the sandbox before shutting down my browser... ugh.  

[Updated Sandbox](https://codesandbox.io/s/material-table-core-hidepanelicon-c50y6?file=/src/AList.tsx)

**Comment by Domino987** [comment]
This will be fixed with the next version release.
Probably tomorrow.
