### ISSUE TITLE
Need to find the index of data in onRowUpdate with the Data Id(differ from the original guide)

### ISSUE THREAD

**Issue by ghyoo91** [material-table-core/core#399]
# Guidelines
Sandbox : https://codesandbox.io/s/wonderful-oskar-2sewq?file=/src/App.js

**Describe the bug**

Preconditions:
When I use the original guide from https://material-table.com/#/docs/features/editable in the onRowUpdate
&
When I use the data id field(As it said in #259)

Bug:
When I update some data, then the below Error message is displayed:

> Cannot read properties of undefined (reading 'id')

---

Details
The original guide is here:
```
        onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    const dataUpdate = [...data];
                    const index = oldData.tableData.id; <-- This line makes an error with the id
                    dataUpdate[index] = newData;
                    setData([...dataUpdate]);

                    resolve();
                }, 1000);
            }),
```

But when I use the data id, "oldData.tableData.id" is just the id of the data even if the id is a string or some big numbers, not the index of oldData in the whole data.

ex) oldData's id is 100 but its index in the entire data is 0, and the entire data has 50 data.
-> oldData.tableData.id is 100 
-> so dataUpdate[100] = newData line executed(out of the original bound)

I can handle this thing by changing the code like below:
```
          onRowUpdate: (newData, oldData) =>
            new Promise((resolve, reject) => {
              const tmp = [...data];
              // This came from the original guide
              // https://material-table.com/#/docs/features/editable
              // const idx = oldData.tableData.id;

              // NOW
              // IF we want to avoid the "data id warning"
              // and some errors when trying data update both,
              // we have to find the index of the oldData.
              const idx = tmp.findIndex(
                (val) => val.id === oldData.tableData.id
               );

              tmp[idx] = newData;
              setData([...tmp]);
              resolve();
            })
```
But I don't think this is the intended behavior. Is there a way I don't know?

**Expected behavior**
Change the "oldData.tableData.id" has the index in the entire data.

**Desktop (please complete the following information):**
- OS: MacOS 12.0.1
- Browser : chrome (95.0.4638.69)
- Version : Package version 4.3.9

**Comment by Domino987** [comment]
The id is given by you, so that's why its a pseudo random number as far as I can tell from your sandbox.

Not using the index and using object reference is indeed a desired effect because its quite fragile.

If you want to use the index instead of looking for it, you can simply set the id to be the index.

**Comment by ghyoo91** [comment]
As you said, id can be a pseudo random number or string, not a simple integer value starting at 0(like index).

If I simply set the id to be the index, I can't update the row in the case that the id isn't same with the index.

I changed my sandbox for this case, with the first row has id "123456789abc", but its index must be 0 if I want to update it.
If I try to update the first row, oldData.tableData.id goes to "123456789abc", so the newData goes to data["123456789abc"].
But my target for updating is data[0], not data["123456789abc"](Even data["123456789abc"] isn't rendered on the table).

I think oldData.tableData.id have to be the index of updated row in the whole data, if I want to use the original guide's code.

Is there something I'm thinking wrong about some point? or should I use some logic to ensure that all data has the same id as the index in the whole data?

Is there any solutions not to set the id and look "The table requires all rows to have an unique id property. A row was provided without id in the rows prop. To prevent the loss of state between renders, please provide an unique id for each row." warning?

**Comment by Domino987** [comment]
> If I simply set the id to be the index, I can't update the row in the case that the id isn't same with the index.
Yes this is the exact reason why we introduced the id in the first place. To improve performance and to preserve state between renders.

You do not want to rely on random positioning of rows to determine the object to change, so yes the original version using the index from the tableData does not work anymore.
But the code you already have in your sandbox works as expected:
` const idx = tmp.findIndex(
              (val) => val.id === oldData.id
              );
`

or you could do
`const tmp = data.map(row => row.id === oldData.id ? newData : row)`

This will both work and you do not opt out of the improvements give by the id in the first place.

But maybe I just do not understand what the problem using the find/map function is for you?

**Comment by ghyoo91** [comment]
Ah, finally I met the point. I've been watching this project since it forked from mbrn/material-table, so I thought this project was trying to avoid changing the appearance (closest to user) like props or callback functions.

If you already know that the changes make the original version doesn't work, then there is no problem!
I just wanted to report if the malfunction of the original code wasn't intended.

Thanks for your kind comments and your effort for this project.

**Comment by Domino987** [comment]
Yes this is indeed what we are trying to do but also we try to improve it. And this change was long overdue since it also mutated the users data, which broke many projects and was a no go.

Good that we cleared this up.
Happy to help .

**Comment by yashaswinibprasad87** [comment]
Please help with a complete example where my  remote data does not have id ... while editing it is not finding index to update

**Comment by yashaswinibprasad87** [comment]
> Yes this is indeed what we are trying to do but also we try to improve it. And this change was long overdue since it also mutated the users data, which broke many projects and was a no go.
> 
> Good that we cleared this up. Happy to help .

 Please help with a complete example where my  remote data does not have id ... while editing it is not finding index to update
