### ISSUE TITLE
Detail panel doesn't open when the rows are grouped

### ISSUE THREAD

**Issue by davidanastasov** [material-table-core/core#402]
#394 breaks the details panel once the rows are grouped by a column. I managed to track the problem down to the following line.

https://github.com/material-table-core/core/blob/47b7080a51cce5597393de4dc1bd78c400d92952/src/utils/data-manager.js#L571 This bug only exists on the latest version (4.3.10), once I downgraded to 4.3.9, the bug was resolved.

**Describe the bug**
The bug occurs because the `findDataByPath` function returns `undefined`.
If you try to open the details panel while no grouping is active, the path array contains only one integer value, and the details panel opens normally.
If you group the rows by some column, the path array now contains two values, the first one being the group index, and the second one being the unique row id (uuid). The uuid is a string, and `result.data["uuid"]` returns undefined.
![image](https://user-images.githubusercontent.com/47048502/141818189-cc6903d9-f029-4741-8b76-8e898791da9e.png)

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/details-row-grouping-bug-p2zlv?file=/src/index.js)
1. Group the rows by the column "Words"
2. Expand the group "Paper"
3. Try to open the details panel for one of the rows inside the "Paper" group
4. The following error will get thrown in the console
![image](https://user-images.githubusercontent.com/47048502/141813238-c1458deb-ada5-43be-8e77-b4492adc0a6e.png)

**Comment by Domino987** [comment]
Seems like there is a mismatch between the grouping and tree data arrays. Would you mind looking into where the wrong thing comes from ?

**Comment by kouraf** [comment]
Did i miss something? or the code in the sandbox works very well! 
![image](https://user-images.githubusercontent.com/22027736/142725886-7dc90914-4f81-4d10-a250-391312b12f49.png)

**Comment by davidanastasov** [comment]
@kouraf Yes, you sorted the values by the column "Word", which should work well. 
The bug occurs when you group the rows by the column "Word". To group the rows drag the header of the column "Word" into the group bar, and then try to expand the detail panel. 
See the example below:
![image](https://user-images.githubusercontent.com/47048502/142743299-c90dd2f7-df55-4b87-a98a-e8c2b7a5391e.png)

**Comment by davidanastasov** [comment]
@Domino987 From what I can see the grouping and data object logic works correctly, I think this bug is connected to the path array. This bug was introduced when [this line](https://github.com/material-table-core/core/pull/394/files#diff-106161477a88fc9a9d8a739a99f5e8f6f321cd6e1ac7d919b2901a10ffeee778L90-R90) was changed in #394:
![image](https://user-images.githubusercontent.com/47048502/142746383-20653187-18fe-46f2-b0a4-3829e32572f4.png)

Reverting that change fixes the bug, but it also reverts back to using the index instead of the row uuid for the path.
I think the solution is to look for a uuid match when trying to get the specific object from the data array:
![image](https://user-images.githubusercontent.com/47048502/142746484-100c70ff-388d-4c8d-928a-ea8a3dfa3e6b.png)

I tested this fix, and it does fix the bug, while also not breaking any other features from what I can see.
Do you think this is a viable fix for this bug? If it is I'd be happy to open a PR for it.

**Comment by Domino987** [comment]
Yes this looks good. Seems like I missed this Point when I converted it to the id.

A PR would be appreciated.

**Comment by matthewoestreich** [comment]
Are we good to close this one out? 

Edit: it looks like a PR has been merged for this, I will close it out. Please let me know if we need to reopen it.
