### ISSUE TITLE
showDetailPanelIcon: false one column is added which shift the row to side (while editing)

### ISSUE THREAD

**Issue by nauman-matloob** [material-table-core/core#403]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

while using detail panel when I set "showDetailPanelIcon" to false and I am in edit mode there is a column that is added. and that shifts the whole line it disturbs a little visually.
I think the added column corresponds to the column of the panel icon.

- actual version  3.0.16
- tried version: 4.3.10

I tried the latest version still having the same issue.

Can you check this Bug please.

![gitissue](https://user-images.githubusercontent.com/22856599/141969078-cbf0cb92-1d0d-4e17-bd62-9fbc7fee19f7.png)
[![Edit angry-solomon-w6kb1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-solomon-w6kb1?fontsize=14&hidenavigation=1&theme=dark
)

**Comment by Domino987** [comment]
Nice catch.

I will try to fix it this weekend. 
Should be a minor fix

**Comment by Domino987** [comment]
It seems like this is connected to the detail panel though.

**Comment by nauman-matloob** [comment]
Yes I have put a detail panel and wanted to remove the icon but when I edit the row the icon cell reappear again the "showDetailPanelIcon" is not respected on edit mode

**Comment by kouraf** [comment]
if you remove `detailPanel={...}` it works normally! @Domino987 do you have an idea where I can start investigating?

**Comment by Domino987** [comment]
Sorry had brain fart. I'll fix it in a bit.

**Comment by Domino987** [comment]
fixed with [this commit](https://github.com/material-table-core/core/commit/b74e63a2bf585ef7ed453aa9ae045c02e2a36e3d). I will release a new version soon
