### ISSUE TITLE
Registry version uniquely for fork

### ISSUE THREAD

**Issue by lucasgonze** [material-table-core/core#404]
(First: thanks for making this fork!)

When switching from the non-forked original of this repo to the forked version, there needs to be an npm/yarn friendly way of managing the dependency. The simplest from a user POV is to publish a new package to the NPM registry. 

Otherwise, I believe users have to do some trickery using the resolutions field in package.json.

**Comment by Domino987** [comment]
I think so far there is only one break. You need to update material-ui to < 4.12 or to Mui v5 with the next branch as far as I can tell.

What do you have in mind?

**Comment by lucasgonze** [comment]
Now that I understand the history of this project I see that you are on top of this already. Thanks for being nice about my newb question.
