### ISSUE TITLE
helperText not defined at line 27 of LookupField.js

### ISSUE THREAD

**Issue by calcari** [material-table-core/core#405]
Maybe a simple oversight in components/MTableEditField/LookupField.js:27

~~`{Boolean(helperText) && <FormHelperText>{helperText}</FormHelperText>}`~~
`{Boolean(props.helperText) && <FormHelperText>{props.helperText}</FormHelperText>}`

Don't have a use case, only had a look at the file.

**Comment by Domino987** [comment]
Would you mind creating a PR for this.
Thanks for finding this.
