### ISSUE TITLE
Add ability to disable unmountOnExit on DetailPanel Collapse

### ISSUE THREAD

**Issue by TheGoodSpinach** [material-table-core/core#407]
**Is your feature request related to a problem? Please describe.**
Today, a detail panel is unmounted upon the parent row being collapsed, wiping out any state that was present in the detail panel. This is a little annoying in my use case, as selections inside the detail panel are lost without propagating this selection change up to the parent component.

I am assuming this is caused by the `mountOnEnter` / `unmountOnExit` props being passed into `Collapse` here:

https://github.com/material-table-core/core/blob/9245d2ff602e4444ac4c4b842dcee525254c9ec4/src/components/m-table-detailpanel.js#L66-L77

**Describe the solution you'd like**
To avoid introducing breaking changes, we could pass some prop like `disableDetailPanelUnmount`:

```
<Collapse
     in={isOpen}
     timeout="auto"
     unmountOnExit={!props.disableDetailPanelUnmount}
     mountOnEnter={!props.disableDetailPanelUnmount}
     onExited={() => {
       renderRef.current = undefined;
       rerender();
     }}
>
     {Render({ rowData: props.data })}
</Collapse>
```

**Describe alternatives you've considered**
Alternatively, I can propagate any detail panel state I need to preserve to a parent component, and then repopulate the newly mounted detail panel with the old state. This is very annoying, however.

**Comment by Domino987** [comment]
I agree that option would be nice. 
Maybe even add it to the detail panel itself instead to the option. This would keep the stuff together. 
Would you mind creating a PR for this ?

**Comment by TheGoodSpinach** [comment]
Sure, I'll try to put something together soon. Thanks!
