### ISSUE TITLE
Issue with icons in the pagination

### ISSUE THREAD

**Issue by kouraf** [material-table-core/core#408]
#### Fork the following to reproduce the bug:

  - #### [CodeSandbox](https://codesandbox.io/s/quizzical-mountain-wsxu4)

**Bug Description**
There's an issue with icons in the pagination. 

**Screenshots**
![image](https://i.imgur.com/cltVNTY.png)

**To Reproduce**
Just copy the `Hello-world` example.

**Expected behavior**
Getting the right icons.

**Desktop (please complete the following information):**

- OS: Ubuntu and macOS
- Browser Chrome and firefox
- Version 4.3.10

**Suggestion**
Make `TABLE_ICONS` default icons
![image](https://i.imgur.com/aKyZ0hh.png)

**Comment by Domino987** [comment]
This technically not a bug. You could also just added the icons to your head file.

Adding them would result in an increased bundle size and more dependencies.

In the other hand, I feel like 99% of the users are using most of the icons anyway so the lib is already added anyway. 

Would you mind creating a PR for this.

**Comment by andremantaswow** [comment]
I'm having the same issue but im using Material UI 5 so I installed as described here: https://material-table-core.com/docs/material-ui-v5

```
    "@material-table/core": "^0.2.8",
    "@mui/icons-material": "^5.0.4",
    "@mui/lab": "^5.0.0-alpha.51",
    "@mui/material": "^5.1.0",
    "@mui/styles": "^5.0.1",
```

Is this still work in progress or should I install something?

**Comment by kouraf** [comment]
@andremantaswow i'll rise a `PR` this night!

**Comment by andremantaswow** [comment]
@kouraf thanks but I solved my issue just by importing Material Icons in the `<Head>` of my _document.tsx file (im using nextjs)
```
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/icon?family=Material+Icons"
></link>
```

**Comment by kouraf** [comment]
@andremantaswow Yes this solve the issue, but I prefer to install mui/icons, as said @Domino987 since everyone is already doing it.

**Comment by Domino987** [comment]
Maybe we can also check if they are installed? And use them as fallback if they are installed? That should work in plain js

**Comment by kouraf** [comment]
@Domino987 :thinking: interesting !! how do you see that exactly ? by checking inside the `package.json` ? or running programmatically `npm ls @material-ui/icons`? i don't feel comfortable with having a conditional import also ! can you tell me more about your idea :smile:

**Comment by Domino987** [comment]
Maybe import the icons and if the are not undefined. Not sure if that works though.

**Comment by kouraf** [comment]
I don't think it's a good idea, if you are too concerned about the bundle size, maybe we just grab the svgs we need and don't install all the package !

**Comment by Domino987** [comment]
After thinking about it, we should just import them, threeshaking should apply anyway. Anybody wants t create a PR for this?

**Comment by Domino987** [comment]
I will release a new version soon.
