### ISSUE TITLE
Material table re-renders on change state of parent functional component

### ISSUE THREAD

**Issue by elettrodue** [material-table-core/core#412]
I have a MaterialTable component with a custom column's render that has a fetch.
Every time I change the state of the table's parent component, it re-render and call the column component 2 times , by doing so, the whole application is slowed down.
Is there any solution to prevent this behavior? 
This is an example: 
```
function TestTable(props){
    const[test, setTest] = useState(false) 
    const [columns] = useState([
      { title: 'Id', render: rowData => JSON.stringify(rowData.tableData) },
      { title: 'Articolo', field: 'cd_ar' },
      { title: "Stato lavorazione", render: rowData => <Completamento data={rowData} height= "1.3rem" /> }
    ])
    const {loading, data, options } = props 

    return <>
      <MDBBtn onClick={()=>setTest(!test)}>TEST</MDBBtn>
      <div className="ordini-table mt-2 mb-3" style={{ maxWidth: '100%' }}>
        <MaterialTable
          title = 'Tabella'     
          isLoading = {loading}
          columns = {columns}
          data = { data}
          options = {options}
          components={{
            Row: props => <MTableBodyRow key={props.data.id_dorig} id={props.data.id_dorig} {...props} />
          }}
        />
      </div>
    </>
  }
```
If I change the test state, the whole table will re-render and the columns Id change every time (uuid)
Thanks in advance

**Comment by matthewoestreich** [comment]
I believe re-rendering all children when the parent state changes is expected behavior. This is just how React works. In order to prevent child re-renders on parent state change, you can use something like `useMemo` or `useCallback`. You will most likely need to memoize the entire TestTable component.

Something like this..

```js
function TestTable(props) {
  // ...
}

const TestTableMemo = React.memo(TestTable);
export default TestTableMemo;
```
