### ISSUE TITLE
Large bundle file because of @mui/icons-material

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [material-table-core/core#418]
**Describe the bug**
Large bundle file because of @mui/icons-material

**To Reproduce**

1. Create a fresh new project.
2. Build project.
3. Watch files in browser or analyze with @next/bundle-analyzer

**Expected behavior**
Not bundling all unused mui icons.

**Screenshots**
![](https://i.imgur.com/jtPIHsd.png)

**Additional context**
The version of packages:

```json
{
    "@material-table/core": "0.2.9",
    "@mui/icons-material": "5.1.1",
    "@mui/lab": "5.0.0-alpha.56",
    "@mui/material": "5.1.1",
    "@next/bundle-analyzer": "12.0.4",
    "next": "12.0.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "typescript": "4.5.2"
}
```

**Comment by matthewoestreich** [comment]
We do not use that package as a dependency. It looks like you'll need to open an issue with them.

**Comment by ClassicDarkChocolate** [comment]
> We do not use that package as a dependency. It looks like you'll need to open an issue with them.

It's there in next branch

https://github.com/material-table-core/core/blob/24c83c5e0e52bc204655cdc0e33b7eee1b3747e8/package.json#L113

**Comment by matthewoestreich** [comment]
Ahh my bad!

**Comment by Mohron** [comment]
I'm having this same issue.
![image](https://user-images.githubusercontent.com/3623122/145304065-0b9e59fd-faf5-4035-a756-8bb454d5258f.png)
