### ISSUE TITLE
Tree data icon style

### ISSUE THREAD

**Issue by rokpu** [material-table-core/core#419]
Hello,
I'm bringing up an issue from _**material-table**_ that wasn't addressed - https://github.com/mbrn/material-table/issues/707.

Would it be possible to add different icons for the root table, and/or allow customization? The root table icon is very confusing when you have several layers of nesting. It's hard to distinguish what's a parent and what's a child. 
A branch line indicator, different icons for nested layers, or even some color change would make it a lot easier to differentiate for a user.

**Comment by matthewoestreich** [comment]
Yes, that sounds like it should be possible. I can get around to this when I have some time, or if you would like it fixed quicker we are actively merging PR's here.

**Comment by Tobbe129** [comment]
Really want this aswell

**Comment by Domino987** [comment]
How about this.
If you want to adapt the icon, you pass a custom function to the DetailPanel icon and adapt it as you want it.
And the fallback would be the ChevronRight, since it is also used for the detail panel? Would that work for you?
@Tobbe129 @rokpu 

```
 icons={{
        DetailPanel: ({level}) => {
          if (level === 0) {
            return level;
          }
          return <ChevronRight data-testid="chevron_right" />;
        }
      }}
```

Passed props would include the row and the level/current depth.

**Comment by rokpu** [comment]
Thanks, @Domino987 this is awesome!

 I'll adapt it to rotate through 3 different icons depending on the level.

Do you have any suggestions on the proper way to pass the level to the DetailPanel without altering other behaviors?

**Comment by Domino987** [comment]
Good that you like it. I already have an implementation. I'll crate a PR that you can check it out in a bit. I'll link it here.

**Comment by rokpu** [comment]
Awesome, thanks for the quick turnaround. Looking forward to it!

**Comment by Domino987** [comment]
https://github.com/material-table-core/core/pull/451 does this work for you?

**Comment by Domino987** [comment]
I am releasing a new version right for. So should be a few minutes till you can try it out in real.
