### ISSUE TITLE
Is it possible to start the component in bulk edit mode?

### ISSUE THREAD

**Issue by obsd** [material-table-core/core#422]
I'm using this great table, and I want to start this in bulk edit mode.
like that:

![image](https://user-images.githubusercontent.com/1475778/143872649-c5b032c8-ff06-484c-8dd6-4c61ced22555.png)

Any help would be appreciated.

**Comment by matthewoestreich** [comment]
I do not believe this is possible using native, built-in options. You may be able to get away with doing something hacky (like forcing a click on the bulk edit button?).  I know that isn't the answer you're looking for, though :(

**Comment by fagom** [comment]
@obsd will this work?
[Bulk-Edit-Default](https://codesandbox.io/s/mtable-bulk-edit-tn5uye?file=/src/App.js)

**Comment by Domino987** [comment]
I am closing this, because this seems to be the right answer. Ty
