### ISSUE TITLE
Searching throw error while using tree data

### ISSUE THREAD

**Issue by UgurKacak** [material-table-core/core#424]
**Describe the bug**

Searching functionality on material-table-core version 2.0.12 with same data working well. However search input be laggy. Somehow latest version of library throwing error.
`Cannot read properties of undefined (reading 'tableData')`

**To Reproduce**

1. Go to sandbox: https://codesandbox.io/s/elated-dew-rzmos
2. Try to search.

**Expected behavior**
Should filter data correctly.

**Comment by 9RA** [comment]
I had the same error. There is a problem in the markForTreeRemove function.

In older versions, the pathPart was assigned the index of the array, but now it is assigned the uuid.
However, the subsequent code still tries to use pathPart to refer to the index of the array.
As a result, undefined is assigned to pointer, and an error occurs when the next loop tries to refer to the undefined property.

```
const markForTreeRemove = (rowData) => {
  let pointer = this.treefiedData;
  rowData.tableData.path.forEach((pathPart) => {  // pathPart is any uuid
    if (pointer.tableData && pointer.tableData.childRows) {
      pointer = pointer.tableData.childRows;
    }
    // Try to reference pointer.uuid, but it is undefined
    pointer = pointer[pathPart];
  });
  pointer.tableData.markedForTreeRemove = true;
};
```

The following modification will allow the search to work properly with tree data.

```
if (Array.isArray(pointer)) {
  pointer = pointer.find(p => p.tableData.uuid === pathPart)
}
```

**Comment by UgurKacak** [comment]
Thanks for solution 🎉

**Comment by rokpu** [comment]
Hi, I'm still experiencing the same error. I'm running on the latest version `4.13.31`

```
data-manager.js:1038 Uncaught TypeError: Cannot read properties of undefined (reading 'tableData')
    at data-manager.js:1038:1
    at Array.forEach (<anonymous>)
    at markForTreeRemove (data-manager.js:1037:1)
    at data-manager.js:1075:1
    at Array.forEach (<anonymous>)
    at DataManager.treefyData (data-manager.js:1062:1)
    at DataManager.getRenderState (data-manager.js:198:1)
    at Object.<anonymous> (material-table.js:423:1)
    at later (index.js:27:1)
```

**Comment by rokpu** [comment]
In the interim, i've reverted to `2.0.12`, and that works. It's much slower

**Comment by rokpu** [comment]
Slight update here, changing the order of the data to tree based solves the problem for the latest version as well
