### ISSUE TITLE
Multiselect popover jumping around

### ISSUE THREAD

**Issue by RomaBogatikov** [material-table-core/core#428]
When using filtering option with a lookup, multiselect popover modal jumps up/down when different select options are clicked/tapped.

Demo of a bug can be found in the sandbox below.
https://codesandbox.io/s/material-table-core-multiselect-popover-bug-yj9xn?file=/src/index.js

A discussion of this issue in Material UI on StackOverflow (a very nice explanation with a solution to the problem is there as well): https://stackoverflow.com/questions/59785482/multiselect-box-popover-keeps-jumping-when-scroll-or-select-items

Steps to reproduce
1. Open sandbox
2. Click on 'Birth Place' filtering dropdown:
![image](https://user-images.githubusercontent.com/40308050/145464517-09552d54-4db2-4f1d-a530-e0d142416925.png)

3. Click on different select options
4. Observe the popover jumping up/down

![image](https://user-images.githubusercontent.com/40308050/145465026-88b17a81-79f6-4f49-bbf0-6586491a6dfa.png)

**Comment by Domino987** [comment]
Fixed with the newest version
