### ISSUE TITLE
reorder of rows using drag and drop are breaking in latest version

### ISSUE THREAD

**Issue by yashaswinibprasad87** [material-table-core/core#431]
Below doesnot work:

onDragStart={(e) => {
                    console.log("onDragStart");
                    DrageState.row = props.data.tableData.id;
                  }}
                  onDragEnter={(e) => {
                    e.preventDefault();
                    if (props.data.tableData.id !== DrageState.row) {
                      DrageState.dropIndex = props.data.tableData.id;
                    }
                  }}
                  onDragEnd={(e) => {
                    console.log(`onDragEnd`);
                    if (DrageState.dropIndex !== -1) {
                      this.reOrderRow(DrageState.row, DrageState.dropIndex);
                    }
                    DrageState.row = -1;
                    DrageState.dropIndex = -1;
                  }}

throws error

data-manager.js:358 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at data-manager.js:358
    at Array.map (<anonymous>)
    at DataManager.setData (data-manager.js:357)
    at MaterialTable.setDataManagerFields (material-table.js:712)
    at MaterialTable.componentDidUpdate (material-table.js:752)
    at commitLifeCycles (react-dom.development.js:20684)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23151)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at commitRoot (react-dom.development.js:22990)
    at performSyncWorkOnRoot (react-dom.development.js:22329)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at discreteUpdates$1 (react-dom.development.js:22420)
    at discreteUpdates (react-dom.development.js:3756)

Help to get it work

**Comment by Domino987** [comment]
Is this still a problem with the latest version?

**Comment by yashaswinibprasad87** [comment]
> Is this still a problem with the latest version?

yes still no fix for the mentioned issue


below are my versions
 "@material-table/core": "^0.2.9",
 "@mui/material": "^5.2.3",

below is sample code of reordering Rows
https://codesandbox.io/s/confident-austin-poz9z?file=/src/CustomTable.js

**Comment by Domino987** [comment]
It seems like you are mixing mui v4 and mui v5, Also I cannot reproduce the error for me. Can you check the sandbox and set the correct dependency?

**Comment by yashaswinibprasad87** [comment]
Code Sandbox throws  error for muiv5 if using material table... its
mandatory to use material core v4 dependency...
But my original project has no depenendency on material ui core

**Comment by Domino987** [comment]
No you dont actually: https://material-table-core.com/docs/material-ui-v5.
Just install the next version aka 0.2.X

**Comment by yashaswinibprasad87** [comment]
> No you dont actually: https://material-table-core.com/docs/material-ui-v5. Just install the next version aka 0.2.X

please find below screenshot i have removed dependency

![image](https://user-images.githubusercontent.com/43347321/147905238-0a2ef213-22eb-471a-84eb-ed7da2e9619a.png)

Below dependencies added in codeSandBox

![image](https://user-images.githubusercontent.com/43347321/147905269-a8b5b520-9d7c-4aca-8cea-7b9f6578f758.png)

**Comment by Domino987** [comment]
Yes as I said above, if you use the Mui v5 version, you need to use the next version of material table. Which is currently 0.2.11. so if you select this version instead of 4.x.x, it should only be Mui v5.

**Comment by yashaswinibprasad87** [comment]
> Yes as I said above, if you use the Mui v5 version, you need to use the next version of material table. Which is currently 0.2.11. so if you select this version instead of 4.x.x, it should only be Mui v5.

Yes , i have changed it in CodeSandbox as mentioned,

 "dependencies": {
    "@emotion/react": "11.7.1",
    "@emotion/styled": "11.6.0",
    "@material-table/core": "0.2.11",
    "@mui/icons-material": "5.2.5",
    "@mui/material": "5.2.5",
    "@mui/styles": "5.2.3",
}

But unable to reorder rows using the code , it was working in earlier versions
Please check out the [link](https://codesandbox.io/s/confident-austin-poz9z?file=/src/CustomTable.js).

**Comment by Domino987** [comment]
I cannot reproduce the error, It just does not do anything when reordering. Would you mind creating a video or a step by step guide to cause the error in the sandbox?

**Comment by yashaswinibprasad87** [comment]
> I cannot reproduce the error, It just does not do anything when reordering. Would you mind creating a video or a step-by-step guide to cause the error in the sandbox?

Re-order is not working in the below Sandbox link:
https://codesandbox.io/s/confident-austin-poz9z?file=/src/CustomTable.js

Uploading 
 screen-capture (1) (4).mp4…

**Comment by yashaswinibprasad87** [comment]
> > I cannot reproduce the error, It just does not do anything when reordering. Would you mind creating a video or a step-by-step guide to cause the error in the sandbox?
> 
> Re-order is not working in the below Sandbox link: https://codesandbox.io/s/confident-austin-poz9z?file=/src/CustomTable.js
> 
> Uploading screen-capture (1) (4).mp4…

@Domino987  any update on this?

**Comment by Domino987** [comment]
No not yet because this is such a complex demo with manipulating the internals of the table itself making it super hard to track what the error might be.
Can you pinpoint the problem or create a minimal demo where the error might be apparent?
