### ISSUE TITLE
Validate fails to click on  save button on add row/edit row

### ISSUE THREAD

**Issue by yashaswinibprasad87** [material-table-core/core#433]
Steps to reproduce:

 columns: [
            {
                title: 'Code', field: 'code', width: 150,
                validate: rowData => rowData.code === '' || rowData.code === undefined ? 'Mandatory' : '',
            },
Before:
![image](https://user-images.githubusercontent.com/43347321/145947475-421dfdbb-4dd9-4610-bd0c-efcd9c16eec4.png)

After entering Value
![image](https://user-images.githubusercontent.com/43347321/145947313-23c45659-096f-4a2f-8a4a-ca5b6f9f9813.png)
button is not able to click , still it is in disabled after entering a value

Please provide solution to fix it

**Comment by Domino987** [comment]
Can you produce that in a complete sandbox per our guidelines?

**Comment by yashaswinibprasad87** [comment]
> Can you produce that in a complete sandbox per our guidelines?

![image](https://user-images.githubusercontent.com/43347321/147068821-eba7a992-76fe-4ae7-945a-b3a2a30e198c.png)


[https://codesandbox.io/s/confident-austin-poz9z?file=/src/CustomTable.js](url)

**Comment by matthewoestreich** [comment]
That link doesn't seem to work?

**Comment by yashaswinibprasad87** [comment]
> That link doesn't seem to work?
Above Link works.
you can check below too
https://codesandbox.io/s/confident-austin-poz9z?file=/src/App.js

**Comment by Domino987** [comment]
So I looked into it and with the newst version, if you return true isntead of an empty string (indicating some kind of error), it works: 

```
 validate: (rowData) =>
        (rowData.name === "" || rowData.name === undefined)
          ? "Name is Mandatory"
          : true
```

**Comment by yashaswinibprasad87** [comment]
> So I looked into it and with the newst version, if you return true isntead of an empty string (indicating some kind of error), it works:
> 
> ```
>  validate: (rowData) =>
>         (rowData.name === "" || rowData.name === undefined)
>           ? "Name is Mandatory"
>           : true
> ```

It worked. Thanks.

Any patch release will be there for  validation changes?

**Comment by Domino987** [comment]
What do you mean with validation changes?

**Comment by yashaswinibprasad87** [comment]
> What do you mean with validation changes?

It is hard for a new developer to identify such fixes. All these changes or solutions to be in documentation or release notes.

**Comment by Domino987** [comment]
Ah you mean the docs.
I just added some [docs for the valdiation](https://material-table-core.com/demos/validation/basic).
