### ISSUE TITLE
Action column not ignored in editmode

### ISSUE THREAD

**Issue by Tobbe129** [material-table-core/core#434]
v4.3.11

Having selection box enabled and going to editmode, makes the actions to its own column in edit mode. A bit hard to explain but please look at the picture:

OK display mode:
![image](https://user-images.githubusercontent.com/12426470/146260759-86bc481e-9c7b-441d-8582-efec808ca7f0.png)

Not OK edit mode, extra column (actions?):
![image](https://user-images.githubusercontent.com/12426470/146260690-22ec9a8e-2cb5-49c6-83b2-d28b3fa0952d.png)

**Comment by Tobbe129** [comment]
Guessing the bug is somewhere here by the look of the code: https://github.com/material-table-core/core/blob/master/src/components/MTableEditRow/index.js#L266-L284

**Comment by Tobbe129** [comment]
Confirmed, this is the issue, removing this and everything works fine, treedata or not: https://github.com/material-table-core/core/blob/master/src/components/MTableEditRow/index.js#L276

**Comment by Domino987** [comment]
Is this still a problem with the newest release?

**Comment by Tobbe129** [comment]
Yes, just tried it out

**Comment by Domino987** [comment]
Ok can you put that in a sandbox so we can check it with your setup? @Tobbe129

**Comment by Tobbe129** [comment]
This is now fixed in latest version. GJ!
