### ISSUE TITLE
The class name of Table title have unexpected ForwardRef prefix.

### ISSUE THREAD

**Issue by salmanorak** [material-table-core/core#437]
**Describe the bug**

The wrappers of title, actions and etc. on the toolbar are having unexpected class names prefix as ForwardRef(MTableToolbarRef).

**To Reproduce**

1. Kindly open the sandbox below. 
2. Inspect the table title
3. Check the table title field HTML on the developer tools.
4. See "ForwardRef(MTableToolbarRef)-title-9"  class.

[Sandbox](https://codesandbox.io/s/title-class-name-u2gqj)

**Expected behavior**

Instead of "ForwardRef(MTableToolbarRef)" it should have "MTableToolbar" prefix on each part's class name

**Screenshots**
![image](https://user-images.githubusercontent.com/41747037/146793169-fc7cd83a-a723-43f2-9a04-643fde031903.png)

**Desktop :**

- OS: [Window 10]
- Browser [chrome]
- Version [96.0.4]

**Version:**
@material-table/core : 4.3.11
@material-ui/core : 4.12.3

**Comment by saiemsaeed** [comment]
Thank you for starting this issue @salmanorak, I'm also facing this issue.

**Comment by matthewoestreich** [comment]
Since these components are using ForwardRef, is this expected behavior? Or should that not show up in the rendered class name when using ForwardRef?

I'm asking because I do not know if this is expected or not when using ForwardRef.

**Comment by ymor** [comment]
@oze4 This is not expected behaviour, you shouldn't see the ForwardRef in the class name, though technically it doesn't  actually cause any issues as the class has the correct styles.
I had a quick look and changing 
```javascript
export default withStyles(styles)(MTableToolbarRef);
```
to
```javascript
export default withStyles(styles, { name: 'MTableToolbar' })(MTableToolbarRef);
```

Results in the classes having the `MTableToolbar` prefix:
![image](https://user-images.githubusercontent.com/2701844/146978203-13277e8d-bb75-4fde-9f60-5989124ca242.png)

**Comment by matthewoestreich** [comment]
@ymor thank you so much for figuring this out! I will make the necessary changes and publish a new version.

**Comment by matthewoestreich** [comment]
Published v4.3.14

**Comment by salmanorak** [comment]
thanks a lot @oze4  for your quick handling. 
Take care and stay healty.

**Comment by salmanorak** [comment]
@oze4
I have realized that The same issue is also existing in another field. We have the same issue on MTableHeader.

- ForwardRef(MTableHeaderRef)

I have checked all markup but couldn't find any other instance except the `ForwardRef(MTableHeaderRef)`. But please do check the code base for possible other instances.

Should I open another bug entry for this one? @oze4

**Comment by matthewoestreich** [comment]
#441
