### ISSUE TITLE
4.3.12: data-manager 'findDataByPath' unable to find by path if not treedata

### ISSUE THREAD

**Issue by Tobbe129** [material-table-core/core#438]
4.3.12 (and 4.3.11)

Trying to select single rows in a non-treedata table, results in this:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tableData')
    at DataManager.changeRowSelected (data-manager.js:504)
```

Maybe related to this PR: https://github.com/material-table-core/core/pull/411
And this reported issue: https://github.com/material-table-core/core/issues/402

Issue is probably located here: https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L572-L573

This is a blocker for us, is there anyway to override this in an easy way until fixed? 
Thank you and keep up the awesome work!!

**Comment by matthewoestreich** [comment]
Are you wanting to do something like this? https://material-table-core.com/demos/selection/on-row-click

**Comment by matthewoestreich** [comment]
@Tobbe129 please let me know if that helped at all, if not I will reopen the issue.

**Comment by Tobbe129** [comment]
Hi @oze4, 

Im a bit of a newbie regardgin sandbox, otherwise I would have created one.
Im just refering to the regular select checkboxes, in a flat table (not tree). Its just crashing for me, no custom things around it.

**Comment by matthewoestreich** [comment]
So if you copy that demo code locally, it doesn't work for you?

**Comment by Tobbe129** [comment]
Got it working, of course it was my fault, I was adding the function for finding parent node (for tree mode) conditionally, otherwise false which was incorrect, undefined instead made it work. Closing this.
