### ISSUE TITLE
Having summary row as first row

### ISSUE THREAD

**Issue by salmanorak** [material-table-core/core#442]
**Is your feature request related to a problem? Please describe.**

No, it is not related to any problem. 

**Describe the solution you'd like**

Right now there is only one option to have a summary row at the bottom with renderSummaryRow prop. 

Having the summary row as a first row also makes sense, This is another common use-case of summary row.

When there are lots of rows existing, then the user should scroll down to the end of the table to be able to see the summary row. In this kind of case having the summary row as the first row increases the user experience. This feature is also required in one of my projects. Right now I am overriding the MTableBody Component to add a new row to the table body as a first row and style it.

Additionally, this row should not be affected by sorting. The position should be consistent with the preference of the user.

So as a solution one new parameter can be added to renderSummaryRow as a position with "bottom, top" options.

**Describe alternatives you've considered**

1- As I mentioned overriding MTableBody is an alternative solution but it is not looking good. This solution has a problem with export features since it is not a native part of TableBody it is being omitted on the export process.
2- One row can be added to data and that row can be styled with a summary row style. In that case, the summary row should be excluded from sorting. This is also a kind of hack so it is also not looking good.

**Comment by matthewoestreich** [comment]
Hi! Would you mind using codesandbox to recreate this issue? I'm not sure I understand.

**Comment by salmanorak** [comment]
Actually, Let me clarify my point then if You still think we need code sandbox then I will create one.

Right now there is no option for managing the position of the summary row which is going to be created by renderSummarRow prop. It is always at bottom of table.

So I am suggesting to add a new feature that will enable to render summary row as first row or last row in table body. This feature can be achieved by just adding position argument to renderSummaryRow and utilize it during positioning the summary row.

This feature is needed in my project and there is no native way to do it right now. I have just some solutions which looks like hacking so it would be great if you can introduce a native way to do it.

**Comment by matthewoestreich** [comment]
Hello @salmanorak you will need to provide a SandBox if you want this issue addressed - otherwise, you will need to provide a PR to fix this. The reason we require SandBox is because they clearly show, without any misunderstanding, what you are talking about. Otherwise, it is very easy for things to get lost in translation. A SandBox is a million times easier than going back and forth like this.

Please, create a reproducible demo for this issue.

**Comment by matthewoestreich** [comment]
If you review our guidelines you will see we even created starter templates in codesandbox that you can fork instead of having to start from scratch.
