### ISSUE TITLE
Fixed Header on scroll

### ISSUE THREAD

**Issue by iamwilson** [material-table-core/core#449]
Hi Devs,

Just wanted to ask whether there's an implementation/ workaround for having fixed table headers on scroll.

Looking forward to hear from you.

Thanks.

**Comment by fagom** [comment]
Hi @iamwilson, is this what you are looking for?
[MTable-Fixed-Header](https://codesandbox.io/s/mtable-fixed-header-wkw89q?file=/src/App.js)

**Comment by iamwilson** [comment]
Thanks a tonne. That's exactly what I wanted.
