### ISSUE TITLE
Support for search field props

### ISSUE THREAD

**Issue by alex-phillips** [material-table-core/core#450]
**Describe the solution you'd like**
Currently there's no way to provide additional props to the search field in the toolbar, specifically controlling the `size` field of the TextField that MUI provides.

**Describe alternatives you've considered**
Attempted to manually control the CSS via classes, but this seems a bit out-of-the-way compared to how MUI handles these styles.

**Comment by Domino987** [comment]
Would you mind creating a PR for this for example by expanding the Toolbar component to spread optional searchbar props for example to the search input when overriding the Toolbar via the component toolbar??
