### ISSUE TITLE
Fix changelog generation automation

### ISSUE THREAD

**Issue by kkirsche** [material-table-core/core#453]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
https://github.com/material-table-core/core/blob/master/CHANGELOG.md is not populated with changes between releases.

- #### Please try to be as detailed as possible
It appears that the changelog is generated via automation, and currently states that there are no changes between the releases.

**Describe the bug**
The changelog does not contain a list of commits, changes, or other information about what has changed aside from the updated version number and release date.

**To Reproduce**
Visit https://github.com/material-table-core/core/blob/master/CHANGELOG.md

**Expected behavior**
The changelog would contain a summary of the changes between versions.

Thanks for all you do

**Comment by Domino987** [comment]
Hi, yes thank you for this.
It is indeed auto generated if we use correct pretags to the commits like fix: bug: etc.
Seems during the latest development, we omit those a few times.
Ill try to do better,
