### ISSUE TITLE
Wrong detailPanel prop signature when passing array of functions

### ISSUE THREAD

**Issue by tondi** [material-table-core/core#455]
When passing array of functions to `detailPanel` prop, a typescript error is shown. It works well in runtime.

`type RowData = { word: string };`

```
const App = () => {
  const [data, setData] = useState(rawData);

  return (
    <MaterialTable<RowData>
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
      // here:
      detailPanel={[
        (rowData) => ({
          render: () => <pre>{rowData.word}</pre> // Property 'word' does not exist on type '{ rowData: RowData; }'.ts(2339) error
        })
      ]}
    />
  );
};
```

rowData.word gives `Property 'word' does not exist on type '{ rowData: RowData; }'.ts(2339)`

**To Reproduce**

1. Go to https://codesandbox.io/s/material-table-starter-template-forked-yrup9?file=/src/index.tsx
2. See error in `detailPanel` definition
3. Expand row
4. Notice that data is properly rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/25098043/149162563-a2a61aa0-ade6-4d14-93fc-1930b1c8674a.png)
![image](https://user-images.githubusercontent.com/25098043/149162634-648c790c-9c3e-4ca1-8db8-1fb07e14b8fd.png)

We probably want no ts error when using `(rowData: RowData) => ...`
```
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -28,7 +28,7 @@ export interface MaterialTableProps<RowData extends object> {
     | (({ rowData }: { rowData: RowData }) => React.ReactNode)
     | (
         | DetailPanel<RowData>
-        | (({ rowData }: { rowData: RowData }) => DetailPanel<RowData>)
+        | (( rowData: RowData ) => DetailPanel<RowData>)
       )[];
   editable?: {
     isEditable?: (rowData: RowData) => boolean;
```
or a change in detailPanel to make it really return `{ rowData: RowData }`

**Comment by Domino987** [comment]
Rowdata needs to be the type of the row and not if the column. Rowdata does not contain Word, so it's correct. If you update your type to include word it will work.

**Comment by tondi** [comment]
Sorry, it should be `type RowData = { word: string }`. I created this example quickly.
Here you can see screenshot with `RowData` updated to correct type, and that the error persists:

![image](https://user-images.githubusercontent.com/25098043/149194905-19f0c959-31ea-46e7-84e5-af5d239ea689.png)

https://codesandbox.io/s/material-table-starter-template-forked-vbd27?file=/src/index.tsx:496-529

**Comment by tondi** [comment]
@Domino987 Do you want me to submit a PR with the proposed fix?

**Comment by Domino987** [comment]
I am currently looking into it but sure!
