### ISSUE TITLE
Unable to render tables with mui v5 and pre-release version

### ISSUE THREAD

**Issue by feline-dis** [material-table-core/core#456]
We have recently upgraded from mui v4 to v5, and subsequently had to upgrade `@material-table/core` to the pre-release version for compatibility. Doing so seems to have caused the tables to stop working due to some undefined variables/type errors. Here are the errors present: 

```
ReferenceError: resizing is not defined
Source
MTableHeader
node_modules\@material-table\core\dist\components\MTableHeader\index.js (133:3)
```

```
TypeError: this.tableContainerDiv.current is null
Source
componentDidMount
node_modules\@material-table\core\dist\material-table.js (684:0)
```

I was able to reproduce with a simple codesandbox using mui v5 and the @material-table/core pre-release version [here](https://codesandbox.io/s/great-gagarin-o4k62?file=/src/App.js).

Let me know if I can supply any more info/do anything to help.
Thanks in advance 😄

**Comment by DavidLemayian** [comment]
related to https://github.com/material-table-core/core/issues/454

try install 0.12.11 for now

**Comment by rjumatov** [comment]
When will the main releases of this library support MUI5?

**Comment by Domino987** [comment]
Yes we had an erroneous merging which I will fix over the weekend and will release a new version. Sorry for that. Regarding the main branch, since it works currently quite well, I am not sure but as soon as majority is using the next Branch I guess.

**Comment by Domino987** [comment]
I just release v0.2.13 which works again xD

**Comment by rjumatov** [comment]
@Domino987 could you take a look at #460?
