### ISSUE TITLE
Enhance "remote data"

### ISSUE THREAD

**Issue by ckchiu2** [material-table-core/core#457]
**Is your feature request related to a problem? Please describe.**

I am integrating material-table with redux. However, redux is designed to return its latest state **after** a render, causing it incompatible with the remote data feature offered by material-table.

**Describe the solution you'd like**
1. In fact, the table itself has the `page` and `totalCount` props which are used for leveraging the pagination to the parent. However, it is neither documented nor demonstrated in any demo. 

2. By using the `data`, `page` and `totalCount` props, material-table will consider it as not a remote data, and will use the data-manager to manage the filtering, searching, sorting, etc. Currently I am working around by setting `customFilterAndSearch: () => true` and `customSort: () => true` for all columns.

I suggest to add a `remoteData` props for controlling the behavior of material-table. We can do something like `isRemoteData = () => this.props.remoteData || !Array.isArray((props || this.props).data)` to prioritize the remote data flag. And in `onQueryChange(query)`, do a `typeof(this.props.data) === 'function' ? this.props.data(query) : this.props.onQueryChange(query)` to preserve the original implementation of remote data feature. 

Note: `onQueryChange` is typed as a props of material-table but I cannot find any usage in the component.

Letting developers gain control over the internal data manager could also be an option (via injecting as props or providing other options to configure), but it requires them to have a good understanding to know how it works.

Another side note: Current the `onOrderChange(orderedColumnId, orderDirection)` callback uses `tableData.id` as the first argument, which we cannot link it to a column definition outside material-table. Suggest changing it to columnDef to align with the remote data flow.

**Describe alternatives you've considered**

Running `tableRef.current.onQueryChange` is not an option. 

1. I cannot get the latest redux state in the same render. (Of course one may just use the store directly, but it is an anti-pattern)

2. It will become an infinite loop if I run the function after the redux state change. [data(query) -> dispatch -> state changed -> onQueryChange() -> data(query)]

**Remarks**

This is the first time for me to write an issue with solutions (to be concise, the ever first attempt in joining an open-source project). Should I just create a PR instead?

**Comment by ckchiu2** [comment]
Any comment on this item?

**Comment by matthewoestreich** [comment]
If you provide a function to the `data` prop that is considered remote data. This is not documented on material-table-core.com but it is on material-table.com. You can find more here https://material-table.com/#/docs/features/remote-data

**Comment by Domino987** [comment]
Hi i wanted to come back to this. Why do you want to manage the current page etc with redux instead of just passing all data into the table? Could you elaborate on your setup.

**Comment by ckchiu2** [comment]
Our team uses redux for managing every single request goes to the server. 

I also have a private ~abandoned~ project which uses react-apollo to connect to MongoDB Realm GraphQL, where I can foresee s similar problem.

**Comment by Domino987** [comment]
Can I ask why the request goes through redux? The table can only work if it has full control, aka pass all the data, or no control of the data, in the form that data is a function and the current data is returned for the given query. Anything in between would be quite difficult to maintain because there is no true source of Truth. Why does it have to go through redux anyway?

**Comment by ckchiu2** [comment]
~Convention problem~

That is why I am suggesting to add an explict flag to indicate that the data is managed outside the table, instead of determining whether it is remote data only by checking if it is an async function.

**Comment by Domino987** [comment]
Would you mind setting up your data flow on a sandbox so I can understand your use case better ?

**Comment by ckchiu2** [comment]
https://codesandbox.io/s/get-started-coinbase-client-forked-vlygm9

Just a simple demo of how I want to integrate material table with redux or apollo client

**Comment by Domino987** [comment]
Ok, so you download all the data to the frontend, only to download it again during the filtering, instead of just using the table.

I do not understand why you want to download everything and if filtering, download the filtered list again.
Instead of just downloading it and just filter it in the frontend in the first place. Can you walk me through your thought process here?
Mix and matching filtering/sorting between both frontend and backend might also cause confusion.

**Comment by ckchiu2** [comment]
I just edited the sandbox to include pagination in the request. I think it is clear enough to show that the filter and pagination (and search and sort, to name but a few) should be done by the backend.

useQuery is just a simple hook provided by apollo client to handle the request state. When variable changes (for example, the name field), the hook will help us to send the request to the backend. When the request is completed, it will update the {data} returned and trigger a re-render, so that the table will receive the new data to be rendered.

In another speaking, I want to pass partial data as an array to the table, instead of a Promise, because I cannot create a promise and resolve it when data is updated as the new data is only available in the next render. And to distinguish between full data and partial data, we need a new flag.
