### ISSUE TITLE
On "add row", set focus on the new row

### ISSUE THREAD

**Issue by Phygon** [material-table-core/core#458]
This can be seen in the "editable" demo: https://material-table-core.com/demos/edit/editable

When clicking the "add" button, the focus is not in the edit fields of the new row, so that we have to click again before starting to write. This becomes tedious when adding multiple rows.

Is there an easy fix to add that behaviour (set focus on the edit fiels of the new row), or should that even be added to the component?

**Comment by Domino987** [comment]
I like that, I will add it to the base lib.

**Comment by Domino987** [comment]
Done with the most recent release.

**Comment by Phygon** [comment]
Thanks, that was quick!

However, I have two problems with this implementation:
1) My first column is not editable, so nothing gets the focus; Currently, I made a monkey patch like this:
```
const MyEditField = (props) =>
    <MTableEditField {...props} autofocus={!!props.columnDef.autofocus} />;
```
However, either setting focus on the first editable, non-hidden column would be good.

1) Similar to #456 , the element focus is set back each time the components refreshed. That is, when I type in one of the other edit fields, or when a ticker updates the redux store.
Could the focus be set on mount only?

**Comment by Domino987** [comment]
Hmh seems like there is still some stuff to work out ;)
Regarding number 2, I change the base implementation and it should work with the next release.

Also I am working on a heuristic to improve the focus.

**Comment by Domino987** [comment]
Can you check out the new implementation?

**Comment by Phygon** [comment]
> Can you check out the new implementation?

This works. Thanks!
