### ISSUE TITLE
next-branch uses deprecated @mui/styles since 0.2.13

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#460]
**Describe the bug**
I get a `DependencyNotFound` error when upgrading from 0.2.11 to 0.2.13.
It suddenly depends on `@mui/styles` which is per mui documentation:
> ⚠️ @mui/styles is the legacy styling solution for MUI. It is deprecated in v5. It depends on JSS as a styling solution, which is not used in the @mui/material anymore. If you don't want to have both emotion & JSS in your bundle, please refer to the @mui/system documentation which is the recommended alternative.
> ⚠️ @mui/styles is not compatible with React.StrictMode or React 18.

**To Reproduce**

1. Go to https://codesandbox.io/s/material-table-starter-template-forked-c43h3?file=/src/index.js
2. Everything works as expected without `@mui/styles` dependency

3. Go to https://codesandbox.io/s/material-table-starter-template-forked-inzm0?file=/package.json 
4. `DependencyNotFound` error arises

**Expected behavior**
The next-branch should not depend on a legacy styling solution.

**Desktop (please complete the following information):**

- OS: MacOS Monterey 12.1
- Browser: chrome
- Version: 97

**Comment by Domino987** [comment]
Will be fix with the next release

**Comment by rjumatov** [comment]
Fixed in 0.2.14
