### ISSUE TITLE
When making a cell editable with the lookup property in the column the value passed to the Select component is wrong.

### ISSUE THREAD

**Issue by pinkMoneyKing** [material-table-core/core#461]
**Describe the bug**
When making a cell editable with the lookup property in the column, the value passed to the Select component is wrong. In the data, the value for the lookup property corresponds to the lookup key. `data = {name: 41}, column: {field: 'name', lookup: {41: 'this is my name'}`. When you make the cell editable and click into it, opening the select component, the value passed to the select component is "this is my name" and not 41 causing an out of range error and for the select component to start out as empty. 

**To Reproduce**
Go to https://material-table-core.com/demos/filter/custom-filter/ and repalce the component with the below code. Then when you click on birthplace, the Select component opens but the currently selected value is missing and a out of range error is triggered. 
```
function CustomFilter() {
  return (
    <MaterialTable
      icons={TABLE_ICONS}
      cellEditable={{
        onCellEditApproved: (newValue, oldValue, rowData, columnDef) => {
          return new Promise((resolve, reject) => {
            console.log('newValue: ' + newValue);
            setTimeout(resolve, 1000);
          });
        }
        }}
      data={[
        {
          name: "Mehmet",
          surname: "aran",
          birthYear: 1987,
          birthCity: 63,
        },
        {
          name: "Zerya Betül",
          surname: "Baran",
          birthYear: 2017,
          birthCity: 34,
        },
      ]}
      columns={[
        {
          title: "Name",
          field: "name",
          filterComponent: () => <input placeholder="custom" />,
        },
        {
          title: "Surname",
          field: "surname",
        },
        {
          title: "Birth Year",
          field: "birthYear",
          type: "numeric",
        },
        {
          title: "Birth Place",
          field: "birthCity",
          editable: 'always',
          lookup: {
            34: "İstanbul",
            63: "Şanlıurfa",
          },
        },
      ]}
      
    />
  );
}

```

**Expected behavior**
The correct value be shown in the Select Component. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35308560/150235568-7e45a9e0-ed0f-4349-af9f-e9c1376efee1.png)
![image](https://user-images.githubusercontent.com/35308560/150235602-d71b235e-2666-4a1a-b2d0-db7bc96c833a.png)

**Comment by Domino987** [comment]
Would you mind throwing this in a sandbox?

**Comment by Domino987** [comment]
This will be fixed with the next release.
