### ISSUE TITLE
Create a custom Filter component not working with tableData property

### ISSUE THREAD

**Issue by yashaswinibprasad87** [material-table-core/core#464]
function handleChange(e) {
const val = e.target.value;
setSelectedVal(val);
console.log(val,props)
props.onFilterChanged(props.columnDef.tableData.id, val);
}

provide a solution for filtering column values

**Comment by Domino987** [comment]
Per our guidelines, could you create a sandbox and you want to acheive?

**Comment by yashaswinibprasad87** [comment]
> Per our guidelines, could you create a sandbox and you want to acheive?

https://codesandbox.io/s/confident-austin-poz9z?file=/src/App.js link filters are enabled u can check on this and update the solution

**Comment by yashaswinibprasad87** [comment]
> > Per our guidelines, could you create a sandbox and you want to acheive?
> 
> https://codesandbox.io/s/confident-austin-poz9z?file=/src/App.js link filters are enabled u can check on this and update the solution

Expected : to filter based on Languages

**Comment by ckchiu2** [comment]
You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.

Made some changes to your sandbox
https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js

Edit: swapped the parameters per comment

**Comment by Domino987** [comment]
@ckchiu2 Yes this would be the way to do it. Thanks for the answer.

Just FYI, you need to swap value and rowdata params in the customFilterAndSearch.

**Comment by yashaswinibprasad87** [comment]
> You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.
> 
> Made some changes to your sandbox https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js
> 
> Edit: swapped the parameters per commenanks will try this out

> You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.
> 
> Made some changes to your sandbox https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js
> 
> Edit: swapped the parameters per comment

Thanks will try this out,.. why is render and customFilterAndSearch method used? any reference docs to read about it, as there are lot of difference between this version and previous versions. (as the same code was working before migration to latest version of material-table-core

**Comment by ckchiu2** [comment]
You can view the ~outdated~ documentation from the original repository: https://material-table.com/#/docs/get-started
I used to dig out what can be achieved by referring to this guide (and from the source code lmao)

**Comment by yashaswinibprasad87** [comment]
> You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.
> 
> Made some changes to your sandbox https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js
> 
> Edit: swapped the parameters per comment

reseting the filter on change of empty option  is not Working with the code , can you verify and update it

**Comment by ckchiu2** [comment]
> > You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.
> > Made some changes to your sandbox https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js
> > Edit: swapped the parameters per comment
> 
> reseting the filter on change of empty option is not Working with the code , can you verify and update it

I think I forgot to save my latest change to the sandbox. Try again now.

**Comment by yashaswinibprasad87** [comment]
> > > You are filtering like using an ordinary text filter. To filter for an exact match of the row data, you need to provide the `customFilterAndSearch(value, rowData)` callback in the column definition.
> > > Made some changes to your sandbox https://codesandbox.io/s/quirky-haibt-qu5t3?file=/src/App.js
> > > Edit: swapped the parameters per comment
> > 
> > 
> > reseting the filter on change of empty option is not Working with the code , can you verify and update it
> 
> I think I forgot to save my latest change to the sandbox. Try again now.

Worked

**Comment by yashaswinibprasad87** [comment]
Working
