### ISSUE TITLE
Detail panel closes when component refreshes

### ISSUE THREAD

**Issue by isabellachen** [material-table-core/core#465]
Due to my component which contains this table being connected to the redux store, the table is continuously being refreshed due to a ticker in the store. I want to remove the ticker from the store but for now I can't remove it.

In the original implementation, this did not happen. I'm not sure why? Perhaps it was a simple DOM element unaffected by re-renders? But because now the detail panel is a full React component with [isOpen set to false at the very start](https://github.com/material-table-core/core/blob/f2f69b3cc913b7952ae13a6b759a2d9032008a19/src/components/m-table-detailpanel.js#L5), upon each update of the store the detail panel is closed.

Is there a way to somehow make sure the panel stays open?

**Comment by Domino987** [comment]
This was not the case because the original one mutated your data up into the redux store.
Would you mind creating a sandbox for this (maybe without redux but just a local ticker wit huse state maybe?) so I can take a look?

**Comment by isabellachen** [comment]
@Domino987 Thanks for the comment. Can you explain what you mean by the original material-table mutating the data up into the redux store?

I'll look at creating a sandbox on Monday. Thanks for maintaining this package :)

**Comment by Domino987** [comment]
Check it this issue die more Infos: https://github.com/mbrn/material-table/issues/1371

**Comment by Domino987** [comment]
This is fixed in the newest version
