### ISSUE TITLE
When the draggable false, the sorting is not working. (v4.3.16 -> v4.3.17)

### ISSUE THREAD

**Issue by ghyoo91** [material-table-core/core#466]
**Describe the bug**
When the options.draggable is false, the options.sorting is not working - sortIcon isn't rendered + header can't be clicked for sorting.

**To Reproduce**

1. Prepare a table with data and using release version before v4.3.16.
2. Set the "options.draggable" false & the "options.sorting" true.
3. Check the sortIcon has appeared and the sorting can be done.
4. Change the version into v4.3.17 or after versions.
5. Check the sortIcon hasn't appeared and the sorting cannot be done.

sandbox : https://codesandbox.io/s/wonderful-oskar-2sewq?file=/src/App.js

**Expected behavior**
The sorting should be working regardless the draggable is false or true.

**Screenshots**

v4.3.16 (NOT ISSUE!)
![v4 3 16](https://user-images.githubusercontent.com/20279300/150776956-ff1ebd80-60f6-49d6-9da9-e29d9f1e756d.png)

v4.3.17 (Bug)
![v4 3 17](https://user-images.githubusercontent.com/20279300/150776964-1b1e72d7-92aa-4049-8b10-81596f2915ed.png)

**Desktop (please complete the following information):**

- OS: MacOS 12.1
- Browser : Chrome
- Version : ~ v4.3.16 / v4.3.17 ~

**Comment by Domino987** [comment]
Seems like [this PR](https://github.com/material-table-core/core/pull/444) introduces some breaking changes and bugs.

I fix this and should be working with the lastest version v4.3.23.

**Comment by ghyoo91** [comment]
Thank you for correcting it immediately!
But sadly I think there is a side-effect.

In v4.3.23, the sorting is functionally working but the header's style is applied to the icons only.
![side-effect_v4 3 23](https://user-images.githubusercontent.com/20279300/151130396-04e3e4a3-e19c-4bd0-9d60-8495827906fc.png)

And this is the same example with just changing the version to v4.3.16. Several styles are applied to the "title" of the header when mouseover or selected.
![side-effect_v4 3 16](https://user-images.githubusercontent.com/20279300/151130595-7897a4d3-a968-44f5-90a1-08ea177045f4.png)

Should I find some other way to apply my styles on the header?
