### ISSUE TITLE
Toolbar action icons not aligned with default action icons (MUI 5)

### ISSUE THREAD

**Issue by andremantaswow** [material-table-core/core#469]
**Describe the bug**
Toolbar default icons are not aligned with custom action icons because they have different paddings.

Looking at the code for the `columnsButton`, we can see it has a prop `size="large"`
https://github.com/material-table-core/core/blob/next/src/components/MTableToolbar/index.js#L143

But the other ones don't have this `size` prop set. Eg the `Add` action: https://github.com/material-table-core/core/blob/next/src/material-table.js#L321

So I think it reaches here as undefined: https://github.com/material-table-core/core/blob/next/src/components/MTableAction/index.js#L59
(at least looking at React components tab I can see the `IconButton` has `size: undefined`)

**To Reproduce**
Example table

```
<MaterialTable
  data={[{ id: 1, name: 'test' }]}
  editable={{
    onRowAdd: (data) => { console.log(data); return Promise.resolve(true); },
  }}
  columns={[
    { field: 'id', title: 'ID' },
    { field: 'name', title: 'Name' },
  ]}
  options={{
    columnsButton: true,
    exportMenu: [
      {
        label: 'PDF',
        exportFunc: (cols: any, datas: any) => console.log('pdf export'),
      },
    ],
  }}
  actions={[
    {
      icon: 'save',
      tooltip: 'Save',
      isFreeAction: true,
      onClick: (event) => alert("You want to add a new row")
    }
  ]}
/>
```

**Expected behavior**
Icons should have same padding so that they are aligned.

**Screenshots**

![image](https://user-images.githubusercontent.com/58601723/151448551-c25eac51-b3e2-46da-a13f-68603accc710.png)

![image](https://user-images.githubusercontent.com/58601723/151448733-05846059-a6d5-470d-b17b-27aea8170907.png)

![image](https://user-images.githubusercontent.com/58601723/151448820-018729ab-3bf8-4862-9324-159c60d61d1a.png)

**Desktop**

- OS: Windows
- Browser Chrome
- Versions
```
"@material-table/core": "^0.2.17",
"@material-table/exporters": "^1.0.8",
"@mui/icons-material": "^5.0.4",
"@mui/lab": "^5.0.0-alpha.51",
"@mui/material": "^5.1.0",
"@mui/styles": "^5.0.1",
```

**Comment by Domino987** [comment]
Thank you for the detailed issue. It will be fixed with the next release!

**Comment by r0binxp** [comment]
I Have the same problem , any solution ?

**Comment by matthewoestreich** [comment]
@r0binxp which version are you on?

**Comment by r0binxp** [comment]
The Latest of Material table core
        "@material-table/core": "^4.3.39",
        "@material-ui/core": "^4.12.3",
        "@material-ui/icons": "^4.11.2",

**Comment by matthewoestreich** [comment]
Are you on the latest version?
