### ISSUE TITLE
Incompatible version of @date-io/date-fns in dependencies & peerDependencies

### ISSUE THREAD

**Issue by rok4f** [material-table-core/core#47]
@date-io/date-fns 2.x is incompatible with @material-ui/pickers 3.x which causes crash when editing row with date type field.
Please downgrade version of @date-io/date-fns to 1.x (e.g. "^1.3.13").

See also:
https://material-ui-pickers.dev/getting-started/installation
https://stackoverflow.com/questions/59600125/cannot-get-material-ui-datepicker-to-work

**Comment by matthewoestreich** [comment]
Thanks for opening this! I'll get that done ASAP.

**Comment by matthewoestreich** [comment]
I hate that commenting `Fix #n` closes the issue... sorry about that.

At any rate, I tested this and saw the same behavior (didn't work until downgrading). 

Version [2.3.1](https://www.npmjs.com/package/@material-table/core/v/2.3.1) has been published with these changes.

Thanks again for opening this!

**Comment by rok4f** [comment]
> Version [2.3.1](https://www.npmjs.com/package/@material-table/core/v/2.3.1) has been published with these changes.
> 
> Thanks again for opening this!
Upgraded, works fine.

**Comment by rok4f** [comment]
Upgraded, works fine.

> Version [2.3.1](https://www.npmjs.com/package/@material-table/core/v/2.3.1) has been published with these changes.
> 
> Thanks again for opening this!
