### ISSUE TITLE
Proptypes warning in console when passing a ref to MTableCell

### ISSUE THREAD

**Issue by josue-uitzil-by** [material-table-core/core#470]
Hi, I found the following proptypes warning while trying to override the cell component on material-table/core v4.3.10, however it can also be reproduced in v4.3.23.

**Describe the bug**
A proptypes warning is printed into the console when you override the cell component with a custom MTableCell that receives a ref. The issue is reproduced in the following codesandbox: [https://codesandbox.io/s/elated-beaver-0j1zf?file=/src/App.tsx](https://codesandbox.io/s/elated-beaver-0j1zf?file=/src/App.tsx)

![image](https://user-images.githubusercontent.com/87137177/151454685-5c41c474-87a5-4b36-a39f-6b6af3b3a5c9.png)

**To Reproduce**
1. Create a new custom Cell component that uses MTableCell component and pass a ref to it
2. Render a material table overriding the cell component with the custom cell
3. Open the console to see a proptypes warning

**Desktop**

- OS: macOS 11.4
- Browser: Chrome
- Version 97

I think that this issue might be caused by the propTypes definition of forwardedRed in the [MTableCell file](https://github.com/material-table-core/core/blob/master/src/components/MTableCell/index.js). 
For reference, material-ui defines the ref type of its component in the following way: [https://github.com/mui-org/material-ui/blob/master/packages/mui-utils/src/refType.ts](https://github.com/mui-org/material-ui/blob/master/packages/mui-utils/src/refType.ts). Maybe modifying the proptype definition of the forwardedRef in the MTableCell to also accept object could remove the warning.

**Comment by Domino987** [comment]
This should be fixed with the next release!
