### ISSUE TITLE
Sorting - Hover over column does not show sort icon, clicking column does not sort

### ISSUE THREAD

**Issue by mseccafien-sap** [material-table-core/core#471]
See demo: 
https://codesandbox.io/s/wonderful-oskar-2sewq?file=/src/App.js

**Describe the bug**

In current version 4.3.24, hovering over a column does not show the sort icon. You have to hover slightly to the right of the column name to reveal the hidden sort icon which is not very user friendly and not consistent with https://material.io/components/data-tables#behavior. In 4.3.16, this is not the case. 

Additionally, clicking the column does not sort but that is minor/optional compared to the missing icon hover.

**To Reproduce**

1. Hover over column name

**Expected behavior**
- See the sort icon

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- Version 97.0.4692.99

**Comment by Domino987** [comment]
Yes, I am aware and we are working on fixing it.

**Comment by Domino987** [comment]
Looks like #444 introduced that error. It should be fixed by the latest version.
