### ISSUE TITLE
Summary row crashes when search or filter result is empty 

### ISSUE THREAD

**Issue by Tatfi32** [material-table-core/core#472]
The example link from the official website: https://material-table-core.com/demos/Summaryrow/basic

When you type in the search element something, that is not present in the table, the whole table crashes. 
Tables without summary row don't exhibit this behavior. Filters also cause the same issue.

**Comment by CabdiraxiimAxmed** [comment]
I want to work on this. **please assign to me**

**Comment by Domino987** [comment]
Sure thing. Go for it!! Thank you

**Comment by Domino987** [comment]
I think this was caused because the version of the table in the docs was still old.

**Comment by Tatfi32** [comment]
It is not a bug probably, it appears you need to add a length check on data. The following code solves the issue.
But it is not obvious.

```
renderSummaryRow={({ column, data }) =>
  data.length == 0
     ? undefined
     :column.field === "age"
     ? {
          value: data.reduce((agg, row) => agg + row.age, 0),
          style: { background: "red" },
        }
        : undefined
}
```
![image](https://user-images.githubusercontent.com/45382631/151662054-f90d7468-1562-45f7-b4af-5af36576a7e2.png)

**Comment by Domino987** [comment]
It also should not be. Since its a hassle for the user, we should do this.

**Comment by Domino987** [comment]
Ok I updated the table version on the website. Seems to work now
