### ISSUE TITLE
Data with no id attribute

### ISSUE THREAD

**Issue by hlarouss** [material-table-core/core#478]
Hello everyone,

I'm using Material-Table to display a bunch of data I extract from my DynamoDB table. Each row of data has an id field but it's not called "id", it's actually called "SK".

Is there a way I can tell Material-Table to use "SK" (or any other name) rather than "id"? The other solution would be to add the "id" field when I get the data from DynamoDB but I wanted to avoid doing that.

Thanks in advance for your help!

**Comment by Domino987** [comment]
That would be an interesting prop to add. Would you mind creating a PR to adress this?

**Comment by hlarouss** [comment]
Sure thing! It's done, thanks!
