### ISSUE TITLE
`@mui/lab` should be part of dependencies

### ISSUE THREAD

**Issue by thisismydesign** [material-table-core/core#483]
I'm following the official docs for mui v5 and installing via `yarn add @material-table/core@next`.

Then I get the error: `Cannot find module '@mui/lab/DateTimePicker'`

I think `@mui/lab` should be part of dependencies.

**Comment by Domino987** [comment]
I'll add them to the list. TY!

**Comment by thisismydesign** [comment]
@Domino987 Thanks! I didn't see an update on the next branch yet or any PRs. Could you keep this open until it's resolved so that it's not forgotten?

**Comment by Domino987** [comment]
I already merged it so it's in the code. I'll create a release this week

**Comment by Domino987** [comment]
I already merged it so it's in the code. I'll create a release this week
