### ISSUE TITLE
Include the current query in the export function

### ISSUE THREAD

**Issue by b3ni** [material-table-core/core#484]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

```
exportMenu: [
  {
    label: 'Export CSV',
    exportFunc: (cols, datas) => {
      console.log(cols, datas);
    },
  },
],
```
- #### Please try to be as detailed as possible

In the custom export function, the current value of the global lookup is required.
I already have the filters per column, but the global filter would be necessary. This way you can make requests to the backend and generate custom reports, depending on the state of the table.

**Describe the solution you'd like**

The export function should receive the current query.

```
exportMenu: [
  {
    label: 'Export CSV',
    exportFunc: (cols, datas, query : Query<RowData>) => {
      console.log(cols, datas);
    },
  },
],
```

**Comment by Domino987** [comment]
We already added the searched, filtered and global data to it as 3. parameter. Would that be enough? Or what else do you need for your use case?

**Comment by b3ni** [comment]
> We already added the searched, filtered and global data to it as 3. parameter. Would that be enough? Or what else do you need for your use case?

Its perfect.
Thank you.
I close the issue.
