### ISSUE TITLE
Unable to change header height of material table

### ISSUE THREAD

**Issue by yashaswinibprasad87** [material-table-core/core#485]
Row height cannot be reduced

![image](https://user-images.githubusercontent.com/43347321/152941836-2548e296-9c88-4c1c-b7aa-7a003995e098.png)

Tried with height , maxHeight properties, unable to fix,

Any workaround, please help

**Comment by Domino987** [comment]
Try this:
https://codesandbox.io/s/material-table-starter-template-forked-cmc2f?file=/src/index.js
