### ISSUE TITLE
Column dragging drags the preceding hidden column

### ISSUE THREAD

**Issue by Chee7ah** [material-table-core/core#488]
**Describe the bug**
When dragging a column, which is preceded by a hidden column, material table will drag and drop the preceding hidden column, instead of the column being dragged.

**To Reproduce**

1. Go to [https://material-table-core.com/demos/columns/hide/](https://material-table-core.com/demos/columns/hide/)
2. Update the live demo by adding a new column to the front, so the hidden column is the middle column
3. Drag the last column ("surname") to the front
4. It won't happen, if you inspect the current state, you'll see that the hidden column ("name") has been moved to the front.
5. Trying again to drag the last column to the front will work, as it is no longer preceded by a hidden column

**Expected behavior**
When dragging a column, the hidden ones are not moved, but the one being dragged is.

**Screenshots**
![4V6Rsmbj5N](https://user-images.githubusercontent.com/16325672/153351779-c91780bd-f591-4110-9352-e8db7d276ffa.gif)

**Desktop (please complete the following information):**

- OS: MacOS v12.2
- Browser: Chrome
- Version: 97.0.4692.99 (Official Build) (arm64)

**Additional context**
-

**Comment by Domino987** [comment]
This should be fixed with the lastest release

**Comment by Chee7ah** [comment]
> This should be fixed with the lastest release

Yep, can confirm, latest version works as expected!

**Comment by Domino987** [comment]
Perfect 👍
