### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by vmihalachi** [material-table-core/core#49]
Currently I discovered two accessibility issues of the table using https://accessibilityinsights.io/

- Expand row button doesn't have a name / title. This is visible when you have a detailPanel in the table. https://accessibilityinsights.io/info-examples/web/button-name

  Adding a "title" attribute should fix the issue

- Checkbox filter button doesn't have a label. This filter is visible when you set the column type to 'boolean' and enable filtering. https://accessibilityinsights.io/info-examples/web/label

  Here is how material-ui suggests the fix https://next.material-ui.com/components/checkboxes/#accessibility

![image](https://user-images.githubusercontent.com/956257/104318629-54fdd800-54e8-11eb-9582-b2e2d2120260.png)
![image](https://user-images.githubusercontent.com/956257/104318716-72cb3d00-54e8-11eb-8fcc-73c1f5413009.png)

**Comment by matthewoestreich** [comment]
Thanks for this! I'll look into this today.

**Comment by vmihalachi** [comment]
Thanks @oze4 ! Feel free to change labels as appropriate if you to :)
