### ISSUE TITLE
Disable onRowClick event when a row is being edited

### ISSUE THREAD

**Issue by b3ni** [material-table-core/core#494]
**Describe the bug**

The table is configured with editable (onRowUpdate) and onRowClick.
When in edit mode, the onRowClick event continues to fire.

**To Reproduce**

[Demo](https://codesandbox.io/s/material-table-starter-template-onrowclick-and-onrowupdate-flp1f2?file=/src/index.js)

1. Click on edit row.
2. Click on other row.
3. The onRowClick event fires

**Expected behavior**

The onRowClick event should not fire

**Comment by Domino987** [comment]
Would you mind adding a sandbox for this so I can check it out?

**Comment by b3ni** [comment]
> [Sandbox](https://codesandbox.io/s/material-table-starter-template-onrowclick-and-onrowupdate-flp1f2?file=/src/index.js)

**Comment by Domino987** [comment]
Will be fixed with the next release
