### ISSUE TITLE
Draggable columns are hidden behind grouping bar?

### ISSUE THREAD

**Issue by janwolfram** [material-table-core/core#495]
Hey that's an issue that is maybe easily fixable. When I try to pull a header to the groupbar you can not see it anymore (the text you pull). Check it out on the demos:
https://material-table-core.com/demos/group/basic
That was not the case in the real material-table:
https://material-table.com/#/docs/features/grouping.

Maybe anyone has a good workaround to fix it :)

Thanks

**Comment by Domino987** [comment]
This will be fixed with the next release. Thank you for notice
