### ISSUE TITLE
Cannot read properties of null (reading 'scrollWidth')

### ISSUE THREAD

**Issue by ngoc-d-t** [material-table-core/core#500]
**Describe the bug**
I am getting the following error: Cannot read properties of null (reading 'scrollWidth')
when using jest to test

**To Reproduce**
should checked this.tableContainerDiv?.current?.scrollWidth

**Screenshots**
material-table.js file
![image](https://user-images.githubusercontent.com/44255006/156133856-7da189d0-f844-41ff-8712-3c1f0dd631f4.png)

**Desktop (please complete the following information):**

**Comment by Domino987** [comment]
This works for my setup. Can you reproduce this I'm a sandbox or look why scroll width of a component might be undefined?

**Comment by tondi** [comment]
I think this happened to me as well when `data` prop was incorrect. Not sure if that was the reason tho

**Comment by ngoc-d-t** [comment]
> This works for my setup. Can you reproduce this I'm a sandbox or look why scroll width of a component might be undefined?

My fault, the project's setup is problematic.
