### ISSUE TITLE
How to test filters (Is it possible to add custom classNames / attributes to default filter?)

### ISSUE THREAD

**Issue by tondi** [material-table-core/core#504]
Hello, 
I'm wondering how to add custom selectors to filter components within `MaterialTable` whilst not having to provide a whole new custom implementation of `filterComponent`.

So, this is what I wanted to do:
```
// column def
filterComponent: (props) => (
    <span data-cy="table__some-filter">
      <LookupFilter {...props} />
    </span>
  ),
```
but the LookupFilter is not exported.

Is there any other way of achieving this? 🤔

**Comment by Domino987** [comment]
Thats a good point. Maybe we should set a name, placeholder or id to the inputs with props by default.
Would you mind creating a PR with a prospeod fix so we can merge it?

**Comment by tondi** [comment]
I will try to do that later. Generally I think it feels good to have control over selectors/classes in any library.

In this case I need them for filters only, but I'm 100% sure that users would benefit from some name/placeholder/id being embedded in the UI in other places - buttons, data cells in `tbody` etc. It would be nice to have the ability to distinguish columns. I also think that in a perfect world they should have the ability to configure it themselves

![image](https://user-images.githubusercontent.com/25098043/157862033-907426fc-f461-4943-b3fd-136cc73e334e.png)

As a small-effort solution we may use  the `id` from columnDef. This however is not explicit - someone may expect a dedicated prop to solve that. The advantage is that the id is already stable and suitable for this case (correct me if I'm wrong)

**Comment by Domino987** [comment]
Yes this seems like a good idea. Do you have an idea on how to implement this? I would interested in this as well.

**Comment by tondi** [comment]
Unfortunately I couldn't find any spare time so I could work on this topic yet. However, I still think this feature would be helpful and is indeed needed.
