### ISSUE TITLE
Column filtering breaks after column reordering

### ISSUE THREAD

**Issue by Chee7ah** [material-table-core/core#505]
**Describe the bug**
After reordering columns, the filtering either: works, filters another column, breaks altogether (as the below demo illustrates).

**To Reproduce**

1. Go to [https://material-table-core.com/demos/filter/custom-filter/](https://material-table-core.com/demos/filter/custom-filter/)
2. Drag a column around (e.g. Birth Year)
3. Try filtering

**Expected behavior**
Filtering continues to filter the moved column.

**Screenshots**
![at9EF35svq](https://user-images.githubusercontent.com/16325672/157844576-b430f6fe-61ae-4991-86a8-19b43ae73028.gif)

**Desktop (please complete the following information):**

- OS: MacOS 12.2.1
- Browser: Chrome
- Version: 98.0.4758.109

**Additional context**
When filtering [we pass the `columnId` to the filter function](https://github.com/material-table-core/core/blob/master/src/components/MTableFilterRow/DefaultFilter.js#L24).
This eventually ends up in the [dataManager's `changeFilterValue` function](https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L220), which uses the `columnId` as an index.
This is where the mismatch happens. The `columnId` is not necessarily the same as the column index at this point and it ends up trying to filter a different column.

**Comment by Domino987** [comment]
Ah nice catch, Would you mind creating a PR with a proposed fix to use the id for all caes instead of the index?

**Comment by Domino987** [comment]
Will be fixed with next release
