### ISSUE TITLE
Row index option

### ISSUE THREAD

**Issue by cococov** [material-table-core/core#507]
A boolean option to render a first column with the row index would be very usefull or at least return the row index in the RowData object in render function of a column (to build it myself).

The desired behavior is this:

![image](https://user-images.githubusercontent.com/19384973/158035415-e8408987-f4cd-427d-a36e-67ee34250fb5.png)

Despite the sort criteria, always show the renderd row index.

Thank you for the efford in this project ♥.

**Comment by Domino987** [comment]
Hi, could you not just add a column and render the id for example. Because we are not tracking the index currently.
https://codesandbox.io/s/material-table-starter-template-forked-q85qi?file=/src/index.js or https://codesandbox.io/s/material-table-starter-template-forked-68c5qb

**Comment by cococov** [comment]
But in that way when the rows order change, the ID index column gonna change too. Anyway, I gonna try to build a work around, ordering the data object before and adding an index based on the order. Is not the desired behavior, but is close. 

Thanks for the answer, if I have some time later, I'll going to make a PR with my Feature request.

**Comment by Domino987** [comment]
But this would also be the case if we do it at the level of the table or am I missing something?

**Comment by cococov** [comment]
The index I've been refering is the rendered index. 

Example:

(Base ordered by id)

| index | id |  letter |
| --- | --- | --- |
| 1 | 2 | J |
| 2 | 5 | B |
| 3 | 8 | H |
| 4 | 10 | E |

(now ordered by letter)

| index | id |  letter |
| --- | --- | --- |
| 1 | 5 | B |
| 2 | 10 | E |
| 3 | 8 | H |
| 4 | 2 | J |

As you can see, an inmutable index relative to the row rendered.

**Comment by Domino987** [comment]
I just added the index to the tableData, so you can add it yourself now.

**Comment by cococov** [comment]
Thanks !!!
