### ISSUE TITLE
Numeric column header aligns to left instead of right since 4.3.17

### ISSUE THREAD

**Issue by buugaj** [material-table-core/core#508]
**Demo**
4.3.16
https://codesandbox.io/s/numeric-align-4-3-16-njfb70
4.3.36
https://codesandbox.io/s/numeric-align-4-3-36-z6yhjh
v5
https://codesandbox.io/s/material-table-numeric-align-muiv5-ku9kf5

Numeric column headers doesn't align properly since 4.3.17. This might be caused by the https://github.com/material-table-core/core/pull/444.

**Describe the bug**
Numeric column headers doesn't align to right.

**To Reproduce**

1. Go to https://codesandbox.io/s/numeric-align-4-16-njfb70
2. Observe id column alignment
3. Go to https://codesandbox.io/s/numeric-align-4-3-36-z6yhjh
4. Observe id column alignment doesn't reflect data alignment

**Expected behavior**
Column header alignment follows content alignment.

**Screenshots**

**4.3.16**
![image](https://user-images.githubusercontent.com/9086221/158179082-9ee118f2-6820-4af2-8b89-9fafc9c6f058.png)

**4.3.36**
![image](https://user-images.githubusercontent.com/9086221/158178530-238059af-cab3-49c8-80ce-278eca8b2381.png)

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version:  99.0.4844.51

**Comment by Apoerin** [comment]
@buugaj I have the same issue as you have here https://codesandbox.io/s/material-table-numeric-align-muiv5-ku9kf5
but I don't use `type: 'numeric`,
still on column with icon buttons column header doesn't aligning with rows

I'm using `"@material-table/core": "^0.2.27"` with MUI 5

**Comment by Domino987** [comment]
seems that the drag and drop wrapper interferes with the alignment.
I might be able to take a look this week, but PRs or hints are always appreciated.

**Comment by Domino987** [comment]
This should be fixed with the latest release

**Comment by GabrielMLV** [comment]
Add **draggable: false** works for me. 
` options={{
     draggable: false
 }}`
 
 Version: "@material-table/core": "4.3.44"
