### ISSUE TITLE
Table tree/sorting/... state is lost every time a Dialog is open from a clickable cell

### ISSUE THREAD

**Issue by koutto** [material-table-core/core#51]
Hello all,
Thanks for keeping this project alive !
I am using latest version of @material-table/core.
I have a table with custom rendering in a column, that displays a clickable icon. Every time it is clicked, a state is changed to open a Dialog.
However, everytime it is done, the state of the table is lost, i.e. if any column sortering has been set up, it is lost. Similarly, I am also using tree data, and if some rows have been expanded, everything is collapsed like in initial state.

Do you have any idea of how to avoid this behaviour and keep the current table state ?

**Comment by matthewoestreich** [comment]
Hello! Hopefully this will be fixed today. There is currently another issue open #48 where we pinpointed the root cause. 

We will be putting all updates on #48 so I'm going to close this one out. 

Thanks for bringing this to our attention! We apologize for the inconvenience.

**Comment by matthewoestreich** [comment]
@Domino987 another issue in regards to the table losing state. Looks like it's related to #48

**Comment by Domino987** [comment]
@oze4 Probably yes. This might cause it. The change was introduced to respond to changes to the default prop changes, like initial page etc. If we remove this, these changes of the prop during the lifecycle of the table will be ignored. Maybe we can think of a way to get around it. To both respond to the changes but not lose State

**Comment by matthewoestreich** [comment]
Sounds good to me.  In that case I will reopen this issue.

**Comment by jok3r-framework** [comment]
Ok thanks a lot for your awesome work for keeping this project up-to-date.
Cheers guys

**Comment by matthewoestreich** [comment]
@Domino987 so this was introduced in case someone wants to start on page 2 (or 5 or 103 or whatever) vs page 1? I'm not sure I follow entirely.

**Comment by matthewoestreich** [comment]
All updates will be on https://github.com/material-table-core/core/issues/59

Closing.
