### ISSUE TITLE
Absolutely positioned column over other columns

### ISSUE THREAD

**Issue by josue-uitzil-by** [material-table-core/core#510]
Hi devs, I was wondering if it possible to achieve the behavior shown in the following sandbox using a recent version of material table:
[https://codesandbox.io/s/material-table-starter-template-forked-di81ti?file=/src/index.js](https://codesandbox.io/s/material-table-starter-template-forked-di81ti?file=/src/index.js)

In the sandbox we have a table in which the last column has a fixed width and an absolute position, this way we can have content displayed over other columns on hover. This works for material-table/core v4.3.16 or lower.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/87137177/158686555-ff43a386-4f34-4aa3-9a1d-aa522a1371c6.png">

This approach no longer works in newer versions of the library, since the width of the absolutely positioned column is considered when calculating the width of the other columns, making the table to have an empty space. It can be tested on the codesandbox just by changing the material-table/core version.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/87137177/158687548-eb7bb52d-399f-4469-8563-f02c101e02d0.png">

Do you know if there is alternative way of achieving this? Or maybe a way to exclude a column for the width calculation?

Thank you for the help and your great work on the library

**Comment by josue-uitzil-by** [comment]
It seems that setting tableData in the column definition works for recent versions of the library, but it might be problematic since it messes up with the internal implementation of the table and is not included in the Column interface: https://codesandbox.io/s/material-table-starter-template-forked-llrkqo?file=/src/index.js

```
{
    title: "",
    field: "absolute",
    width: 0,
    tableData: { width: "200px" },
    cellStyle: {
      position: "absolute",
      right: 0,
      opacity: 0,
      textAlign: "right"
    },
    headerStyle: {
      position: "absolute",
      right: 0,
      opacity: 0
    }
  }
```

**Comment by Domino987** [comment]
Hmh did you try to override the tablerow component?

**Comment by josue-uitzil-by** [comment]
I think that overriding the row could also bring some problems. If we override the row with a completely custom component, then we would either lose some functionality or have to make a custom implementation for it. Also doing something like this would print some warnings in the console (td cannot be a direct descendant of tbody):
```javascript
components={{
        Row: (props) => (
          <>
            <MTableBodyRow {...props} />
            <MTableCell
              columnDef={absoluteColumn}
              className="absolute-cell"
            >
              Absolute position
            </MTableCell>
          </>
        )
      }}
```

I did some research on what caused the absolute positioning to stop working in version 4.3.17 and I think that it is related to commenting the following lines on data-manager https://github.com/material-table-core/core/pull/444
<img width="521" alt="image" src="https://user-images.githubusercontent.com/87137177/159585767-0c1111ba-38e2-445c-8038-8af81e40b29a.png">

I tested with those lines uncommented using a local build and the width calculation works correctly with absolute columns. Maybe a new property could be added in the column definition to replace the commented conditions and exclude columns from the width calculation?

**Comment by Domino987** [comment]
@jet11x would you mind taking a look here why those changes were made and if this could be fixed?

**Comment by jet11x** [comment]
Will do

**Comment by jet11x** [comment]
tableData had to be ignored on initial render as the field is never present then - agree with above comment not to try setting it as it's really internal MaterlalTable state that which could move out of props in the future.

Thanks for the codesandbox example - made it much easier to think about this.

A new column property is one way forward - as you say that will be cause column width to be ignored from the calculation of table width.  That may not play well with other options on column width options - I'll have to experiment.  Other possibility would be event for cell or row focus.  Or you could use column.render and then use focus event to change the text.

**Comment by Domino987** [comment]
This would work as well @josue-uitzil-by :
https://codesandbox.io/s/material-table-starter-template-forked-c47txh?file=/src/index.js

**Comment by josue-uitzil-by** [comment]
Hi @Domino987, sadly that approach adds a new column with normal positioning to the table instead of having it absolutely positioned over the last column.

I want to share more details about the use case I have for the absolute positioning. I have a table which displays a Chip (or any other component) on hover to give additional information about the row; something similar to this:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/87137177/161121379-226d468e-1300-41a8-a33f-565a8a3f3cc7.png">



@jet11x I have been thinking on you suggestion of changing the rendered content of the cell, but I think that there could be some problems. It could be possible to have absolutely positioned content wider than the content of the last column, so maybe when the content of the cell changes, the columns would look jumpy.

Another consideration is accessibility; having an absolute position and opacity 0 is just CSS and the screen readers are able to read the last column fine. If we dynamically change the content rendered, then screen readers would probably not be able to read all the content.

**Comment by Domino987** [comment]
Well the sandbox you added would add another column as well. 
If you just want to add a absolute Element to the row, the overriding of the rows would be best to render the addition to the rows. But this totally depends on your specific use case.

**Comment by Domino987** [comment]
@josue-uitzil-by check out this: https://codesandbox.io/s/material-table-starter-template-forked-moiw4n?file=/src/index.js

**Comment by jet11x** [comment]
Like it @Domino987.  That's a lot cleaner than adding a new prop to stop a column from being including in the width calculation.

**Comment by josue-uitzil-by** [comment]
Looks nice @Domino987, I think that it could also work and seems resilient to future changes in the width calculations. One possible drawback is that it logs an error to the console (div cannot be a direct child of tbody), which also affects screen readers, but I think it's a good enough solution right now. 

I understand that this is a very specific use case, so I'll close this question. If you feel like continuing the conversation, feel free to reopen it.
Thanks for all the help @Domino987 and @jet11x! ❤️
