### ISSUE TITLE
MUI v5.4.4 Introduces changes that breaks various dark mode styling when using useTheme

### ISSUE THREAD

**Issue by ShotSkydiver** [material-table-core/core#511]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
Can't reproduce in sandbox, needs browser window dark mode

- #### Please try to be as detailed as possible

**Describe the bug**
Since [MUI 5.4.4](https://github.com/mui/material-ui/releases/tag/v5.4.4) was released, I noticed that some of my custom-set dark mode palette colors are no longer used for certain elements in material-table. 

- I've got custom SvgIcons that I pass in to override the default table icons (using the icons prop), and after MUI 5.4.4 the color of the ViewColumn and Export icons in dark mode are incorrectly falling back to the default MUI light mode palette color. I'm guessing 5.4.4 changed the way the theme hook gets passed in or accessed. (possibly forwardRef changes)
- Also, when the isLoading prop is set on the Table, the loading overlay now exhibits the same issue of using default light theme color palette. The backgroundColor is set here: https://github.com/material-table-core/core/blob/9fe2890d9ea0f33c354ff3be97714b17b6aa7fc8/src/components/Overlay/OverlayLoading.js#L15 and in dark mode, the background color is displayed as `#fff`, which is the light mode palette color.
- That's all I noticed so far; I ended up fixing these issues in my code temporarily by setting a color prop value on my SvgIcons and completely overriding the OverlayLoading component. 

**To Reproduce**

- Install MUI 5.4.4 or above
- Set the browser window to Dark mode
- incorrect colors will be seen for table toolbar icons and loading overlay

**Expected behavior**
Dark mode colors should use the correct dark version of the theme palette.

**Screenshots**

<img width="1799" alt="Screen Shot 2022-03-16 at 4 18 06 PM" src="https://user-images.githubusercontent.com/2718920/158707125-835aa485-1fc2-4fd8-ac49-8d02ea91f52b.png">
<img width="1361" alt="Screen Shot 2022-03-16 at 4 17 23 PM" src="https://user-images.githubusercontent.com/2718920/158707141-c3c0cc11-db82-4b1a-80ab-240d34f0da4b.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Safari
- Version: 15.4

**Smartphone (please complete the following information):**

N/A

**Additional context**
N/A

**Comment by Domino987** [comment]
It works for me. If you cannot reproduce it in a sandbox, this might be difficult.

**Comment by ShotSkydiver** [comment]
The only reason I can't easily reproduce it in a sandbox is because the in-sandbox browser doesn't respect the system's dark mode, but it might be possible to use the dev tools to force it, I'll try and get it working in a sandbox. It might be a specific issue with a combination of having a custom dark mode theme and a custom theme provider?

**Comment by Domino987** [comment]
Probably, especially if it changes with the mui version. Might be a problem on their end. But if you have a sandbox, ill check it out.

**Comment by ClassicDarkChocolate** [comment]
I had this issue as well. But after I removed yarn.lock and reinstalled all dependencies, the problem solves.

**Comment by RELNO** [comment]
Similar issue. Tried @ClassicDarkChocolate solution but it didn't work.
My app uses 
```
 "@material-table/core": "^5.0.4",
    "@mui/material": "^5.8.6",
```
and when I inject the theme:

```
import { createTheme } from "@mui/material/styles";
const theme = createTheme({
  palette: {
    mode: "dark",
  },
});
export default theme;
```
into: 
```
const App = () => {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Main />
    </ThemeProvider>
  );
};
```
the table renders itself and the rest of that page in bright theme colors. 
When checking the source:
```
.MuiPaper-root {
    color: rgba(0, 0, 0, 0.87);
    transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;
    background-color: #fff;
}
```
is the element that overrides the dark theme props, setting that page to bright theme.

**Comment by Domino987** [comment]
Because you are mixing Muir v4 with mui V5. Für mui v5, use the next branch.

**Comment by RELNO** [comment]
@Domino987 thank you. Is there a build for `next` branch already I can use?

**Comment by Domino987** [comment]
No not yet because we still have a few kinks to iron out. Maybe in 2 weeks as I am on vacation right now

**Comment by RELNO** [comment]
> as I am on vacation right now

You're doing the right thing ;) 
Thanks, looking forward to it.
