### ISSUE TITLE
Feature request: add sortDirection to customSort function

### ISSUE THREAD

**Issue by JeomJeom** [material-table-core/core#512]
**Is your feature request related to a problem? Please describe.**
Request for a `sortDirection` param in the customSort function. 
I need it to achieve an outcome where some designated records are always set to be on the top. 

**Describe the solution you'd like**
 `customSort(a, b, ..., sortDirection)`

**Describe alternatives you've considered**
The recommendation provided in https://github.com/mbrn/material-table/issues/3054 by @tian-lan-landing . 
```
  customSort?: (
    data1: RowData,
    data2: RowData,
-   type: "row" | "group"
+   type: "row" | "group", 
+   sortDirection?: "desc",
  ) => number;
```
It would be the best if the sortDirection is "asc" | "desc". 

And he's created an example. [here](https://github.com/mbrn/material-table/blob/b7474ca0f5497f04ff3a3d50e709d86de7c639b0/types/index.d.ts#L159).

Or Perhaps, anyone knows alternative ways to make certain records always on the top when the columns is clicked to sort.

**Comment by Domino987** [comment]
Looks like an easy fix. Will do.

**Comment by Domino987** [comment]
I added the commit, it will be in the next release.
