### ISSUE TITLE
How can I add loading mask when click the onBulkUpdate button.

### ISSUE THREAD

**Issue by kirin-yuen** [material-table-core/core#513]
In my project, I need to overwrite the components props `Action` for get into onBulkUpdate mode, so I want to add a loading status during click the Action button, but if there are too many records and to many columns (validation, cellStyle, editComponent need to gothrought), that get into onBulkUpdate mode will be very slowly (likely it is break down)

So, is there a function that will execute after all the validation, cellStyle, editComponent and so on over? Or other solution for many records and column into onBulkUpdate mode.

**Comment by Domino987** [comment]
Could you add a sandbox for this? Many records still a problem that we are working on. But for this we need a deep rewrite on how the props are passed and memorization. As far as I know the only thing that could be executed after render would be the useEffect, maybe with that somehow

**Comment by abhishek0502** [comment]
We have the same use case, can this be prioritized. Thanks

**Comment by Domino987** [comment]
Well as requests, a sandbox is needed or we can't start even looking into it.
