### ISSUE TITLE
How to write custom select/checkmark logic for material-table, to include selected rows inside of detail panel nested material-table

### ISSUE THREAD

**Issue by Diae-Louali** [material-table-core/core#515]
I have a [material-table][1] component where I am rendering a nested materiel-table in the detail panel of each row. I would like to know if there is a way to include detail panel material-table rows in the functions offered by the package. I am mainly interested in the [selection][2] feature for now, but will likely need the same support for other functions like filtering, search, etc...

Now I know that [Tree Data][3] allows this since all rows are part of the same table. But I need to be able to do it with using the Detail Panel.

NB: For more clarity, [here is a code sandbox][4] I found with the nested table functionality.

So how would one go about adding their custom select function to a material-table, such as to include selected rows inside nested material-tables ?

  [1]: https://material-table.com/#/
  [2]: https://material-table.com/#/docs/features/selection
  [3]: https://material-table.com/#/docs/features/tree-data
  [4]: https://codesandbox.io/s/restaurant-menu-as-material-table-with-nested-material-table-detail-panel-osihz?file=/src/App.js

**Comment by Domino987** [comment]
Can you describe what you mean with custom select function. What is it you want to achieve.

**Comment by Diae-Louali** [comment]
> Can you describe what you mean with custom select function. What is it you want to achieve.

Imagine a table with nested tables in the detail panels. I need to have a way to select all rows including those in the nested tables.  I should also be able to trigger the selection of all the rows in a nested table by selecting its parent row.

**Comment by matthewoestreich** [comment]
It sounds like you are looking for a way to control row checked state outside of the table - meaning, not using the provided check box, `options.selection`.

I went ahead and added a demo to our website that shows how you can control row checked state from "outside" of the table. You should be able to follow the same logic to accomplish this.

https://material-table-core.com/demos/selection/outside-of-table

**Comment by Diae-Louali** [comment]
Thanks, that seems exactly like what I needed.
