### ISSUE TITLE
When a column is grouped how to expand the rows by default?

### ISSUE THREAD

**Issue by sabbirahmed07** [material-table-core/core#516]
Hello I am taking a default column to group the rows in a table. So, when every time expanding the rows of a particular group is quite tedious. So, is there any way that by default all the rows will be expanded of that group?

**Comment by matthewoestreich** [comment]
Would you mind creating a sandbox that details your issue? You can also check out the demos found here. https://material-table-core.com/demos

**Comment by sabbirahmed07** [comment]
Here is my sandbox code: 
https://codesandbox.io/s/goofy-herschel-u9iq7p?file=/src/App.js

**Comment by Domino987** [comment]
Hi, you need to hack into the internals for that using the tableRef and calling `onGroupExpandChanged` after the initial render:
`ref.current.onGroupExpandChanged([0])` with 0 being the index of the group.
https://codesandbox.io/s/upbeat-lucy-vq1y9g?file=/src/App.js

**Comment by sabbirsristy7494** [comment]
@Domino987 Thank You Very Much
