### ISSUE TITLE
Memory Leak [existing issue in mbrn/material-table]

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#52]
## Resources

https://github.com/mbrn/material-table/issues/2727

https://github.com/mbrn/material-table/issues/2733

## Description

Memory leak when updating table data/editing cell.

## Possible Solution

Apparently, this bug was introduced in all versions *greater than **or** equal to*  `mbrn/material-table` **v1.68.2**, as  `mbrn/material-table` **v1.68.1** [does not have this issue](https://github.com/mbrn/material-table/issues/2727#issuecomment-758271621).

**Comment by peacechen** [comment]
This was fixed in #5, which was from mbrn#2689

I recommend tabling this unless someone has a demo reproducing this type of issue.  I've not seen it since the fix was merged.

**Comment by matthewoestreich** [comment]
Yea you're correct - it is not an issue in this repo. https://github.com/mbrn/material-table/issues/2727#issuecomment-759078523

I saw it over at mbrn and it freaked me out haha.  I haven't tested anything or looked into it yet (and I'm glad I didn't).

Thank you very much!
