### ISSUE TITLE
How do you validate cell value against the rest of the values from the same column?

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#520]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

So, I have MT with just one editable column. It is of numeric type. When user enters a value, I have a validation code which checks for a valid number i.e. > 0 and also it checks against a range i.e. value must be within that range else it rejects it. All of this works fine so far. Now, I want to ensure that user doesn't enter a duplicate value so, I need a way to check the user input against ALL values from that column. How do I do that? I also need to check the value against the DB by making an API call to ensure that it's not a duplicate value.

**Comment by Domino987** [comment]
Could you add your current setup in a sandbox? There are several ways but it depends. You could use the data prop there as well, or the tableRef. It would also be possible to add a parameter to include all data if needed. But we can check that out afterwards.

**Comment by matthewoestreich** [comment]
Hi @DewangS - perhaps this demo may help? https://material-table-core.com/demos/validation/basic

**Comment by DewangS** [comment]
First of thanks tons for a super quick response @Domino987  and @oze4 . @oze4 , I do have a current validation on this ONLY editable column and it works fine i.e. it checks if the value is a valid number and within a certain range. All good so far though the new requirement is to validate the value against the rest of the values in that column to ensure that user don't accidentally enter any duplicates. The second requirement is to validate the value (as user enters) against the values in the database by calling an API to ensure that the value DOESN'T already exists in the DB.. i.e. once again not a duplicate value. 

So far I've created an API to validate the value against the DB. The issue is, I make API call using AXIOS and APIs are promises i.e. you can't get an instant response back. so, when I tried the below code to use async\await, it doesn't show 'duplicate' error message and accepts the user input. My question is, does MT allows async validation calls? 

```
const validatePermitNumber =  (
  permitRanges,
  permitYear,
  permitTypeID,
  permitNumber
) => {
  let message = "";
  let isValid = false;
  let retVal = {};
 

  for (let index = 0; index < permitRanges.length; index++) {
    const record = permitRanges[index];
    console.log("+++ permitYear : " + permitYear);
    if (
      record["permitTypeID"] === permitTypeID &&
      record["permitYear"] === permitYear
    ) {
      if (permitNumber >= record["start"] && permitNumber <= record["end"]) {
        isValid = true;
        break;
      } else {
        isValid = false;
        message =
          "Valid range for this permit type is " +
          record.start +
          " to " +
          record.end +
          ".";
          break;
      }
    }
  }
  if(!isValid)
  return { isValid: isValid, helperText: message };
  
  console.log("+++ Calling API");

  checkDuplicate(permitNumber, permitTypeID).then((result) => {
    console.log("+++ result ", result);
    isValid = result;
    **if (!isValid) {
      alert("+++ DUPLICATE Permit Number");
      return { isValid: isValid, helperText: "Duplicate Permit Number." };
    }**
   
  });
  
  console.log("+++ AFTER Calling API");

  return retVal;
```

checkDuplicate() function is as per below in the above call ...

```
function checkDuplicate(permitNumber, permitTypeID) {
  return new Promise(async (resolve, reject) => {
    API.get(
      "/api/permits/Permit/validatePermitNumber/" +
        permitNumber +
        "/" +
        permitTypeID
    )
      .then((response) => {
        //console.log('+++ Permit Number validation response : ', response.data)
        if (response.data) {
          let result = response.data;
          console.log("+++ Permit Number validation response : ", result);
          resolve(result.isValid);
        }
      })
      .catch((error) => {
        console.log("*** ERROR RESPONSE validating Permit Number : ", error);
        resolve(false);
      });
  });
}
```

**Comment by Domino987** [comment]
Again, putting this in a sandbox is a requirement so that we can actually look at the whole code instead of snippets.
Only the whole setup would let use efficiently help so, so please provide one. 

Async validation is currently not supported.

**Comment by DewangS** [comment]
@Domino987 will add it to the sandbox and let you know

**Comment by DewangS** [comment]
here you go @Domino987  

[sandbox code](https://codesandbox.io/s/material-table-starter-template-forked-3weg9o?file=/src/index.js)

**Comment by Domino987** [comment]
2 things, you need to use the current saved data, not the initial data. and also exclude the current row in the count:
https://codesandbox.io/s/material-table-starter-template-forked-3weg9o?file=/src/index.js

**Comment by DewangS** [comment]
@Domino987 doesn't seem to work. It displays Duplicate Id where there are no duplicates and also accepts duplicates without showing error. It also won't work with the bulk update. Instead of 100 values in that table please try with 5 values.

**Comment by Domino987** [comment]
I guess it did not save. Here: https://codesandbox.io/s/material-table-starter-template-forked-4rnuvz?file=/src/index.js

**Comment by DewangS** [comment]
Thanks @Domino987 while your solution works, mine throws an error when I reference the .tableData element of the rawData. I looked at the package.json from your sample and it looks like it uses "@material-table/core": "0.2.17" version 0.2.17 whereas I use "@material-table/core": "^2.3.37",

is tableData something specific to the older version 0.2.17 which the starter template uses?

**Comment by DewangS** [comment]
@Domino987 managed to get it working for both i.e. individual row update and bulk update including calling an API
