### ISSUE TITLE
Custom Select component value using editComponent

### ISSUE THREAD

**Issue by raulrobi2018** [material-table-core/core#521]
**Hi people!** 

I have an editable table with MUI Select components rendered by the `editComponent `attribute. Everything works well until I save the data row. Instead of displaying the text of the selected value, it shows the value. After clicking on the Edit button, it shows the Select correctly, with the correct text. According to my investigation, **rowData** stores the value of the Select component and not the text. I think this behavior it's ok, but how can get the same behavior as when we use the lookup attribute?

This issue is made me feel crazy!! I also tried to get the **rowData** when clicking on the Edit button but was impossible.

Please, I really appreciate any help!!
Thanks in advance!

**Before save**
![imagen](https://user-images.githubusercontent.com/45154459/160925441-edd50a04-37e3-4abd-9b93-35bd1a62ca35.png)

**After save**
![imagen](https://user-images.githubusercontent.com/45154459/160925525-7687f9de-705d-4a32-8e17-90aa5dc54082.png)

**This is one of the Select fields:**
```
const BANCOS = [
  { value: "", label: "" },
  { value: "1", label: "BROU" },
  { value: "2", label: "BCU" },
];
.
.
.
{
      title: "Banco",
      ...cellStyles(5),
      field: "codBanco",
      editComponent: ({ value, onChange, error, helperText }) => (
        <TextField
          select
          value={value === undefined ? "" : value}
          onChange={(e) => onChange(e.target.value)}
          style={{ width: 80 }}
          error={error}
          helperText={helperText}
        >
          {BANCOS.map((banco) => (
            <MenuItem key={banco.value} value={banco.value}>
              {banco.label}
            </MenuItem>
          ))}
        </TextField>
      ),
      validate: (rowData) =>
        rowData.codBanco === "" || rowData.codBanco === undefined ? "" : true,
    },
```

And this is the table:

```
        <MaterialTable
          title={TOTAL}
          data={data}
          columns={tableColumns}
          options={tableOptions}
          localization={{
            ...localization,
            toolbar: {
              ...localization.toolbar,
            },
            header: {
              actions: "",
            },
          }}
          editable={{
            onRowAddCancelled: (rowData) => console.log("Row adding cancelled"),
            onRowUpdateCancelled: (rowData) =>
              console.log("Row editing cancelled"),
            onRowAdd: (newData) => {
              return new Promise((resolve, reject) => {
                /*                 httpClient
                  .post(
                    "configurarEvaluacionDesempenio?accion=agregarModulo",
                    newData
                  )
                  .then((data) => { */

                if (!validarTipoCheque(newData.tipo, archivos)) {
                  console.log("no valid");
                  setMessageOpen(true);
                  reject();
                } else {
                  console.log("newData", { ...newData, archivos });
                  setData([...data, { ...newData, archivos }]);
                  resolve();
                }
              });
              //});
            },
            onRowUpdate: (newData, oldData) => {
              console.log("new Data", newData);
              console.log("old Data", oldData);
              return new Promise((resolve, reject) => {
                setTimeout(() => {
                  const dataUpdate = [...data];
                  // In dataUpdate, find target
                  const target = dataUpdate.find(
                    (el) => el.id === oldData.tableData.id
                  );
                  const index = dataUpdate.indexOf(target);
                  dataUpdate[index] = newData;
                  setData([...dataUpdate]);
                  resolve();
                }, 1000);
              });
            },
            onRowDelete: (oldData) => {
              return new Promise((resolve, reject) => {
                setTimeout(() => {
                  const dataDelete = [...data];
                  const target = dataDelete.find(
                    (el) => el.id === oldData.tableData.id
                  );
                  const index = dataDelete.indexOf(target);
                  dataDelete.splice(index, 1);
                  setData([...dataDelete]);
                  resolve();
                }, 1000);
              });
            },
          }}
        />

```

**Comment by matthewoestreich** [comment]
Hello! Would you mind throwing that into a sandbox so we can take a look?

**Comment by raulrobi2018** [comment]
Hello @oze4, thank you for your reply.

Here is the example in CodeSandbox. I had to reduce a lot of code but the behavior of Select fields is the same in this example.

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-forked-zhzl9y?file=/src/index.js)

**Comment by matthewoestreich** [comment]
In your `useTable` file/hook, when rendering the `MenuItem` component you can just pass the `.label` into the `value` prop instead of passing the `.value` in.

I changed it to the following and it worked:

```js
// Pass in `.label` to the `value={..}` prop
<MenuItem key={banco.value} value={banco.label}> 
    {banco.label}
</MenuItem>
```
<img width="695" alt="mtc_issue_521" src="https://user-images.githubusercontent.com/21092343/161125605-e8d59135-5208-4c70-acba-6277074c38cf.png">

**Comment by raulrobi2018** [comment]
Thank you! Yes, I know that. But the problem is that every option value on selects is the key to the database. For example:
**Id      Desc**
1      BROU
2      BCU

so I need the server to receive the Id and not the description. rowData stores the Id, which is ok, but also displays the id in the table after saving the row instead of the description.

**Comment by raulrobi2018** [comment]
I don't know how the `lookup `attribute works internally, but it has a value and a label, after saving the data it displays the label and not the value.

**Comment by matthewoestreich** [comment]
I guess I still don't understand the issue.

I thought the issue was that after adding a new row, the displayed text in the row was showing the number (ID) and not the text. I'm not sure where a server comes in or the lookup attribute as your demo is not using them.

Is this the behavior you're after? https://codesandbox.io/s/material-table-starter-template-forked-jluhtg?file=/src/index.js

### Before Save

<img width="783" alt="before_save" src="https://user-images.githubusercontent.com/21092343/161139010-3dad4b9a-f09f-4c60-b226-9ca76f395115.png">

### After Save

<img width="783" alt="after_save" src="https://user-images.githubusercontent.com/21092343/161139048-86126a3d-eb7a-4afb-bac0-ae8ddb2ed61f.png">

**Comment by raulrobi2018** [comment]
Thank you! I really appreciate your help!

Now, I added a new field that uses lookup. If you take a look at the console.log, rowData stores the id of the country field and displays the text in the cell, that is the behavior I need for my custom select.

The server comes when it has to save the data in the database. The value of the options selected corresponds to an ID in tables in the database and it is the foreign key for the data I am stored in another table. It's for performance. Imagine if I have to display 100 options, I will not write them in a JS file, I will get them from the database and then load them in a select with their corresponding id.

I hope you can understand. Again, thank you very much for your help!!

https://codesandbox.io/s/material-table-starter-template-forked-kz7f8f?file=/src/useTable.js

**Comment by matthewoestreich** [comment]
Ok cool that makes sense. You would have to keep track of that logic yourself, most likely within the `onChange` handler in the `TextField`. 

Another way would be to use the lookup column prop and modifying the data before passing it in. https://codesandbox.io/s/material-table-starter-template-forked-t898yo?file=/src/index.js (I am only referring to the `lookup` field on the bancos column - the demo doesn't actually work)

The column definition would look something like this:

```js
{
    title: "Banco",
    ...cellStyles(5),
    field: "codBanco",
    lookup: BANCOS.reduce((acc, banco) => {
      return {
        ...acc,
        [banco.value]: banco.label
      };
    }, {}),
    /*
    editComponent: ({ value, onChange, error, helperText }) => {
      console.log({ value, onChange, error, helperText });
      return (
        <TextField
          select
          value={value === undefined ? "" : value}
          onChange={(e) => {
            console.log({value})
            onChange(e.target)
          }}
          style={{ width: 80 }}
          error={error}
          helperText={helperText}
        >
          {BANCOS.map((banco) => (
            <MenuItem key={banco.value} value={banco.label}>
              {banco.label}
            </MenuItem>
          ))}
        </TextField>
      );
    },
    */
    validate: (rowData) =>
      rowData.codBanco === "" || rowData.codBanco === undefined ? "" : true
  }
```

I honestly can't think of a quick/easy way to accomplish that - are you overriding the editComponent to change styling?

**Comment by Domino987** [comment]
> Another` way would be to use the lookup column prop and modifying the data before passing it in.

Is the correct answer here, I think. Since we use the keys for mapping and values for display, the lookup item you pass must be shaped like this as well.
If you look into the ts files: https://github.com/material-table-core/core/blob/master/types/index.d.ts#L227 you can see that it should not be an value label array, but an object, where key is the id and value the display value.

**Comment by raulrobi2018** [comment]
Thank you, guys!!!

The main reason I'm using the `editComponent `is that I'm doing some validation between fields. In the onChange of the select component, I check if the value 5 in the field "Tipo" is selected, then I enable two other fields using a variable state called `tipoSelected`. With this validation, in the "Banco emisor" field I do `editable: tipoSelected !== 5 ? "never" : "onAdd"`.

I don't know if I can do the same with the `lookup`. 
I will try both solutions you suggested to see if I can replicate the same I'm doing with Select component.

I will keep informed and close the issue if everything works well.

**Comment by Domino987** [comment]
@raulrobi2018 Maybe this helps as well: https://medium.com/@domino051/cascading-dropdown-material-table-e9025a424715

**Comment by raulrobi2018** [comment]
Thank you @Domino987 !!

It is not exactly what I need but it solved another problem I had. 
Thank you very much!!

**Comment by raulrobi2018** [comment]
Hi people! Unfortunately, I didn't find a solution to my problem, so I decided to use another approach that is used at the moment in other functions and it is working correctly. I changed the Select component to the Autocomplete. It use objects to display the options. When I try to save it, an error related to "React child" is displayed. Just complete a line and save it.

I have updated the Sandbox example with the autocomplete component in the "Tipo" column.

[Sandbox](https://codesandbox.io/s/material-table-starter-template-forked-vfw1vr?file=/src/useTable.js)

I appreciate any help!

**Comment by Domino987** [comment]
@raulrobi2018 You are trying to display an object because if you console.log your value, its an object. But you need the value.
SO try this:
```
 onChange={(e, {value}) => {
            onRowDataChange({ ...rowData, tipo: value });
          }}
```
Or else tipo is and object and react cannot render an object, once the edit is through and row.tipo is accessed.

**Comment by raulrobi2018** [comment]
Thank you very much @Domino987 . I'll try it!

**Comment by raulrobi2018** [comment]
Hi @Domino987 @oze4 ! Finally solved!! 
The key was to change the `field `attribute of the column definition. I was defining the field attribute of the column "tipo" with `tipo `value, instead of doing that I changed it to `tipo.title`. 

Since I managing the `Autocomplete `with objects and setting the value with the `title `attribute, the field should be referenced with the same attribute `title `as well.

Take a look at the `console.log `to see the object selected in the autocomplete inside the `rowData`.

Here is the sandbox:
[Sandbox](https://codesandbox.io/s/material-table-starter-template-forked-vfw1vr?file=/src/useTable.js)

**Comment by Domino987** [comment]
?
