### ISSUE TITLE
Check and prevent duplicate values

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#522]
Would it be possible to introduce a UNIQUE property for column(s) which can auto check and prevent duplicate values?

**Comment by Domino987** [comment]
It is most likely possible. Would you mind creating a PR to address this?
I am sure could also be achieved using the validation honestly. Would you share a sandbox with your setup?

**Comment by DewangS** [comment]
@Domino987 will do.

**Comment by Domino987** [comment]
Duplicate of #520
