### ISSUE TITLE
Make API calls from custom validation functions

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#523]
# Guidelines

- #### Please include a demo of the issue/behaviour/question you have

Make API calls during the validation event

- #### Please try to be as detailed as possible

Would be good if we can make API calls during the custom validation function execution and wait for the API's response esp. when your validation needs to take place against the persistent DB values

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Is your feature request related to a problem? Please describe.**

Currently in order for API calls to work as a part of the custom validation function, one need to make the call async as API calls are promises. If you mark your custom validation function as async, nothing gets validated. So, it appears that you can't have promises in custom validation routine

**Describe the solution you'd like**

Have an ability to make API calls within custom validation functions.

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Comment by Domino987** [comment]
Yes, promises are currently not supported, but would be an interesting use case. Do you have an idea on how to achieve this?

**Comment by DewangS** [comment]
Hey @Domino987 I managed to get this working though not under the validation rule but under the onRowUpdate and onBulkUpdate events.

**Comment by Domino987** [comment]
Thats works as well. Very good. Ill close this then.
