### ISSUE TITLE
reseting pagination options when trying to override pagination component

### ISSUE THREAD

**Issue by tednaaa** [material-table-core/core#525]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

https://codesandbox.io/s/material-table-starter-template-forked-tonu5m?file=/src/index.js

- #### Please try to be as detailed as possible

default pagination:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/79831859/162636836-35f533d9-b04e-46cd-9061-a1bb36317cc6.png">

overridden pagination:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/79831859/162636999-660d6414-8587-4630-a47f-01aa2bb893bf.png">

as you can see, in 2th screenshot, pagination missing `select` component for showing rowsPerPage, and other options like `paginationType: 'stepped'`, how can i restore that settings in overridden component?

**Comment by Domino987** [comment]
The sandbox is missing your setup, its just the base sandbox. Could you update it?

**Comment by tednaaa** [comment]
https://codesandbox.io/s/material-table-starter-template-forked-7z69be?file=/src/index.js

**Comment by tednaaa** [comment]
@Domino987 updated :)

**Comment by Domino987** [comment]
So the way the pagination was originally was written is quite complicated: https://github.com/material-table-core/core/blob/master/src/material-table.js#L904

Rewriting this would be quite extensive, but if you want to try it, a PR would be welcomed. Or you could try to mimic the written code from the link to adjust it yourself in the override level.

**Comment by Domino987** [comment]
Ah, I just found the problem.
 You are importing the wrong Pagination. For this, you need the base pagination from material ui.
https://codesandbox.io/s/material-table-starter-template-forked-roeiyl?file=/src/index.js
