### ISSUE TITLE
Multi-select field?

### ISSUE THREAD

**Issue by TheSNSCompany** [material-table-core/core#527]
Is there as such thing as a multi-select column?  I have a dataset that returns a column of objects (one-many table relationship) and I'd like it to be editable with a "multi-select" (https://codesandbox.io/s/10xn41w767).  Is this currently possible?

Thanks!

**Comment by Domino987** [comment]
It is but you would need to override it yourself, the edit component and render.
Render like this: https://material-table-core.com/demos/columns/render-image
and editComponent like this in Custom Edit Component Example: https://material-table.com/#/docs/features/editable
