### ISSUE TITLE
Resize column not working if there are hidden columns

### ISSUE THREAD

**Issue by emikira** [material-table-core/core#529]
When hiding some columns, then if you try to resize a column that is on the right from those, the table is not taking in count the hiding ones to make the resize.
Here is a demo where you can see that
https://codesandbox.io/s/material-table-starter-template-forked-m05mdr?file=/src/index.js

**To Reproduce**
1. Hide some columns, e.g. `Word` & `Word 1`
2. Resize column `Word 2`
4. See, table is trying to resize the columns `Word` & `Word 1`:
![image](https://user-images.githubusercontent.com/21212143/163184338-b54e8fa4-8592-4eaa-971d-f32d93580f62.png)

**Comment by Domino987** [comment]
This should be fixed with the next release. Thanks for finding this.

**Comment by emikira** [comment]
Almost there! Thanks for solving it @Domino987
I'm getting this on `v4.3.41` when I tried to resize the column that is on the left than a hidden column
```
TypeError
Cannot read properties of undefined (reading 'tableData')
    at handleMouseDown (https://m05mdr.csb.app/node_modules/
[material-table/core/dist/components/MTableHeader/index.js:99:88]()
    at onMouseDown (https://m05mdr.csb.app/node_modules/
[material-table/core/dist/components/MTableHeader/index.js:276:20]()
HTMLUnknownElement.callCallback
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:149:14]()
Object.invokeGuardedCallbackDev
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:199:16]()
invokeGuardedCallback
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:256:31]()
invokeGuardedCallbackAndCatchFirstError
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:270:25]()
executeDispatch
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:561:3]()
executeDispatchesInOrder
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:583:5]()
executeDispatchesAndRelease
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:680:5]()
executeDispatchesAndReleaseTopLevel
[https://m05mdr.csb.app/node_modules/react-dom/cjs/react-dom.development.js:688:10]()
```

**Comment by Domino987** [comment]
@emikira should work with the latest. But maybe you have another edge case ;)
