### ISSUE TITLE
Add columnDef.tableData to the typescript types

### ISSUE THREAD

**Issue by KippWade** [material-table-core/core#530]
- When utilizing custom components, tableData is not included in the typescript types, so we have to do an ignore to be able to utilize this in the custom component, as we need to use the id & filterValue present in the tableData:

```
	filterComponent: ({ columnDef, onFilterChanged }) => {
		// @ts-ignore
		const td = { ...columnDef.tableData }
		return (
			<TextField
				disabled={isSearchActive}
				InputProps={{
					className: isSearchActive ? classes.input : undefined
				}}
				onChange={(e) => {
					onFilterChanged(td.id, e.target.value)
				}}
				size="small"
				value={td.filterValue || ""}
				variant="outlined"
			/>
		)
	},
```

- We also ran into this issue utilizing rows data for selectedRows
```
		// @ts-ignore
		var data = selectedRows.map(sr => sr.zip);
```

We would like the Typescript types to include these types of data points, so the @ts-ignores aren't needed.

**Comment by Domino987** [comment]
The tabledata is internal and might change between versions, also they are quite extensive.
You could type it yourself with:

    const td : any= { ...columnDef.tableData } // Why do you copy the tabledata here anyway?

You are welcome to try to type it though in a PR

**Comment by KippWade** [comment]
With the custom element for the column filter, we need the id to update the table onFilterChanged.

**Comment by KippWade** [comment]
`const td : any= { ...columnDef.tableData }`

This still throws a typescripting error

`Property 'tableData' does not exist on type 'Column<{ id: any; } & { accountName: any; } & { primaryAddress: any; } & { primaryAddress: any; } & { chainAccountName: any; } & { accountTypes: any; } & { businessStatus: any; }>'.  TS2339`

The table onFilterChanged requires the rowId, the only way we found to provide that, was to use tableData.

We also needed the tableData.filterValue for the custom component...  

If there is another way to provide these values, we would be very interested, we never found any indications in the documentation at material-table.com

**Comment by Domino987** [comment]
> With the custom element for the column filter, we need the id to update the table onFilterChanged.

You should provide an id yourself anyway. Could you not use this?

Ah I see what you mean. Try (coulumDef as any).tableadata

**Comment by KippWade** [comment]
Yes, the (columnDef as any).tableData works.  Thank you very much for that, I hadn't tried that approach before.

We tried to set an id in the column definition, but it appears that the onFilterChanged property doesn't resolve to that in any way.  When I logged the tableData, it still reported the id = 0, instead of the "col1" we attempted.

Boss appears to be moderately happy with this solution.  He'd rather have the 'as any' than have the // @ts-igore.

**Comment by Domino987** [comment]
Good that that works. You just tell ts that this one instance could be anything aka not typed. So its quite local, which is to be preferred.

Oh you meant column id, ok yes that's always the index.

Can I close this, since the problem is resolved. IF you want you can try to type tableData but its prone to change and be used as little as possible.

For your use case it should be fine though.

**Comment by KippWade** [comment]
Yes, close.  Thanks again!
