### ISSUE TITLE
Remote data, initialPage and detailPanel can't open

### ISSUE THREAD

**Issue by Pietro2999** [material-table-core/core#532]
# Remote data, initialPage and detailPanel
With material-table/core@next from npm (0.2.29)

## Description
I'm using remote data to fill my table. All my rows have a detailPanel. 
I have to save the state of my filter and the page I was from when dismounting the table. I'm using redux store for it.

So in order to chose the page when I come back on the table, I use the options initialPage with the number in my store. However when this number is higher than 0. After loading the table, the detailPanel can't open because line 553 in data-manager.js rowData is null.

It never happens if initialPage is not used.

**Comment by Domino987** [comment]
Would you mind putting this into a sandbox for us to check out custom your setup

**Comment by Pietro2999** [comment]
Here is the sandbox: https://codesandbox.io/s/compassionate-architecture-3kicok

**Comment by Domino987** [comment]
Should be fixed with the latest release
