### ISSUE TITLE
How to scroll to newly added row in a table automatically when we click on add row button in React JS

### ISSUE THREAD

**Issue by monkyaro** [material-table-core/core#533]
is m using Material table core to create table in react. I am performing CRUD operations on Table. In a table at a time only six rows are visible.If we want to see more records, need to scroll down and see remaining rows. The problem is when I click on add row button, new row is adding but, the focus is not moving to newly added row(It should scroll down automatically). In first column of table row, created text field. When I add row It should focus that text field.I tried by using focus() method, but it didn't work.Thanks in Advance

**Comment by Domino987** [comment]
Autoscroll ist currently not supported, but you can change the location of the new row to be top. Does that help you ?
