### ISSUE TITLE
Export does not get called

### ISSUE THREAD

**Issue by joeflatt** [material-table-core/core#535]
**Describe the bug**
When upgrading library from 4.3.9 to 4.3.31 export stopped working.  Upgrading to 4.3.41 did not fix the issue.

**To Reproduce**
When user clicks on export icon the export menu pops up but when clicking on a menu item the export function is not called.  The popup menu acts as if it doesn't receive a click at all.  It stays displayed.

**Expected behavior**
I believe the code below will show the bug... when clicking the menu item the console will not log but I would expect it to

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome

**Additional context**
`<MaterialTable 
  // ...
  options={{
    // ...
    exportMenu: [{
      label: 'Export CSV',
      exportFunc: (cols, datas) => console.log('FUNCTION WAS CALLED')
    }]
  }}
/>
`

**Comment by Domino987** [comment]
Could you add a sandbox as requested?
