### ISSUE TITLE
Support React v18

### ISSUE THREAD

**Issue by MLNW** [material-table-core/core#536]
**Is your feature request related to a problem? Please describe.**

I want to use this package with React v18. When I upgrade my dependencies accordingly, `pnpm` shows the following peerDependency issues:

```console
├─┬ @material-table/core
│ ├─┬ react-beautiful-dnd
│ │ ├── ✕ unmet peer react@"^16.8.5 || ^17.0.0": found 18.0.0
│ │ ├── ✕ unmet peer react-dom@"^16.8.5 || ^17.0.0": found 18.0.0
│ │ ├─┬ react-redux
│ │ │ └── ✕ unmet peer react@"^16.8.3 || ^17": found 18.0.0
│ │ └─┬ use-memo-one
│ │   └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.0.0
│ └─┬ @mui/lab
│   └─┬ @mui/x-date-pickers
│     └── ✕ unmet peer react@^17.0.2: found 18.0.0
```

**Describe the solution you'd like**
This package should natively support React v18.

**Describe alternatives you've considered**
Do not upgrade React until its new version is supported.

**Additional context**

Relevant package versions:

```json
"@emotion/react": "^11.9.0",
"@emotion/styled": "^11.8.1",
"@material-table/core": "^0.2.32",
"@mui/icons-material": "^5.6.2",
"@mui/lab": "^5.0.0-alpha.78",
"@mui/material": "^5.6.2",
"react": "^18.0",
"react-dom": "^18.0",
```

**Comment by Domino987** [comment]
Hi, yes we want to support all versions of react in the future, but as the pnmp print already mentions, we have to wait for the other libs to support it.
And since is not the case yet, we have to wait as well. But ill keep this open to support it ASAP

**Comment by MLNW** [comment]
Regarding the `@mui/x-date-pickers`: It seems like the date pickers were moved out of the lab with [Release v5.6.0](https://github.com/mui/material-ui/releases/tag/v5.6.0). Relevant MR: https://github.com/mui/material-ui/pull/31984

Here is the migration guide: https://mui.com/x/react-date-pickers/migration-lab/

**Comment by MLNW** [comment]
Regarding `react-beautiful-dnd`: It seems like the package is no longer maintained as seen in the README and this issue regarding React v18 migration https://github.com/atlassian/react-beautiful-dnd/issues/2388. Maybe we need to move on to https://github.com/react-forked/dnd?

**Comment by MLNW** [comment]
Regarding `react-redux`: The major release v8 about a week ago has introduced React v18 support, see https://github.com/reduxjs/react-redux/releases/tag/v8.0.0.

**Comment by Domino987** [comment]
> ```
> ea
> ```

This is done locally.

**Comment by Domino987** [comment]
> Regarding `react-redux`: The major release v8 about a week ago has introduced React v18 support, see https://github.com/reduxjs/react-redux/releases/tag/v8.0.0.

This is only connected to dnd so we do not need to update it manually.

**Comment by Domino987** [comment]
> Regarding the `@mui/x-date-pickers`: It seems like the date pickers were moved out of the lab with [Release v5.6.0](https://github.com/mui/material-ui/releases/tag/v5.6.0). Relevant MR: [mui/material-ui#31984](https://github.com/mui/material-ui/pull/31984)
> 
> Here is the migration guide: https://mui.com/x/react-date-pickers/migration-lab/

This is done locally.

**Comment by Domino987** [comment]
> Regarding `react-beautiful-dnd`: It seems like the package is no longer maintained as seen in the README and this issue regarding React v18 migration [atlassian/react-beautiful-dnd#2388](https://github.com/atlassian/react-beautiful-dnd/issues/2388). Maybe we need to move on to https://github.com/react-forked/dnd?

I agree, but they do not support 18 yet either.

**Comment by MLNW** [comment]
> > Regarding `react-beautiful-dnd`: It seems like the package is no longer maintained as seen in the README and this issue regarding React v18 migration [atlassian/react-beautiful-dnd#2388](https://github.com/atlassian/react-beautiful-dnd/issues/2388). Maybe we need to move on to https://github.com/react-forked/dnd?
> 
> I agree, but they do not support 18 yet either.

Yes that is correct, here is the relevant MR: https://github.com/react-forked/dnd/issues/293

**Comment by sairam0903** [comment]
Any news or updates on when this is supported for React 18?

**Comment by Domino987** [comment]
The redux fork is not yet updated

**Comment by imnasnainaec** [comment]
> > > Regarding `react-beautiful-dnd`: It seems like the package is no longer maintained as seen in the README and this issue regarding React v18 migration [atlassian/react-beautiful-dnd#2388](https://github.com/atlassian/react-beautiful-dnd/issues/2388). Maybe we need to move on to https://github.com/react-forked/dnd?
> > 
> > I agree, but they do not support 18 yet either.
> 
> Yes that is correct, here is the relevant MR: [react-forked/dnd#293](https://github.com/react-forked/dnd/issues/293)

Here's the hold-up as of April: https://github.com/react-forked/dnd/pull/336

**Comment by mahmoudim** [comment]
I know it doesn't have the same behavior but might be a good idea to migrate to [react-dnd](https://react-dnd.github.io/react-dnd/)

**Comment by Xhale1** [comment]
@imnasnainaec @MLNW I created a new fork of `react-beautiful-dnd` which supports React 18 and react strict mode, [@hello-pangea/dnd](https://github.com/hello-pangea/dnd)

It should be a drop-in replacement. Just replace every mention of `react-beautiful-dnd` with `@hello-pangea/dnd`

**Comment by Domino987** [comment]
I'll try that this week. That's great thank you. I might come back to you if you want to help make the table v18 ready too 😅 or at least show some pitfalls to avoid

**Comment by avenger90** [comment]
Hi @Domino987 , I am using `mui` v5, does ` material-table-core ` v0.2.35 supports reacts 18 or are we still waiting on dependencies to upgrade?

**Comment by Domino987** [comment]
Yes, we did a great leap with the dnd update, but we are still missing out on an few.

**Comment by Domino987** [comment]
Can you guys try the newest next version 0.2.40 for react 18?

**Comment by avenger90** [comment]
yes, we will try with react 18 and let you know.

**Comment by sucy6330133** [comment]
I have tried the latest next version 0.2.42, the deepmerge-ts issue is still there. Seems more like a webpack issue. Any plan to fix it?

**Comment by Domino987** [comment]
The deep merge work for me. Did you update your npm install and everything?

**Comment by sucy6330133** [comment]
Yes, I have fully updated. v0.2.37 is working, just broken after upgrade to 0.2.38. Also tried the latest one. No luck.

**Comment by Domino987** [comment]
weird. Would you mind throwing your setup into a sandbox? For me to inspect

**Comment by sucy6330133** [comment]
It might related to this issue https://github.com/facebook/create-react-app/pull/12605

**Comment by Domino987** [comment]
Can you all try the latest version ;)

**Comment by imnasnainaec** [comment]
Oh yay, `react-beautiful-dnd` supports React v18 now: https://github.com/atlassian/react-beautiful-dnd/releases/tag/v13.1.1!

**Comment by sucy6330133** [comment]
> Can you all try the latest version ;)

Works fine to me now. Tried version v0.2.48.

**Comment by sairam0903** [comment]
Hi @Domino987  can you help with this issue https://github.com/material-table-core/core/issues/660
