### ISSUE TITLE
Searching on boolean value: false returns no results

### ISSUE THREAD

**Issue by grtn316** [material-table-core/core#537]
When binding a table with boolean values and using the search feature, it only returns values "true" and finds no matches for value "false". I have tried various combinations of searching and cannot get it to work.

I am using version: 4.3.41.

Example of data:

```json
[
    {
        "Id": 1,
        "Status": true,
        "Price": null,
        "Sales": 2
    },
    {
        "Id": 2,
        "Status": false,
        "Price": null,
        "Sales": 2
    }
]

**Comment by Domino987** [comment]
Could you add a sandbox of your exact setup in a sandbox as requested?
