### ISSUE TITLE
disable click on sort button

### ISSUE THREAD

**Issue by strawji02** [material-table-core/core#542]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

hello. I am using the material table well.

Is it possible that the sort function exists only in desc in the columns button and the button click is disabled?

**Comment by Domino987** [comment]
You can override the sort function or the defaultSort on the column to force a specific sort direction.
