### ISSUE TITLE
How to align pagination controls to the left bottom corner of the table?

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#543]
Currently the page navigation control appears on the bottom right corner by default. This makes it harder esp for tables with many columns as user has to scroll all the way to right to use the pagination. Is there any way to align this on the left bottom of the table instead of the right bottom by default?

**Comment by DewangS** [comment]
does anyone know how to align this on left side? @oze4 @DominikEngel

**Comment by Domino987** [comment]
@DewangS 
```
components={{
        Pagination: props => (
                <TablePagination {...props} style={{display: "flex",
                  justifyContent: "flex-start"}}/>
        )
    }}
```

**Comment by DewangS** [comment]
Sorry @Domino987  but when I added this under <MaterialTable> declaration, I got weird output. Where exactly should this go? I've imported TablePagination from the material-table/core

**Comment by Domino987** [comment]
No it's has to be be pagination from Material ui

**Comment by DewangS** [comment]
@Domino987  So, I have below in my JSX component. As you can see I've imported the TablePagination from Material-ui and added the styling code snippet which you've provided under the <MaterialTable> declaration. Still can't see the pagination aligned to left.

```
import { Box, Grid, TablePagination } from "@material-ui/core";

<MaterialTable
      components={{
        Pagination: props => (
                <TablePagination {...props} style={{display: "flex",
                  justifyContent: "flex-start"}}/>
        )
    }}
      localization={{
        pagination: {
            labelDisplayedRows: '{from}-{to} of {count}',
        }
    }}
        title={title}
        icons={tableIcons}
        columns={columns}
        data={reportData}
        options={{
          grouping: true,
          search: true,
          showTitle: true,
          isLoading: true,

          //exportDelimiter: '        ',
          headerStyle: {
            backgroundColor: "#01579b",
            color: "#FFF",
          },
          
        }}
      />
```

**Comment by Domino987** [comment]
Can you throw this in a sandbox?

**Comment by DewangS** [comment]
@Domino987  here it is [Sandbox link](https://codesandbox.io/s/material-table-starter-template-forked-91el43?file=/src/index.js) 

I think the issue is with the Material Table core package version ... see below

It works with the "@material-table/core": "0.2.17" which is part of the template code in the sandbox when first fork it.

It gives strange results as I use "@material-table/core": "^2.3.37" as you can see [here](https://codesandbox.io/s/material-table-starter-template-forked-91el43?file=/src/index.js)

I think props with spread is causing the issue. If you remove {...props} you will see the control moves to left though page numbers gets stuffed up showing NaN (Not a number)

**Comment by Domino987** [comment]
You are mix and matching versions of mui, material table and lab that are not compatible. Using material table v2 uses super old code, which needs to use old Mui versions as well. And lab and icons need to be below 5 as well, if you use them Mui V4 in other places. I recommend upgrading the versions to use either but mui VT with material table core 0.2.X or the latest mui V4 with the core 4.x.

**Comment by DewangS** [comment]
Thanks. Just updated package.json on the forked sandbox with below latest packages ..still no luck

"@material-ui/core": "^4.12.4",
    "@material-table/core": "^4.3.43",
    "@material-ui/icons": "4.11.3",
    "@mui/icons-material": "5.6.2",
    "@mui/lab": "5.0.0-alpha.81",
    "@mui/material": "5.7.0",

**Comment by Domino987** [comment]
You are still using both Mui and Material ui. Those clash, use only one

**Comment by DewangS** [comment]
even withe below packages it doesn't align left ... the moment you remove {...props} it works irrespective if you have MUI and material UI packages.

"dependencies": {
    "@material-ui/core": "^4.12.4",
    "@material-table/core": "^4.3.43",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "3.4.4"
  },

**Comment by Domino987** [comment]
It seems like it differs between mui v4 and v5.
This works for mui v4:
```
components={{
        Pagination: props => (
                <TablePagination {...props}
                style={{display: "flex",
                  justifyContent: "flex-start"}}
                 classes={{}}/>
        )
    }}
```
https://codesandbox.io/s/material-table-starter-template-forked-u2e3i7?file=/src/index.js

**Comment by DewangS** [comment]
@Domino987  Perfect...  Thanks tons. This worked.
