### ISSUE TITLE
Issue rendering when large amount of colums

### ISSUE THREAD

**Issue by skearney414** [material-table-core/core#545]
I have a table that displays the output of a select from a database, 
issue is sometimes people do a "select *" some tables have 500 plus columns. 
This causes the screen to freeze until material-table loads the columns. 

Is it possible to have some kind of suspense feature while the table is rendering ? 
Looks like the columns rendering is not part of isloading.

**Comment by Domino987** [comment]
Hi,
so rendering 500+ columns is not a use case that we are aiming to support.
So many columns are neither a good user experience nor is it a reasonable amount of components to render in react.
While we are working on improving the performance, I dont think this will be feasible in the future.

We also cannot detect the rendering with react < 18 the transition. So after we upgrade to react18, we might be able to display a spinner during the transition.

So I will be closing this.
