### ISSUE TITLE
Feature request to have custom alignment of the pagination control

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#549]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

Current pagination control element appears on the right bottom end of the table. It would be nice to have an option in the <MaterialTable> declaration 

- #### You may fork one of the following starter templates if you would like:

[codesandbox with a tweak to align controls to left]( https://codesandbox.io/s/material-table-starter-template-forked-u2e3i7?file=/src/index.js)

**Is your feature request related to a problem? Please describe.**

When table contains many columns, it's hard for the user to scroll all the way to the right just to use the pagination. Also at times it looks good to have these controls in the middle\centre of the table for a better UI experience

**Describe the solution you'd like**

Having alignment options in the MaterialTable declaration like below will help in many scenarios to align pagination to the left or center of the table

For example below option of **align LEFT** should place the pagination controls in the middle of the table

localization={{
        pagination: {
            **align: 'left',**
            labelDisplayedRows: '{from}-{to} of {count}',
        }
    }}

For example below option of **align CENTRE** should place the pagination controls in the middle of the table

localization={{
        pagination: {
            **align: 'centre',**
            labelDisplayedRows: '{from}-{to} of {count}',
        }
    }}

#543

**Comment by Domino987** [comment]
Sounds reasonable. I'll take a look at it.

**Comment by Domino987** [comment]
This will be possible with the next release. Ill like the docs soon.
UPDATE:
https://material-table-core.com/demos/pagination/positioning

**Comment by DewangS** [comment]
Thanks @Domino987
