### ISSUE TITLE
Testing v5

### ISSUE THREAD

**Issue by Domino987** [material-table-core/core#550]
Hello everybody,
we just released a work in progress release: [5.0.0-experimental.0](https://www.npmjs.com/package/@material-table/core/v/5.0.0-experimental.0). The start of a major rewrite using zustand is included to both reduce complexity and prop drilling as well as improve performance by reducing rerenders.

This rewrite is not yet complete and might contain bugs, but is an important step towards getting rid of the data manger and using a proper data management and distribution of data to child components.

So if you find any problems with this, please open a ticket so we can take a look. Thank you.

FYI, this will be ported to the next branch once it is classified as stable.

**Comment by GenesisAtMac** [comment]
https://github.com/material-table-core/core/blob/v5.0.0/types/index.d.ts#L217

RReact.ReactNode is part of v5.0.0.  Any chance for a quick 5.0.1?

**Comment by Domino987** [comment]
Ups, will change it, sry.

Update, done

**Comment by GenesisAtMac** [comment]
Thanks! 

And sorry, I should have been a bit more tongue in cheek as I have neeeever done something similar (said with a lot of self-deprecation!)

**Comment by Domino987** [comment]
haha no problem xD
Should have check it one more time anyway ;)
Obviously first time for me as well.

**Comment by MLNW** [comment]
Is v5 now compatible with MUI v5? Or do we have to continue using the next branch?

**Comment by Domino987** [comment]
Those are still separated due to the large amount of people still using V4.

**Comment by FalkF** [comment]
"1139 commits ahead" 🎆 is that a 90% rewrite? I have the perfect project for testing it open, nice!

**Comment by Domino987** [comment]
No it's not, but we changed a lot with both new features, bug fixes, ts support improved and Muir v5 support.
The new version V5 is started to improve the prop drilling and performance.

**Comment by ckchiu2** [comment]
When will the new features in master branch be available in v5? Or any plans for (legacy) release for v4 on the master branch?

**Comment by imnasnainaec** [comment]
@Domino987 Do you mean for this issue to still be pinned?
