### ISSUE TITLE
onRowSelected does not workk

### ISSUE THREAD

**Issue by ogozman** [material-table-core/core#551]
Hi, I am having an issue with onRowSelected prop. I have added a function there but it is not getting called.
My entries all have ids (not sure if it is importnat in this case).
I am using the table in electron with typescript. 
Other props work, but onRowSelected is not getting called for some reason:
Reproduce 
1. Create a table 
2. Assign function to onRowSelected props
3. Select row via checkbox
4. Nothing happens

**Comment by Domino987** [comment]
Please provide a sandbox as requested
