### ISSUE TITLE
error with onSearchChange prop

### ISSUE THREAD

**Issue by tednaaa** [material-table-core/core#552]
[demo](https://codesandbox.io/s/material-table-starter-template-forked-nm6tvx?file=/src/index.js)

in the documentation, the name of the prop is `onSearchChange`

<img width="879" alt="image" src="https://user-images.githubusercontent.com/79831859/170945941-aeb90c2d-178f-403e-8c3f-18eb839633f5.png">

But in the code is `onSearchChanged`
also if you try to use `onSearchChanged`, this function will not actually work because it doesn't accept the argument `searchtext`

<img width="305" alt="image" src="https://user-images.githubusercontent.com/79831859/170947525-6facb650-6465-4528-a116-36b038bc7374.png">

**Comment by Domino987** [comment]
Can you put your code in a sandbox ?

**Comment by Domino987** [comment]
I think you are mixing two different things here. In the demo, you are overriding the toolbar, which is so far not documented and the props are given from its parent.

The onsearch change of the docs is actually a callback executed when the search value changes to notify the parent component.

So these are different things. What do you want to achieve.

**Comment by tednaaa** [comment]
I want to implement custom search input field, I searched in closed issues smth like that, but doesn't found

**Comment by Domino987** [comment]
You would need to override the whole toolbar. Look into the toolbar component to get a sense of what is going on within the toolbar.
What do you want to achieve?
