### ISSUE TITLE
Sort by Date is not working as expected. It only sorts based on the day and not considering month and year

### ISSUE THREAD

**Issue by testgh2022** [material-table-core/core#556]
```
function BasicTable(props) {
const [tableData, setTableData] = useState(data)
const columns = [
    {
      title: "Date", field: "transDate", type: 'datetime', sorting: true, search: true, width: 200,
      dateSetting: {
        format: 'dd/MM/yyyy'
      },
      cellStyle: styles.cellStyle
    },
    {
      title: "From", field: "userName", sorting: true, search: true, width: 200
      cellStyle: styles.cellStyle
    },
    {
      title: "Sent To", field: "addressee", sorting: true, search: true, width: 200,
      cellStyle: styles.cellStyle
    }
];
return (
    <MaterialTable
      columns={columns}
      data={tableData}
      options={{
        sorting: true
      }}
/>
  );
}

export default BasicTable;
```

**Comment by Domino987** [comment]
Could you add a sandbox as requested? Since it works for me, it might depend on the version or the data objects you are passing. But since there is not sandbox, we cannot verify any of it.

**Comment by testgh2022** [comment]
Please find the sandbox link.
https://codesandbox.io/s/thirsty-pasteur-1nfobx

**Comment by testgh2022** [comment]
> Could you add a sandbox as requested? Since it works for me, it might depend on the version or the data objects you are passing. But since there is not sandbox, we cannot verify any of it.

> I have added source in the below sandbox. I also noticed that string is sorted by capital letter first and then sorted by lowercase. Is this expected behaviour?
> 
> https://codesandbox.io/s/thirsty-pasteur-1nfobx

**Comment by Domino987** [comment]
Hi, as expected you are not passing dates to the table within the fields. You need to wrap the date fields with new Date(value).

The sorting with upper vs lower case originates from Javascript. If you want, you can overwrite the custom sort to compare the fields with .to lowercase()

**Comment by testgh2022** [comment]
> Hi, as expected you are not passing dates to the table within the fields. You need to wrap the date fields with new Date(value).
> 
> The sorting with upper vs lower case originates from Javascript. If you want, you can overwrite the custom sort to compare the fields with .to lowercase()

I tried to pass the date value in the render, however it's throwing the below error.
"Objects are not valid as a React child (found: [object Date]). If you meant to render a collection of children, use an array instead."

render: (rowData) => {
      return new Date(rowData.transDate);
    },
    dateSetting: {
      format: "dd/MM/yyyy"
    }

Could you provide sample code?

**Comment by Domino987** [comment]
No you need to change your data object. I am not at my computer right now so maybe later. But the data you are passing into the data prop needs to be data at the right places

**Comment by testgh2022** [comment]
> No you need to change your data object. I am not at my computer right now so maybe later. But the data you are passing into the data prop needs to be data at the right places

I am sorry I don't understand what you have explained. It's not urgent, but I would really appreciate if you could share sample code when you are free. 

I also have one more problem with the search functionality. 
I have a requirement to extend search functionality for detail panel. The default search functionality of Material-table works fine for tree data. However my detail panel records are different from parent row, hence I cannot use tree data.

Hence I have written a custom function which extend search for detail panel and calling it from onSearchChange.
It works when I log the searched the rows in the console it returns the matched records(correct data based on the search text), however material-table is not displaying updated records(returns empty record even though detail panel has the search text).

I may be doing something wrong in setting the searched data to Material-table. It's in the same sandbox code.

Would it be possible for you to check the sandbox code and let me know if that can be done?

**Comment by Domino987** [comment]
https://codesandbox.io/s/zealous-leavitt-h4nhbf?file=/src/component/BasicTable.js

Here you can see how I modify your data to have a date object.

Regarding the search, you should be able to just override the customSearch and search each object in there instead of listening to the onSearchChange.
https://github.com/material-table-core/core/blob/master/types/index.d.ts#L184
You just have to return true or false if the entry should be included

Update:
https://codesandbox.io/s/misty-haze-zm6d9g
Something like this should be enough @testgh2022

**Comment by testgh2022** [comment]
> https://codesandbox.io/s/zealous-leavitt-h4nhbf?file=/src/component/BasicTable.js
> 
> Here you can see how I modify your data to have a date object.
> 
> Regarding the search, you should be able to just override the customSearch and search each object in there instead of listening to the onSearchChange. https://github.com/material-table-core/core/blob/master/types/index.d.ts#L184 You just have to return true or false if the entry should be included
> 
> Update: https://codesandbox.io/s/misty-haze-zm6d9g Something like this should be enough @testgh2022

It's working. It simplified my work in a great way. Thanks a lot.

**Comment by testgh2022** [comment]
Selection is not working when Custom sort and local storage implemented together. I had to remove custom sort in order to make selection work. Is there any reason why I can't use them together with selection?

Sandbox code:
https://codesandbox.io/s/thirsty-pasteur-1nfobx?file=/src/component/BasicTable.js

**Comment by testgh2022** [comment]
> https://codesandbox.io/s/zealous-leavitt-h4nhbf?file=/src/component/BasicTable.js
> 
> Here you can see how I modify your data to have a date object.
> 
> Regarding the search, you should be able to just override the customSearch and search each object in there instead of listening to the onSearchChange. https://github.com/material-table-core/core/blob/master/types/index.d.ts#L184 You just have to return true or false if the entry should be included
> 
> Update: https://codesandbox.io/s/misty-haze-zm6d9g Something like this should be enough @testgh2022

Selection is not working when Custom sort and local storage implemented together. I had to remove custom sort in order to make selection work. Is there any reason why I can't use them together with selection?

Sandbox code:
https://codesandbox.io/s/thirsty-pasteur-1nfobx?file=/src/component/BasicTable.js
