### ISSUE TITLE
After open Dropzone dialog in edit mode, the edit state changes to disabled

### ISSUE THREAD

**Issue by raulrobi2018** [material-table-core/core#557]
I have a similar situation to this post [Stackoverflow](https://stackoverflow.com/questions/69804535/material-table-after-open-dialog-in-edit-row-is-closed-edit-of-row), but the solution didn't work for me.

This is the [Sandbox](https://codesandbox.io/s/material-table-starter-template-forked-vfw1vr?file=/src/useTable.js) example.

I would really appreciate it if someone could help me because I'm really stuck in this situation.

Thank you!

**Comment by Domino987** [comment]
So you have a few unessary useCallbacks.
Instead you should move the dialog together with the icon/EditComponent as show in the following sandbox.

https://codesandbox.io/s/material-table-starter-template-forked-k2c4fr?file=/src/useTable.js
