### ISSUE TITLE
Is it possible to customize the details panel icon on a per row basis?

### ISSUE THREAD

**Issue by jasonleenaylor** [material-table-core/core#558]
In my application I am using a details panel to display the contents of a Notes field on the row.
Users can add multiple Notes, or have no notes at all for any given row.
I would like users to be able to see by the icon if there are any notes for a row to save clicking on the icon.

I see that there is a way to add a custom icon, but is there any way currently to customize the rendering of the icon that opens up the panel?

**Comment by Domino987** [comment]
Yes you can pass a function to return the detail panel object to the prop
