### ISSUE TITLE
Add 'overlay' as an accepted value in the overflow options

### ISSUE THREAD

**Issue by josueuitzil** [material-table-core/core#559]
Hi devs, 

I noticed that you get a prop-types error in the console when you try to set the overflowY property of the table container to 'overlay'.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/61981074/173452708-8a0b4fd8-a8cf-4c03-b078-554febc60956.png">
[Sandbox](https://codesandbox.io/s/material-table-starter-template-forked-f5jyf0?file=/src/index.js)

This error comes from overlay not being included in the array of the type definition of the options:
https://github.com/material-table-core/core/blob/4fd6f459b17be7efed77f2e3686307cbcac82a5d/src/prop-types.js#L342

While overlay is a deprecated value, it is still valid CSS. It is supported and also behaves differently in Chromium browsers, so I think that it would be valid to include it as an option in the prop-types file. What do you think?

I could open a PR with this change if you are ok with it.

Thanks for the great job in the library!

**Comment by Domino987** [comment]
Hi, those prop types are really old and most likely need updating. So yes please open an PR, thanks !!

**Comment by josueuitzil** [comment]
I just opened a PR for this, thank you!
