### ISSUE TITLE
Filtering Bug With Lookup

### ISSUE THREAD

**Issue by matthew-kusz** [material-table-core/core#56]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
Demo: https://codesandbox.io/s/jolly-minsky-de7b9?file=/src/App.js

**Describe the bug**
Enabling filtering and using `lookup` in a column to create a drop down with selectable options causes an error `ReferenceError: props is not defined`. I can select different options, but there is no filtering and I cannot exit out of the selection by clicking off or pressing esc.

**To Reproduce**

1. Create a MaterialTable with filtering enabled.
2. Set up `lookup` in one of the columns.
3. Try filtering with that column and exiting the selection.

**Expected behavior**
Selecting one or more of the options should filter the data and allow me to exit out of the selection.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 2.3.2

**Comment by matthewoestreich** [comment]
Thank you very much for this. I was able to get this issue resolved and a new package published.

https://www.npmjs.com/package/@material-table/core/v/2.3.3

Working demo:

[![Edit mystifying-robinson-wyn8e](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-robinson-wyn8e?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matthew-kusz** [comment]
Thank you for the quick fix!

**Comment by matthewoestreich** [comment]
No problem! Sorry for the inconvenience. Please let us know if you have any further problems.

Cheers!
