### ISSUE TITLE
Number of rows selected banner hides export icon in MTableToolbar

### ISSUE THREAD

**Issue by NivBox** [material-table-core/core#560]
![image](https://user-images.githubusercontent.com/66591073/173512467-dbd5a582-a561-4fcc-ae39-351c6c132fc1.png)

I'm using @material-table/core version 0.2.32. Here is my codesandbox for the implementation. https://codesandbox.io/s/little-brook-2mfzf1?file=/src/App.js

The select rows banner overlaps/hides the export icon in the toolbar, while search bar is still visible.

**Comment by Domino987** [comment]
Can you add a sandbox as requested so we can take a look at it ?

**Comment by NivBox** [comment]
Updated the comment with a link to codesandbox implementation

**Comment by NivBox** [comment]
@Domino987 Just checking to see if there is any update on this issue

**Comment by Domino987** [comment]
I am looking into it but the bug is not yet resolved since the rendering differs between the two states and I do not want to introduce a bug because of this

**Comment by Domino987** [comment]
This will be fixed with the next release this week.
