### ISSUE TITLE
Grouping Header does not disappear

### ISSUE THREAD

**Issue by Linos2508** [material-table-core/core#561]
# Guidelines

dragged column does not disappear until next render, same viceversa the column does not appear until next render when you deleted from the grouped columns
version 5.0.1 and bigger

https://codesandbox.io/s/grouping-zu4gw

**Describe the bug**

**To Reproduce**

1. Go to the codeSandbox
2. Drag&Drop anycolumn to groupBy it, grouping is applied but the column persist on headers
3. refresh data with the button above and column disappear
4. Delete the column from the grouping group, got delete but now the column does not show
5. refresh data with the button above
6. see error

**Expected behavior**
The column should dissapear once the grouping is applied, and also appear again once the group gets deleted

![image](https://user-images.githubusercontent.com/59886302/173716219-3fe7b78d-1acd-4639-b99f-99bf3d14457e.png)
![image](https://user-images.githubusercontent.com/59886302/173716255-a0d835e5-3eec-4c1b-a813-667b747bf1bd.png)

**Comment by Domino987** [comment]
It seems like this is connected to the `persistentGroupingsId`. Ill check it out

**Comment by Linos2508** [comment]
Hi @Domino987 any update on this issue?

**Comment by Domino987** [comment]
I looked into it but did have a fix yet.
