### ISSUE TITLE
onGroupRemoved wrong type

### ISSUE THREAD

**Issue by Linos2508** [material-table-core/core#562]
at onGroupRemoved prop the type of parameter index is boolean and it should be number 4.3.43 and bigger

https://github.com/material-table-core/core/blob/4fd6f459b17be7efed77f2e3686307cbcac82a5d/types/index.d.ts#L63

**Comment by Domino987** [comment]
That's true, would you mind open a PR for this?

**Comment by Linos2508** [comment]
I will

**Comment by Linos2508** [comment]
I Opened the PR please take a look as soon as you can @Domino987

**Comment by Domino987** [comment]
I merged the PR. Thanks.
