### ISSUE TITLE
How to prevent reordering first column in material table.

### ISSUE THREAD

**Issue by nguyentienviet123456** [material-table-core/core#563]
Hello all,
I'm wondering how to add custom attribute to prevent reordering first column in material table. MaterialTable doesn't provide attribute to do that.

Is there any other way of achieving this? 🤔

**Comment by Domino987** [comment]
What do you mean reordering. Can you specify or share a sandbox?

**Comment by nguyentienviet123456** [comment]
> What do you mean reordering. Can you specify or share a sandbox?

I mean prevent to drag/drop on first column header.

**Comment by Domino987** [comment]
Did you try this column prop https://github.com/material-table-core/core/blob/master/types/index.d.ts#L222 ?

**Comment by nguyentienviet123456** [comment]
> Did you try this column prop https://github.com/material-table-core/core/blob/master/types/index.d.ts#L222 ?

Hi Domino987, I did try this property but It's not work

**Comment by Domino987** [comment]
draggable: false should work.

**Comment by nguyentienviet123456** [comment]
It's work with draggable. Btw Column type doesn't have prop draggable, please add it.

**Comment by Domino987** [comment]
will be added with 5.0.4
