### ISSUE TITLE
Crash when filtering on tabletree

### ISSUE THREAD

**Issue by DennisRP** [material-table-core/core#566]
Demo running 4.3.44: 
https://codesandbox.io/s/material-table-starter-template-forked-qnwwfg
Try to enter any term in the filter field. The first keypress will crash the table.

This seems to happen due to the ordering of the items. If I move the first item ("failswhenfirstinobject") to the bottom, it works as expected.

I couldn't locate the issue, but I did see it crashed, because the array of paths for childRows didn't contain the path of the current row (which is expected it would). When that lookup fails, the pointer would be set to undefined [Link](https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L1071)

**Comment by DennisRP** [comment]
This seems to be caused by an index lookup with incorrect offset. 

The first object in my data:
`    {
      id: "failswhenfirstinobject",
      parentId: "white2"
    },` 
is level 3, and will create level 2 (white) and level 1 (main).

The next set of data, will create level 2 (black) and attach to level 1 (main).

The next set of data, is level 2 (white) again, which already exists. [The code updates path on each iteration](https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L1039-L1042) no matter if row was added or not. It takes the latest child (by using array length index) and uses the path of that - only that now, white was skipped (since it was already created), and path for black is used instead (as it was the latest added child to main). That leaves us with an inconsistent path for white and its children.

Which on filtering gives a null pointer, when [code cannot lookup the path of one of its children](https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L1068).

I am not sure why indexes are used for this, as it seems obvious to just use the path of the current dataRow. I am guessing its legacy from when path seems to be built by increasing integers as indexes `[0,1,2,etc]`.
https://github.com/material-table-core/core/blob/4a144447c647f075d4d2552a3f21efa9fc5b3756/src/utils/data-manager.js#L964 

An obvious fix could be:
~~`[parent.tableData.childRows[parent.tableData.childRows.length - 1].tableData.uuid`~~ -> `[rowData.tableData.uuid]]` (https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L1041)

Let me know if I am missing something. I'll try to cook up a PR for this otherwise.

**Comment by Domino987** [comment]
Could you verify that this has no unseen sideeffects?

**Comment by Domino987** [comment]
Should be fixed with next release
