### ISSUE TITLE
Aria Sort Issue:

### ISSUE THREAD

**Issue by ljcuneo** [material-table-core/core#570]
Element source contains aria-sort='none' and does not contain a role property.
How can I set a new role for this element in the table?
<img width="924" alt="Aria" src="https://user-images.githubusercontent.com/52754384/174893707-9f97eb9d-a9d6-453a-8111-70c07bad991e.PNG">
 
Any help would be appreciated!

**Comment by Perronef5** [comment]
I am seeing the same issue as well.

**Comment by Domino987** [comment]
It is none, if that column has no current sorting: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaSort

**Comment by ljcuneo** [comment]
I understand, but it still needs a role to be set.

**Comment by Domino987** [comment]
What role do you have in mind?
