### ISSUE TITLE
ThemeProvider Dark Mode Not Wokring

### ISSUE THREAD

**Issue by LukePrior** [material-table-core/core#573]
# ThemeProvider Dark Mode Not Wokring

I am trying to use dark mode in Material UI but the table styling is not updating. You can see an example codesandbox where this behavior is demonstrated below.

## Example

  - https://codesandbox.io/s/material-table-starter-template-forked-2i9dkh

**Comment by Domino987** [comment]
Its because you are mixing wrong versions,
If you use mui v5, you need to use the next branch aka 0.XX of material table core.
https://material-table-core.com/docs/material-ui-v5

**Comment by LukePrior** [comment]
NVM resolved
