### ISSUE TITLE
Problem with yarn and dependency solving

### ISSUE THREAD

**Issue by andrija29** [material-table-core/core#574]
# Problem with yarn and dependency solving

## Error
We get the following error:

```
Module not found: Can't resolve '@material-ui/core/Paper'
Import trace for requested module:
./node_modules/@material-table/core/dist/components/index.js
./node_modules/@material-table/core/dist/index.js
./src/components/analyst_dashboard.tsx
./src/pages/dashboard/index.tsx
```

## Explanation
We are using  @mui/lab: 5.0, @mui/material: 5.8.6, @mui/styles: 5.8.6 and since we don't like their table plugin we are using yours @ 5.0.2.
We were using npm and it all worked fine, after we switched to yarn it broke.
So after some debugging I realized that yarn resolves @material-ui/core to the version 4.12.4, which your plugin does not like and it breaks, but on the other hand with npm it works fine.

### Temporarily fix:
If I manually fix @material-ui/core to the 4.12.1 it works fine with both MUI and your plugin. I am not 100% sure why it happens, but my hunch is that npm actually installs two versions of @material-ui/core, one for your plugin and one for MUI, or it resolves versions better, I'm not sure.

**Comment by Domino987** [comment]
I used it with both yarn and npm and did not have problems. Can you sagte both your package json, at least the important things, and a sandbox with your set-up?
