### ISSUE TITLE
pageSize props is being ignored on v5 onwards

### ISSUE THREAD

**Issue by Elabar** [material-table-core/core#577]
How to change the initial pageSize?
We used to do this in `mbrn/material-table`

```jsx
<MaterialTable 
   // ...
   options={{
      pageSize: 10,
      pageSizeOptions: [10, 50, 100, 200]
   }}
/>
```

But it doesn't work now

**Comment by Domino987** [comment]
As requested, please add a sandbox!!!

**Comment by Elabar** [comment]
ok

**Comment by DukeManh** [comment]
@Elabar, do you mind telling us your solution, please? I'm having the same issue, the `pageSize` prop has no effect.

**Comment by Elabar** [comment]
> @Elabar, do you mind telling us your solution, please? I'm having the same issue, the `pageSize` prop has no effect.

I don't have a solution, In fact, it works out of the box when I try to reproduce it with a minimal reproduction sandbox. I reverted back to `mbrn/material-table` for now

**Comment by DukeManh** [comment]
Downgrading from v5 to v4 makes it work for me.

**Comment by DukeManh** [comment]
@Domino987, Here's the sandbox of v5 where `pageSize` prop doesn't seem to work. https://codesandbox.io/s/hidden-dew-hr95kq?file=/src/App.js

**Comment by Elabar** [comment]
Ahhh, that explains why I couldn't make a reproduction. I used the sandbox in the bug template which was using 0.xx version. After upgrading to 5.x version, pageSize is indeed not working. Here's my repro link with server data. Reopening this issue as the issue is easily reproduceable. 

https://codesandbox.io/s/material-table-starter-template-forked-8w2rr9?file=/src/index.js

**Comment by Domino987** [comment]
Will be fixed with the next version. thank sguys

**Comment by areiterer** [comment]
Thanks for the fix! 
Unfortunately, it seems the fix (https://github.com/material-table-core/core/commit/eda9e4305910dd480896c80634016c8b4f97213f) doesn't update the page size of the `query` object when working with remote data.
