### ISSUE TITLE
Overriding Row Component not working in 5.0.2

### ISSUE THREAD

**Issue by sarveshp17** [material-table-core/core#578]
I am overriding the Row component to implement a Right Click event for each row. It is working fine with v4.3.44 but not working on v5.0.2

**Expected behavior**
Right Click on any row should display an alert saying "right click event"

**Working sandbox with v4.3.44**
https://codesandbox.io/s/mat-table-right-click-4-3-44-g1zvmh

**Not working sandox with v5.0.2**
https://codesandbox.io/s/mat-table-right-click-5-0-2-1yh9rx

**Comment by Domino987** [comment]
Oh yes, good catch.
Next version will have this fixed.
