### ISSUE TITLE
Wrong type in index.d.ts in release 5.0.3

### ISSUE THREAD

**Issue by ckchiu2** [material-table-core/core#580]
**Describe the bug**

In 5.0.3 release, the component types are changed to React.ReactNode, and it throws error in typescript.
It also does not match with the types declared in master branch. 

**To Reproduce**

https://codesandbox.io/s/gracious-hofstadter-mpxqsv?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/43362431/177081692-008418eb-877b-4e8f-b065-ec50f0eba71c.png)

You can see typescript is hinting the error for the return type of MTableBodyRow.

I cannot reproduce the compilation error in sandbox though.

**Comment by Domino987** [comment]
Yes we were a little bit to free with the replace all. will be fixed next version
