### ISSUE TITLE
Localization not working on v5.0.3 

### ISSUE THREAD

**Issue by priscaure** [material-table-core/core#583]
Hey guys, 

I'm having an issue with localization on version 5.0.3, it's being totally ignored. Seems to work with version 4.3.44 though. 
The issue is easily reproducible on the sandbox.  

- #### Please include a demo of the issue/behavior/question you have
  https://codesandbox.io/s/material-table-starter-template-forked-ng9kfq?file=/src/index.js

**Comment by Domino987** [comment]
Yes, my bad, will be fixed with the next version.
