### ISSUE TITLE
Selection action event that changes values, won't update UI

### ISSUE THREAD

**Issue by DennisRP** [material-table-core/core#584]
When using selection and triggering an event, I change some values in the data, but it does not get reflected onto the UI. Only when some other refresh is forced (like changing page or sorting), the values are updated.

If one instead of changing the property values, changes array length of data (push/pop), the UI is updated.

https://codesandbox.io/s/material-table-starter-update-bug-1so7nu

The demo shows cloning existing data and changing all values.
```    
let cloned = [...rawData];
    cloned.forEach((r,i) => {
      r.word = "Fire 🔥";
    });
```

Update - but UI doesn't change.
`setData(cloned);` 

If instead doing 
`setData(cloned.filter(x => x.id > 50));`
.. then UI is updated as expected.

A half fix would be to iterate selected rows (replace `cloned.forEach` with `selectedRows.forEach`, which will update the UI. But its not immutable and also will not be affected by any filtering.

I expect table to show my updated data, when executing `setData` with no changes to size of items.

Running 4.11.4.

**Comment by Domino987** [comment]
This is indeed weird. Ill check it out this weekend.

**Comment by Domino987** [comment]
Ah this is actually the expected behavior.

The problem is, that you are mutating both the new as well as the old data. So they are both equal because you only shallowly copy the array, but not the objects. So after the safe, the old and new data is equal, which skips the rerender.

**Comment by DennisRP** [comment]
Ahh I see it now. Thanks for spotting it out.
