### ISSUE TITLE
Mutliple Sorting

### ISSUE THREAD

**Issue by kirin-yuen** [material-table-core/core#585]
# Guidelines
https://github.com/mbrn/material-table/issues/541

The feature request before 3 years ago, will it be implement it in the core version?

**Comment by Domino987** [comment]
You are welcome to try it and add a PR

**Comment by Domino987** [comment]
This was done with the latest release for Mui V4 via the experimental branch and will be soon merged to the next branch. I'll update the docs as well this week.

**Comment by samuelbailor** [comment]
> This was done with the latest release for Mui V4 via the experimental branch and will be soon merged to the next branch. I'll update the docs as well this week.

I don't see where the docs were updated. Both `options.sorting` and `onOrderChange` were deprecated and I need to figure out the best practice for implementing the previous functionality within my app.

**Comment by Domino987** [comment]
Ok those are a few different things. What do you want to achieve?
