### ISSUE TITLE
Unwanted State Changes: A Megathread

### ISSUE THREAD

**Issue by matthewoestreich** [material-table-core/core#59]
## Reports of unnecessary rerenders include: 

 - https://github.com/material-table-core/core/issues/48
 - https://github.com/material-table-core/core/issues/51

These issues appear to be related to [the same change](https://github.com/material-table-core/core/issues/48#issuecomment-758330483).

Please comment here if you are having issues with rerenders.

**Comment by Domino987** [comment]
So the problem is described int his PR.

https://github.com/mbrn/material-table/pull/1975

As you can see, a bug was fixed by that, but losing the state in not acceptable. So I will take a look now on how to keep this behavior withtout the bug.

**Comment by aventide** [comment]
I believe this is happening with overridden components as well. I noticed specifically with the search bar and input focus.

If you use the built-in search functionality, i.e. `options: {search: true}`, then you can focus and type in the bar, through rerenders. In my case, I have polling going on.

If you then do `options: {search: false}` and then insert your own input component with a `Search` component override, the input loses focus with each change to the table's input data.

Example: https://codesandbox.io/s/agitated-einstein-xs6f0?file=/src/MTable.js

**Comment by matthewoestreich** [comment]
@misterlocations nice find. There are a lot of kinks that need to be worked out =/

**Comment by matthewoestreich** [comment]
@koutto @ishake does the newest version, 2.3.6 fix this for you?

**Comment by cbaker** [comment]
#66 related

**Comment by ishake** [comment]
@oze4 2.3.6 fixes it in the sandbox I had in #48 , so I'm guessing we're set. Thanks!

**Comment by aventide** [comment]
> @misterlocations nice find. There are a lot of kinks that need to be worked out =/

@oze4 Should the loss of input focus be a separate issue? I'd be happy to write one up. Just curious how we want to track all the different pieces related to state/rendering problems.

**Comment by matthewoestreich** [comment]
Yes, I think that is a good idea. Thanks again @misterlocations !

**Comment by cbaker** [comment]
I'm willing to bet that fixing one state issue will likely fix a lot of others as a side effect. Also @material-ui has a new "data grid" (material-table) in the /lab. Maybe it's worth just scrapping material-table entirely and rebuilding with that.

**Comment by matthewoestreich** [comment]
@cbaker which state issue are you referring to? One of them has already been fixed. 

As far as XGrid over at @material-ui [please see this discussion](https://github.com/material-table-core/core/discussions/16#discussioncomment-240719). 

I'm starting to think it may be best to just scrap this project and point everyone in the direction of XGrid.

**Comment by cbaker** [comment]
@oze4 Actually might not be a good idea as they want to charge a very large license fee for the same features you get for free from material-table.

**Comment by matthewoestreich** [comment]
@cbaker Yea I noticed that (makes sense why he recommended we stop working on this project).

Truth is, this project is at a crossroad. It needs a refactor. It has a lot of issues that need to be fixed. Do we just ignore all of these issues and refactor? or do we spend time bandaiding a codebase that needs a great amount of attention?

**Comment by cbaker** [comment]
@oze4 I say we just dump it all and refactor around the current API.

**Comment by matthewoestreich** [comment]
What about those that open issues? Tell them too bad? Wait for the refactor?

This project has good concepts just not good design imo.

**Comment by cbaker** [comment]
@oze4 Try hard to provide them with workarounds like the one I just provided in this thread. I must stress though that the refactor must maintain current usage so that it can be drop-in. The real professional way to handle it would be to start another "alpha" branch for the refactor and only fix breaking / major bugs in the current release then do a major release.

**Comment by matthewoestreich** [comment]
@cbaker I'm down.

**Comment by cbaker** [comment]
@oze4 get it organized, ill pitch in.

**Comment by vizardkill** [comment]
I am a co-founder of SoultechCol in Colombia, a technology company for software development, if you need financing I am willing to help prevent the project from dying, just tell them what you need @cbaker  @oze4

**Comment by cbaker** [comment]
@oze4 @vizardkill I may have a bit less burnout and more free time after I begin a new role on Apr 19, I am seriously down to start contributing to a refactor.

**Comment by vizardkill** [comment]
@oze4  Do not worry calmly and patiently, great progress can be made, I am willing to help you in what is within my power, just tell me how I could help

**Comment by matthewoestreich** [comment]
@vizardkill I am humbled by your generous offer. Your kindness is a breath of fresh air.

I would like to see this project survive as well. I think mbrn has done an amazing job. 

From my perspective, I'm not looking to make any money from this (I would feel bad because that money belongs to mbrn) but I would happily accept people's time/contributions!

**Comment by matthewoestreich** [comment]
> @oze4 @vizardkill I may have a bit less burnout and more free time after I begin a new role on Apr 19, I am seriously down to start contributing to a refactor.

@Domino987 should be included as well - he's the boss around here ;)

**Comment by cbaker** [comment]
> @vizardkill I am humbled by your generous offer. Your kindness is a breath of fresh air.
> 
> I would like to see this project survive as well. I think mbrn has done an amazing job.
> 
> From my perspective, I'm not looking to make any money from this (I would feel bad because that money belongs to mbrn) but I would happily accept people's time/contributions!

I mean if you’re rewriting it all... that’s your work and you shouldn’t feel bad about being compensated for it.

**Comment by matthewoestreich** [comment]
@cbaker agreed. That's why I can't accept anything. It wouldn't be just me rewriting it. This should remain a community driven project. Ideally, if something is broken, someone would submit a PR vs an issue. That's the mindset I'm after.

**Comment by Domino987** [comment]
Hi guys. Sorry for being AFK the last weeks. I am at the end of my master thesis and its taking up quite a bit of time and mental space right now.
But the main part will be done next week, which will free up some time for me. 
If we want to start a refactor, we would need a coordinated and set up a plan on how to do it/ what best practices we want to use. 
@vizardkill I can only echo @oze4. We are not doing this for the money since its open source and I kinda set my hearth to it since I started using and working on this a few years back.
Nevertheless, if you insist, I think tying some money around this would greatly improve the possible time we all can spend on this. And would keep the focus on actually rewriting it. But I am not sure on how we would handle this.

Anyway, I would be glad to work on this with you all to keep this alive and running.

**Comment by vizardkill** [comment]
I could host them and help them design the website for documentation and help with tag issues if needed.
We could start a new project based on refactoring, giving rise to a new library, so that we could include similar functionalities and create totally different ones from the existing ones.

From my point of view, it seems to me that this library contains totally essential functionalities for handling information in tables on the web, something that we could achieve by financing and opening a place for more participants.

**Comment by matthewoestreich** [comment]
@vizardkill I agree with @Domino987. Financing this project would def streamline things and allow us to keep focus. But I'm not sure what that would look like.

By biggest concern is I'm afraid that money will produce an "owner" or "owners" of this project. As long as it remains MIT licensed, I'm in. 

For now I think providing resources in the form of time is the best route. Perhaps in the near future, when we all have our calendars aligned, we can start planning other routes. 

Again, I cannot thank you enough for extending such a generous offer. It really does mean a lot!

**Comment by vizardkill** [comment]
For me it is with all the affection that I have for the library because we have included it in a hundred projects within our company, so when we can have time, we will have a meeting and talk to carry out a new project focused on refactoring.

**Comment by Domino987** [comment]
Many errors should be fixed with the newest release 3.1 by providing an optional id to the rows. I will add the link to docs later. Can you check it out if the errors still exist?
