### ISSUE TITLE
Group by does not work for date strings

### ISSUE THREAD

**Issue by JoshSinghEscreen** [material-table-core/core#590]
DEMO: [CodeSandbox mui v4](https://codesandbox.io/s/material-table-starter-template-forked-821buo)

**Describe the bug**
When having date strings of the same day but different time. Group by date does not work as expected.

**To Reproduce**
1. Go to provided demo.
2. Group by timestamp column

**Expected behavior**
Expected 2 grouped rows for 6/2/2022 and 6/3/2022, but instead of date is a separate groupby

**Screenshots**
<img width="427" alt="image" src="https://user-images.githubusercontent.com/69487971/179613304-0d2ea1a6-cdea-43e3-bbbd-2d3fbf8e3282.png">

**Comment by JoshSinghEscreen** [comment]
I tried to look into why this could be occurring. 
I think I've pinpointed it to the data-manager.groupData function

**Comment by Domino987** [comment]
You need to provide dates instead of strings to make them sortable by their date and not string comparison.
