### ISSUE TITLE
Previous columns's width is reduce when adding one or more column

### ISSUE THREAD

**Issue by nguyentienviet123456** [material-table-core/core#592]
When I set properties :
<MaterialTable
  ...
  options={{
    tableLayout: "fixed",
    columnResizable: true
  }}
/>
I need to set tableLayout to fixed inorder to enable resizable. But when I adding one ore more column, previous columns's width is reduce.

Please give me a solution to keep previous columns's width as it have

**Comment by Domino987** [comment]
Can you out that in a sandbox?
