### ISSUE TITLE
onRowDelete TypeError, crashes the app

### ISSUE THREAD

**Issue by RELNO** [material-table-core/core#594]
#### Demo
https://codesandbox.io/s/young-frog-gf3po2?file=/src/App.js 

**Describe the bug**
When implementing editable table as described here https://material-table-core.com/demos/edit/editable, row delete crashes the app

**To Reproduce**
click the row delete icon, click yes

**Expected behavior**
row should be deleted as expected 

**Screenshots**
<img width="579" alt="Screen Shot 2022-07-25 at 11 15 19 AM" src="https://user-images.githubusercontent.com/14296774/180730732-eabb20b8-4522-4019-9785-fe683079793b.png">

**Comment by RELNO** [comment]
Adding to the above, when editing a row without any change (= clicking the edit icon, but not actually changing anything) same issue occur and the app crashes. See above codesandbox to reproduce. 

** UPDATE **: with `@material-table/core@next` this issue is resolved, thank you. **The above issue is still there.**

**Comment by Domino987** [comment]
Hi, this should be fixed with the next release. Thanks
