### ISSUE TITLE
Filtering on boolean columns works counterintuitive/wrong

### ISSUE THREAD

**Issue by JanKhstll** [material-table-core/core#595]
**Describe the bug**
The checkbox for filtering booleans has three options: checkmark, minus and no filling at all. 
I would expect that checkmark only returns the true data entries, minus the false data entries and no filling means no filtering. 

It seems to me that the filtering for minus and no filling are switched. So when there is the minus all entries are returned and when there is no filling only the false entries are returned. 

**To Reproduce**
https://codesandbox.io/s/material-table-starter-template-forked-1300cr?file=/src/index.js

In the provided code sandbox. Half the enties are true and the other half of the entries are false. 
To reproduce the behaviour described above, filter on the Success column.  

**Desktop (please complete the following information):**

- OS: Windows
- Browser Edge
- Version 103.0.1264.62

**Additional context**
I only tested on the MUI v5 compatible versions of material-table-core.

**Comment by Domino987** [comment]
The minus is not actually a minus but the definition of intermediate, aka no filtering in this case. So the filtering is correct.
https://material.io/develop/android/components/checkboxes
