### ISSUE TITLE
Unable to change or override the background color of Menu for Export option

### ISSUE THREAD

**Issue by yashaswinibprasad87** [material-table-core/core#596]
Kindly check below screenshot
"& .MuiList-root-MuiMenu-list": {
        backgroundColor: "red !important",
      },
![image](https://user-images.githubusercontent.com/43347321/181435015-2326c712-5a41-4452-8b39-91578929d40c.png)

Please provide a solution

**Comment by Domino987** [comment]
Can you add a codesansbox for you code?
