### ISSUE TITLE
Adding detail panel hooks for custom actions when panel is toggled

### ISSUE THREAD

**Issue by bailor1** [material-table-core/core#597]
### This issue is pulled from the following stale PR on mbrn/material-table:
https://github.com/mbrn/material-table/pull/2032

### Description
Clients need some mechanism to tap into when the detail panel is expanded/closed. This creates two new hooks so clients can record state, metrics and much more. There are at least 3-4 issues/questions about this feature, over Github, StackOverflow and Gitter.

### Related PRs
The PR below the author provides the suggestion of creating these hooks.
https://github.com/mbrn/material-table/pull/1452

### List general components of the application that this PR will affect:
Detail Panel

### Additional Notes
This is a sample test showing the hook doing a simple log when the detail panel is expanded.
![68747470733a2f2f692e696d6775722e636f6d2f3750304a7470692e676966](https://user-images.githubusercontent.com/78231932/181588804-2cdc87a5-017e-41aa-840f-1ecb14f4cda6.gif)

**Comment by Domino987** [comment]
Would you mind creating a PR for this?
