### ISSUE TITLE
Multiple Child Tree Data Search Bug

### ISSUE THREAD

**Issue by UgurKacak** [material-table-core/core#599]
**Describe the bug**
when data has multiple level of child data as tree data search function not working as expected.

**To Reproduce**

1. Go to https://codesandbox.io/s/happy-khayyam-mro8wu
2. Try to search "hello world"
3. "Cannot read properties of undefined (reading 'tableData')"

**Expected behavior**
Table should be filtered for search keyword.

I cloned the master repo and try Basic demo with same data. Its work! however latest npm package version not working.

**Comment by Domino987** [comment]
We do not yet support react 18, can you verify if it works for react < 18?

**Comment by UgurKacak** [comment]
Hello,
As you mentioned react 18 not supported yet. Our project is run on react 18 right now.
