### ISSUE TITLE
MUI v5.9.3 does not apply the theme to the MaterialTable using the @next tag (or vice versa?)

### ISSUE THREAD

**Issue by ar4hc** [material-table-core/core#600]
Hi,

i know this is a very shallow problem description, but i'm sure i'm just missing something obvious....

i just upgraded to MUI v5.9.3 and used their codemods, and now my material table ignores all the theme settings and is all standard and bright...

The input fields are now variant outlined, but the global theme has an override and my own components are variant standard (and themed):
```
  components: {
    MuiSelect: {
      defaultProps: {
        variant: 'standard',
      },
    },
    MuiTextField: {
      defaultProps: {
        variant: 'standard',
      },
    },
// [...]
```

Funny thing: The global search box in the header is variant standard, but the  search fields above the columns are Outlined...

i assume it's due to the new emotion / styled styling and stuff but ... How? Where?

The codemods make my table file look like this:

```
const Root = styled('div')(({ theme }) => ({
  [`& .${classes.root}`]: {
    // flexGrow: 1,
    '& > *': {
      margin: theme.spacing(1),
      backgroundColor: '#424242',
    },
    normRow: {
      backgroundColor: theme.palette.secondary.main,
    },
    highRow: {
      backgroundColor: theme.palette.primary.main,
    },
  },
}));
```
and later wrap it so:
```
<Root>
      <MaterialTable ... />
</Root>
 ```

 the theme looks like this:

```
const appThemeOptions = (theme) => ( {
  spacing: 4,
  components: {
    MuiSelect: {
      defaultProps: {
        variant: 'standard',
      },
    },
    MuiTextField: {
      defaultProps: {
        variant: 'standard',
      },
    },
    MuiContainer: {
      defaultProps: {
        disableGutters: true,
      },
    },
  },
  overrides: {
    MuiCardContent: {
      root: {
        padding: '4px 8px',
        '& :lastChild': '12px',
      },
    },
    MuiCardHeader: {
      root: {
        padding: '8px',
      },
    },
  },
});

const dark = deepmerge(appThemeOptions(), {
  components: {
    MuiButton: {
      styleOverrides: {
        outlined: {
          color: '#eee',
        },
      },
    },
  },
  palette: {
    mode: 'dark',
    primary: {
      light: '#3f587a',
      main: '#102F59', /
      dark: '#0b203e',
      contrastText: '#fff',
    },
    secondary: purple,
    background: {
      main: '#424242',
      dark: '#343434',
      paper: '#424242',
    },
  },
});
export const darkTheme = createTheme(dark);
```

the App.js looks normal too:
```
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <StyledEngineProvider injectFirst>
        <ThemeProvider theme={currentTheme}>
          <CssBaseline />
            <Container maxWidth={false}>
              <NavBar />
              <Routes>
                <Route path='/' element={<Home />} />
                <Route path='/entry' element={<Entry />}>
                  <Route index element={<FaxList />} />
                </Route>
[...]
```

but all styles are ignored. removing Root changes nothing, the background-color is also ignored.

My own react components get the styling and theming, just material-table ignores it.

How do i get the MaterialTable@next themed with my styles in MUI v5?

Tried to do a sample but no matiral-table@next available in the sandboxes mentioned below... :(
- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by ar4hc** [comment]
Got something working at [codesandbox](https://codesandbox.io/s/material-table-starter-template-forked-29ppyd?file=/src/index.js)
And it does apply the theme... :(

So what happens in my app that resets or breaks the theme?

Has some errors in the console, but still...

EDIT: link to sandbox

**Comment by Domino987** [comment]
Can you reproduce your setup in an sandbox? sounds like a version mismatch

**Comment by ar4hc** [comment]
not yet, can't break the sandbox...
and i got distracted for a while.
Still trying.

I observed that my react component, a nav bar,  above the table does have the theme applied, the table itself ignores it and is light themed.

**Comment by ar4hc** [comment]
i  ound an error in the console
```
 You are loading @emotion/react when it is already loaded.
```

 that seems to link to #509

And the sandbox mentioned above  does not show this...

**Comment by ar4hc** [comment]
if i add something like this to the theme:
```
 components: {
      MuiCssBaseline: {
        styleOverrides: 
        @font-face {
// [...]
  }
}
```

and then use ` <CssBaseline />` the font in the MaterialTable changes.
But only if the CssBaseline is in and above the MaterialTable.

So some parts of the theme get through, but not the `palette` stuff ?

**Comment by ar4hc** [comment]
Creating a new CRA project with the same code from  the codesandbox  worked.
Copying the code in in the old project did not.

i delete everything yarn related and and babel, eslint, package.*, etc. and started adding the, again until the project worked and then it did the theming.

Even with everything restored but the yarn cache(build by yarn install)  and  the other stuff. (babel, eslint, prettier,...)

So it was some misconfiguration in the project, nothing in the code...
