### ISSUE TITLE
Add new row on load programmatically.

### ISSUE THREAD

**Issue by Diae-Louali** [material-table-core/core#603]
The goal would be to trigger the Add row function which show a new row form with inputs and all given a certain condition. Is this possible at all ? How would I go about achieving this ?

An example of the behavior I want to achieve can be found in the documentation under "Editable Example - Editable Preview" : https://material-table.com/#/docs/features/editable .

The only difference is that I would not need to click on the button to trigger the add new row function. 

![image](https://user-images.githubusercontent.com/68733422/184405505-f0e84ca7-c9c3-49df-adcb-b7d1cd833575.png)

**Comment by Domino987** [comment]
If you use the ref, this would work:
```
React.useEffect(() => {

ref.current.dataManager.changeRowEditing();
ref.current.setState({
              ...ref.current.dataManager.getRenderState(),
              showAddRow: !ref.current.state.showAddRow
            })
}, []);
```
