### ISSUE TITLE
Column / Layout State 

### ISSUE THREAD

**Issue by christanfoden** [material-table-core/core#605]
Our users want to be able to save their own table layouts (i.e. column order and which columns are hidden), Im searching the docs to find out if there is a column state that we can save against a user record in our database so that when they come back to the table it is in their unique layout. 

I haven't been able to find anything about column state in the docs / props, could you help point me in the right direction?

As a back up plan I'd watch every onChange that the user makes and build a sort of column map that the columns prop then adheres to but I'd only like to go down that rabbit hole if I know there is no way to call the column state at any point in time.

Any help greatly appreciated.

**Comment by Anubiso** [comment]
We had this requirement as well and solved it like this (watch out, only parts of the code): 

```
import { Column } from '@material-table/core'

export interface CustomColumn<T extends Object> extends Column<T> {
  minWidth: number
}

export const getSortedColumns = (columns: Array<Column<any>>) => {
  return columns.sort((a, b) =>
    (a.editPlaceholder ?? '').localeCompare(b.editPlaceholder ?? '', 'de-DE', { numeric: true }),
  )
}

const columns: Array<CustomColumn<Type>> = [
{
      title: t('domain.br'),
      field: 'br',
      width: getWidthOfColumn(state.columnSettings.br.width),
      minWidth: getMinWidthOfColumn(),
      defaultSort: state.columnSettings.br.sortBy,
      editPlaceholder: state.columnSettings.br.sort + "",
      hidden: state.columnSettings.br.hidden,
      render: (data) => (
        <div className={'text-no-wrap'} title={data.br}>
          {data.br}
        </div>
      ),
    },
]


const sortedColumns = getSortedColumns(columns)
const onColumnDragged = getOnColumnDragged(columns, dispatch, state.columnSettings, sliceToUse)
const onColumnSortChanged = getOnColumnSortChanged(columns, dispatch, state.columnSettings, sliceToUse)
const onColumnWidthChanged = getOnColumnWidthChanged(columns, dispatch, state.columnSettings, sliceToUse)

return (
   <MaterialTable 

           columns={sortedColumns}
            onColumnDragged={onColumnDragged}
            onOrderChange={onColumnSortChanged}
            onColumnResized={onColumnWidthChanged}
    />
)

```

**Comment by christanfoden** [comment]
> We had this requirement as well and solved it like this (watch out, only parts of the code):
> 
> ```
> import { Column } from '@material-table/core'
> 
> export interface CustomColumn<T extends Object> extends Column<T> {
>   minWidth: number
> }
> 
> export const getSortedColumns = (columns: Array<Column<any>>) => {
>   return columns.sort((a, b) =>
>     (a.editPlaceholder ?? '').localeCompare(b.editPlaceholder ?? '', 'de-DE', { numeric: true }),
>   )
> }
> 
> const columns: Array<CustomColumn<Type>> = [
> {
>       title: t('domain.br'),
>       field: 'br',
>       width: getWidthOfColumn(state.columnSettings.br.width),
>       minWidth: getMinWidthOfColumn(),
>       defaultSort: state.columnSettings.br.sortBy,
>       editPlaceholder: state.columnSettings.br.sort + "",
>       hidden: state.columnSettings.br.hidden,
>       render: (data) => (
>         <div className={'text-no-wrap'} title={data.br}>
>           {data.br}
>         </div>
>       ),
>     },
> ]
> 
> 
> const sortedColumns = getSortedColumns(columns)
> const onColumnDragged = getOnColumnDragged(columns, dispatch, state.columnSettings, sliceToUse)
> const onColumnSortChanged = getOnColumnSortChanged(columns, dispatch, state.columnSettings, sliceToUse)
> const onColumnWidthChanged = getOnColumnWidthChanged(columns, dispatch, state.columnSettings, sliceToUse)
> 
> return (
>    <MaterialTable 
> 
>            columns={sortedColumns}
>             onColumnDragged={onColumnDragged}
>             onOrderChange={onColumnSortChanged}
>             onColumnResized={onColumnWidthChanged}
>     />
> )
> ```

Thank you this looks great, I am looking now at going this route. Very much appreciate the clarification.
If any maintainers watch this issue, I'd really suggest exposing the current column state in a prop so that this can be saved and then recalled on mount.

**Comment by matthewoestreich** [comment]
I believe @Anubiso solution is how column state is exposed. Does that suffice?
