### ISSUE TITLE
Dragging columns is unpredictable

### ISSUE THREAD

**Issue by nkindrew** [material-table-core/core#609]
When dragging a column left or right of its original position, the resulting location is not where you'd expect it to be. For example, using the "Render Image" example in the documentation (https://material-table-core.com/demos/columns/render-image) try to drag the Birth Year column between Name and Surname (I'm specifically aiming for the white space between the columns before I drop). For me it jumps to the left of the name column rather than rendering in between them. When comparing it to the project from which this was forked, the mbrn version has a visual indication of where the column would land which doesn't seem to be available here.

I have determined that it works better if you drop the column on the column you wish to switch with rather than to the left or right of that column, but it still results in an unexpected order.
Using the Render Image example, if I drag Birth Place and drop it on top of the Surname column, the resulting order is Name, Birth Place, Surname, Birth Year.
If I then drag Birth Place and drop it on Name, it results in Birth Year, Name, Birth Place, Surname.
I'd have expected it to be Birth Place, Name, Surname, Birth Year.

I'm experiencing this in Chrome 104.0.5112.102 in Windows.

**Comment by DaveITpl** [comment]
I have the same problem
Video: https://watch.screencastify.com/v/Wvsh0irPBbMGLnrPoHWv

**Comment by ChethanaBellechalu** [comment]
Is there any updates on this? or any other workarounds which could help?

**Comment by Domino987** [comment]
This should work now
