### ISSUE TITLE
pageSize props is being ignored on v5 onwards

### ISSUE THREAD

**Issue by Elabar** [material-table-core/core#614]
Related issue: #577 
It seems like the applied fix is not resolving the issue completely as pointed out [here](https://github.com/material-table-core/core/issues/577#issuecomment-1219891576).

The component does actually render the correct page size. But the query parameters is still using the incorrect pageSize value.

repo: https://codesandbox.io/s/material-table-starter-template-forked-8w2rr9?file=/src/index.js

**Comment by Domino987** [comment]
Missed one spot. Should be done now
