### ISSUE TITLE
Error in onRowDelete function when clicked delete Button Actions

### ISSUE THREAD

**Issue by shwe-yi-win** [material-table-core/core#616]
Kindly check below screenshot

- When I clicked delete button, the error is 
<img width="952" alt="Screenshot 2022-09-15 151927" src="https://user-images.githubusercontent.com/51367279/190362408-a5fb6965-3532-489a-a0c1-c6e3001781e5.png">

**Comment by Domino987** [comment]
We need a sandbox. OR else we cannot help.
