### ISSUE TITLE
Not able to apply CSS classes to MTableHeader

### ISSUE THREAD

**Issue by wliu0921** [material-table-core/core#617]
I am trying to add a customized icon to action header, but there is a disabled container <span> tag (TableSortLabel) wrapping up the customized part so that the icon is not able to be trigger. 

My approach is applying css classes to MTableHeader in order to enable the pointer event for the disabled <span> tag. 
Here is the Demo 
https://codesandbox.io/s/material-table-starter-template-forked-ct59d0?file=/package.json:154-220
<img width="186" alt="Screen Shot 2022-09-15 at 3 50 04 PM" src="https://user-images.githubusercontent.com/90004135/190495904-8caa3a0f-e201-4da2-8754-0bac6ce870ff.png">

But the issue I have is In the @next version for MUI V5, css style is hard coding in MTableHeader component which is no longer from props and can't customize. 
I'd expect the @next version of MTableHeader element is accepting css classes and apply to the TableCell component like what the master branch(v4) having right now.

**Comment by Domino987** [comment]
Can you make the demo use the appropriate versions and actually compile? Thank you.

**Comment by wliu0921** [comment]
@Domino987 I had updated the demo url on the description also attach it here: https://codesandbox.io/s/material-table-starter-template-forked-ct59d0?file=/package.json:154-220.

**Comment by Domino987** [comment]
You are using Mui v5 where you should use the sx for styling. But I'll add the classes spreading as well again. Should work with the next version 0.2.43.
