### ISSUE TITLE
Sticky action button for toolbar

### ISSUE THREAD

**Issue by jbek7** [material-table-core/core#618]
I want to follow up on this closed issue: https://github.com/material-table-core/core/issues/103

I've a similar use case where I want to hide the a table, like a close button as an action. Along with an action for selected rows. It helps having a sticky action button regardless of the selection.

The current setup  doesn't allow having sticky button.

**Comment by Domino987** [comment]
Can you be a bit more precise or maybe a image/sandbox on what you want to achieve?

**Comment by jbek7** [comment]
So I've two MaterialTable one shows the list, other one has close/hide button on top corner, and it should be shown all the times. But when I select all, `toolbarOnSelect` button hides the close button.  I could hack around having another hide button definition with `toolbarOnSelect` but I didn't like the duplication.

![table](https://user-images.githubusercontent.com/2989603/192017813-2dbc3a63-1ff8-407a-b995-bac5b005fbea.gif)

**Comment by Domino987** [comment]
WOuld you mind putting this in a sandbox for me to play iwth and figure it out?

**Comment by jbek7** [comment]
@Domino987 Here's a sandbox - https://codesandbox.io/s/material-table-starter-template-forked-sl9u9n?file=/src/index.js

**Comment by Domino987** [comment]
That's not possible since you give the parent html element display none. Not possible without hacking the html/css stack, which I think would result in quite complex interaction leading to bugs.

So this will not be supported, I am sorry
