### ISSUE TITLE
Split showFirstLastPageButtons to two options

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [material-table-core/core#621]
**Is your feature request related to a problem? Please describe.**
For cursor-based pagination, jumping to last page is not possible.

**Describe the solution you'd like**
Split `options.showFirstLastPageButtons` to `options.showFirstPageButton` and `options.showLastPageButton`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Domino987** [comment]
Can you show us a sandbox for this?
Possibly could be a boolean or object with first and last? Would you mind creating a PR for this?

**Comment by Domino987** [comment]
This is now possible for the next version: 0.2.42

Link: https://material-table-core.com/demos/pagination/basic/

**Comment by ClassicDarkChocolate** [comment]
Thanks! I am busy with work recently.
