### ISSUE TITLE
Table row not updating after updating a field value in a row

### ISSUE THREAD

**Issue by umeshajb** [material-table-core/core#627]
I am trying update a row in the table using a button with an onClick handler. I made sure the state is being updated correctly by creating a new array for the table data but I am not seeing the table update. However if I remove an element from the array the update works the second time I click the button. I am trying to figure out what am I doing wrong or if this is a bug. Here is an example of what I am trying to do: https://codesandbox.io/s/material-table-starter-template-forked-jodixk?file=/src/index.js

**Comment by Domino987** [comment]
You should never mutate state.

While you create a new array, the object is still mutated and we will skip the rerender for this row since its the same object.
https://codesandbox.io/s/material-table-starter-template-forked-82g5fn
