### ISSUE TITLE
Pagination localization labelDisplayedRows translation

### ISSUE THREAD

**Issue by shaliake** [material-table-core/core#630]
Translated value applies only in page navigation area

**To Reproduce**
1.Create localization object with translated values `tableLanguage={...}`
2. Pass it to component:
`<MaterialTable
                            title={"TITLE"}
                            columns={[]}
                            localization={tableLanguage}
                            data={[]}/>`
3. We can notice that translation is not applied in red area:
![image](https://user-images.githubusercontent.com/79657740/193450624-6c61f5ba-3525-4cce-af1f-dbadc0673cf7.png)

**Expected behavior**
Area marked in red should be with same text as green
**Desktop (please complete the following information):**

- OS: Win10
- Browser: Firefox
- Version 106.0b3

**Comment by Domino987** [comment]
Can you put this into a sandbox s owe can reproduce it and know which version you are using etc?
Can you check again?

**Comment by shaliake** [comment]
The [sandbox ](https://codesandbox.io/s/material-table-starter-template-forked-ccrnp0?file=/src/index.js)is in place.
My concrete dependencies from package.json:
````javascript  
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@fontsource/roboto": "^4.5.8",
    "@material-table/core": "^0.2.35",
    "@mui/icons-material": "^5.10.3",
    "@mui/material": "^5.10.4"
````
![image](https://user-images.githubusercontent.com/79657740/193813879-61a81c31-f22a-4317-827f-d882bb896cf5.png)
But snippet in codesandbox is a bit different:
![image](https://user-images.githubusercontent.com/79657740/193814229-a3b90007-c335-478f-b12a-fa2e743d365c.png)

Only one "x of y" section, somehow Rows per page is displayed, but not translated, in my local it's not even shown. Send help @Domino987 please open this issue again...
