### ISSUE TITLE
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function     at LocalizationStore.js:44:1

### ISSUE THREAD

**Issue by MojtabaDaneshi1366** [material-table-core/core#636]
Hello,

I got this error:
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function
    at LocalizationStore.js:44:1

My App was ok, but today is get this error.

@material-table/core@**next**

Sicnerely

**Comment by Domino987** [comment]
Can you reproduce this in a sandbox ?

**Comment by Domino987** [comment]
Duplicate of #586
