### ISSUE TITLE
Action iconProps not affecting icon itself

### ISSUE THREAD

**Issue by shaliake** [material-table-core/core#639]
- #### [Bug in codesandbox](https://codesandbox.io/s/material-table-starter-template-forked-u9utx7?file=/src/index.js)

iconProps object passed to action doesn't affect action icon displayed

**To Reproduce**

1.Create a table
2. Create a free action in table actions
3. Pass any object with legit props for Icon (style or official mui Icon Props API)
4. Inspect free action applied styles or any other behavior in browser inspect mode

**Expected behavior**
An free action should be affected iconProps?

**Screenshots**
![image](https://user-images.githubusercontent.com/79657740/194221274-ca134221-ae1f-4e06-8e1c-e1c316196fbd.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Edge, Firefox

**Comment by Domino987** [comment]
This is because you need write your own icon during which you drop the props yourself:

```
icon: (props) => <Save {...props} />,
```

You could also use the string `icon: 'save',`, which would work as well.

So its not a bug.
