### ISSUE TITLE
Exporting after grouping - missing data

### ISSUE THREAD

**Issue by andrei10k** [material-table-core/core#640]
https://github.com/mbrn/material-table/issues/2492 
this is still reproducing with the latest v5 version

basically if you export pdf/csv after grouping by a column the export is broken, no data is showing up.

**Comment by Domino987** [comment]
Would you mind creating a codesandbox using the next version?

**Comment by andrei10k** [comment]
sure: https://codesandbox.io/s/material-table-starter-template-forked-ouc14b?file=/src/index.js

just group by 'word' column and then export. the csv will have no data

**Comment by Domino987** [comment]
Are you using the next or normal branch? For now it will be fixed in the next "next" release.

**Comment by andrei10k** [comment]
@Domino987 i tried it with the next branch. it's not working. it's not showing grouped rows. this is how my table looks like:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/14038494/208980489-125fb080-3ae3-4357-afa7-92cce68b78ce.png">

and this is how the export looks like 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/14038494/208980629-8125fad7-6a87-4ee3-adbe-12429f6aa5c9.png">

it's exporting 4 rows indeed, like the number of groups. but we also need the rest of the data there...

**Comment by Domino987** [comment]
Can you create a new sandbox with the current version ?

**Comment by andrei10k** [comment]
will do. give me 10 minutes

**Comment by Domino987** [comment]
I won't be able to check tonight. But hopefully on Friday. Can you link me again if I miss it by Saturday?

**Comment by andrei10k** [comment]
sure thing, thanks

**Comment by andrei10k** [comment]
@Domino987 if you're still around, do you happen to know a way i can import material-table-core/core#next branch into codesandbox? it doesn't appear to work. i also tried stackblitz but to no avail :( i have no idea how i can give you a working example

**Comment by Domino987** [comment]
If you create a new issue and copy the link of the sandbox linking to v5 from the example text, that should work

**Comment by andrei10k** [comment]
@Domino987 thanks. actually ignore my last complain, it works just fine with one group by. the issue is it's not working when you have more than one. the export is blank. see the sandbox: https://codesandbox.io/s/material-table-starter-template-forked-ouc14b?file=/src/index.js. try to group by both number and word columns  and try to export.

 thank you!

**Comment by Domino987** [comment]
Can you describe what you are dragging where and click and what you expect the csv to look like?

**Comment by andrei10k** [comment]
hey, sure. so basically add word and singer as group by here: https://codesandbox.io/s/material-table-starter-template-forked-ouc14b?file=/src/index.js

the grouping works just fine, and the table looks like this:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/14038494/209436366-b0815055-96dd-433d-a10d-dfa7b5b4b9f7.png">

but when you export csv it's an empty file: 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/14038494/209436382-ed2d0216-8ab5-4c32-abb4-a0f65e7f0b3e.png">

i think the csv should also take into consideration multiple levels of grouping. so in our example above, it should first group by word (scissors, rock, paper) but then inside each one should also group by the second column, in this case singer. 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/14038494/209436532-99c1a4e0-c24b-4c45-8914-14170b113c4f.png">

e.g all the 'paper' rows should have the  Frank Sinatra rows first and then the Elvis Presley ones. 

and this should continue for all the columns you;re grouping by. if this is a lot, it should support at least 2 columns like in the example above. 

thanks

**Comment by Domino987** [comment]
Can you check the latest version? @andrei10k

**Comment by andrei10k** [comment]
@Domino987 sorry for my late reply. looks good!! thank you!
