### ISSUE TITLE
@material-table/core version 4.3.45 depends on MUI version 5

### ISSUE THREAD

**Issue by lmolteno** [material-table-core/core#643]
I'm just raising this as I'm not sure whether this is intentional or not, seeing as you appear to have branches explicitly for mui versions >=5.

As a project still running on mui v4, we now have to explicitly specify material-table/core version 4.3.44 in order to get it to build.

**Comment by Domino987** [comment]
Try the experimental branch v5 with many changes and fixes. Will be the the stable branch soon.
