### ISSUE TITLE
Use render function for components 

### ISSUE THREAD

**Issue by ckchiu2** [material-table-core/core#644]
I want to enable the following use case:

```
const MyComponent = () => {
    const [state, useState] = useState("");
    ...some state logic

    const renderToolbar = (props) => {
        ...some logic that consumes the state above
        return <MToolbar {...props} />
    }

    return (
        <MaterialTable
            ...
            components={{
                Toolbar: renderToolbar
            }}
        />
    )
}
```

Currently overridden components will always be remounted when the state changes because of reference inequality. 

Below is a simple demonstration of the current behaviour. Notice the behaviour when clicking on the checkbox.

https://codesandbox.io/s/material-table-starter-template-forked-nwshky?file=/src/index.js

A possible workaround is to pass the state using Context, but I think it would be kind of overkilling.

**Comment by Domino987** [comment]
This is actually a react problem because react needs a stable object reference to keep the state.

Nothing we can do about this on the lib level.

One workaround could be:

```
const MyToolbar = React.useCallback((props) => (
    <Box>
      <SomeComponent
        search={search}
        onSearchChange={(event, checked) => setSearch(checked)}
      />
      <MTableToolbar {...props} />
    </Box>
  ),[]);

```

**Comment by ckchiu2** [comment]
The search state comes from the parent component (i.e App) directly, so we need to add it in the dependency array. The sandbox should also warn you about this.

```
const MyToolbar = React.useCallback((props) => (
    <Box>
      <SomeComponent
        search={search}
        onSearchChange={(event, checked) => setSearch(checked)}
      />
      <MTableToolbar {...props} />
    </Box>
  ),[search]);
```

It seems working because I used wrong prop (value) for the <Checkbox /> component. I have updated the sandbox and you may try again.

**Comment by ckchiu2** [comment]
Haven't tried but I think following snippet can help support the use case.

```
const renderComponent = (component, props) => {
    if (typeof component === "function") {
        // just capitalize it to feel better
        const Component = component;
        return <Component {...props} />
    } else if (typeof component === "object") {
        if (typeof component.render === "function") {
            return component.render(props);
        }
    }

    throw new Error("Failed to render component!");
}
```

I can submit a PR if you want.

**Comment by Domino987** [comment]
I don't think that this would actually help keeping the state I think, because a new function is created anyway. Did you check this or have a sandbox to verify this?

**Comment by ckchiu2** [comment]
demo: https://codesandbox.io/s/young-fog-ks52n4?file=/src/App.js

Try updating both <InnerComponent /> state and update the parent to force a render. You can see that using the function method won't reset the inner state.

**Comment by Domino987** [comment]
Yes but you are fixing a problem that comes only from mismanaging the react tree and those associated states. Can you just use it as a normal external function?

**Comment by ckchiu2** [comment]
By further evaluation I agree that the components should be provided as stable components instead of functions that returns component. Additional information should be passed by either context or props, but it is another issue.
