### ISSUE TITLE
localization prop labelRowsPerPage not working

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#645]
**Describe the bug**
`labelRowsPerPage` does not seem to work anymore. It was working in 0.2.37.

**To Reproduce**

1. Go to [CodeSandbox MUI v5](https://codesandbox.io/s/material-table-starter-template-forked-163zk1?file=/src/index.js)
2. Edit `labelRowsPerPage`
3. No changes can be seen, it stays at `Rows per page:`

**Expected behavior**
`labelRowsPerPage` should update the rows per page label.

**Screenshots**
<img width="401" alt="Bildschirmfoto 2022-10-12 um 15 57 18" src="https://user-images.githubusercontent.com/39101755/195362660-968152ba-4065-4fb7-8fea-26a8dc98ea38.png">

**Desktop:**
- OS: macOS Monterey 12.5 
- Browser: Google Chrome
- Version: 105

**Comment by ertu68** [comment]
same problem man

**Comment by Domino987** [comment]
That is because it was renamed to `labelDisplayedRows` for the table pagination from mui: https://mui.com/material-ui/api/table-pagination/#main-content

I'll add a warning so that you can name them correctly.

**Comment by rjumatov** [comment]
Unfortunately `labelDisplayedRows` is not the same as `labelRowsPerPage`.

<img width="553" alt="Bildschirmfoto 2022-10-19 um 09 08 01" src="https://user-images.githubusercontent.com/39101755/196621124-383cfd59-1335-4874-894e-4399e3aee3f5.png">

Please reopen this issue.

**Comment by Domino987** [comment]
My bad, works now.

**Comment by rjumatov** [comment]
I am using `v0.2.51` and unfortunately the issue is still there.

**Comment by rjumatov** [comment]
@Domino987 any updates on this?

**Comment by Domino987** [comment]
Which version are you using?

**Comment by rjumatov** [comment]
`v0.2.51`

**Comment by Domino987** [comment]
Seems like a commit did not go through. can you check?

**Comment by rjumatov** [comment]
It is fixed now
