### ISSUE TITLE
renderSummaryRow callback is not working with remotedata 

### ISSUE THREAD

**Issue by vsn530** [material-table-core/core#649]
**Describe the bug**
https://material-table-core.com/demos/Summaryrow/basic/ 
the above example for showing summary row is not working if we set remotedata/ApI call for data prop 

in case of remote data , the data coming to callback is empty array . we dont have any data to do aggregation on column values

**Comment by Domino987** [comment]
Can you add a sandbox with your setup

**Comment by imbysho** [comment]
I have the same issue in a more complex project, here is a simple [sanbox](https://codesandbox.io/s/eloquent-leavitt-cwb5mr?file=/src/App.js) to a basic example.

I debug for a while and I think that the summary row dont wait for the remote data to render.

I really hope you can fix this. @Domino987 

Thanks!

**Comment by imbysho** [comment]
Hi, @Domino987 any update on this, I really need it 😞

**Comment by Domino987** [comment]
No not yet but you are welcome to open a PR to address this. I am not sure if I'll be able to fix this this week.

**Comment by Domino987** [comment]
Can you try the latest version?

**Comment by imbysho** [comment]
In the latest version it seems to be working fine. Thanks so much for your work @Domino987 😄
