### ISSUE TITLE
DetailPanel not working anymore

### ISSUE THREAD

**Issue by stefanvanderzanden** [material-table-core/core#65]
When adding a detailPanel to a Table, it tries to use a function that doesn't exist.

It happens in `core/src/components/MTableHeader/index.js` And the following function should be added (I think, I quickly tested it :) )
  
```
function renderDetailPanelColumnCell() {
    return (
      <TableCell
        padding="none"
        key="key-detail-panel-column"
        className={props.classes.header}
        style={{ ...props.headerStyle }}
      />
    );
  }
```

**Comment by stefanvanderzanden** [comment]
Nevermind ... See what I'm doing wrong :)

**Comment by oze4** [comment]
Can you provide a link to your fork?

**Comment by stefanvanderzanden** [comment]
Created pull request :)

**Comment by stefanvanderzanden** [comment]
Sorry, one final question, but do you need to make a new release for this?
