### ISSUE TITLE
exportAllData options prop being ignored. on next version 0.2.48

### ISSUE THREAD

**Issue by skearney414** [material-table-core/core#650]
**Describe the bug**
ExportAll is now being ignored on export and only data visible on the screen is exported. 

Previously on v0.2.35 exporting paginated data would export the entire dataset once exportAll was set to true on the options prop.

**Comment by Domino987** [comment]
Could you add a sandbox for this?

**Comment by Domino987** [comment]
Fixed with 0.2.51

**Comment by skearney414** [comment]
Thank you 🙏
