### ISSUE TITLE
Ref forwarding in MTableBody

### ISSUE THREAD

**Issue by josueuitzil** [material-table-core/core#651]
Hi devs, I have a question related to the refForwarding on the MTableBody component.

I see that https://github.com/material-table-core/core/pull/569 was merged some months ago to allow passing a ref to the component, however, the changes are not included in the latest release (5.1.6 at the time of writing). While the changes are in the master branch, they are not in the experimental.

Are there plans to include this in a future release? Or is there any way I could contribute to include this change in the future (like opening a pull request to the experimental branch)?

**Comment by Domino987** [comment]
Yes of course. I try to merge everything. But might have missed this with the merging. A PR would be  most welcome. Can also work towards your hacktober participation;)

**Comment by josueuitzil** [comment]
Thanks! I opened #661 to also include this change in the experimental branch
