### ISSUE TITLE
Column resize does not work

### ISSUE THREAD

**Issue by ogozman** [material-table-core/core#652]
Hello, it seems that columns do not become resizable when the option is set to true. Here is a sandbox with example
https://codesandbox.io/s/material-table-starter-template-forked-oqoq0q?file=/src/index.js
As you can see, the rendered table does not have resizable columns

**Comment by Domino987** [comment]
The tableLayout must be set to "fixed" for the columns to be static so they can be correctly resized.

Maybe we should add a warning.
