### ISSUE TITLE
(Bug) Localization for selected Rows not working

### ISSUE THREAD

**Issue by sairam0903** [material-table-core/core#660]
I have a table as below and I am on `@material-table/core: 0.2.52` version

```
<MaterialTable
      isLoading={loading}
      title=""
      columns={[
        {title: 'Track', field: 'track'},
        {title: 'Tier', field: 'tier'},
        {title: 'Architecture', field: 'architecture'},
        {title: 'Archtier', field: 'archtier'},
        {title: 'Lifecycle State', field: 'lifeCycleState'},
      ]}
      data={data}
      options={{
        selection: true,
        rowStyle: {
          fontSize: '14px'
        }
      }}
      localization={{
        toolbar: {
          nRowsSelected: '{0} application(s) selected'
        },
        body: {
          emptyDataSourceMessage: `No applications found with owner email ${selectedEmail}`
        }
      }}
      onSelectionChange={(rows) => onSelect(rows)}
    />
```

When I select all or individual row checkbox, I should see something like this below (Screenshot from using ([https://github.com/mbrn/material-table](https://github.com/mbrn/material-table))
![Screen Shot 2022-11-08 at 8 17 34 AM](https://user-images.githubusercontent.com/8981107/200618515-4054496a-1cce-4983-9a7f-aa9ab9417309.png)

But I am seeing nothing
![Screen Shot 2022-11-08 at 8 18 17 AM](https://user-images.githubusercontent.com/8981107/200618710-b4aa8029-9a7f-4296-859c-bfb82c85df11.png)

am I missing any options here?

My dependencies in package.json

```
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@material-table/core": "^0.2.52",
    "@mui/icons-material": "^5.10.6",
    "@mui/lab": "^5.0.0-alpha.100",
    "@mui/material": "^5.10.6",
    "axios": "^0.27.2",
    "filefy": "^0.1.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-google-charts": "^4.0.0",
    "react-router-dom": "^6.4.0",
    "react-scripts": "^5.0.1",
    "sass": "^1.54.9"
  }
```

**Comment by sairam0903** [comment]
@DominikEngel  can you help with this issue?

**Comment by Domino987** [comment]
Hi ill look into it, was away for two weeks and now I am back.

**Comment by Domino987** [comment]
Will be fixed in next verison

**Comment by sairam0903** [comment]
Thanks for taking care of it. When can I expect this to be released?

**Comment by Domino987** [comment]
Roughly 1.5h ago ;)
