### ISSUE TITLE
Suggest promoting off of fork

### ISSUE THREAD

**Issue by webark** [material-table-core/core#665]
A large downside of this being a fork is that you cannot perform a code search on the repository. With its continued api changes that are progressing past the former upstream material table, it makes sense for this to no longer be a fork.

I do not expect this to ever get merged back into material table either.

Homage can still be payed in the readme to the work and dedication they provided in the original package.

**Comment by Domino987** [comment]
Do you have an example on how to remove the fork itself?

**Comment by webark** [comment]
No. I could look around. I've never tried before.

**Comment by Domino987** [comment]
That would be most appreciated

**Comment by webark** [comment]
I'd give this a try sometime. https://support.github.com/request/fork?tags=rr-forks

Seems like some people have had quick success with the chat bot.

**Comment by Domino987** [comment]
Done. Thank you

**Comment by webark** [comment]
thanks!!
