### ISSUE TITLE
localization prop labelRowsSelect not working

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#668]
**Describe the bug**
`labelRowsSelect` does not seem to work since `v0.2.53` anymore. It was working in `v0.2.52`.

**To Reproduce**

1. Go to [CodeSandbox MUI v5](https://codesandbox.io/s/material-table-starter-template-forked-sk78ry?file=/src/index.js)
2. Edit `labelRowsSelect`
3. No changes can be seen, it stays at `rows`

**Expected behavior**
`labelRowsSelect` should update the rows select label.

**Screenshots**
<img width="244" alt="Bildschirmfoto 2022-11-14 um 10 09 23" src="https://user-images.githubusercontent.com/39101755/201620099-6713a096-10f4-4a46-9526-1b30e1deb819.png">

**Desktop:**
- OS: macOS Monterey 12.5 
- Browser: Google Chrome 107
- Version: 0.2.53

**Comment by Domino987** [comment]
Yes I am still working on the release notes. A legacy naming bug was introduced a while back. Can you look into the typescript types to get the new naming for the rows to align it with the correct naming ? It's just that the key changed

**Comment by rjumatov** [comment]
I am currently unable to make any adjustments since I am very busy with work.
I would recommend fixing the types before releasing further versions.

**Comment by Domino987** [comment]
No I mean the types are correct so you can just check those.

**Comment by rjumatov** [comment]
Unfortunately this problem still occurs in v0.2.62 and v6.1.6,
v0.2.52 does not have the issue.

**Comment by rjumatov** [comment]
Why is this issue closed? It still occurs in the latest versions

**Comment by Domino987** [comment]
Because it was simply renamed as written in the release docs as well it's in the typescript files. So check those for the name and adapt your code.

**Comment by rjumatov** [comment]
`labelRowsSelect` is now `labelRows`, thanks
