### ISSUE TITLE
Ability to exclude some data fields from search

### ISSUE THREAD

**Issue by LifeIsStrange** [material-table-core/core#669]
My need is very basic and important, the searchbar by default do a fuzzy search on all data fields, which is good.
However I am not aware of any way to exclude search from some data keys.

for example when I search a number (e.g. 50) on my rows labels, it shows me many rows that are irrelevant and of which the label does not containt "50".
They are shown because some data.id do contains 50, which is irrelevant to the end user.
So I would like to be able to specify a blacklist of keys to ignore in data during search.

@Domino987 Friendly ping, btw this issue matters more to me than https://github.com/material-table-core/core/discussions/659
Without this feature, on many datasets, the local search is basically broken..

**Comment by Domino987** [comment]
The easisest way woudl be to orveride the customFilterAndSearch prop for a column and always return false for that column

Link: https://codesandbox.io/s/material-table-starter-template-forked-nulzj3?file=/src/index.js

**Comment by LifeIsStrange** [comment]
Excellent! That looks really simple :)
I can't seem to find documentation about this prop though https://material-table-core.com/demos/search/basic but anyway your given example is sufficent for my need !

**Comment by LifeIsStrange** [comment]
edit:
it seems removing the prop 'field' from the column make it non-searchable too. Does the field props has other uses/consequences than allowing search? @Domino987

**Comment by Domino987** [comment]
Yes it is the basic for all interaction with the column. Display, search Filter etc. You should not see anything in the column without actually.

**Comment by LifeIsStrange** [comment]
Field is not necessary to display the cell, as I use the render prop.
Thanks for your help :)
Again I think the documentation could be improved.
