### ISSUE TITLE
Sorting undefined/null data 

### ISSUE THREAD

**Issue by Diiegoav** [material-table-core/core#673]
# Guidelines

## Demo sandbox
- https://codesandbox.io/s/material-table-starter-template-forked-g38sv9?file=/src/index.js

**Is your feature request related to a problem? Please describe.**
Hi, I would like if we can enhance the sorting of material table, when related to `undefined/null` values. currently as shown on the code sandbox above, when you have undefined/null values, depending on the order direction sort, sometimes are shown on top, which does not make to much sense, I think they should be always at last.

**Describe the solution you'd like**
Undefined null values should be sorted always at last of the data.

**Comment by Domino987** [comment]
Merged, thank you!

**Comment by Diiegoav** [comment]
@Domino987  based on https://mui.com/x/react-data-grid/ I think could be good idea to replicate their behavior, when ASC empty fields can be updated on top, DESC at last.

Any thoughts ?
