### ISSUE TITLE
MTableBodyRow props being passed through to the DOM

### ISSUE THREAD

**Issue by ewanmellor** [material-table-core/core#677]
**Describe the bug**

`MTableBodyRow` on the `next` branch (0.2.53) is passing its `columns` and `options` props through to MUI's `TableRow`, which then passes them to the `<tr>` elements in the DOM.

https://codesandbox.io/s/material-table-mtablebodyrow-props-bug-rdpid3

<img width="1004" alt="Screen Shot 2022-11-18 at 12 52 56 PM" src="https://user-images.githubusercontent.com/894011/202800489-31dc1e97-5184-43f4-858a-12eb8364cb1b.png">

This comes from the following changeset:

```
commit cee0e0f1fafa3e8208e9051b6f8d3039c1de4372
Author: Domino987 <domino987@gmail.com>
Date:   Sat May 14 10:40:59 2022 +0200

   add zustand

diff --git a/src/components/MTableBodyRow/index.js b/src/components/MTableBodyRow/index.js
index 70f30604..4f2ea389 100644
--- a/src/components/MTableBodyRow/index.js
+++ b/src/components/MTableBodyRow/index.js
@@ -13,12 +13,14 @@ import { MTableDetailPanel } from '@components/m-table-detailpanel';
 import * as CommonValues from '@utils/common-values';
 import { useDoubleClick } from '@utils/hooks/useDoubleClick';
 import { MTableCustomIcon } from '@components';
+import { useLocalizationStore, useOptionStore, useIconStore } from '@store';

 export default function MTableBodyRow(props) {
+  const localization = useLocalizationStore().body;
+  const options = useOptionStore();
+  const icons = useIconStore();
   const {
-    icons,
     data,
-    columns,
     components,
     detailPanel,
     getFieldValue,
@@ -28,11 +30,9 @@ export default function MTableBodyRow(props) {
     onToggleDetailPanel,
     onEditingCanceled,
     onEditingApproved,
-    options,
     hasAnyEditingRow,
     treeDataMaxLevel,
     path,
-    localization,
     actions,
     errorState,
     cellEditable,
@@ -44,6 +44,7 @@ export default function MTableBodyRow(props) {
     onRowDoubleClick,
     ...rowProps
   } = props;
+  const columns = props.columns.filter((columnDef) => !columnDef.hidden);

   const onClick = (event, callback) =>
     callback(event, data, (panelIndex) => {
```

Removing `columns` and `options` from the spread means that they get into `rowProps` instead, which is why they now get passed to `TableRow`.

As an extra wrinkle: the changeset above removed `icons` and `options` from `MTableBodyRow.propTypes` and removed them from the callsite in `m-table-body.js`, but the following merge changeset put the `options` prop back at the callsite (which is why we get `options` in the DOM even though `MTableBodyRow.propTypes` doesn't have that).  This looks like a mis-merge to me.

```
commit 518f25574ecf5b199fe56c520781e7a13106861a (from b7b4a9f587c40291e4795c8f9b45acad5ee33530)
Merge: b7b4a9f5 6d6a3500
Author: Domino987 <domino987@gmail.com>
Date:   Sun Oct 2 13:00:26 2022 +0200

    Merge branch 'experimental' into next
```

Also, I noticed that the `EditRow` and `FilterRow` callsites have an `icons` prop, and the `GroupRow` callsite is passing `icons` and `options`.  I don't know if there's a good reason for the different types of rows to have some parameters through the store and some through props.  It seems confusing to me, but I don't understand the code well enough to know.

**Comment by Domino987** [comment]
Yes, this seems like a merge error. Will be fixed in the next release. Thank you
