### ISSUE TITLE
Spacer icon appears as 'div'

### ISSUE THREAD

**Issue by ewanmellor** [material-table-core/core#678]
In the following changeset on the `next` branch (0.2.53), a spacer icon was added to line some columns up:

```
commit 1a926fb3b3627166d2c264a8acf691d56a8fb876
Author: Domino987 <domino987@gmail.com>
Date:   Fri Sep 23 13:50:34 2022 +0200

    fix for action columns display

diff --git a/src/material-table.js b/src/material-table.js
index b55c8403..7ce567fd 100644
--- a/src/material-table.js
+++ b/src/material-table.js
@@ -419,6 +419,19 @@ export default class MaterialTable extends React.Component
{
           }
         });
       }
+      // If only bulk update and add row are used, the columns do not align wit
h the action column, because no action column is present for the add
+      if (
+        this.state?.showAddRow &&
+        calculatedProps.editable.onRowAdd &&
+        calculatedProps.actions.filter((action) => action.position === 'row')
+          .length === 0
+      ) {
+        calculatedProps.actions.push({
+          icon: 'div',
+          position: 'row',
+          onClick: () => {}
+        });
+      }
     }

     return calculatedProps;
```

This use of `icon: 'div'` is bogus, and it results in 'div' being added to the page as text.

The string here is passed to MUI's `Icon` by `MTableAction`, so it is a font icon name, not a component name.  When I do not have an icon font in my build, I see 'div' in the page directly. When I add a stylesheet from https://fonts.googleapis.com/icon?family=Material+Icons, I see 'div' flash and then fade to blank (presumably there's no matching icon for `div` and so it replaces it with a blank icon).

Using this as a spacer is a bit nasty anyway: it results in a blank button that you can click and see the MUI ripple effect even though it doesn't do anything.  The code in MTableAction is already handling the difference between strings and components for the icon, so maybe we could add special-case handling for a spacer here?

Also, `disabled: true` would be better than `onClick: () => {}`.

/cc @domino987

**Comment by Domino987** [comment]
agreed and will be fixed with the next release. Thank you
