### ISSUE TITLE
Global checkbox issue with parentChildData

### ISSUE THREAD

**Issue by nathanm960** [material-table-core/core#679]
Hello,

It seems to have a new issue with this [fix](https://github.com/material-table-core/core/issues/606) (it appear in 5.1.1). The issue is also in 0.2.54

I updated the codesandbox : https://codesandbox.io/s/material-table-starter-template-forked-woh93u?file=/src/index.js

**How reproduce**

Go on the sandbox and click on the global checkbox

Every row are selected but not the global checkbox

The global checkbox is not clickable anymore  

\
The issue appear when there is at least one parentId in data

**What is expected**

The global checkbox should be selected and clickable

**Comment by Domino987** [comment]
Fixed with the next version
