### ISSUE TITLE
headerStyle not applied

### ISSUE THREAD

**Issue by nathanm960** [material-table-core/core#680]
Hello,

My headerStyle is not applied. I have a codesandbox here : https://codesandbox.io/s/material-table-starter-template-v5-forked-0d1c6w

**How reproduce**

Simply go on the codesandbox and watch :)

The first cell of the header is not colored in blue

**What is expected**

The backgroundColor property in headerStyle should be applied on every cell of the header

This issue appear in v0.2.38

**Comment by Domino987** [comment]
![image](https://user-images.githubusercontent.com/17567991/208136268-c0d05086-3b70-4b89-a562-eb30e0c84a0e.png)
 You mean this like white square, right?

**Comment by nathanm960** [comment]
Yes

**Comment by Domino987** [comment]
Fixed with the latest release
