### ISSUE TITLE
Clicking a column in multisort should make that column the first in the sort order

### ISSUE THREAD

**Issue by ewanmellor** [material-table-core/core#682]
**Describe the bug**

On a table using multiple sorted columns, if you click the column that is currently not first in the sort order, that column should move to the first position, and all the other columns should move down the order.

With the current behavior, when the user clicks the second-sorted column, it reverses order but the other column is still in first position, so the table doesn't actually sort by the column the user clicked on.  This is very confusing and feels broken, especially with `showColumnSortOrder: false`.

**To Reproduce**

https://codesandbox.io/s/material-table-multi-column-sort-tqu8gu?file=/src/index.js

In the demo above:
1. Click the "Id" header.  Note that the table isn't sorted by the ID, which feels totally broken.
2. Click the "Other word" header.  This moves it to position 2 in the sort order, so now the table is sorted by Word followed by Other word, which again looks broken.
3. Change `showColumnSortOrder: true` so you can see what's going on.  Note that with three columns, it's possible to rearrange the column sort order by clicking on an unsorted column.  This is the only way to get columns up the sort order.

**Expected behavior**

In the demo above:
1. Click the "Id" header.  This would change the column sort order to `[Id, Word]` (Word moves from 1 to 2 and Id moves to position 1.)
2. Click the "Other word" header.  This would change the sort order to `[Other word, Id]` (Other word moves to position 1, Id moves down to position 2, and Word is dropped because `maxColumnSort: 2` is set in the options.

/cc @Diiegoav

**Comment by kushpathak** [comment]
Hi I would like to work on this! could you assign this to me? thanks!

**Comment by ewanmellor** [comment]
@kushpathak Thank you!
