### ISSUE TITLE
Multiselect is not working with tree data by clicking on select all checkbox

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#683]
I am using latest @material-table/core version of 4.12.4
Looks like select all is broken for TreeData view
Issue is also reproducible in latest document [here](https://material-table-core.com/demos/tree-data/basic)
I have also created a sandbox as below
  - #### [Material-table-treeData](https://codesandbox.io/s/youthful-bhaskara-nb2gkm?file=/src/App.js)

**Describe the bug**
Try to click on select all checkbox, all the rows gets selected but select all checkbox stays unselected
Now click again on select all checkbox and nothing happens all rows stays selected

**To Reproduce**
Just open the sandbox

**Expected behavior**
Select all checkbox should be able to toggle all rows selection

**Screenshots**
![image](https://user-images.githubusercontent.com/25742857/203767043-5dc211ae-e133-4ebc-bb88-607e4b479706.png)

**Comment by ccrsxx** [comment]
Is there any update on this?

**Comment by pratik-nagpure** [comment]
No update yet.

**Comment by Domino987** [comment]
Will be fixed with the next release
