### ISSUE TITLE
Making "Actions" and Other Columns Sticky

### ISSUE THREAD

**Issue by cbthompson1** [material-table-core/core#686]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
https://codesandbox.io/s/material-table-starter-template-forked-huuu34?file=/src/index.js

- #### Please try to be as detailed as possible
I would like to have both the actions column and a regular data column fixed to the left such that when I scroll I can see both unobstructed. I have tried using `fixedColumns` and also manually fixing elements into place. These are the problems I've run into:
- Using `fixedColumns` changes the width of the columns to be an undesired value that causes folding in the table because it causes the widths to become "fixed" (to see this, remove `fixedColumns` from the first table).  In [the code](https://github.com/material-table-core/core/blob/348d52c19faf2c3c85718938636ecc57cff5615f/src/material-table.js#L1010), it doesn't look like there is a way to override this determination? Ideally `tableLayout` could still be auto, I think that might fix the issue but I'm unsure.

- I've also tried fixing items manually into place. I can get everything into place that I would like with the sole exception of the actions header. I don't see a way in the table header file to change _only_ the style of the actions header cell. ([relevant code](https://github.com/material-table-core/core/blob/348d52c19faf2c3c85718938636ecc57cff5615f/src/components/MTableHeader/index.js#L145))

I've been stuck on this for a few days but I don't think it's because there is functionality missing in material-table, I think I just don't know how I should effectively be using it. Any help would be amazing. Thanks! :)

**Comment by cbthompson1** [comment]
@Domino987 it looks like you're pretty active in this project, do you know what I can do in this situation?

**Comment by peleyal** [comment]
Any update on this one?
It seems like a feature that should be supported\fixed... Right?

**Comment by Domino987** [comment]
Hi, yes I am the maintainer. I had no time to look into it, but I am also not happy with the current sticky setup. SO this would probably go hand in hand with rewriting the sticky code and fix this in combination. I am more than open for PRs though
