### ISSUE TITLE
Sandbox fails to compile with mui5 using the latest @material-table/core version

### ISSUE THREAD

**Issue by ckchiu2** [material-table-core/core#689]
**Describe the bug**

sandbox: https://codesandbox.io/s/material-table-starter-template-forked-p6yrde?file=/src/index.js
Just found out that `store/LocalizationStore.js` is still referencing the library `fast-deep-equal` which is removed in package.json. Don't know why it can still compile though.

**Additional context**

https://github.com/material-table-core/core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
sandbox for mui4 and mui5 are pointing to the same sandbox

**Comment by Domino987** [comment]
Can you create a PR to adress this?
