### ISSUE TITLE
[next] Implement or allow drag&drop for row reordering

### ISSUE THREAD

**Issue by Phygon** [material-table-core/core#695]
I would like to be able to reorder data rows via drag & drop, for example using react-beautiful-dnd.

In a previous version of the next branch (0.2.20), I could extend the TableBody class and inject the neccessary placeholder <div>s from react-beautiful-dnd. But with the rewrite from class-based to function components, this is not possible anymore.

I would suggest to add an API to inject the placeholders and styles to the table components to make it possible for client code to implement d&d, or alternatively, to support row reordering natively.

**Comment by Phygon** [comment]
Here is an example of a d&d-able table with the older version of the next branch:

https://codesandbox.io/s/material-table-drag-drop-on83oj

**Comment by ckchiu2** [comment]
I created the PR #569 (and also merged in #661) for the exact purpose.

Although you cannot inject the placeholder in the _same_ table body, you can create another one and put it in.

Demo: https://codesandbox.io/s/material-table-drag-drop-forked-ncq5y9?file=/src/TableComponents.js

**Comment by Phygon** [comment]
Thanks!
I didn't know you could just have another <TableBody> in there.

Would you consider adding something like this to the core, or do you think it's a niche use case?

**Comment by ckchiu2** [comment]
It is more like a workaround because all material-table components are self contained.
