### ISSUE TITLE
ExportAllData not working

### ISSUE THREAD

**Issue by Snowblaze** [material-table-core/core#697]
So exportAllData option doesn't work as stated in the title.
After looking for the problem, found that the issue is fixed in 0.2.51, but the solution still isn't released. Any ETA for the release?

**Comment by Domino987** [comment]
We are currently on 0.2.57, so what you mean?

**Comment by Snowblaze** [comment]
Well, that's "next" version, right? Shouldn't this be released as a hotfix for 5.x?

**Comment by Domino987** [comment]
0.2.57 will be merged to 5.x soon and this will be fixed then.
