### ISSUE TITLE
Specifying a render method in for the detail panel breaks the table in starting in v2.3.5. [codesandbox]

### ISSUE THREAD

**Issue by ishake** [material-table-core/core#70]
Hi, all. Thanks for your work on this!

I found another one. The issue appears to have been introduced in v2.3.5. Here's the [CodeSandbox](https://codesandbox.io/s/material-table-broken-details-panel-0c37j) . If you switch between v2.3.4 and v2.3.5 it goes away and appears again.

**Description**
Specifying a render method in for the detail panel breaks the table in the latest version.

The error message shown is:
ReferenceError
renderDetailPanelColumnCell is not defined

**To Reproduce**
See [CodeSandbox](https://codesandbox.io/s/material-table-broken-details-panel-0c37j). It appears right away.

Or if you add this to any table it looks like you'll see it:

`detailPanel={[
          {
            render: (rowData) => <span>bob</span>
          }
        ]}`

**Desktop:**

- OS: macOS
- Browser chrome
- Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by matthewoestreich** [comment]
Ah yeah that's my bad. I fixed this, then had to revert for a different issue and must have overrode my changes. I think this is the issue I'm thinking of, bit could be wrong. 

I should be able to take a look at this in about 2 hours. Apologies.

**Comment by ishake** [comment]
Perfect! Thanks for the fast response!

**Comment by matthewoestreich** [comment]
This is resolved in 2.3.7!

Updated Sandbox:

[![Edit material-table-broken-details-panel (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-broken-details-panel-forked-gnhf0?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matthewoestreich** [comment]
Hey @ishake I'm going to close this out for now. Please let us know if you're still having issues.

Thanks again!

**Comment by pbr0ck3r** [comment]
I was getting this issue after upgrading to 2.3.7 when I built my code for production and it was live, but running locally it ran just fine did not show any errors. Code was the follwing:
```
const details = (rowData) => {
     <span>bob</span>
}
<MaterialTable
        columns={columns}
        data={data}
        title=""
        detailPanel={details}
        options={options}
        onRowClick={(event, rowData, togglePanel) => {
          togglePanel(rowData.tableData.id);
        }}
      />
```

Once I added the `render` in the detailPanel it worked just fine before build and after. Would be nice to throw a error if you are forgetting to pass in `render`. Code after looked like this:

```
<MaterialTable
        columns={columns}
        data={data}
        title=""
        detailPanel={[{ render: details }]}
        options={options}
        onRowClick={(event, rowData, togglePanel) => {
          togglePanel(rowData.tableData.id);
        }}
      />
```

**Comment by matthewoestreich** [comment]
Hey @pbr0ck3r thank you VERY much for this. I will look into this.

**Comment by pbr0ck3r** [comment]
Also I was on 2.3.4 when I originally saw this issue.

**Comment by matthewoestreich** [comment]
It doesn't appear to be an issue in the newest version (2.3.7). Would you mind giving it a shot? @pbr0ck3r

**Comment by pbr0ck3r** [comment]
I am on 2.3.7 and if I do not include `render` in the detailPanel (i.e. `detailPanel={[{ render: details }]}`) it breaks.

**Comment by pbr0ck3r** [comment]
```
const details = (rowData) => {
     <span>bob</span>
}
```
My original examples with `detailPanel={details}` with details being declared above does not work.

**Comment by matthewoestreich** [comment]
I'm not seeing the same behavior?

[![Edit recursing-heyrovsky-wxz26](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-heyrovsky-wxz26?fontsize=14&hidenavigation=1&theme=dark)

**Comment by pbr0ck3r** [comment]
Looking at your example yes, that is how I had it previously. Possible it could have been a cache issue in the browser. I will test again tomorrow as this is production code and things are working as is right now with `detailPanel={[{ render: details }]})`

**Comment by matthewoestreich** [comment]
@pbr0ck3r 

Ok sounds good.

I was going to say your bob example and my example are the exact same, but I actually think I just spotted the issue...

```js
// This is wrong
const details = (rowData) => {
     <span>bob</span>
} 

// Should be this....
const details = (rowData) => {
     return <span>bob</span>
} 
// ....or this....
const details = (rowData) => {
     return (
        <span>bob</span>
    );
} 
// ....or this...
const details = (rowData) => (
     <span>bob</span>
)
// ...or this...
const details = (rowData) => <span>bob</span>
// ...or this... (same as above just on a diff line)
const details = (rowData) => 
    <span>bob</span>
// ...or this...
function details(rowData) {
     return <span>bob</span> // or with return ( ... )
}
```

**Comment by pbr0ck3r** [comment]
Yeah, in my production code I do have a return... that is my fault for not sharing that.

**Comment by pbr0ck3r** [comment]
```
const details = (rowData) => {
    return ( 
        <span>bob</span>
   );
}

**Comment by matthewoestreich** [comment]
ok cool - just making sure!

Let us know if 2.3.7 fixes it for you. Sorry about the issues!

**Comment by pbr0ck3r** [comment]
Ran, in locally in a docker image and verify that 2.3.7 does fix the issue.

**Comment by pbr0ck3r** [comment]
Sorry for the extra work on your end. Appreciate the quick testing on your side and also quick responses. Appreciate the work you all do!

**Comment by matthewoestreich** [comment]
No worries mate!
