### ISSUE TITLE
Unexpected behavior with TotalCount and page properties

### ISSUE THREAD

**Issue by 0xRelu** [material-table-core/core#703]
# Description
While working on my project, I noticed that TotalCount no longer does what it did before. So the passed value at TotalCount is not displayed in the table below. However, I am not sure if there is a problem with my dependencies and thus it is with my implementation or it is a bug.

# Steps to reproduce the behavior:

1. Import newest version of the table
2. Add totalCount and page

# Sandbox
Earlier version (Material-Table) - with expected behavior: https://codesandbox.io/s/material-table-starter-template-forked-742pq0?file=/src/index.js
Latest version (Meterial-Table/core) - with unexpected behavior: https://codesandbox.io/s/material-table-starter-template-forked-no9dr6?file=/src/index.js

If the behavior is wanted, I would like to know how to change totalCount now.

**Comment by Domino987** [comment]
Seems like the css keys changed. Will be fixed with the next version

**Comment by 0xRelu** [comment]
Thank you^^
