### ISSUE TITLE
onRowsPerPageChange callback triggers onPageChange

### ISSUE THREAD

**Issue by dcaudillo99** [material-table-core/core#706]
Hi team, I have a question about the behavior when the number of rows per page changes. I noticed when I move to another page and then change the number of rows per page, first the `onPageChange` callback triggers, returning the value of the first page. You can test this behavior in the following sandbox: https://codesandbox.io/s/material-table-starter-template-forked-wfhwi0?file=/src/index.js

Currently, I'm using v5.1.6, but I've already tried with some of the previous versions and it seems this behavior has been there for a while now. Is there any reason/purpose for calling the `onPageChange` and returning the value of the first page (0) when the `onChangeRowsPerPage` is called?

**Comment by ckchiu2** [comment]
I am not the author, but I can give you a few possible reasons:
1. You don't know which page to start with (current page? a page that keep the current record at top? a page that contains the top record and fits in the restriction page * number of rows?)
2. What if the page range falls outside the record count?

**Comment by dcaudillo99** [comment]
So, Is there no way to avoid `onPageChange` being called when I try to set a different number of rows per page?

**Comment by ckchiu2** [comment]
The logic is embedded within `onRowsPerPageChange` [here](https://github.com/material-table-core/core/blob/master/src/material-table.js#L542), so no.
