### ISSUE TITLE
Summary row doesn't keep position when ordering or sorting columns

### ISSUE THREAD

**Issue by andrei10k** [material-table-core/core#707]
https://codesandbox.io/s/material-table-starter-template-forked-1x2gni?file=/src/index.js 

The summary row should be below the id column. try changing columns between themselves or order by word column. the summary will appear below the 'word' column. it should always be beneath the 'id' column

**Comment by Domino987** [comment]
Will be fixed with the next release ty

**Comment by andrei10k** [comment]
@Domino987 thank you! On what branch? I was using the next branch since it has export with ordering fixed

**Comment by Domino987** [comment]
The next one

**Comment by andrei10k** [comment]
this is fixed only for sorting columns but not for when you group by.

https://codesandbox.io/s/material-table-starter-template-forked-wn22r0?file=/src/index.js

to reproduce, group by the 'word' column. the summary row will be displayed beneath the name column which is incorrect

<img width="662" alt="image" src="https://user-images.githubusercontent.com/14038494/210048937-5dfa47df-deff-4be6-94a5-da6fbdee4311.png">
