### ISSUE TITLE
Using render for a column breaks the column label after you order by it

### ISSUE THREAD

**Issue by andrei10k** [material-table-core/core#710]
https://codesandbox.io/s/material-table-starter-template-forked-7nk0y1?file=/src/index.js

to reproduce, group by the 'word' column. the label disappears like in the screenshot below

<img width="667" alt="image" src="https://user-images.githubusercontent.com/14038494/210005913-5640d7f6-a987-44fb-88d7-96f704802495.png">

**Comment by Domino987** [comment]
Actually no, there are 2 cases for the grouping of column render:

```
render?:
    | ((data: RowData, type: 'row') => React.ReactNode) // The normal render of the table cell
    | ((data: string, type: 'group') => React.ReactNode); // The render for the group wording
```
You have to differentiate between those to render the text correctly.

**Comment by andrei10k** [comment]
ahhh, right, thanks a lot!
