### ISSUE TITLE
Sorting issue: null records are getting sorted

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#712]
# Guidelines

- #### On the latest material-table/core  version 6.0.3
- #### Sorting is not working as expected
- #### I have added a sandbox link below to reproduce this issue
 - #### [CodeSandbox](https://codesandbox.io/s/small-resonance-y4bvyg?file=/src/App.js)

**Describe the bug**
Open the sandbox and try to sort the "desc2" column and observe that rows are getting sorted. 
If a column has similar data or null data, rows should not get sorted.
There is one catch though. Let's say if I provide data in reverse order as below, where now the first row dbKey value is less than the second one. it works

`[
          {
            dbKey: 1,
            name: "Thornhill",
            dbstatus: 1,
            company: "a",
            desc1: "Test_Store",
            desc2: null,
            desc3: null,
            desc4: null,
            value1: null,
            storeNumber: 8490
          },
          {
            dbKey: 298,
            name: "Thornhill",
            dbstatus: 1,
            company: "b",
            desc1: "Test_Store",
            desc2: null,
            desc3: null,
            desc4: null,
            value1: null,
            storeNumber: 7790
          }
        ]`

**To Reproduce**

1. Go to [CodeSandbox](https://codesandbox.io/s/small-resonance-y4bvyg?file=/src/App.js)
2. Click on  desc2 column
4. See rows getting sorted

**Expected behavior**
Rows should not sort if columns data is null

**Comment by Domino987** [comment]
Fixed with 6.1.3
