### ISSUE TITLE
Render function (member of column) is broken in v6.1.3

### ISSUE THREAD

**Issue by andrei10k** [material-table-core/core#716]
In the latest version the table does not take into consideration the render function. when the data is an object and you want to transform it using render, you always get the error: Objects are not valid as a React child (found: object with keys). If you meant to render a collection of children, use an array instead. Also I tried to debug it but apparently is not being called any more. See sandbox below 

https://codesandbox.io/s/material-table-starter-template-forked-yfqjgx?file=/src/index.js

**Comment by Domino987** [comment]
Yes, i had a typo, fixed in the next version. Sry, still missing the typescript support here xD
