### ISSUE TITLE
parentChildData and selection issue #2

### ISSUE THREAD

**Issue by nathanm960** [material-table-core/core#717]
Hello,

With the new versions this issue is back : https://github.com/material-table-core/core/issues/606

I made this sandbox with the latest version of material-table/core : https://codesandbox.io/s/material-table-starter-template-v5-forked-0d1c6w

**Comment by Domino987** [comment]
Yes there are a few things that work against each other here due to the old code written by the original writer. Can you check the latest version?

**Comment by nathanm960** [comment]
I tried with v6.1.8 on codesandbox, I have this result :
![image](https://user-images.githubusercontent.com/28100281/212026741-4a2ea6d8-1168-492b-8e0a-8b22364a6183.png)

**Comment by Domino987** [comment]
Ok I added some tests and the next version should work I hope.
