### ISSUE TITLE
Dragging columns to new positions doesn't work if there are hidden columns

### ISSUE THREAD

**Issue by sjdemartini** [material-table-core/core#718]
### Describe the bug
If a MaterialTable has hidden columns within the list of column headers (e.g. [visible, hidden, visible]), dragging the column headers to new positions does not seem to work as expected most of the time, with columns seeming to end up "randomly" positioned after dropping them.

### To Reproduce

1. View this Code Sandbox https://codesandbox.io/s/material-table-starter-template-forked-ho9o8u?file=/src/index.js
2. Take note of the current column positions: [Score, Surname, Age]
3. Click and drag the "Surname" column from the second position to the first (to try to make it come first in the header)
4. Notice that the columns are now in a new unexpected order: [Age, Score, Surname]

You'll also notice in the console there's this warning as soon as you start to drag, which may be indicative of the problem:

```
@hello-pangea/dnd

Detected non-consecutive <Draggable /> indexes.

(This can cause unexpected bugs)

0, [🔥2], 3
```

**More general instructions to reproduce**:

1. Create a MaterialTable that includes at least one hidden column in the middle of the `columns` array
2. Click and drag a column header to a new position
3. Observe that the column doesn't land where you dropped it, and all columns seem to be "randomly" reordered.

### Expected behavior

Dragging columns to new positions should work based on which columns are currently visible, just like for tables where all columns are visible.

**Comment by Domino987** [comment]
Should be fixed with the next release
