### ISSUE TITLE
Unnecessary console log

### ISSUE THREAD

**Issue by arulprabhin** [material-table-core/core#719]
![image](https://user-images.githubusercontent.com/93645929/211805509-249da3c5-6902-4924-bb08-e5cc3ecf4e1f.png)
This above code block is causing this
![image](https://user-images.githubusercontent.com/93645929/211805693-83e4d18b-bed9-4caf-ae4b-3dcda81942f0.png)
Checked on both v6.1.6 and v6.1.7

**Comment by Domino987** [comment]
Yes I saw it and it will be removed with the next release
