### ISSUE TITLE
Issues with parent selection

### ISSUE THREAD

**Issue by nathanm960** [material-table-core/core#723]
Hi,

It's me again :)

I updated the codesandbox with 6.1.10 https://codesandbox.io/s/material-table-starter-template-v5-forked-0d1c6w

If you type "test" in the search bar and then you try to select all :
![image](https://user-images.githubusercontent.com/28100281/212643595-050a659f-0a3e-46cb-9f57-484d1bc7db1a.png)

**What is expected**

The parent checkbox should be selected too

**Comment by Domino987** [comment]
Hi, yes while looking into it I was wondering the same.
What is here the expected behavior, since 1 was not searched, should it get selected, or just the searched ones?

**Comment by nathanm960** [comment]
You're right but I think 1 should be selected because it's visible
