### ISSUE TITLE
row data lost class function

### ISSUE THREAD

**Issue by vmia159** [material-table-core/core#725]
If we pass in a class array as data, the function cannot be used in columns render.

Let say if we have a class like this. We cannot use testFunction in render
```js
class Test {
   constructor(){
    this.field = 'field'
  }

  testFunction() {
   console.log('testing')
  }
}
```
This is because the current implementation on data-manager.js setData use spread operator to add tableData to the rowData
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals
```js
const newRow = {
        ...row,
        tableData
}
```
To fix this, use Object.assign instead
```js
const cloned = Object.assign(Object.create(Object.getPrototypeOf(row)), row)
const newRow = Object.assign(cloned , {tableData})
```

I am not going to give a pr because @material-table/core are refactoring and removing data-manger.js
To work around this without updating @material-table/core
```js
class Test {
   constructor(){
    this.field = 'field'
    this.testFunction = this.testFunction; // add this property so it we get copied by spread operator
  }

  testFunction() {
   console.log('testing')
  }
}
```

**Comment by Domino987** [comment]
Can I ask a more general question first, why would you use classes for data storage?

**Comment by vmia159** [comment]
You can implement function in class for complex display logic. And in case server make changes to the property names, you can just correct the constructor instead of find out every places you have used the data.
