### ISSUE TITLE
Asynchronously load a column when using remote data

### ISSUE THREAD

**Issue by dema-u** [material-table-core/core#726]
I want to load a column asynchronously in separate requests after the bulk of paginated data has been loaded. The closest I can get to making this work is using the `render` parameter:

```javascript
<MaterialTable
    columns={
        ...,
        {
            title: 'Sample',
            field: 'sample',
            render: (data: Types.MyData) => (
                // Async HTTP request for extra data and render it.
            )
        }
    }
    data={query =>
        new Promise((resolve, reject) => {
            // Async HTTP request .then((result) = > ...)
            resolve({
                data: result.items,
                page: result.pagination.page,
                totalCount: result.pagination.total_items
            });
        })
    }
/>;
```

I could theoretically load this extra data with the remote data request, however in my use case this takes 2+ seconds so I would rather render the majority of the data while defaulting to empty 'Sample' column. Only when the bulk of the data has been loaded and displayed I want to asynchronously populate the 'Sample' column.

As of now I believe the render parameter will not accept promises so the code I outlined will not work. Have I overlooked some obvious solution to this? Happy to create a feature request if the maintainers think this could be useful feature. 

Ty

**Comment by Domino987** [comment]
Hi, interesting. Would you mind creating a sample sandbox so I can look into your setup?
There are probably a few way on how to handle this, but if not, we might think about integrating it.
