### ISSUE TITLE
Pagination 'NextPage' icon using 'LastPage' icon.

### ISSUE THREAD

**Issue by jkaffrey** [material-table-core/core#729]
**Describe the bug**
When using pagination on the table component, the 'NextPage' icon is using the 'LastPage' icon. Additionally, trying to override the 'NextPage' icon using the 'icons' prop on the component ignores the passed in value.

This behavior can also be noticed on the example table at the bottom of the page at: https://material-table-core.com/ 
<img width="600" alt="Screen Shot 2023-01-23 at 10 21 27 AM" src="https://user-images.githubusercontent.com/18563238/214092592-ddf2bec6-1181-4a95-a55e-ece039cc5198.png">

**To Reproduce**

1. Implement the library and enable pagination.
2. Under the 'options' prop set: `paginationType: 'stepped'`
3. Observe the icon is incorrect.

**Expected behavior**
- The correct icon is used for the 'NextPage' icon.
- Overriding the 'NextPage' icon displays the passed in component value.

**Desktop (please complete the following information):**
- OS: iOS
- Browser: Chrome
- Version: 6.0.3

**Comment by arulprabhin** [comment]
Same here
![image](https://user-images.githubusercontent.com/93645929/214496826-0dc415ac-858c-42c7-b59e-39aaaf42bf7c.png)
on Firefox 109.0 desktop

**Comment by Domino987** [comment]
Will be fixed with the next release, ty
