### ISSUE TITLE
Breaking Change: MTableEditRow does not accept ref prop

### ISSUE THREAD

**Issue by paintier** [material-table-core/core#73]
I wanted to migrate from material-table to material-table-core, but ran into the following issue:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ClickAwayListener`.
    in MTableEditRow (at ...)
    in ClickAwayListener (at ...)
    in EditRow (created by MTableBody)
```

This warning is triggered by the following code fragment:
```
<MaterialTable>
   components={{
      EditRow: editRowProps => (
              <ClickAwayListener
                onClickAway={() => editRowProps.onEditingCanceled(editRowProps.mode, editRowProps.data)}
              >
                <MTableEditRow {...editRowProps} />
              </ClickAwayListener>
            )
   }}
   ...
</MaterialTable>
```

The idea behind the code is to cancel the row editing in case of clicking anywhere outside the row being edited. 
Maybe there is a different way how that behaviour could be achieved. That would be fine for me, too.

**Comment by matthewoestreich** [comment]
I think I understand what you're saying, but providing a reproducible example via one of the templates we provide would make things a little more clear. Would you mind creating one? Links are in the issue template.

**Comment by paintier** [comment]
sorry for the incomplete bug report, please find an example here: 
[Codesandbox example](https://codesandbox.io/s/material-table-starter-template-forked-67pjs?file=/src/index.js)

The expected behaviour is: if a row is in "editing mode" and a click happens outside that row, then the editing is canceled
This works with "material-table" but not with  "@material-table/core". You can see the warning in the browsers developer tools console

I think the root cause is that the components have been converted into functional components, but don't follow the material-ui coding conventions to accept a "ref" property.

**Comment by matthewoestreich** [comment]
Do you have a reference to these conventions? I'd like to get this resolved!

**Comment by Domino987** [comment]
This is caused by the function component conversion.

So this is how it gets fixed:

1. Remove the export default from all components.
2. Add a default export with forwardRef.
3. Pass the forwared ref to the first child in the return.
```
export default React.forwardRef(function MTableWithRefEditRow(props, ref) {
  return <MTableEditRow {...props} forwardedRef={ref} />;
});

```
``` <TableRow
        onKeyDown={handleKeyDown}
        {...rowProps}
        ref={forwardedRef} // This ref needs forwarding
        style={getStyle()}
      >
```

I added a PR (#82), but Ineed help to get it done for all components.

**Comment by matthewoestreich** [comment]
Thank you! I'll help out with this. Completely slipped my mind what OP was referring to.

**Comment by paintier** [comment]
#82 fixes the issue. thx for your support.
