### ISSUE TITLE
bug: grouping not working 

### ISSUE THREAD

**Issue by DavidLemayian** [material-table-core/core#736]
Grouping by dragging column is not working > 6.1.8

Demo: https://codesandbox.io/s/react-forked-eywb8o?file=/src/App.js

Related: https://github.com/material-table-core/core/issues/727#issuecomment-1407677555

**Comment by Domino987** [comment]
Seems like draggable changed the id to force it to be a string. Will be fixed with the next release

**Comment by DavidLemayian** [comment]
@Domino987  yes! this also fixes another bug I was seeing with grouping. Thank you ❤️
