### ISSUE TITLE
localization prop `labelDisplayedRows` not working

### ISSUE THREAD

**Issue by rjumatov** [material-table-core/core#738]
**Describe the bug**
`labelDisplayedRows` does not seem to work anymore. I've upgraded from v0.2.51 to the latest version v6.1.11

**To Reproduce**
1. Install latest version of `@material-table/core` v6.1.11
2. Add `localization` prop `labelDisplayedRows`
3. No changes can be seen, it stays at default

**Expected behavior**
`labelDisplayedRows` should update the displayed rows label

**Screenshots**
<img width="252" alt="Bildschirmfoto 2023-01-31 um 14 36 09" src="https://user-images.githubusercontent.com/39101755/215775091-9b77e6e0-fb78-4368-b94d-4c0f75b6d12d.png">

**Desktop:**

- OS: macOS Monterey 12.5 
- Browser: Google Chrome
- Version: 109

**Comment by Domino987** [comment]
https://github.com/material-table-core/core/issues/668

**Comment by rjumatov** [comment]
Reading from the typescript declarations in `index.d.ts` it is being used correctly as `labelDisplayedRows`:
```ts
export interface Localization {
  ...
  pagination?: {
    firstTooltip?: React.ReactNode;
    firstAriaLabel?: string;
    previousTooltip?: React.ReactNode;
    previousAriaLabel?: string;
    nextTooltip?: React.ReactNode;
    nextAriaLabel?: string;
    labelDisplayedRows?: React.ReactNode;
    labelRowsPerPage?: React.ReactNode;
    lastTooltip?: React.ReactNode;
    lastAriaLabel?: string;
    labelRows?: React.ReactNode;
  };
  ...
}
```
Adding a custom string value does not work in v6.1.11

**Comment by Domino987** [comment]
Mui Changed the labeling and the previous string is now used for something different. That's why we had to rename the original prop , bit we needed to keep the key for the other prop. So we need both, the new one is the one you need. Adjust the key and it should work
