### ISSUE TITLE
Action not updated in internal state

### ISSUE THREAD

**Issue by juanevp** [material-table-core/core#741]
I don't know if it is really a bug, but it is an unexpected behavior.

Suppose I have an action that is hidden based on an external data:

```typescript
    const myAction = useMemo(() => {
        return {
            action: (rowData: RowData) => {
				const isHidden = hiddenItems.includes(rowData.code);
                const action: Action<any> = {
                    icon: MoreHorizIcon,
                    tooltip: "Item",
                    onClick: (event, rowData) =>{},
                    position: "row",
                    hidden: isHidden,
                };
                return action;
            },
            position: "row",
        };
    }, [hiddenItems]);
```
As the hiddenItems changes, I would expect the row actions to change accordingly, showing or hiding this action.
But it is not so, for a couple of renders the action is updated but then it won't update anymore.
I traced this behavior to the method componentDidUpdate() of the main component. There the set of actions stored in state will only get updated if propsChanged is true. But this conditions does not take into account the actions. So the only workaround I can think of is to access hiddenItems through a useRef instead of using it as a dependency. Which seems rather awkward.
Is this behavior by design? Or was it an oversight?

**Comment by ccks01** [comment]
I'm facing a similar issue using disabled attribute. I'm rerendering the whole table right now.

**Comment by Domino987** [comment]
Can you, as requested, add a sandbox for it?
