### ISSUE TITLE
Add button becomes unusable after deleting a record

### ISSUE THREAD

**Issue by Kitsune401** [material-table-core/core#742]
**Describe the bug**
From version 5.0 to current version 5.1.11, there's a bug appearing when you try to delete a record. The record indeed get deleted, but then the Add button top right becomes unusable. Version 4.3.46 seems unaffected

https://codesandbox.io/s/aged-wave-6lk8f5?file=/src/App.js

**To Reproduce**

1. Delete any record
2. Try to click on Add button
3. See error

**Expected behavior**
The Add button is expected to not be disabled after deleting a record.

**Screenshots**
![image](https://user-images.githubusercontent.com/19733831/217514778-409e357b-bd40-464a-a2ba-f8e5c8077db3.png)

**Desktop:**

- OS: Windows 11
- Browser: Chrome
- Version: 109

**Additionnal context**
I'm using version 5.1.3, since later 5.1.x versions are affected by another bug I will describe in another ticket

**Comment by Domino987** [comment]
What about version 6.x, which is the current version.

**Comment by Kitsune401** [comment]
Hello,

My bad, I didn't even try version 6.x as I thought it would not be compatible with our current react and material-ui versions.
It indeed works with version 6.1.13.
Thank you, and sorry for this pointless spam
