### ISSUE TITLE
A weird button gets added in rows after adding a record

### ISSUE THREAD

**Issue by Kitsune401** [material-table-core/core#743]
**Describe the bug**
From version 5.1.4 to current version 5.1.11, there's a bug appearing after adding a record. A weird inactive button gets added next to delete button in rows. These buttons stay after adding more records, but can disappear if a record gets deleted.

https://codesandbox.io/s/distracted-kowalevski-9dlu95?file=/src/App.js

**To Reproduce**

1. Click on Add
2. Enter any text in the new record's field
3. Validate

**Expected behavior**
There's not supposed to be any weird button to be added there.

**Screenshots**
![image](https://user-images.githubusercontent.com/19733831/217517321-49796aac-bbe1-4049-885a-68c488902602.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 109

**Comment by Domino987** [comment]
Same as the others, please try out v6
