### ISSUE TITLE
Tooltips of Add and Delete buttons do not use localization

### ISSUE THREAD

**Issue by Kitsune401** [material-table-core/core#744]
**Describe the bug**
From 5.1.3 to current version 5.1.11, there's a bug affecting the tooltips of the Add and Delete buttons when localization is used. Localized tooltips are not applied, until an action is done like add or deletion of records.

https://codesandbox.io/s/agitated-borg-73z2gn?file=/src/App.js

**To Reproduce**

1. Look at the tooltips of Add and Delete buttons
2. Delete or add a record
3. Check the tooltips again

**Expected behavior**
Tooltips are supposed to use localization even before doing any action

**Screenshots**
![image](https://user-images.githubusercontent.com/19733831/217520305-a8e3855c-8e3d-42d3-af9c-c91430eb9026.png)
![image](https://user-images.githubusercontent.com/19733831/217520774-f4678b21-22e3-4774-b27f-bb2ed18a6a8a.png)
After adding or deleting at least one record :
![image](https://user-images.githubusercontent.com/19733831/217520510-a3d25aad-8b9e-4cf2-a5d9-22fa755f8690.png)
![image](https://user-images.githubusercontent.com/19733831/217520642-c2a3ab00-6849-478d-806b-650bdc5d39f6.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 109

**Comment by Domino987** [comment]
Please use the latest version, where this should work.
