### ISSUE TITLE
onRowUpdate does not stay in edit mode if promise is rejected

### ISSUE THREAD

**Issue by edoLtomo** [material-table-core/core#746]
Hi All,

does anyone know about the issue when updating the row (onRowUpdate) does not stay in edit mode event if promise is rejected.
this happen in material-table next to 1.56.1 version.

the working example here as expected:
https://codesandbox.io/s/materialtabledemo-validation-error-kgnww?file=/package.json

but then will be broken after 1.56.1 version.

now i am using the material-table-core but same issue show.

this also mentioned in this : https://github.com/mbrn/material-table/issues/3068

please help to fix

**Comment by Domino987** [comment]
Hi, can you create a sandbox with the latest version of this library and add it to the description? And ping me once you did. Thanks.
