### ISSUE TITLE
How to set a key for the rows?

### ISSUE THREAD

**Issue by NelsonGP2110** [material-table-core/core#747]
# Guidelines
- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible
Hello, I migrated a project from material-table to material-table/core due to Muiv5. For some reason, the material-table is using the uuid from the row data.tableData as the key instead of the id from the dataset. I would greatly appreciate it if someone provides me with a solution to this issue. Thanks!
- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by zhammer** [comment]
why is this closed as completed? i'm currently stuck on this and don't see an answer. the data for my table is being polled, and i would like to set the proper key on the table rows so that on each poll the entire table isn't rerendered.
