### ISSUE TITLE
Cannot read properties of undefined (reading 'id')-Material table core

### ISSUE THREAD

**Issue by SmackzR6** [material-table-core/core#748]
Good day guys, Im currently having a problem where when i delete a record i get this error below
Uncaught TypeError: Cannot read properties of undefined (reading 'id')

Here is the sandbox - https://codesandbox.io/s/shy-surf-6w9vud?file=/src/App.js

![ErrorDelete](https://user-images.githubusercontent.com/18571690/220173569-e64d835f-79ab-4f8b-b5e6-1737af30a394.PNG)

click delete to remove a record.

A record should be deleted. Without any errors. Debugging shows there is no tabledata index row object. same behavior on demo page https://material-table-core.com/demos/edit/editable/#usage

**Desktop (please complete the following information):**

- OS:Windows 10
- Browser chrome
- Version 110.0.5481.77 (Official Build) (64-bit)

**Comment by Domino987** [comment]
We decided not to expose the inner workings anymore aka tabledata.
So try this
```
setTimeout(() => {
              const dataDelete = data.filter((el) => el.id !== oldData.id);
              setData(dataDelete);
              resolve();
            }, 1000);
```
I also updated the docs to reflect this. ty

**Comment by SmackzR6** [comment]
Thank you Domino. all is working as expected :)
