### ISSUE TITLE
Not able to export data when more number of columns are present

### ISSUE THREAD

**Issue by pratik-nagpure** [material-table-core/core#752]
I am trying to export PDF and CSV.
If there are more number of columns lets say more than 30 then application hangs and I see the error in console that 
"Will not be able to print row -1 correctly since it's minimum height is larger than page height"

I have also created the sandbox to reproduce this issue 
  - #### [CodeSandbox](https://codesandbox.io/s/kind-haslett-2nfoxi?file=/src/App.js)

Let me know if there is any fix for this.
Thanks in advance

**Comment by Domino987** [comment]
Seem like this is a problem with the pdf generator. Please see https://github.com/simonbengtsson/jsPDF-AutoTable/pull/732 and that is fixed on their end, let me know.

**Comment by pratik-nagpure** [comment]
Hi @Domino987 
I tried with the latest of @material-table/exporters and jspdf-autotable
I am still able to reproduce this issue

![image](https://github.com/material-table-core/core/assets/25742857/bb307f9a-4cc8-4a0c-bc5f-be779d0c94b8)
![image](https://github.com/material-table-core/core/assets/25742857/168fb0e9-ed4a-4e03-984f-8b01bac5da4e)

Thanks

**Comment by Domino987** [comment]
As you can see [here](https://github.com/material-table-core/exporters/blob/main/src/pdf/index.js) we are just passing the data into the jsPDF library. If the library we are using is the problem, there is noting I can do.
