### ISSUE TITLE
Not able to test onRowClick with react testing library.

### ISSUE THREAD

**Issue by manubolla-jolt** [material-table-core/core#754]
Hi guys, I'm trying to do some testing with react testing library and I'm not able to fire the onRowClick event. Can someone give me a hand? It's driving me crazy. Thanks.

**Comment by Domino987** [comment]
Can you show us what you are doing in a sandbox?

**Comment by manubolla-jolt** [comment]
Sorry i didnt answer before. Here is a sandbox, similar of what I'm trying to do.

https://codesandbox.io/s/beautiful-keldysh-fbm3oj?file=/src/App.js

Let me know if that helps.

Thanks!

**Comment by Domino987** [comment]
Hi,
so it gets clicked, but we wait a few milliseconds for a possible double click to happen.

So youneed to await the clicking with ``await waitFor(() => expect(props.history.push).toBeCalled());``

[Link](https://codesandbox.io/s/blissful-boyd-e442qg?file=/src/Table.test.js:463-525)
