### ISSUE TITLE
The locale property labelDisplayedRows is not reflecting on UI

### ISSUE THREAD

**Issue by pedrohenriiz** [material-table-core/core#755]
The ```labelDisplayedRows``` is not working properly. I found this issue https://github.com/material-table-core/core/issues/738, but this didn't helped me. 
Also, I read the source code and found that the prop ```labelRowsSelect``` has changed to ```labelRows```. I did this change. However, the ```labelDisplayedRows``` doesn't seems to be reflecting on the ui.

It's possible to see here: https://codesandbox.io/s/delicate-water-pzhhkp?file=/src/App.js

**Comment by Domino987** [comment]
Ah yes, will be fixed with the next release. Thanks
