### ISSUE TITLE
Question: Is there a stateSave option available?

### ISSUE THREAD

**Issue by refactor73** [material-table-core/core#756]
Hi guys!
thank you for your work on material table!

i got a customer asking if it would be possible to keep the state of a table (e.g. the current selected page) after browse on a detail page and going back to the table (the table he is asking for has a detail button which redirects to a detail page, with different URL, for the chosen item).

so i've gone through the docs and searched for something, which stores the state of a table in a cookie or somewhat. Also in the issues i didn't find anything related (maybe i search with the wrong wording...).

i know from another table project based on jQuery that they've implemented an option called stateSave which is doing exactly this:
https://datatables.net/reference/option/stateSave

so my question is: does material-table-core has an option like this? 

regards
chris

**Comment by Domino987** [comment]
Currently not, but you can save the page and page size with the callbacks and set them on mount? Would that be enough?

**Comment by refactor73** [comment]
thank you @Domino987
