### ISSUE TITLE
Pagination row elements are vertically misaligned

### ISSUE THREAD

**Issue by sarveshp17** [material-table-core/core#757]
The pagination row elements are not aligned properly. I am using version 6.1.13. I have attached screenshot below.
![image](https://user-images.githubusercontent.com/106380017/229998446-c109ad0d-4a39-443e-9ef2-34d32eb9bb98.png)

I believe this is happening because of some CSS clash between the material-table/core and some other Material UI components on the page. I tried to create a small sandbox example but was not able to reproduce the issue in the sandbox. However, the issue is visible in the demo page. If you scroll down to the end of the page, the table at the bottom has the same issue.

https://material-table-core.com/demos/pagination/basic/

![image](https://user-images.githubusercontent.com/106380017/230001935-a5286bf4-d073-4da4-a7e3-8424d481a89c.png)

**Comment by brunohpg** [comment]
It disapeared now?

![image](https://user-images.githubusercontent.com/4167545/232527213-b60a9cb8-9341-413b-9345-acf272d061ac.png)

It's changed recently, commit https://github.com/material-table-core/core/commit/3bc70742181e9e48b981a9cdc7560233c62b2b51

I did not understand the fix:
https://github.com/material-table-core/core/blob/611bcab2201ca0bf54e40c765acab23e6a91cd05/src/material-table.js#L914-L918

**Comment by sarveshp17** [comment]
In our application it was looking slightly different
![image](https://user-images.githubusercontent.com/106380017/232848922-bcfa719a-e2ae-411c-957b-381d4e5b93f1.png)

the "1-5 of 132" was inside the previous and next buttons and only the "Rows per page:" was misaligned

I used the following localization setting to disable the "Rows per page:"
localization={{
  pagination: {
    labelRowsPerPage: "",
  },
}}

**Comment by Domino987** [comment]
Hi, yes we had a slight missmatch when we upgraded the mui versions.
We accidently show the default pagination text, but the original approach was to show it within the brackets.
I moved it so that it looks again like in the previous version.
Can you create some sandboxes with your code and how it looks?

**Comment by brunohpg** [comment]
@Domino987 
The @sarveshp17 pic had given me a clue what this problem would be. I changed some location information and it worked. Thanks.

**Comment by Domino987** [comment]
What do you mean with location information? Great that it works for you

**Comment by brunohpg** [comment]
localization! Sry.

I have removed:
labelDisplayedRows: 'Linhas',
