### ISSUE TITLE
Column swap not work as expected

### ISSUE THREAD

**Issue by vmia159** [material-table-core/core#759]
**Describe the bug**
Column swap not work as expected.

**To Reproduce**

On this demo https://material-table-core.com/demos/columns/render-image/

1. Swap Avatar (index 0) to name (index 1)
2. Avatar is now on index 1 and name is on index 0 (Correct)
3. Swap Avatar (index 1 original index 0) to surname(index 2)
4. Avatar on index 0, name is on index 2, surname is on index 1

**Expected behavior**
Expect avatar and surname swap in step 3 and name should not be affected.
(Avatar on index 2, surname on index 1, name on index 0

**Screenshots**

**Desktop (please complete the following information):**

- OS:  windows & iOS
- Browser: chrome, safari

**Comment by Domino987** [comment]
Tahnks, ill check it out.
