### ISSUE TITLE
Table footer doesn't properly handle right-to-left languages (dir="rtl")

### ISSUE THREAD

**Issue by imnasnainaec** [material-table-core/core#760]
**Describe the bug**
In our React app, when we set `document.body.dir = "rtl"`, the left-right ordering of MUI components switches. That causes the material-table footer to go from
<img width="509" alt="Screenshot 2023-04-26 at 13 34 38" src="https://user-images.githubusercontent.com/6411521/234657046-c9f1394c-6c4b-49e8-9908-ebb123914e81.png">
to
<img width="509" alt="Screenshot 2023-04-26 at 13 22 54" src="https://user-images.githubusercontent.com/6411521/234657073-8923ec0e-243a-4bfc-881f-50a0924bb27f.png">

**Expected behavior**
The "10 rows ▾" became "rows 10 ▾", but should have the triangle button move to the other side (either "▾ 10 rows" or "▾ rows 10").
The "1-10 of 8045" became "of 8045 10-1"; it should either not change or become "8045 of 10-1".
Since the arrows reverse order, they should also switch direction.

**Desktop (please complete the following information):**

- OS: macOS 13.2.1
- Browser: Chrome 112

**Comment by imnasnainaec** [comment]
I see that some of that can be handled with the `localization` prop (https://material-table.com/#/docs/features/localization). Though it appears the order/direction of arrows still needs to be fixed.

**Comment by Domino987** [comment]
Would you mind creating a pull request to fix this for your case? Since I dont have a working rtl setup?

**Comment by imnasnainaec** [comment]
@Domino987 Sure, I'll work on that.

I also just discovered that the arrow directions can be flipped, but are responsive to the MUI theme rather than the `.dir` tag of the parent, which makes sense.

The two things that I intend to create a pr to fix are:
- moving the placement of the triangle button for the drop-down menu
- fixing the localization of the {from}-{to} of {count}
<img width="521" alt="Screenshot 2023-04-28 at 08 15 21" src="https://user-images.githubusercontent.com/6411521/235145380-262b6438-acd4-47b7-b76e-508e6783548e.png">

**Comment by Domino987** [comment]
Sounds good.
Thank you
Maybe we should stick with the theme to reasoned to the rtl setting in the first place and arrange the ui with that.

**Comment by imnasnainaec** [comment]
The placement of the triangle button for the drop-down menu seems to be an issue within MUI's `TablePagination`, so I didn't address that in the pr.
