### ISSUE TITLE
suggestion: pass props.groupData to groupRender

### ISSUE THREAD

**Issue by DavidLemayian** [material-table-core/core#762]
props.groupData is a lot more useful for `groupRender` customization

https://github.com/material-table-core/core/blob/master/src/components/MTableCell/cellUtils.js#L60

**Comment by Domino987** [comment]
Can you provide a sandbox, a usecase or a PR with reasoning?

**Comment by DavidLemayian** [comment]
Apologies. Not forgotten about this, just been a busy three weeks. Will hopefully be able to circle back on this next week
