### ISSUE TITLE
Custom components no longer have access to localization.

### ISSUE THREAD

**Issue by bsmith-code** [material-table-core/core#764]
Describe the bug
Custom components no longer have access to localization since it has been moved to context. The useLocalizationStore consumer hook is not available in the public API.

Expected behavior
Export the useLocalizationStore hook from entry point to allow usage of localization in custom components.

Desktop (please complete the following information):
OS: macOS 13.1
Browser: Chrome 112

**Comment by Domino987** [comment]
That's true, would you mind creating a pr for this? Or add it to the props maybe?

**Comment by bsmith-code** [comment]
@Domino987 PR has been created here: https://github.com/material-table-core/core/pull/765
