### ISSUE TITLE
'ExportCsv' (reexported as 'ExportCsv') |  package.json contains '"type": "module"'). 

### ISSUE THREAD

**Issue by Shrinath-HST** [material-table-core/core#766]
export 'ExportCsv' (reexported as 'ExportCsv') was not found in '@material-table/exporters' (module has no exports)
ERROR in ./node_modules/@material-table/exporters/index.js 1:0-45
Module not found: Error: Can't resolve './pdf' in 'E:\Shrinath\HST\rabbit_v2_react\node_modules\@material-table\exporters'
Did you mean 'index.js'?
BREAKING CHANGE: The request './pdf' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

----------------------------------
package.json

{
  "name": "erma_v2_react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@material-table/core": "^0.2.32",
    "@material-table/exporters": "^1.0.12",
    "@mui/icons-material": "^5.10.6",
    "@mui/lab": "^5.0.0-alpha.108",
    "@mui/material": "^5.11.5",
    "@mui/x-date-pickers": "^5.0.15",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "ace-builds": "^1.13.1",
    "axios": "^0.27.2",
    "axios-hooks": "^4.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-ace": "^10.1.0",
    "react-checkbox-tree": "^1.8.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.39.4",
    "react-router-dom": "^6.4.1",
    "react-scripts": "^5.0.1",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

-----------------------------------
Previously, it was working fine, but suddenly started getting this error  while running the project.
Tried with different versions of "@material-table/core": "^0.2.32", "@material-table/exporters". Same error!!!

Tried after removing node_modules & package-lock.json. Tried with with new npm version install. Showing new errors.

**Comment by Domino987** [comment]
Can you create a sandbox?

**Comment by pr-arun** [comment]
I am also facing the same issue.

**Comment by Domino987** [comment]
Also for you, @Arun-Ravi could you add a sandbox with your code?
