### ISSUE TITLE
How to Display Export Button

### ISSUE THREAD

**Issue by matthew-kusz** [material-table-core/core#77]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have
[Demo](https://codesandbox.io/s/brave-babbage-gvloq?file=/src/App.js)
- #### Please try to be as detailed as possible
I want to export the data in my table to a csv. I followed the code [here](https://material-table-core.com/docs/api/props/options#exportmenu), but I do not know how to get the export button to show up. Do I need to create my own? I tried on versions 2.3.6 and 2.3.8.

**Comment by matthewoestreich** [comment]
Hey @matthew-kusz would you mind upgrading to 2.3.9? It is fixed in that version. Apologies.

**Comment by matthew-kusz** [comment]
Thanks for the fix!
