### ISSUE TITLE
material-table-core.com not accessible 

### ISSUE THREAD

**Issue by SmackzR6** [material-table-core/core#770]
Good day,

cant seem to access the website,its been like this since last week.
![image](https://github.com/material-table-core/core/assets/18571690/71faf9f9-b361-4961-aa3a-deebb2ec9c80)

Chrome is up to date
Version 113.0.5672.127 (Official Build) (64-bit)

kind regards
Tony

**Comment by aramyesildeniz** [comment]
Any updates on this?
Or is there another way to read the docs?

**Comment by SmackzR6** [comment]
have no idea whats happening. Can they advise way forward to read the docs. Or perhaps they are building a new site for the docs or updating it

**Comment by Domino987** [comment]
Seems like the guy who set up did not keep the instance around. I am looking into it.

**Comment by Domino987** [comment]
Meanwhile please use  https://davidlemayian.github.io/material-table-core-website/

**Comment by flash-me** [comment]
What is going on here? 
![image](https://github.com/material-table-core/core/assets/5240450/d97eff21-2187-487e-843a-924ad21c9786)

cheers
flash ⚡

**Comment by Domino987** [comment]
Haha wow. I guess the domain got sold.
https://material-table-core.github.io/ will be the new url. I'll update the urls and the cli script this week.

**Comment by sdtai** [comment]
npm homepage is still the old site
