### ISSUE TITLE
Grouping by column breaks the table if tree data exists

### ISSUE THREAD

**Issue by DavidLemayian** [material-table-core/core#771]
**Describe the bug**

Grouping by column breaks the table if tree data (`parentChildData` option) exists

**To Reproduce**

1. Setup from demo:

    ```js
    <MaterialTable
      data={TREE_DATA}
      columns={TREE_COLUMNS}
      parentChildData={(row, rows) => rows.find((a) => a.id === row.parentId)}
      options={{
        selection: true,
        grouping: true,
        showGroupingCount: true
      }}
    />
    ```

2. and then drag a column to be grouped

Sandbox: https://codesandbox.io/s/nervous-swirles-7427gu?file=/src/App.js:1384-1707

[nervous-swirles-7427gu---CodeSandbox.webm](https://github.com/material-table-core/core/assets/877919/d8eed504-987a-485a-86d3-8994bc70fbc7)

**Comment by Domino987** [comment]
@DavidLemayian  Hi, thanks for reporting this. I am also not sure (apart from the obvious error) on how these two would work together. Would you mind providing an example on how you would expect grouping and tree data to behave in this case?
