### ISSUE TITLE
Filter doesn't work if the value is 0

### ISSUE THREAD

**Issue by DeekshithBanjan** [material-table-core/core#772]
Hi,

Check the below link and try to filter the month value by 0, it says no records even though it has entries.

[https://codesandbox.io/s/agitated-bash-0hf8uy?file=/src/table.js]([https://codesandbox.io/s/agitated-bash-0hf8uy?file=/src/table.js](https://github.com/material-table-core/core/issues/url))

**Comment by Domino987** [comment]
It seems like there weer some falsy miss check. Will be fixed with the next version. Thanks.
