### ISSUE TITLE
Problem with labelDisplayedRows

### ISSUE THREAD

**Issue by DaveITpl** [material-table-core/core#773]
**Describe the bug**
I have problem with latest version of material-table-core
```
"@material-table/core": "^6.1.17",
```
Information about the number of items in the table and the total number of items is not shown
Sandbox:
- #### [CodeSandbox mui v5](https://codesandbox.io/s/material-table-starter-template-forked-pp56zv?file=/src/index.js)

**Screenshots**
v6.1.17
![image](https://github.com/material-table-core/core/assets/33221430/b051e2c8-c0c2-4169-a1e8-e8e3fbc0ad73)
v6.1.15
![image](https://github.com/material-table-core/core/assets/33221430/4f7332b4-37b2-4b00-ad48-791be7b193ff)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser chrome

**Comment by Domino987** [comment]
Seems like it got deleted on accident. Will be back with 6.1.18. Thank you

**Comment by DaveITpl** [comment]
@Domino987 you have a problem with tests
https://github.com/material-table-core/core/actions/runs/5294450281/jobs/9583807423
