### ISSUE TITLE
Extra Console.logs getting printed whenever table is filtered

### ISSUE THREAD

**Issue by tejaswikarasani2001** [material-table-core/core#774]
I'm using version 6.1.17 and I'm seeing extra logs getting printed on console whenever I filter the table

Here is the demo: https://codesandbox.io/s/ecstatic-wilbur-jrrskq?file=/src/App.js

When I filtered rows based on column:

1) if type of column  is number below console.log is getting printed 

https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L946

<img width="361" alt="image" src="https://github.com/material-table-core/core/assets/115219216/e9c5238e-7768-4cc5-84e8-c9e65a46dbe4">

2) if type of column is others then below line of code is getting executed which leads to printing the data

https://github.com/material-table-core/core/blob/master/src/utils/data-manager.js#L1015

<img width="353" alt="image" src="https://github.com/material-table-core/core/assets/115219216/32fecbcd-bc59-4c15-8d45-58d89af2c0ff">

**To Reproduce**
Filter any column using version 6.1.17 and you will see extra console.logs on frontend

**Expected behavior**
No console.logs should be printed on frontend

**Comment by Domino987** [comment]
Seems like it snuck in. Will be removed with the next release. Thanks.
