### ISSUE TITLE
Allow adding a clickable custom icon in column header

### ISSUE THREAD

**Issue by mkasid** [material-table-core/core#778]
Hi Everyone,

Do we have any feature in the material table to add a clickable icon to the column header? The only option I can think of is by adding a custom header with custom sorting. Right now, with the documented options, we I try to add an icon to the column header, clicking it will just keep sorting the table instead of allowing me to go to another website or navigate to another page. See the example below of what I am looking for, is this something available in the material table or will I need to create a feature request?

Please see the attached image for what I need.
![MicrosoftTeams-image](https://github.com/material-table-core/core/assets/20172453/9f1ccf5f-c889-42a3-800a-af73baa9ae03)

**Comment by Domino987** [comment]
Hi this has not come up yet as a request. I'll take a look and keep you posted.

**Comment by mkasid** [comment]
> Hi this has not come up yet as a request. I'll take a look and keep you posted.

Thanks, @Domino987, please let me know if you need development help with this request, we are a team of developers who can help out with coding this feature.

**Comment by Domino987** [comment]
You are always welcome to create a PR maybe add some tests as well. That would be greatly appreciated and would probably reduce the time for the feature to land.

**Comment by Domino987** [comment]
@mkasid Can you add your current implementation as a sandbox?

**Comment by mkasid** [comment]
@Domino987 
I haven't yet scheduled a time to implement this, I will add that as soon as I have it. Just occupied with some other priorities right now.

**Comment by Domino987** [comment]
@mkasid Did you try to call `stopPropagation` onClick?

```
 title: (
      <div>
        Test
        <button
          onClick={(e) => {
            e.stopPropagation();
    // my stuff
          }}
        >
          icon
        </button>
      </div>
    ),
```

**Comment by mkasid** [comment]
> @mkasid Did you try to call `stopPropagation` onClick?
> 
> ```
>  title: (
>       <div>
>         Test
>         <button
>           onClick={(e) => {
>             e.stopPropagation();
>     // my stuff
>           }}
>         >
>           icon
>         </button>
>       </div>
>     ),
> ```

I will try this out, thanks!

**Comment by mkasid** [comment]
The e.stopPropagation() suggestion worked, thanks for the help, closing this issue now.
