### ISSUE TITLE
onQueryChange with remote data feature rerenders whole table

### ISSUE THREAD

**Issue by andiries** [material-table-core/core#78]
Hey guys,
I already asked the following question in the material-table repository, but as you know it has become very quiet over there.

I am using the remote data feature of material-table-core and want the table data be updated on a regular interval like every 2 seconds.

For that i use the useEffect() hook which calls onQueryChange() on a tableRef.
See https://codesandbox.io/s/material-table-flickering-forked-9d2w5 for an example.

Everything works as expected besides whenever I call onQueryChange(), the whole table is rerendered.

My expectation is that only the table data should be rerendered in the same way as when you change the table data directly by setting a new array to the data prop.

Is there a way to use onQueryChange() or some other method to make material-table only rerender the data and not the whole table?

**Comment by matthewoestreich** [comment]
Hey @andiries the way we are currently handling state needs to be improved upon greatly.  It seems as though we have the typical case of "left hand not knowing what the right hand is doing".  Making one minor tweak to state here, causes issues over there, etc..

Truth be told, I'm at a crossroads of what to do with this project. Fix issues like this? Ignore them and refactor appropriately? Abandon this project altogether in favor of `@material-ui` and `DataGrid`?

**Comment by andiries** [comment]
Hey @oze4 thanks for your quick reply. I totally understand your point.
I have to decide if I want to use material-table in our environment. With the fact that @mbrn is somehow not available I guess I have to move forward to DataGrid or maybe react-table.

Anyway, Thanks for your efforts
