### ISSUE TITLE
Show filtered count of rows instead of total count

### ISSUE THREAD

**Issue by tejaswikarasani2001** [material-table-core/core#780]
I want show the filtered count instead of total count. Can the team add this feature in the new release?

This is screenshot of the original table which is pagination to show 5 rows per each page

<img width="946" alt="image" src="https://github.com/material-table-core/core/assets/115219216/6a54856e-64f6-4684-aff8-7d7f29835801">

This is the screenshot when filtered Name column with "M" which matches with only one row but the count on the bottom still shows the "5" 

<img width="952" alt="image" src="https://github.com/material-table-core/core/assets/115219216/505f3291-d385-40de-adad-f6a766e1f169">

**Comment by Domino987** [comment]
Well this is not the count. But the rows per page. The count is next to it, in the second screenshot it is 1 of 1. You can always override the component, if that would help you.

**Comment by tejaswikarasani2001** [comment]
Thank you!
