### ISSUE TITLE
How to style pagination section and buttons

### ISSUE THREAD

**Issue by RitchieP** [material-table-core/core#788]
I am able to style the table cells to my liking but not the pagination section and the add row button on the top right corner. My table now looks like this:

Pagination section
![image](https://github.com/material-table-core/core/assets/26197115/97685cb1-f0f3-4e1e-aebe-fb6f32216b38)
Add row button
![image](https://github.com/material-table-core/core/assets/26197115/79c1195a-f020-45af-9528-01e2c20d0530)

I also noticed when I try to edit the rows, the colors are also black.
![image](https://github.com/material-table-core/core/assets/26197115/9e1faa5a-e7c5-4038-be72-e28fffbc4abb)
![image](https://github.com/material-table-core/core/assets/26197115/845d2fb6-4ae9-4b28-bd70-92d44cec8e27)

My website has sort of a dark theme to it, so I need the buttons and text to be white in color. How do I style them? 

I've tried looking in `mbrn`'s original documentation and this repo's documentation but no luck. Maybe I'm missing something? Thanks for any help in advance!

**Comment by Domino987** [comment]
Can you add a sandbox as requested?

**Comment by RitchieP** [comment]
https://codesandbox.io/p/sandbox/material-table-test-y7cq2n

This is my first time using a sandbox, I hope you can see it. If there's anything missing please let me know! I've tried my best to include only the parts necessary to recreate the table view. Some files have a lot of commented lines because those are working with my Firebase backend and I think is not needed for the rendering.

**Comment by RitchieP** [comment]
I've managed to style most of the buttons and text I mentioned. For the pagination section's text, I had to set the `WebkitTextFillColor` key in `style` attribute to `#ffffff`.

For the icons, I had to install material ui icons, and basically override the original icons. So I had to override the icons attribute like so:
```js
import { 
    AddBox, 
    KeyboardArrowLeft, 
    KeyboardArrowRight,
    FirstPage,
    LastPage,
    Edit,
    Delete,
    Check,
    Clear
} from "@mui/icons-material"

<MaterialTable
  icons={{
      Add: () => <AddBox sx={{ color: "white" }} />,
      Edit: () => <Edit sx={{ color: "white" }} />,
      Delete: () => <Delete sx={{ color: "white" }} />,
      NextPage: () => <KeyboardArrowRight sx={{ color: "white" }} />,
      PreviousPage: () => <KeyboardArrowLeft sx={{ color: "white" }} />,
      FirstPage: () => <FirstPage sx={{ color: "white" }} />,
      LastPage: () => <LastPage sx={{ color: "white" }} />,
      Check: () => <Check sx={{ color: "white" }} />,
      Clear: () => <Clear sx={{ color: "white" }} />
  }}
/>
```

But I am still not able to change the small little expand button when selecting number of rows to show in a page.
![image](https://github.com/material-table-core/core/assets/26197115/47189471-deb0-4b27-9b30-c23ea400e19f)

**Comment by Domino987** [comment]
Wait, you are not using the theme provider with dark mode? [Docs](https://mui.com/material-ui/customization/dark-mode/)
@RitchieP 

Check this out:
https://codesandbox.io/p/sandbox/material-table-test-forked-rgxjrf?file=%2Fsrc%2FApp.js%3A3%2C48-7%2C18

**Comment by RitchieP** [comment]
Ah, my bad I overlooked using the theme provider. This works perfectly.

Thanks!
