### ISSUE TITLE
Tree view rerenders when editing a value, resetting the expanded rows when expanding after having searched something

### ISSUE THREAD

**Issue by klassm** [material-table-core/core#79]
Not sure whether this is a known issue - I also tried to fix it already but it does not seam trivial:

- Let's start by some tree data.
- We search something, so that we find a value that has an editable child
- We open the row and edit a value
- Now the table rerenders and the collapse state resets to the state when the search was issued, so the child we just edited is collapsed again.

I saw this happening both on Linux and on MacOS, both on Chrome and on Firefox.

**Comment by klassm** [comment]
Maybe this is also related to https://github.com/material-table-core/core/issues/59 ?

**Comment by matthewoestreich** [comment]
I think our plan is to just refactor from the ground up using a new API.

**Comment by Domino987** [comment]
@klassm To better understand the issue, would you mind adding a sandbox to this?
