### ISSUE TITLE
Grouped rows spaced incorrectly

### ISSUE THREAD

**Issue by TheGoodSpinach** [material-table-core/core#792]
**Describe the bug**
When adding the option `grouping: true`, the sub-rows of the groups are incorrectly sized, leading to awkward looking spacing between each cell. On older versions of material-table/core, the sub-rows were correctly positioned to the left of the table, with the checkbox row having a static width according to the size of the checkbox.

**To Reproduce**
Please refer to this sandbox: https://codesandbox.io/s/material-table-starter-template-forked-nm5slj

1. expand one of the group rows
2. Observe that the three cells are all equal width, rather than the first two cells being thin and the last cell filling the rest of the space. 

**Expected behavior**
The checkbox and spacing cells should be small so the checkbox appears on the left of the table rather than the middle

**Screenshots**
![image](https://github.com/material-table-core/core/assets/11195965/fea0f8a0-dff6-433e-97b3-4b98c75a3c11)

**Desktop (please complete the following information):**

- Windows
- Chrome
- material-table/core version 6.2.0, but I observe at least as far back as 4.3.46

**Comment by Domino987** [comment]
Seems like there were some legacy paddings. Will be fixed with the next release. Thank you
