### ISSUE TITLE
Add localization support for datepicker component (v5)

### ISSUE THREAD

**Issue by DreadCube** [material-table-core/core#798]
**Is your feature request related to a problem? Please describe.**

The DatePicker component does not have the possibility to have translated buttons and a custom format for the header text.

Current behaviour:
![image](https://github.com/material-table-core/core/assets/13951257/4c2ac6cb-a6a1-416d-a42f-ac0b8e3d1feb)

What it should look like (in my case german locale and text):
![image](https://github.com/material-table-core/core/assets/13951257/bb11c2b4-6b99-4b97-90fd-b1eb1f1514d7)

I forked this repo and created a PR on the latest v5 on my side with the needed changes to accomplish this:
https://github.com/DreadCube/material-table-core/pull/1

Maybe we wanna support that generally for the v5?

On v6 things look a little different because from there on material ui v5 is used with new Date Picker components:
![image](https://github.com/material-table-core/core/assets/13951257/3eb41382-37b7-493d-9712-237d3da9893c)
But i guess formatting the placeholder / value to a different locale would make sense there too.

In my case we have to stay still for a while on material-ui v4 with the older DatePicker variant.

**Comment by Domino987** [comment]
Hi, did you try this: https://mui.com/x/react-date-pickers/localization/#set-translations-globally
Can you also proivde a sandbox with your setup? @DreadCube
