### ISSUE TITLE
Layout breaks when no nested rows on screen for a table with nesting

### ISSUE THREAD

**Issue by pgbradbury** [material-table-core/core#799]
**Describe the bug**
When I have a table using the parent and child nesting, if all the displayed rows have no nested rows, the columns in the table align to the right.

**To Reproduce**

1. Go to a table with some nested rows
2. Click on navigation until you get to a screen without any nested rows
3. See error

**Expected behavior**
Layout should not change, just nesting arrows should not be displayed

**Screenshots**
![CleanShot 2023-10-13 at 17 41 59](https://github.com/material-table-core/core/assets/73958879/e5357f78-3e9f-44ed-9040-bfed475d14ae)

![CleanShot 2023-10-13 at 17 43 23](https://github.com/material-table-core/core/assets/73958879/1570ef7e-cc34-44e6-b048-d15739e8a531)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 117.0.5938.149 (Official Build) (arm64

**Comment by Domino987** [comment]
Please provide a sandbox
