### ISSUE TITLE
onBulkUpdate not working properly

### ISSUE THREAD

**Issue by dinesh-techahead** [material-table-core/core#80]
onBulkUpdate: changes => 
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log(changes);

                    resolve();
                }, 1000);
            }),

when we using bulk upload. In material-table we get only those rows which are changed rows but in material-table-core we are getting all rows.
 
![screenshot-nimbus-capture-2021 01 22-12_07_05](https://user-images.githubusercontent.com/74606207/105456124-9fcadd00-5caa-11eb-9319-de5aa402180b.png)

**Comment by matthewoestreich** [comment]
@Domino987 is that what you were referring to? Or do you know what may be the cause?
