### ISSUE TITLE
Don't list @material-ui/styles as a dependency.

### ISSUE THREAD

**Issue by quirinpa** [material-table-core/core#800]
# Guidelines

listing @material-ui/styles as a dependency causes duplicate dependency issues.
Instead, import from "@material-ui/core/styles".

**Describe the bug**
Because of multiple instances of the @material-ui/styles dependency, Theme options are not properly passed down (Context mismatch).

**Comment by Domino987** [comment]
Which version are you talking about currently?
Please add a sandbox with your code/setup

**Comment by imnasnainaec** [comment]
@quirinpa The current version doesn't have `@material-ui` dependencies. I'm browsing `package.json` in the released versions (https://github.com/material-table-core/core/releases). It looks like `@material-ui/styles` was present in [v5.1.12](https://github.com/material-table-core/core/releases/tag/v5.1.12), was changed to `@mui/styles` by the time of [v6.1.13](https://github.com/material-table-core/core/releases/tag/v6.1.13), which was also removed by [v6.2.0](https://github.com/material-table-core/core/releases/tag/v6.2.0). Does updating your `@material-table/core` dependency to 6.2 solve the issue?
