### ISSUE TITLE
 Retain search results in a Material UI table across page changes in Next.js without reloading the table?

### ISSUE THREAD

**Issue by daveclinton** [material-table-core/core#803]
# Retaining Search Results across page changes

I am working on a way to keep the search results of a Material UI table in a Next.js app, even when I go to a different page. I tried using local state to store the search results, but the table re-renders and the data is fetched again every time I go back to the page. What is the best way to do this?

The code uses the remote data fetching logic. We can use this sample from the docs to get a fix
```
import MaterialTable from "@material-table/core";

<MaterialTable
  // ...
  data={(query) =>
    new Promise((resolve, reject) => {
      let url = "https://reqres.in/api/users?";
      url += "per_page=" + query.pageSize;
      url += "&page=" + (query.page + 1);
      fetch(url)
        .then((response) => response.json())
        .then((result) => {
          resolve({
            data: result.data,
            page: result.page - 1,
            totalCount: result.total,
          });
        });
    })
  }
/>;
```

**Comment by Domino987** [comment]
Can you create a sandbox with what you have and how you would like it to work? Url Params are the best way to achieve this probably, but again, let's see a sandbox first.

**Comment by Domino987** [comment]
And since this is not a bug, can you change the tags
