### ISSUE TITLE
Browser crash when rendering large amount of rows (1000+)

### ISSUE THREAD

**Issue by mkasid** [material-table-core/core#806]
We use the material table in a large accounting application and have a user requirement to display rows without pagination. This works fine for most cases, but for a few large clients, this is becoming an issue where the number of rows can sometimes reach 8K to 10K. The browser crashes when loading these many rows in the material table. Is there a solution to this?

The material react table component implemented a virtualized data feature so it is possible to render large amounts of rows and columns, it can be found here: https://www.material-react-table.com/docs/examples/virtualized do we have something similar in material table core?

**Comment by Domino987** [comment]
Hello,
There should be < 6000 react elements on a page roughly. 
With 10k rows and 30 elements per rows, you easily run out of memory, so that's the obvious explanation.

There ist currently not a way to virtualze the list, but if you want to work on a PR, you are more than welcome.
