### ISSUE TITLE
Opened/Closed hooks for detail panel 

### ISSUE THREAD

**Issue by jbek7** [material-table-core/core#809]
**Is your feature request related to a problem? Please describe.**
I want to know which row's detail panel is opened/closed so I can run operations inside detail panel knowing which row's detail panel that I'm working with. Currently detailPanel property just passes rowData but it sends not only one but other row's rowData too which is not reliable. See the gif - it's from the doc's [detail panel's live demo](https://material-table-core.github.io/demos/details-panel/basic#live-demo). I just added the log inside the detailPanel property to show what rowData brings.

![material-table-hook](https://github.com/material-table-core/core/assets/2989603/3c5f7053-77a8-4509-9869-066f9e7a451d)

**Describe the solution you'd like**
It would be nice to have opened/closed hooks with rowData for detailPanel so we can keep track what's open/closed.

**Comment by Domino987** [comment]
The gif is not visible.

**Comment by Domino987** [comment]
Will be included in the next version: 
  onDetailPanelChange?: (row: RowData, state: 'open' | 'closed') => void;

**Comment by jbek7** [comment]
Great that should solve the problem that I'm having.

**Comment by Wdifulvio523** [comment]
I am on the most up-to-date version of this and I am not getting  onDetailPanelChange to trigger, has it not been released yet?
