### ISSUE TITLE
Forgotten console.log

### ISSUE THREAD

**Issue by AllytaDemiangel** [material-table-core/core#812]
Hello,
I noticed what I think is a forgotten console.log in material-table.js

V.6.3.0 :
Path to file :  core>dist>material-table.js
l.405 : console.log(row, row.tableData.showDetailPanel ? 'open' : 'closed');

Current master : 
Path to file : core/src/material-table.js
l.838 : console.log(row, row.tableData.showDetailPanel ? 'open' : 'closed');

It's always in onToggleDetailPanel.

PS : I should have tag this as inconvenience instead of bug. My bad. Edit unavaiable for tags. =/

**Comment by Domino987** [comment]
Oh thanks.
Can you create a PR to fix this?
