### ISSUE TITLE
Provide column.key in orderByCollection for remote sorting

### ISSUE THREAD

**Issue by kkl4261** [material-table-core/core#818]
- #### Request
Allow the user to access column field attribute in Query.orderByCollection[] directly, instead of requiring the user to pass the columns prop manually into the query method.

- #### Description
Currently, only column index is provided in the query.orderByCollection, which is insufficient in case a sortKey has to be passed to the API for remote sorting. Requiring the user to manually compute the column field string in query method is quite unintuitive.
In fact this has made the code migration from using orderBy props to orderByCollection props quite difficult.

- #### Expectation
Add orderByField:string in the interface OrderByCollection

**Comment by Domino987** [comment]
Sounds reasonable. Can you create a PR?

**Comment by kkl4261** [comment]
Sure. Will open one in a few days.
