### ISSUE TITLE
onRowUpdateCancelled doesn't return any rowData information

### ISSUE THREAD

**Issue by KippWade** [material-table-core/core#819]
**Issue**
When cancelling a row edit, the OnRowUpdateCancelled function rowData always returns undefined.
This seems to have never returned anything, even since the mbrn days.

**Sandbox link**
https://codesandbox.io/p/sandbox/material-table-issue-onrowupdatecancelled-vz4r6z

**Expected behavior**
Since rowData is  shown in the Editable example, it is expected that the rowData would be available.
https://material-table-core.github.io/demos/edit/editable

**Screenshots**
![image](https://github.com/material-table-core/core/assets/43067502/62740f90-6d41-4735-bae6-860ce264c581)

**Desktop:**
- OS: Windows 10
- Browser : Chrome
- Version: 120.0.6099.110 (Official Build) (64-bit)

**Comment by Domino987** [comment]
Ah yes, it will be removed from the example in the future.

**Comment by KippWade** [comment]
So, the workaround will still have to be:

```
                components={{
                    EditRow: (props) => {
                        return (
                            <MTableEditRow
                                {...props}
                                onEditingCanceled={(mode: any, rowData: any) => {
                                    // do stuff here
                                    props.onEditingCanceled(mode);
                                }}
                            />
                        );
                    },
                }}
```

We were hoping that this prop was intended to not have to do that...

**Comment by Domino987** [comment]
Ah you mean the whole object, not the rowData key from the object.

That can easily be returned, in my opinion. Would you mind creating a PR with the change to onEditingCanceled material-table.js?

**Comment by KippWade** [comment]
I imagine that onRowAddCancelled has the same issue, but we haven't had a need for that one...

I will attempt to make a PR here shortly.

**Comment by Domino987** [comment]
Done and relased. Thanks
