### ISSUE TITLE
Deselect all programatically

### ISSUE THREAD

**Issue by atowler84** [material-table-core/core#820]
I see that there is a demo for select/deselect all when using non-remote data, but how is this accomplished when you are using remote data? The use-case is that I want to have the user select multiple/all rows, perform an action on those rows via a button, then when the promise returns it deselects everything. I see in the _tests directory an example using onAllSelected(false), but that appears to no longer be exposed.

**Comment by Domino987** [comment]
Can you create a sandox with your setup?
