### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by weimerb-tng** [material-table-core/core#825]
Can you update the following dependencies to the latest version?

* `@mui/x-date-pickers`
* `@date-io/date-fns`
* `date-fns`

We are using `material-table-core` and are not able to update these packages to the latest versions due to `material-table-core` having transitive dependencies to old versions.

**Comment by Domino987** [comment]
What version are you using? And would that brick the previous version?

**Comment by weimerb-tng** [comment]
We are using 
* `material-table-core` version `6.3.2`
* `@mui/x-date-pickers` version `5.0.20` and would like to update to version `6.19.2`. `material-table-core` declares the dependency `"@mui/x-date-pickers": "^5.0.3"`, so a major version update to 6 is not possible.
* `@date-io/date-fns` version `2.17.0` and would like to update to version `3.0.0`. `material-table-core` declares the dependency `"@date-io/date-fns": "^2.16.0"`, so a major version update to 3 is not possible.
* `date-fns` version `2.30.0` and would like to update to version `3.3.1`. `material-table-core` declares the dependency `"date-fns": "^2.29.3"`, so a major version update to 3 is not possible.

**Comment by weimerb-tng** [comment]
You already update the dependencies in #836 a month ago. When will be the release of the next version including these changes?

**Comment by Domino987** [comment]
I will release them this week.
