### ISSUE TITLE
Request for Feature Addition: Custom Styling for Actions Cell in Row Editing

### ISSUE THREAD

**Issue by JeanZap** [material-table-core/core#828]
Dear @material-table/core Development Team,

I am writing to request a feature enhancement in the Row Editing functionality of the MTable component. Currently, it seems that adding custom styles to the Actions Cell during row editing is not directly supported.

I have successfully implemented a workaround by modifying the MTableEditRow component, specifically the renderActions function. The added lines of code are as follows:

![image](https://github.com/material-table-core/core/assets/18709872/71aa9e73-b5b7-49b7-9a74-a5c9bf1efdd3)

This modification allowed me to apply custom styles to the Actions Cell, and it has been working effectively in my use case.

However, I believe it would be highly beneficial for the broader community if this feature could be officially integrated into the MTable component. Therefore, I kindly request your consideration in accepting a pull request that incorporates this enhancement.

I understand the importance of maintaining code quality and consistency, and I am willing to work collaboratively to ensure that the implementation aligns with the project's standards. If there are any specific guidelines or changes you'd like me to address in the pull request, please let me know.

Thank you for your time and consideration. I look forward to contributing to the improvement of the @material-table/core component.

Best regards,

**Comment by Domino987** [comment]
Hi thanks for this well articulated and detailed issue. Of course this sounds like a good idea and I would accept a PR related to this. Would you mind opening one and tagging me?
