### ISSUE TITLE
Child row of a child row does not show "Are you sure you want to delete this row?"

### ISSUE THREAD

**Issue by KippWade** [material-table-core/core#830]
**Describe the bug**
When using the parent/child option, a child of a child with children will not show the deletion text "Are you sure you want to delete this row?"

**To Reproduce**
https://codesandbox.io/p/sandbox/material-table-core-parent-child-forked-8rk59g

1. Expand first child level by clicking on the row (codesandbox example, the row is blue)
2. Expand the second child level by clicking on the embedded row (codesandbox example, the row is green)
3. On the second level (green row), click the delete trashcan icon
4. The text "Are you sure you want to delete this row?" does not appear, the row is blank.

**Expected behavior**
Expected to see the default "Are you sure you want to delete this row?" text.

**Screenshots**
![image](https://github.com/material-table-core/core/assets/43067502/627b0251-7f23-459f-bc14-2f5eb0a32047)

**Desktop:**

- OS: Windows 11
- Browser Chrome
- Version  120.0.6099.227 (Official Build) (64-bit)

**Comment by Domino987** [comment]
I'll take a look

**Comment by KippWade** [comment]
With new CodeSandbox rules, I'm not sure you can get to that sandbox now?

**Comment by Domino987** [comment]
Yes I cant see it. Thats annoying..

**Comment by KippWade** [comment]
Should be able to see it now.  They defaulted to everything to be private, and I just made it public.

**Comment by Domino987** [comment]
Thanks, Ill check it out.

**Comment by KippWade** [comment]
This is defiantly something to do with using parent/child.  For some reason, the delete text just isn't inserted.

I've been looking through code, but haven't been able to find anything obvious as of yet.

**Comment by KippWade** [comment]
In MTableEditRow, the localization that is passed on non group rows and the nested child rows are coming through differently.  I'm trying to trace through where it is getting the different localization objects.

MTableEditRow:

Other edit rows when deleting, the localization.deleteText is displayed:
props:
localization:
{
    "saveTooltip": "Save",
    "cancelTooltip": "Cancel",
    "deleteText": "Are you sure you want to delete this row?"
}

when it's child of child, there is no localization.deleteText in this object, but it's in localization.editRow.deleteText....
props:
localization:
{
	"addToolTip": "Add",
	"bulkEditApprove": "Save all changes",
	"bulkEditCancel": "Discard all changes",
	"bulkEditTooltip": "Edit All",
	...
	editRow: {
		"cancelTooltip": "Cancel",
		"dateTimePickerLocalization": undefined,
		"deleteText":  "Are you sure you want to delete this row?",
		"saveTooltip": "Save",
		...
	}
	...
}

**Comment by Domino987** [comment]
That seems like an easy fix. Would you mind creating a PR to address this?

**Comment by KippWade** [comment]
I will create one tonight.  If found that if in MTableBodyRow I pass localization.editRow in the create element, it looks to work in every instance.
