### ISSUE TITLE
Warning: MTableHeader: Support for defaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by jalbissimo** [material-table-core/core#832]
**Describe the bug**
A warning appears in the console saying "Warning: MTableHeader: Support for defaultProps will be removed from function components in a future major release"

**To Reproduce**
Have installed the following dependencies 

- "react": "18.2.0"
-  "react-dom": "18.2.0"
-  "@material-table/core": "6.2.11"
-  "@mui/material": "5.14.10",

1. Open browser console
2. Warning: MTableHeader: Support for defaultProps will be removed from function components in a future major release appears

**Screenshots**
![image](https://github.com/material-table-core/core/assets/37750567/5bbbd564-9c92-4c67-af9e-77927645ed92)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome   
- Version: 121.0.6167.161

**Comment by Ggilb3rt** [comment]
Hello !

Got same error here with MTableBodyRow, MTableCell and more.

Using :
- "next": "14.1.0"
- "react": "^18"
- "react-dom": "^18"
- "@mui/base": "^5.0.0-beta.34"

I don't know how to help, I find this [article](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/default_props/) maybe he could help.

**Comment by ro4dev** [comment]
Same here, but it does nothing other than bother.

Using :
- "@emotion/cache": "^11.11.0",
- "@emotion/react": "^11.11.3",
- "@emotion/server": "^11.11.0",
- "@emotion/styled": "^11.11.0",
- "@material-table/core": "^6.3.2",
- "@mui/icons-material": "^5.15.9",
- "@mui/material": "^5.15.9",
- "@mui/material-nextjs": "^5.15.9",
- "@typegoose/typegoose": "^12.1.0",
- "dayjs": "^1.11.10",
- "mongoose": "^8.1.1",
- "next": "14.1.0",
- "react": "^18",
- "react-dom": "^18"

**Comment by Domino987** [comment]
Seems like a deprecation. If you want to work on a PR to change it to the new way to do it, you are more than welcome.

**Comment by SheldonWBM** [comment]
The deprecation warning is for React 19. React 19 is currently in beta. It is expected to be out of beta in June or July 2024. 
So, the person working on the PR could a) Ensure it works without defaultProps in React 18 and b) Use React 19 Beta to test compatibility.

**Comment by SheldonWBM** [comment]
Reviewing issues backlog with a project that uses this component, the issue with React 19 disappeared at some point, perhaps back in 2024?
