### ISSUE TITLE
date-fns V3 and material-table 6.4.1 throws parseISO error when a column has a type of "date"/"datetime"

### ISSUE THREAD

**Issue by ShotSkydiver** [material-table-core/core#838]
# Guidelines

When I updated material-table to the latest 6.4.1, and updated date-fns to its latest version, 3.6.0, my React app crashes when a table column has the type of "date" or "datetime", with this error:
`(0, _parseISO["default"]) is not a function. (In '(0, _parseISO["default"])(props.value)', '(0, _parseISO["default"])' is an instance of Object)`

OS: macOS
Browser: Safari
Version: 17.5

**Comment by Domino987** [comment]
Hi, can you add a sandbox with your minimal reproducible example?
Ty

**Comment by TheWeirdDev** [comment]
I have the same issue. According to the [date-fns](https://date-fns.org/v3.6.0/docs/parseISO) documentation [this line](https://github.com/material-table-core/core/blob/b489dc9bd5a4a52a602b3df176920eeecbeb78c1/src/components/MTableCell/cellUtils.js#L2) should be changed from:

```js
import parseISO from 'date-fns/parseISO';
```

to

```js
import { parseISO } from 'date-fns';
```

**Comment by Domino987** [comment]
Would you mind creating a PR for this?

**Comment by TheWeirdDev** [comment]
Sure
