### ISSUE TITLE
console.log("rendering cell....")

### ISSUE THREAD

**Issue by georgejdli** [material-table-core/core#84]
# Guidelines
Is there a way to turn these console message off? 

- #### Please include a demo of the issue/behavior/question you have
![image](https://user-images.githubusercontent.com/9357792/105553466-11b31e80-5ccb-11eb-8c71-025775bd9daa.png)

- Browser console is getting spammed with "rendering cell..." messages
-

**Comment by matthewoestreich** [comment]
Sorry this was just resolved in v2.3.20. Apologies.
