### ISSUE TITLE
Column sorting for fields that start with "current" breaks after data update

### ISSUE THREAD

**Issue by rachaelacollins** [material-table-core/core#842]
**Describe the bug**
Column sorting for `field`s that start with "current" breaks after `data` update.

**To Reproduce**

1. Load table `data` where a `Column` `field` value starts with "current" (e.g. `"currentValue"`).
2. Sort the column with the `field` that starts with "current" (e.g. `"currentValue"`).
3. The rows are appropriately sorted.
4. The `data` state is updated. 
5. Sort the column with the `field` starts with "current" (e.g. `"currentValue"`).
6. The rows are *not* appropriately sorted.

**Expected behavior**
The same sorting behavior should be preserved after `data` state update. 

**Desktop:**
- OS: MacOS
- Browser: Chrome
- Version: 124.0.6367.78

**Comment by Domino987** [comment]
Can you create a sandbox?
