### ISSUE TITLE
Overridden search component loses focus upon table rerender

### ISSUE THREAD

**Issue by aventide** [material-table-core/core#85]
When using an overridden `Search` component to replace the built-in search bar, focus is lost when the parent table component re-renders due to a data change.

When you use the built-in search functionality, i.e. options: {search: true}, then you can focus and type in the bar, through rerenders. In my case, I have polling going on. If you then do options: {search: false} and then insert your own input component with a Search component override, the input loses focus with each change to the table's input data.

Example: https://codesandbox.io/s/agitated-einstein-xs6f0?file=/src/MTable.js

**To Reproduce**
Use a custom search component in the table, and attempt to type in the resulting search bar with a polling (i.e. setTimeout) running that changes the table's data set periodically.

**Expected behavior**
When using a custom search component, focus is not lost when the table re-renders (presumably due to a data change)

**Desktop (please complete the following information):**

- OS: MacOS Big Sur (Intel)
- Browser Chrome
- Version 88

**Comment by matthewoestreich** [comment]
I believe this is related to a known issue. We are working on separating the actual table body state from the header, in order to prevent rerenders like this.

This one is a work in progress.

**Comment by Domino987** [comment]
@misterlocations This is because how react handles the stable function references internally. If a new function is passed, it will lose its state aka its focus and content.

You need to create a stable reference to the Search component to keep the state.

```
function Seach() {
return <input />
}
```

and 

```
Toolbar: Search
```
