### ISSUE TITLE
Build error from new version of dependecy Zustand

### ISSUE THREAD

**Issue by Ramzza** [material-table-core/core#855]
**Describe the bug**
React material-table is using the "zustand-latest" as a dependency.
Since this morning we are getting an npm build error:

ERROR in ./node_modules/zustand/esm/index.js 1:0
13:29:16 Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
13:29:16 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
13:29:16 > import { createStore } from 'zustand/vanilla';
13:29:16 | export * from 'zustand/vanilla';
13:29:16 | import ReactExports from 'react';
13:29:16 @ ./node_modules/@material-table/core/dist/store/LocalizationStore.js 12:15-33
13:29:16 @ ./node_modules/@material-table/core/dist/index.js 116:25-61

**To Reproduce**
1. npm run build (for react project using material-table-core)
2. build fails

**Expected behavior**
Build passes, as it did yesterday, before the new patch release of Zustand (dependency of material-table-core)

**Comment by Domino987** [comment]
It works for me. Can you create a sandbox with the current zustand version that fails?
