### ISSUE TITLE
Warning `columns` is marked as required in `MTableAction`, but its value is `undefined`

### ISSUE THREAD

**Issue by martin-trajanovski** [material-table-core/core#856]
**Describe the bug**
(console.js:273 Warning: Failed prop type: The prop `columns` is marked as required in `MTableAction`, but its value is `undefined`.)

**To Reproduce**

1. Create table with row action, data and few columns.

**Expected behavior**
Should not see console warning

**Screenshots**
![material-table-warning](https://github.com/material-table-core/core/assets/6333063/b49c1aa0-4fff-4cec-bf03-23c99ef91f12)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 126.0.6478.126 

**Additional context**

**Comment by Domino987** [comment]
Will be removed with next release

**Comment by sovanyio** [comment]
Feb 2025 and no new release..

**Comment by KkatieJ** [comment]
Any updates on this? I just updated to latest and didn't understand what's happening.
