### ISSUE TITLE
Unexpected behavior with TotalCount and page properties

### ISSUE THREAD

**Issue by martin-trajanovski** [material-table-core/core#857]
**Describe the bug**
While working on my project, I noticed that TotalCount no longer does what it did before. So the passed value at TotalCount is not displayed in the table below. However, I am not sure if there is a problem with my dependencies and thus it is with my implementation or it is a bug.

**To Reproduce**

1. Import newest version of the table
2. Add totalCount and page

Earlier version (Material-Table) - with expected behavior: https://codesandbox.io/p/sandbox/material-table-starter-template-forked-f6h46m?file=%2Fsrc%2Findex.js%3A1%2C1-38%2C1
Latest version (Meterial-Table/core) - with unexpected behavior: https://codesandbox.io/s/material-table-starter-template-forked-s5lcd8?file=/src/index.js

If the behavior is wanted, I would like to know how to change totalCount now.

**Comment by Domino987** [comment]
The first link does not work unfortunately
