### ISSUE TITLE
Bug in MTableCell/utils.js, "React"  -> "_react["default"]

### ISSUE THREAD

**Issue by pbogaard** [material-table-core/core#90]
Hi there!

Version: "@material-table/core": "^2.3.24",

In "node_modules/@material-table/core/dist/components/MTableCell/utils.js" there is a bug.

At line 109 and 113 there is:

`/*#__PURE__*/ React.createElement(props.icons.Check, {`

This should be:

`/*#__PURE__*/_react["default"].createElement(props.icons.Check, {`

And ofcouree import "_react" at the top:

`var _react = _interopRequireDefault(require("react"));`

**Comment by MaxiDave** [comment]
Hello! I can confirm this bug. It is solved by changing the code as @pbogaard said.

**Comment by matthewoestreich** [comment]
Hey thank you for this! v2.3.25 has been published with a fix for this.

**Comment by pbogaard** [comment]
@oze4 Matt what is the difference between `var _react = _interopRequireDefault(require("react"));` and importing React like normal?

**Comment by matthewoestreich** [comment]
I'm not sure I follow.

The code you are referencing is transpiled code (via Babel).

**Comment by MaxiDave** [comment]
Hello again,

Thank you, @oze4! Unfortunately, this new version crashes for me. I did a downgrade to the v2.3.24 with @pbogaard proposed fix, and the tables work perfectly. Attached is the error message I am getting with the newest version.

![bug_material_table](https://user-images.githubusercontent.com/26763246/106610985-b5bc8580-6567-11eb-811c-f14ba859dabb.png)

**Comment by matthewoestreich** [comment]
It looks like this error us unrelated to this issue, but still needs to be resolved. I'll look into it ASAP.

**Comment by MaxiDave** [comment]
I thought it was related, my fault. I should have opened a new issue.
Thank you very much for your hard work @oze4!

**Comment by matthewoestreich** [comment]
@MaxiDave I think I found the issue.

I published [v2.3.26](https://www.npmjs.com/package/@material-table/core/v/2.3.26). Would you mind testing with this version? If you still have issues try deleting node_modules then run `npm install` again.

**Comment by MaxiDave** [comment]
Solved! Thank you @oze4.

**Comment by matthewoestreich** [comment]
@pbogaard did this also resolve your issue?

**Comment by pbogaard** [comment]
@oze4 yes resolved 👍

**Comment by matthewoestreich** [comment]
🚀 🚀 🚀
