### ISSUE TITLE
Broken rendering in online docs

### ISSUE THREAD

**Issue by johnthagen** [material-table-core/core#92]
https://material-table-core.com/docs/api/props/options#exportmenu

<img width="850" alt="Screen Shot 2021-02-03 at 9 19 31 AM" src="https://user-images.githubusercontent.com/10340167/106759606-f3212180-6600-11eb-86e7-9496a2f2e739.png">

See the `::: info` line.

**Comment by matthewoestreich** [comment]
Thank you very much! This has been resolved.
