### ISSUE TITLE
Action icons not rendering in a row

### ISSUE THREAD

**Issue by Mohron** [material-table-core/core#94]
After upgrading from `2.3.24` to `2.3.26`, I've started having a rending issue with action icons both in the toolbar and in the rows.

The addition of an additional `div` to the markup seems to be the culprit.

# Screenshots
![image](https://user-images.githubusercontent.com/3623122/106830860-e205fe00-665c-11eb-867b-c3747ddc4764.png)
![image](https://user-images.githubusercontent.com/3623122/106830890-ee8a5680-665c-11eb-9a3b-9f362dff9c79.png)

# Demo
https://repl.it/@Mohron/MaterialTableActionIconBug

Old Markup (Action Cell)
```html
<td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="width: 144px; padding: 0px 5px; box-sizing: border-box;">
   <div style="display: flex;">
      <button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit" tabindex="0" type="button" title="Duplicate">
         <span class="MuiIconButton-label">
            <svg class="MuiSvgIcon-root" focusable="false" viewBox="0 0 24 24" aria-hidden="true">
               <path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm-1 4l6 6v10c0 1.1-.9 2-2 2H7.99C6.89 23 6 22.1 6 21l.01-14c0-1.1.89-2 1.99-2h7zm-1 7h5.5L14 6.5V12z"></path>
            </svg>
         </span>
         <span class="MuiTouchRipple-root"></span>
      </button>
      ...
   </div>
</td>
```
New Markup (Action Cell)
```html
<td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="width: 144px; padding: 0px 5px; box-sizing: border-box;">
   <div style="display: flex;">
      <div>
         <button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-colorInherit" tabindex="0" type="button" title="Duplicate">
            <span class="MuiIconButton-label">
               <svg class="MuiSvgIcon-root" focusable="false" viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm-1 4l6 6v10c0 1.1-.9 2-2 2H7.99C6.89 23 6 22.1 6 21l.01-14c0-1.1.89-2 1.99-2h7zm-1 7h5.5L14 6.5V12z"></path>
               </svg>
            </span>
            <span class="MuiTouchRipple-root"></span>
         </button>
         ...
      </div>
   </div>
</td>
```

**Comment by matthewoestreich** [comment]
Thank you for this! 

Is the issue that they're supposed to be inline?

**Comment by Mohron** [comment]
They were before I tried updating and that would be my expectation. This even occurs when there is plenty of available horizontal space.

**Comment by matthewoestreich** [comment]
Makes sense. The only thing we changed was wrapping all components in 'forwardRef'. I can dig more into this in a couple of hours.

**Comment by Mohron** [comment]
Here's a copy of the [Multiple Actions Example](https://material-table.com/#/docs/features/actions) from the original docs with the latest version of the fork installed. The icons don't render inline as seen in my screenshots



https://repl.it/@Mohron/MaterialTableActionIconBug

**Comment by gulamhussain08** [comment]
> Makes sense. The only thing we changed was wrapping all components in 'forwardRef'. I can dig more into this in a couple of hours.

Yes @oze4. Previous to [this](https://github.com/material-table-core/core/commit/d5d2dd094ee4aaab293a43abbd21bcfac0a12afb) commit, MTableActions used to return an array of actions. Now it's returning a div. Adding `display:flex` to that div wil fix the problem.
