### ISSUE TITLE
How to display the sort icon by default

### ISSUE THREAD

**Issue by zhushenhang** [material-table-core/core#95]
https://material-table.com/#/docs/features/sorting

The current sorting icon is hidden by default and needs to be activated to see it. 
How to make it show by default.

thanks bro.

**Comment by matthewoestreich** [comment]
Needs to be hovered to see it**

@Domino987 what do you think? I kind of like this idea of not having to hover the column header to see you can sort it.

Edit: by default, it should be shown, and the consumer should have the option to only show on hover - is what I mean.

**Comment by zhushenhang** [comment]
@oze4 right.
I think this icon should be configurable to show or hide.
like  ``` options:{sortIcon : "show" } ```

**Comment by matthewoestreich** [comment]
I like the idea but think it would be good to put this prop on the columns object. Like `showSortIconOnHover: false`. Something like that so it's named descriptively (there are a lot of props so while it is long, naming props in a succinct manner goes a long way). I also prefer to keep the prop as a boolean, this way it is easier to use (don't have to remember if that prop value is supposed to be "show" or "shown", etc...)

**Comment by zhushenhang** [comment]
Your idea is better, it is easier to configure independently on the column object.

**Comment by Domino987** [comment]
The problem is, that you cannot find which column is currently being sorted. 
![image](https://user-images.githubusercontent.com/17567991/107874694-8721a180-6ebb-11eb-9f75-56ff52748455.png)
How would you propose to show the currently sorted column?

**Comment by zhushenhang** [comment]
@Domino987 Hi.How about the color distinction?

**Comment by matthewoestreich** [comment]
@Domino987 we could also put this prop on the columns object. (one of the objects that is part of the `columns` array prop)

**Comment by Domino987** [comment]
@zhushenhang If you have a proposition on how to display it, e.g. a color that would work, could you reproduce that in a material-ui sandbox with a [sortlabel](https://material-ui.com/api/table-sort-label/)?

**Comment by matthewoestreich** [comment]
According to the material design standard, the sort icon should only show on hover (while viewed on desktop at least).

<img width="822" alt="md1" src="https://user-images.githubusercontent.com/21092343/116342079-a1270c80-a7a7-11eb-9905-db4df6170593.png">

Taken from [here](https://material.io/components/data-tables#behavior)

I think permanently showing the sort arrow goes against material design. I can't find anything about color distinction, but I would just assume that also goes against the material design standard. 

Just wanted to throw this out there.

**Comment by zhushenhang** [comment]
@Domino987 @oze4 
I also don't have a good idea.I think we should follow the standard, so this issue will be closed

**Comment by ssalib-aamc** [comment]
In more complex designs, based on business needs, not all columns can be sortable.
To show the sort icon for a column **without hover** is the best indication to differentiate and identify sortable columns.
I'm surprised why this issue was closed.
I'd like to reopen it.
Our UX designers and POs don't like the idea of hover to show icon when some of our columns are not sortable from back-end API side.
Please reopen.

**Comment by Domino987** [comment]
Hi. This is currently the state of the whole web, material design and the Mii data grid as well. If you have a proposition on how to implement and style it, you are welcome to pose it. What would you expected it to look like?

**Comment by Expertus777** [comment]
You must be joking. I think it is pretty simple: 

![Image](https://github.com/user-attachments/assets/f011b936-6a26-4d5b-9cf0-ce35cfaa8e61)

Also [another](https://primeng.org/table#sort) example.
