### ISSUE TITLE
Table doesn't refresh upon external CRUD events

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#97]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

As I just had to revert my code and fall back to the TABLE from material-ui, I don't have the actual code but can explain in detail what happened and what is expected
 
- #### Please try to be as detailed as possible

So, here I have a Dialog form which pops-up when user clicks a button to add notes\remarks. The form receives all current persisted remarks as PROPS. I use this PROPS JSON element to extract REMARKS JSON

e.g. the PROPS would look like ..
```
{
  applicationID: 1234,
  remarks: [
                    {remarkID: 1, remark: 'Remark details 01', createdAt: '2021-02-10', createdBy: 'TEST_USER'},
                     {remarkID: 2, remark: 'Remark details 02', createdAt: '2021-02-10', createdBy: 'TEST_USER'},
                     {remarkID: 3, remark: 'Remark details 03', createdAt: '2021-02-10', createdBy: 'TEST_USER'},
              ]
}

let remarks = props.remarks;

```
below array is my column definition ... 

```
const columns = [
  { field: "remark", 
    title: "Remark", 
    cellStyle: {
      width: 650,
      minWidth: 650,
    },
    headerStyle: {
      width: 650,
      minWidth: 650,
      //whiteSpace: 'nowrap',
    } },
  { field: "createdAt", title: "Added On", 
  cellStyle: {
    width: 30,
    minWidth: 30,
    whiteSpace: 'nowrap',
  },
  headerStyle: {
    width: 30,
    minWidth: 30,
    whiteSpace: 'nowrap',
  }  },
  { field: "createdBy", title: "Added By",
  cellStyle: {
    width: 30,
    minWidth: 30,
    whiteSpace: 'nowrap',
  },
  headerStyle: {
    width: 30,
    minWidth: 30,
    whiteSpace: 'nowrap',
  } },
];
```

I use the remarks element from the above JSON object as my input to the MaterialTable 

 ```
<MaterialTable
                    title="Remarks"
                    icons={tableIcons}
                    columns={columns}
                    data={remarks}
                    options={{
                      
                      showTitle: true,
                      isLoading: true,
                      headerStyle: {
                        backgroundColor: "#01579b",
                        color: "#FFF",
                      } 
                    }}
                    
                  />

```

The have a FORMIK form which is a simple one textEdit style element for user to add new REMARK with an OK and CANCEL button. Once user add a new Remark and press the 'OK' button. I make an API call to save the new remark ..everything works fine up to here..

The issue is when I PUSH the new remark in the REMARKS array as a new JSON object, the MaterialTable doesn't reflect that change. I even tried to use REMARKS as a state variable with hooks e.g.

const [remarks, setRemarks] = useState(props.remarks)

and tried to set the new element in the remarks using the setRemarks() in the form submit event post API call. Still the table won't refresh. It seems like the table is just independent by itself post rendering and won't bother to listen to data changes.

I know that I can use the 'EDITABLE' feature of the MaterialTable and allow user to directly add\update row  like the one below but that's not how I want my UI to look\behave...

```
editable={{
onRowAdd: newData =>
            new Promise((resolve, reject) => {
                setTimeout(() => {
                    setData([...remarks, newData]); 

                    resolve();
                }, 1000);
            }),
}}
```
- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**

Simple. MaterialTable fails to re-render itself when the underlying data changes.

**To Reproduce**

Try to use above snippets of code to create a React functional element to reproduce the issue or simply you can see this in your own MaterialTable implementation by updating the data values.

**Expected behavior**

All I expect MaterialTable to do is to reflect changes to the underlying data when the data gets updated. A stale data table doesn't serve much purpose. 

**Screenshots**

don't have any as I created this bug AFTER I had reverted my code to use simple Material Table from material-ui

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac Os Mojave
- Browser [e.g. chrome, safari] Chrome 
- Version [e.g. 22] Version 88.0.4324.96 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
N/A

**Additional context**

Hope someone has an answer or a workaround else it's a bug and needs be addressed as it is a basic requirement for any data table to refresh itself

**Comment by Domino987** [comment]
Thank you for the detailed bug report. Can you put that in a sandbox so we can check it out?

**Comment by DewangS** [comment]
Thanks @Domino987 . I tried to add code to the sandbox but the page hangs for some odd reason so, here is the code sample ... Now, this is NOT the EXACT code which I have but it does mimic the scenario which I described. i.e. upon user clicking the ADD button, I want a new JSON element added to the DATA and expect this to show up in the table.

```
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import SaveAltIcon from "@material-ui/icons/SaveAlt";
import tableIcons from "./TableIcons.js";
import {
  Button
} from "@material-ui/core";
import SaveIcon from "@material-ui/icons/Save";
const rando = max => Math.floor(Math.random() * max);

const words = ["Paper", "Rock", "Scissors"];

const rawData = [];
for (let i = 0; i < 10; i++) {
  rawData.push({ id: rando(300), word: words[i % words.length] });
}

const columns = [
  { title: "Id", field: "id" },
  { title: "Word", field: "word" }
];

const App = () => {
  const [data, setData] = useState(rawData);

 const addRemark = () => {
    rawData.push({ id: rando(300), word: "New text" });
    console.log("+++ RAW DATA : ", JSON.stringify(rawData))
    alert(JSON.stringify(rawData))
    setData(rawData)
  }

  return (
    <React.Fragment>
    <MaterialTable
      data={data}
      columns={columns}
      title="Starter Template"
      icons={tableIcons}
    />
    <Button
      variant="contained"
      
      size="medium"
      
      //style={{marginTop: '10px'}}
      startIcon={<SaveIcon />} 
      
      onClick={addRemark}
    >
      Add
    </Button>
    </React.Fragment>
  );
};

render(<App />, document.querySelector("#root"));

```

**Comment by Domino987** [comment]
This has noting to do with the package, but how you update the hook data.
Never mutate the data but instead create a new array.
Here is a more [detailed SO anwser](https://stackoverflow.com/a/59503022/11599909)

**Comment by DewangS** [comment]
https://codesandbox.io/s/material-table-starter-template-xnfpo?file=/src/index.js

**Comment by Domino987** [comment]
> [codesandbox.io/s/material-table-starter-template-xnfpo?file=/src/index.js](https://codesandbox.io/s/material-table-starter-template-xnfpo?file=/src/index.js)

There is no edit in this sandbox?

**Comment by DewangS** [comment]
@Domino987  Thanks for the SO thread though if you look at my code, I am using the setData() method to update the data NOT directly pushing any value in the data element. Also, the SO thread refers to the onRowAdd, onRowUpdate methods which uses promises and they are part of the MaterialTable's internal event triggers i.e. you will end up having ADD, UPDATE, DELETE buttons on the header or at a row level as soon as you have these in your definition. In my UI requirement, I don't want any buttons on the table but having a small separate FORMIK form on top of the table for user to add new REMARK.

**Comment by DewangS** [comment]
> > [codesandbox.io/s/material-table-starter-template-xnfpo?file=/src/index.js](https://codesandbox.io/s/material-table-starter-template-xnfpo?file=/src/index.js)
> 
> There is no edit in this sandbox?

sorry forgot to save the file before sending the link.. just saved it now..

**Comment by Domino987** [comment]
> rawData.push({ id: rando(300), word: "New text" });

This looks al lot like mutating. And it does not matter where you call it. If its in a custom function or a callback. Don't mutate the data.

The link is still empty.

**Comment by DewangS** [comment]
> > rawData.push({ id: rando(300), word: "New text" });
> 
> This looks al lot like mutating. And it does not matter where you call it. If its in a custom function or a callback. Don't mutate the data.
> 
> The link is still empty.

Not sure why the link is still empty https://codesandbox.io/s/material-table-starter-template-forked-wony3?file=/src/index.js 

Ok, so, based on your suggestion I've updated the addRemark() as per below and now I am able to see the new record every time I hit the ADD button. Thanks very much for pointing out the basics of React as I am fairly new to React. I'll close this as it's not a bug. Thanks again.

const addRemark = () => {
    const newData = { id: rando(300), word: "New text" };
    setData(prevData => [...prevData, newData])
  };

**Comment by Domino987** [comment]
No problem :) glad I could help.
I think sandbox creates a new link on save, that's why it was still the old one.
